### ISSUE TITLE
Issues with window-type when running `M-! iceweasel`

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#1]
Or chromium. Is it not the way to open a new application?

It just hangs, and after a while I cancel with `C-g C-g` and it shows me an error saying exwm--window-type is void.

This project is awesome and I'd love to help debug it.

**Comment by ch11ng** [comment]
`M-!` is bound to `shell-command`, which runs command synchronously. You should instead run command asynchronously. In fact, it doesn't matter how you launch an application, as EXWM can always manage it. For instance, you can execute a shell command with `M-&`, or run it in `ansi-term`. In the [example](https://github.com/ch11ng/exwm/wiki/Configuration-example), I also provided a way to launch application with `s-&`, which you may find useful.

**Comment by ralt** [comment]
Indeed, it works! Thanks a lot.
