### ISSUE TITLE
exwm windows visibility

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#100]
Right now exwm are visible only in one workspace where they were spawned or moved to. Why is that? It would be awesome if they could be moved between workspaces just like normal buffers, eg. I could do helm-mini/ibuffer/different_buffer_managment_tool in different workspace and pull exwm window to the currently active window.

**Comment by ch11ng** [comment]
This has been discussed before and was actually implemented.  See https://github.com/ch11ng/exwm/issues/50#issuecomment-140746653.  I think it's time to document it if it works in your case.

**Comment by fm4d** [comment]
Yes, it does exactly what I wanted, thanks. And yes, adding few sentences about this to wiki sounds like a good idea.
