### ISSUE TITLE
Disable modeline for floating windows by default

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#101]
I would say that disabling it by default is a good idea as it is really hard to imagine any use case for it. It could be solved by adding something like this ```(add-hook 'exwm-floating-setup-hook (lambda () (exwm-floating-hide-mode-line)))``` to default configuration with some explanation.

**Comment by ch11ng** [comment]
IMO the mode line is useful for indicating the buffer name, input mode and input method.  It can be hidden of course if you don't need it at all.  But I still think it's beneficial to make users aware of its existence by showing it by default.  I've just documented it in [this page](https://github.com/ch11ng/exwm/wiki/Configuration-Example).
