### ISSUE TITLE
Nautilus takes over the workspace

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#103]
Launching nautilus (the GNOME file manager) takes over a workspace making it unresponsive.

Steps to reproduce:
- Launch EXWM with the recommended configuration `exwm-config.el`.
- Run <kbd>M-x async-shell-command nautilus RET</kbd>
- The display seems to be split between the nautilus file manager and a Desktop display.  Trying to open any file (for example an image) makes the Desktop display take over the screen.  Emacs commands seem to have no effect.

**Comment by ch11ng** [comment]
Could you explain what a 'Desktop display' is? I can not reproduce it with Nautilus 3.18.2.

BTW, I think Dired is a better alternative.

**Comment by uu1101** [comment]
Ah!  Admittedly is not a great name... By 'Desktop display' I mean the wallpaper and the folder icons on top.  This is drawn on top of the Emacs workspace, so nothing seems to work unless one changes to another workspace.

Thank you for your help,
uu1101

**Comment by ch11ng** [comment]
How do yo set the wallpaper? Or could you take a screenshot?

**Comment by uu1101** [comment]
Sorry for the delay.  After running the <kbd>M-x async-shell-command nautilus RET</kbd> command, the following is on the screen:
![2015-12-10-182817_900x900_scrot](https://cloud.githubusercontent.com/assets/552356/11722970/3323b9ca-9f6c-11e5-9b66-f4a6c629cbed.png)
Note that the file manager occupies half of the display and the "wallpaper plus icons" the rest, and that Emacs is not visible at all.  No emacs keybindings work.

When launchin the application, I would have expected to have the file manager as a managed EXWM window.

Launching an application by double-clicking on a document results in the "wallpaper plus icons" occupying the whole display:
![2015-12-10-183000_900x900_scrot](https://cloud.githubusercontent.com/assets/552356/11723017/59caeb16-9f6c-11e5-9491-577379480e0c.png)

If changing to another EXWM workspace, emacs can be seen again:
![2015-12-10-183344_900x900_scrot](https://cloud.githubusercontent.com/assets/552356/11723079/99924ec4-9f6c-11e5-992b-36c11d54ee55.png)

but the original workspace remains unusable.

**Comment by ch11ng** [comment]
All right.  I've finally found out the cause and fixed it in 4d5dd85dcc49c8ee9f0c496b439b420eaaeae5af.  The desktop feature of Nautilus can be disabled with `gsettings` or `gnome-tweak-tool`, and it probably does not work well on other tilling window mangers.

**Comment by uu1101** [comment]
Works wonderfully!  Thank you!
