### ISSUE TITLE
exwm-input-set-key stops working eventually

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#104]
I have the following line in my init file `(exwm-input-set-key (kbd "C-c l") 'exwm-reset)` after a while of setting the exwm buffer from char to line mode and vice versa the command stops working and I am unable to quit out of char mode unless I click on the "char" icon in the modeline. The command "C-c l" gets sent directly to the window instead of emacs.

edit: This glitch persists even if I close the window and open it again. The only cure so far has been to quit emacs and open it again

**Comment by ch11ng** [comment]
It can't be reproduced here.  Could you provide more details on this? For example, did other key bindings set with `exwm-input-set-key` work? And what if you changed the key to a single event?

**Comment by jtamagnan** [comment]
This problem had been long lasting for a few months prior to writing this issue but around that time I essentially rewrote my init file and it seems to no longer be occuring. I'm not quite sure what was causing it. If it occurs again I will conduct some experiments. Thanks!

**Comment by Myrl** [comment]
This has been happening to me on my laptop recently. It seems to happen if I C-g on some random hangups.

**Comment by Myrl** [comment]
@ch11ng @jtamagnan I've figured it out. The num lock disables input interception in char mode. Is this on purpose?

**Comment by ch11ng** [comment]
@Myrl the bug has been fixed in ch11ng/xelb@1fafa29ee457ec553e14809c4bc5d4fa59244398.
