### ISSUE TITLE
setxkbmap

### ISSUE THREAD

**Issue by securelord** [ch11ng/exwm#105]
Do not work setxkbmap (change keyboard layout).

**Comment by securelord** [comment]
When I open a new buffer with the running program it is impossible to switch the keyboard layout

**Comment by securelord** [comment]
But the emacs's buffer (eg scratch) layout switching is ok.

**Comment by ch11ng** [comment]
This used to work but was disabled because it caused some problems.  Currently EXWM refreshes keymap for only once on startup, so you need to put `setxkbmap` in your `.xinitrc`.

**Comment by ch11ng** [comment]
Fixed in ch11ng/xelb@a8540a5a0891c2ade769f80c05c4c2b08279e71f.
