### ISSUE TITLE
Gnus daemon

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#106]
The gnus daemon can be used to refresh gnus every so often if emacs has not recieved any input in some amount of time. This is good because when gnus checks for mail it blocks all input and having that idle time stops the refreshing from interupting you as you type. It seems that when in an xwindow there is no input that gets sent to emacs which means that the daemon will run and stop any interaction with the xwindow until the command has finished running.

Would there be some way to tell emacs that typing is happening even when typing in a text box in a browser?

**Comment by ch11ng** [comment]
Things are much more complicated actually.  X events are processed sequentially, so if any event is blocked, the latter events will be queued for later processing.  Considering that there're many other kinds of events, simply keeping Emacs busy on every keyboard event is not sufficient to make EXWM always responsive.

**Comment by ch11ng** [comment]
I'm closing this issue for now, as it's not realistic to implement this feature (or resolve this bug).  Gnus basically uses idle timers for this work, and EXWM also employs a few idle timers.  So preventing `gnus-demon` from running will also degrades the performance of EXWM.  This is essentially an issue with Gnus itself, as (I personally think) it should be implemented in an asynchronous fashion.

However, as a workaround you can always start another Emacs instance on a dedicated workspace and make that fullscreen.  It would just appears to be another workspace except it's isolated from the rest world.  This is perhaps the most reasonable solution I can think of.
