### ISSUE TITLE
how to manualy resize emacs window

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#107]
when I use exwm-xrandr I have issues that everytime I power off my monitor it makes some magic with xrandr or whatever I set in the hook, I am not shure I think it reacts I think even to monitor standby. but that creates problems with my dell monitor that sometimes it gets not recognised anymore.

I use a dock and dont need magic with many monitors connected I just need xrandr and windowresize events happen when I releasee my notebook from the dock.

I did that at the moment with a xrandr script I bound to \<f11\>, the docking event detection is a bit wonky for my lenovo dock, so that would be good enough.

Problem is the emacs window still keeps the old size so in the much smaler resolution on my notebook, I only see 1/3 of the emacs window, so I would like to call the rearange/refullscreen function of emacs or exwm, if you could give me the name of that function I would be happy.

Maybe would try to debug my monitor issue further but it seems its a known issue with dell 4k monitors :) I have luck with my hardware it seems :)

**Comment by ch11ng** [comment]
Please show me the xrandr script and the output of xrandr.  Besides, did you execute the script in `exwm-randr-screen-change-hook`?

If you must refresh manually, just call `exwm-randr--refresh`, but it's better for it being called automatically.

**Comment by spiderbit** [comment]
thx for the info I will test it, the problem withthe hook is that it reacts even when I just poweroff a monitor or it goes standby is that right?

Because that fucks here things up, I dont say its exwms fault but this behaviour triggers so far I understood now a bug with my docking-station, notebook or monitor, so that when I poweron him he often stays dark (thats what I remember, had no time back then when I had exwm-randr active to report/debug/solve the issue.

```lisp
  ;; (require 'exwm-randr)
  ;; (setq exwm-randr-workspace-output-plist '(0 "LVDS1"))
  ;; (add-hook 'exwm-randr-screen-change-hook
  ;;           (lambda ()
  ;;             (start-process-shell-command
  ;;              "xrandr" nil "docking-refresh" )
  ;;             )
  ;;           )
  ;; (exwm-randr-enable)
```

```bash
#!/bin/bash

export DISPLAY=:0
export XAUTHORITY=/home/black/.Xauthority

INTERNAL="LVDS1"
EXTERNAL_CENTER="DP3"

sleep 1
xrandr | grep "$EXTERNAL_CENTER connected"
if [ $? -eq 0 ]; then
    xrandr --output $EXTERNAL_CENTER --auto --output $INTERNAL --off
else
    xrandr --output $INTERNAL --auto --output $EXTERNAL_CENTER --off
fi
```

not shure if that was the excact same file when I testet it last time I may have changed the 2 xrandr commands, because of problems and testing

**Comment by spiderbit** [comment]
to be clear I only want either my external or my internal runnig not both of em at the same time.

**Comment by spiderbit** [comment]
k I testet it out, I could not call successfully exwm-randr--refresh, it seems that it does not work to enable exwm-randr after emacs start somehow evaluating the lines did not help.

But when I restart it, with that exwm-randr module enabled. it kind of works in addition to that hook.
But then its like I described already, exwm-randr gets triggered, when i switch off my monitor and my docking-refresh script activates the internal monitor from my laptop, which is not what I want to happen.

**Comment by ch11ng** [comment]
> the problem withthe hook is that it reacts even when I just poweroff a monitor or it goes standby is that right?

Yes, this will trigger the `ScreenChangeNotify` event, which will again trigger the hook and run `exwm-randr--refresh`.

I realized you can simply run the script instead of calling the function directly.  If that does not work either, please show me the output of `xrandr` (with no arguments).

**Comment by ch11ng** [comment]
I think I made a mistake.  Powering off a monitor does not necessarily disconnects it, so it might not trigger the hook.  Have you tried other monitors? At least your script works for me.

**Comment by spiderbit** [comment]
maybe its because I use a docking station or this 4k dell monitors have such problems, I have a older monitor I will try it. and yes the dell gets disconnected in xrandr when I switch him off. standby it seems not the case.

for now the normal exwm-randr stuff kind of works except that powering off triggers the exwm-randr stuff and when I powenon my monitor I have to wait till its done with its commands/resizing.

I will check out the other monitor, but even if there its different it does not really help me :)

**Comment by ch11ng** [comment]
If turning off the monitor closes the connection, then you should disable the hook and run the script manually.  In the way you can have full control over the resizing.

**Comment by spiderbit** [comment]
is there a way to toggle this xrandr--refresh stuff? then I could deactivate it with a button and activate it when I need to undock my notebook, that would at least be a workaround.

**Comment by spiderbit** [comment]
but when I manuelly run the scipt, ith randr--refresh seems to not run. I test that later...

**Comment by spiderbit** [comment]
btw I get each time exwm-xrandr does its thing:

[XELB ERROR] (cl-assertion-failed (<= 2 (length output-plist))) [2 times]

is that related to that setting and is that fixable:
```elisp
  (setq exwm-randr-workspace-output-plist '(0 "LVDS1" "DP3"))
```

**Comment by ch11ng** [comment]
> btw I get each time exwm-xrandr does its thing:

I fixed the bug in 3d643fafbe58d9b3e2dc9e864cbf05a2d911e1b2.  So in your case, when you turn off the monitor and it appears to be disconnected, there would be no output available so EXWM will simply do nothing if you do not configure the hook.

**Comment by spiderbit** [comment]
yes I just testet the git version, and it works like you say. Even when I manuelly start my xrandr script it resises now the emacs-window accordingly to the new lower resolution.

Basicly this bug I would consider fixed. that said, do you save somewhere in exwm-(randr) the current active monitor or resolution? or dpi or something then I could add a hook like that but with different values for each monitor:

```elisp
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (set-frame-font "Bitstream Vera Sans Mono-9")
            )
          )
```

**Comment by ch11ng** [comment]
> do you save somewhere in exwm-(randr) the current active monitor or resolution? or dpi or something then I could add a hook like that but with different values for each monitor:

* You can use xrandr to get the active output and its resolution.
* The Emacs frame on active workspace is `exwm-workspace--current`, you can use `frame-pixel-width` and `frame-pixel-height` to get its geometry.
