### ISSUE TITLE
Keyboard lose access to X11 windows.

### ISSUE THREAD

**Issue by adouzzy** [ch11ng/exwm#11]
After some useage,
keyboard has no response in X11 windows.  The status line shows "Read only buffer"
I can do C-q exwm-send-next-input to regain access. However, after switch to emacs buffer and switch back, I lose access again. C-q would still work.

This could be cause by my wrong customization.
I spawn X11 applications by (async-shell-command "firefox &").
I also wrote a short function to paste paragraph into urxvt.
with   (exwm-input--fake-key 'S-insert)
  (exwm-input--fake-key 13)
 
Any ideas?

**Comment by ch11ng** [comment]
"Read only buffer" perhaps indicates that key events are (wrongly) sent to the Emacs frame. This means the input focus is lost due to some bugs. You may set input focus to the window by click it.

There are many input focus issues right now. Some has been fixed locally but to others I still have no idea.

**Comment by adouzzy** [comment]
Okay, I replicate this.
I have split windows. Left is emacs buffer, right is X11 urxvt.
I can use (other-window 1) to switch between them.
Now I C-c k, turn urxvt to char mode. No problem here.
When I run a command (other-window 1). The focus switch to emacs buffer, but when I type, I still types on the urxvt buffer.
I click back to the urxvt buffer, I can still type, but exwm-reset won't change it back to the line-mode anymore. but it still works.
Now if I continue to use (other-window 1) to switch between windows, it gives me this
Lisp error: (wrong-type-argument number-or-marker-p nil)
(Vector (logan value 255) .... )
xcb:-pack-u4-lsb(nil)
(if ( slot-value obj ....
...
...
...
xvb:marshal-field([eieio-class-tag--xcb:GrabKey t 33 0 nil 32768 0 1 1 3] xcb:WINODW nil 2)
...
...
...

After this, I can not type on the X11 buffer. (Mouse still works, can click).

I think what I can do is write a function to check for line-mode before (other-windows 1)

Cheers,

**Comment by ch11ng** [comment]
`exwm-reset` is broken by @1e36a22. I will push the fix later.
