### ISSUE TITLE
Melpa

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#110]
Would it be possible to add this project to melpa. I know that it is currently on gnu elpa but because of that updates are rolled out to users less frequently than they would be with melpa. If thats not how you want distribute the package I understand and I'll just clone it instead :). Thanks for the great project, its been my only window manager on all my computers for the past few months and I've loved it

**Comment by ch11ng** [comment]
I don't mind if someone other forks it and adds it to MELPA, but won't do it myself.  I'll try to update it on GNU ELPA as often as possible.
