### ISSUE TITLE
Sending C-c to the terminal

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#111]
Hi,

Could you please consider adding C-c C-c to send C-c to the application (like, xterm) as one of the default keybindings?  I could customize it in my configuration, but since C-c prefix is considered mode specific, I think, it may be preferable if exwm default config has this keybinding.

Thanks,
Chaitanya

**Comment by ch11ng** [comment]
So what other applications will benefit from this key binding? If there's a great demand for this, then I'll consider it.

I personally use <kbd>C-q</kbd> as a prefix key to do this, but that can't be made standard.

**Comment by bvk** [comment]
I mostly use exwm+xterm as a faster alternative to ansi-term and ansi-term forwards C-c C-c as C-c to kill any hung commands, etc. So, this will be useful for all ansi-term users.

Most other GUI applications use C-c key as the copy operation. Exwm has M-w for it by default, so I don't know how much other apps benefit from this. That said, IIRC X11 has different copy-to-buffer operations (eg: copy-by-select vs copy-by-C-c), so there may be an unlikely use case for M-w to be different from C-c C-c based copying.

**Comment by bvk** [comment]
Actually, I was wrong. Exwm default configuration doesn't have M-w, my bad :(

**Comment by ch11ng** [comment]
If we use <kbd>C-c C-c</kbd> to copy text then we need a way to send <kbd>C-v</kbd>.  For me it seems <kbd>C-q C-c</kbd> and <kbd>C-q C-v</kbd> are more consistent.  I think you can safely keep this configuration since I'll stick to <kbd>C-c \<letter\></kbd> in the near future.

**Comment by bvk** [comment]
No issues. I can live with that. I just want to bring this to your
attention:


http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting
of C-c and a letter (either upper or lower case) are reserved for users;
they are the only sequences reserved for users, so do not block them.

> Sequences consisting of C-c followed by a control character or a digit
are reserved for major modes.

> Sequences consisting of C-c followed by {, }, <, >, : or ; are also
reserved for major modes.


Exwm user guide mistakenly mentions that C-c prefix is reserved for major
mode, which seems to be in contradiction with what the manual says. It also
defines some keybindings which actually fall into reserved-for-user key
space.

**Comment by ch11ng** [comment]
Sorry but I didn't notice it.  I'll modify the keymap to comply with the convention.  Also I'll still avoid using <kbd>C-c C-c</kbd>.

**Comment by pedrormjunior** [comment]
How could you send C-c to xterm? I'm trying to use `term-send-raw` but no success. I simply cannot send the C-c to xterm... This feature is really required.

**Comment by ch11ng** [comment]
@pedrormjunior, I've just added an [FAQ entry](https://github.com/ch11ng/exwm/wiki#how-to-send-c-c-to-term) for this.  term.el has nothing to do with EXWM actually.
