### ISSUE TITLE
pinentry-gtk window doesn't render when called from auth-source

### ISSUE THREAD

**Issue by wgreenhouse** [ch11ng/exwm#113]
Hello,

I keep my authentication credentials in ~/.authinfo.gpg. I use the gnupg agent and gpg 2.0.x.

When an Emacs command (for example, `gnus`, or `erc-tls`, or a `find-file` command using a TRAMP path) wants to ask `auth-source` for credentials, and my gpg passphrase is not in the agent cache yet, a `pinentry-gtk` window appears. However, in exwm 0.2, this window is never completelt rendered; instead I see only a blue rectangle where the window would be. Typing my passphrase blind into the window I am able to continue and unlock the credentials.

If I instead do something like `gpg2 --decrypt ~/.authinfo.gpg` from `eshell`, I do not see this visual glitch and the window renders immediately.

I know nearly nothing about X protocol details, but I suspect that somehow EXWM is not finishing the placement of the pinentry window while Emacs is waiting for `auth-source-search` to complete.

This is a new issue in exwm 0.2 and apparently a regression from 0.1, where pinentry rendered correctly in this context.

**Comment by ch11ng** [comment]
Thanks for reporting.  This issue has been in 1c79e1c2384128915357ea629fc2a0503bd36733.  It also helps fix the flickering issue with floating X windows.
