### ISSUE TITLE
Suggest add a command:  jump-or-exec

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#115]
Suggest add a command which is like: 

https://github.com/SawfishWM/sawfish/blob/cc2e49ba6e9cb91d6ad4622f6d691adef777773b/lisp/sawfish/wm/commands/jump-or-exec.jl

**Comment by ch11ng** [comment]
What does it exactly do?

**Comment by tumashu** [comment]
Use firefox as a example:
if firefox not start, this command will run firefox's command, if firefox start, this command just jump to the firefox's window instead of start a new one.

**Comment by tumashu** [comment]
This command is my most frequently used command when i use sawfish and stumpwm, It is a kind of Alt-TAB

**Comment by ch11ng** [comment]
I think rather than implementing such a feature myself, it's more preferable for someone else who would use it daily to write and maintain it as an extension.  We should provide more public interfaces to EXWM first.

**Comment by tumashu** [comment]
OK

**Comment by tumashu** [comment]
I hack a very simple version：

```
  (defun eh-exwm/jump-or-exec (regexp cmd)
    "Jump to a window which buffer's name matched `regexp',
if matched window can't be found, run shell command `cmd'"
    (let* ((buffer
            (car (delq nil (mapcar
                            #'(lambda (buf)
                                (when (string-match-p regexp (buffer-name buf))
                                  buf))
                            (buffer-list)))))
           (buffer-window (when buffer
                            (get-buffer-window buffer))))
      (if buffer
          (if buffer-window
              (select-window buffer-window)
            (switch-to-buffer buffer))
        (start-process-shell-command cmd nil cmd))))
```

**Comment by ch11ng** [comment]
> I hack a very simple version：
> 
> ```elisp
>   (defun eh-exwm/jump-or-exec (regexp cmd)
>     "Jump to a window which buffer's name matched `regexp',
> if matched window can't be found, run shell command `cmd'"
>     (let* ((buffer
>             (car (delq nil (mapcar
>                             #'(lambda (buf)
>                                 (when (string-match-p regexp (buffer-name buf))
>                                   buf))
>                             (buffer-list)))))
>            (buffer-window (when buffer
>                             (get-buffer-window buffer))))
>       (if buffer
>           (if buffer-window
>               (select-window buffer-window)
>             (switch-to-buffer buffer))
>         (start-process-shell-command cmd nil cmd))))
> ```

You probably need to also take buffers on other workspaces into account.

**Comment by tumashu** [comment]
```
You probably need to also take buffers on other workspaces into account.
```
Yes， but it is beyond my elisp ability

The below is my current version:

```
  (add-hook 'exwm-update-class-hook #'eh-exwm/rename-buffer)
  (add-hook 'exwm-update-title-hook #'eh-exwm/rename-buffer)

  (defun eh-exwm/rename-buffer ()
    (exwm-workspace-rename-buffer
     (format "EXWM@%s@%s@%s"
             (or exwm-title "")
             (or exwm-instance-name "")
             (or exwm-class-name ""))))

  (defun eh-exwm/jump-or-exec (regexp cmd)
    "Jump to a window which buffer's name matched `regexp',
if matched window can't be found, run shell command `cmd',
this command must work with `eh-exwm/rename-buffer'."
    (let* ((buffers (buffer-list))
           buffers-matched-title
           buffers-matched-instance
           buffers-matched-class
           buffers-alist buffer buffer-window)

      (dolist (buffer buffers)
        (let* ((buffer-name (buffer-name buffer))
               (list (split-string buffer-name "@")))
          (when (string-match-p regexp buffer-name)
            (when (string-match-p regexp (nth 1 list))
              (push buffer buffers-matched-title))
            (when (string-match-p regexp (nth 2 list))
              (push buffer buffers-matched-instance))
            (when (string-match-p regexp (nth 3 list))
              (push buffer buffers-matched-class)))))

      (dolist (x (list buffers-matched-class
                       buffers-matched-instance
                       buffers-matched-title))
        (when x
          (push (list (length x) x) buffers-alist)))

      (setq buffer
            (car (car (cdr (car (sort buffers-alist
                                      #'(lambda (a b)
                                          (< (car a) (car b)))))))))
      (setq buffer-window
            (when buffer
              (get-buffer-window buffer)))

      (if buffer
          (if buffer-window
              (select-window buffer-window)
            (switch-to-buffer buffer))
        (start-process-shell-command cmd nil cmd))))

```
My all exwm config is : https://github.com/tumashu/emacs-helper/blob/master/eh-exwm.el

**Comment by tumashu** [comment]
```
I think rather than implementing such a feature myself, it's more preferable for someone else who would use it daily to write and maintain it as an extension. We should provide more public interfaces to EXWM first.
```
When you start a project which is like exwm-contrib,  I will refactor my exwm config to generate one or two extensions, please note me.

**Comment by ch11ng** [comment]
> When you start a project which is like exwm-contrib, I will refactor my exwm config to generate one or two extensions, please note me.

Or you can just edit the wiki and put a link to your tools.

**Comment by tumashu** [comment]
i do not like write and manage wiki...
