### ISSUE TITLE
How to let floating window hide?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#116]
In my machine, a floating window can't hide, it will stay on the top of the windows stock, I have to kill it or switch it ot tilling mode when i want to see its behind window., I suggest add a hide command.

**Comment by ch11ng** [comment]
You can use <kbd>C-c C-m</kbd> to move it to another workspace for now.

**Comment by tumashu** [comment]
Good tip, thanks!

**Comment by ch11ng** [comment]
You can use <kbd>C-c C-h</kbd> to hide a floating X window since 5a39c5c2fad643a656c59c0071f0cbea58eb65a9.
