### ISSUE TITLE
emacs package: "switch-window" seem conflit with exwm

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#117]

**Comment by ch11ng** [comment]
Yes, it doesn't work on my first try.  And after checking its code I suspect more things can potentially be broken since it actually switches all buffers to display the big figure.  ace-window is a working alternative as someone once mentioned.

**Comment by tumashu** [comment]
I try the ace-window, but I think ace-window is nearly useless (can't see the guide key) for exim while  switch-window's mode is very confortable

**Comment by tumashu** [comment]
Do you know the conflit reason?

**Comment by tumashu** [comment]
I find the reason, when a x-window exist,  read-event can not read a key,  so input is nil,
how to deal with it? 

```
(let ((input
       (event-basic-type
        (read-event
         (if minibuffer-num
             (format "Move to window [minibuffer is %s]: "
                     (switch-window-label minibuffer-num))
           prompt-message)
         nil switch-window-timeout))))
  (princ input))
```

**Comment by tumashu** [comment]
Maybe this can deal with the problem, but it seemd to be obsoleted
```
(push 'switch-window exwm-input-command-whitelist)
```

**Comment by ch11ng** [comment]
This is actually because switch-window causes input focus lost.  It's fixed in 4838f2b7fa2a8f3bdd2a8b2f779039a1b397e12b, but it won't for all X windows.

**Comment by tumashu** [comment]
Any suggestion?

**Comment by ch11ng** [comment]
I think it's fixed, for almost all X windows.

**Comment by tumashu** [comment]
I mean how to let switch-window works with exwm...

**Comment by ch11ng** [comment]
> I mean how to let switch-window works with exwm...

It should work now.  Do you still have any issues?

**Comment by tumashu** [comment]
oh, my fault, it can work now, thanks very very very much!

**Comment by tumashu** [comment]
New code broke switch-window again

**Comment by ch11ng** [comment]
> New code broke switch-window again

It's caused by dimitri/switch-window@56ef6e306d76ec6ab2d370243d2d387ea9f07f73.

**Comment by tumashu** [comment]
Oh, I will fix it.
