### ISSUE TITLE
About mode-line when exwm-mode enable

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#122]
When exwm-mode is enable, default mode-line seemd useless, what about redraw mode-line to
a taskbar or  test-docker when exwm-mode enable?

**Comment by tumashu** [comment]
or title-bar?

**Comment by ch11ng** [comment]
The mode-line displays the buffer name which is useful when switching buffers.  It also shows various other info that can be useful to some users.  I don't think it's possible to move it elsewhere.  If you don't need it, you can toggle it with <kbd>C-c C-t C-m</kbd> or bind the corresponding command to `exwm-manage-finish-hook`.

**Comment by tumashu** [comment]
exwm-manage-finish-hook can not do what I expected,  I only want to change the mode-line of buffer assocated with a x-window, not all the mode-line,

The below seem to work, but it can not update when x-window's status update, another hook may be needed
```
  (defun eh-exwm/update-mode-line-format ()
    (setq mode-line-format
          (concat " " (buffer-name) " ------------- [X] [_]"))
    (force-mode-line-update))

  (add-hook 'exwm-mode-hook 'eh-exwm/update-mode-line-format)

```

**Comment by ch11ng** [comment]
Just use

```elisp
(add-hook 'exwm-manage-finish-hook #'exwm-layout-hide-mode-line)
```

Currently there's a problem that the mode-line may not update when shows up.  You can use `exwm-reset` to force an update for now.  I'll push a fix later.

**Comment by tumashu** [comment]
感觉 exwm-manage-finish-hook 这个hook的行为很难预期，我使用了其他方式来实现我需要的功能了。。。

**Comment by ch11ng** [comment]
`exwm-manage-finish-hook` is run when an X window just got managed with the corresponding buffer being current.  All information about this X window should be available at this time.

**Comment by tumashu** [comment]
![_001](https://cloud.githubusercontent.com/assets/67725/13352860/3b31e690-dccb-11e5-9d68-ca53b18864d2.png)

This is a snapshot, mode-line as  taskbar is possible....

**Comment by ch11ng** [comment]
> This is a snapshot, mode-line as taskbar is possible....

Sorry I misunderstood you.  Of course it's feasible and you can customize `header-line-format` to place it on top of the X window.  I prefer the default format somehow.

**Comment by tumashu** [comment]
header-line-format is possible too and a exist package: tabbar can be used, but i prefer mode-line :-)

**Comment by tumashu** [comment]
![_003](https://cloud.githubusercontent.com/assets/67725/13415067/a3a5bc5a-df92-11e5-983c-ce1da9f56554.png)

Tilling window and floating window save different mode-line
```
[-]: h-split
[|]: v-split
[+]: max-window
[_]: hide floating window
[X]: kill buffer
```

**Comment by tumashu** [comment]
```
[zoom]:  resize current floating window size to 75% screen size
```
