### ISSUE TITLE
Suggest a window info get function

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#123]
I need a function which is like this:
```
(defun exwm-get-wininfo-from buffer (buffer-or-name)
 ...)
```
The output may be a list:
```
(:class "aaa" :instance "bbb" :title "ccc")
```

is this way possible or have another way i don't know?

**Comment by ch11ng** [comment]
Please take a look at the [List of buffer-local variables](https://github.com/ch11ng/exwm/wiki#list-of-buffer-local-variables) section of the wiki.  You can access them in a `with-current-buffer` block.
