### ISSUE TITLE
Some questions about floating window move and resize

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#125]
1. At the moment, we neet press Win key before move or resize a window, it it possible to do the job while don't press Win?
2. I want to add two buttons to floating-window's mode-line, when I hold press Mouse key on these buttons, I can move or resize window, if possible, please tell me your suggestion, thanks!

**Comment by tumashu** [comment]
3. is it possible add a toggle function,  when it enable, i can resize or move floating window only with mouse-1 and mouse-3?

**Comment by ch11ng** [comment]
> At the moment, we neet press Win key before move or resize a window, it it possible to do the job while don't press Win?

The behaviors are controlled by `exwm-input-move-event` and `exwm-input-resize-event` respectively.

> I want to add two buttons to floating-window's mode-line, when I hold press Mouse key on these buttons, I can move or resize window, if possible, please tell me your suggestion, thanks!

Yes it's possible, and you can even do this without EXWM (see `track-mouse`).

> is it possible add a toggle function, when it enable, i can resize or move floating window only with mouse-1 and mouse-3?

I think so.

**Comment by tumashu** [comment]
I find this file may useful to learn: http://www.opensource.apple.com/source/emacs/emacs-39/emacs/lisp/mldrag.el

**Comment by tumashu** [comment]
In my opinion, This is a very big issue if we want exwm to become a usable floating WM,

**Comment by ch11ng** [comment]
> In my opinion, This is a very big issue if we want exwm to become a usable floating WM,

IIRC most tiling window managers use the same key to move/resize floating X windows.  I don't see the benefit of other ways you proposed -- to make it be more like a stacking WM?

**Comment by tumashu** [comment]
you are right  if  you think exwm  is a tilling window with  some floating  support,
most tilling wms do that is because they are no titlebar,  have to do.
