### ISSUE TITLE
Hide mouse pointer in exwm windows when keyboard is active

### ISSUE THREAD

**Issue by bvkchaitanya** [ch11ng/exwm#126]
By default, Emacs hides the mouse pointer each time you type a self-inserting character.  I notice that this doesn't happen when exwm is managing a window.

I think it would be nice to have this behavior uniform across all windows.

**Comment by ch11ng** [comment]
Would [unclutter](https://sourceforge.net/projects/unclutter/) resolve the problem?

**Comment by bvkchaitanya** [comment]
I will test this later and re-open the ticket if necessary. Closing this for now.
