### ISSUE TITLE
Input error when I type 163 user and password

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#128]
Please tray http://www.163.com/ "登录"

**Comment by ch11ng** [comment]
I don't get it.

**Comment by tumashu** [comment]
I have tested on two machine, the problem exist

**Comment by tumashu** [comment]
When I type tuma in user field, it will become t@163.com and insert u in password field

**Comment by tumashu** [comment]
![_001](https://cloud.githubusercontent.com/assets/67725/13414923/59302fe4-df91-11e5-89fb-9a8f48362d3d.png)

**Comment by ch11ng** [comment]
Fixed in 93e42136e3eba95c129c92a928b0c27517f2af7e.
