### ISSUE TITLE
freenode IRC channel #exwm

### ISSUE THREAD

**Issue by wkmanire** [ch11ng/exwm#13]
Hey,

I'm really excited about your project. I talked it up in #emacs and created a channel on freenode for it. You should jump on freenode and register the channel and become the OP for it so that your community of users have a place to go for realtime help.

Great work!

**Comment by tumashu** [comment]
good job.

**Comment by ch11ng** [comment]
Thank you, @wkmanire . I will see if I can spare some time on this. I'll mail you then.
