### ISSUE TITLE
Is it possible save window status of floating window?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#130]
A floating window's size and position info will be lost when toggle floating, it it possible to save these infos when toggle floating?

**Comment by ch11ng** [comment]
It's possible but I'm not sure if it should be the default behavior.

**Comment by tumashu** [comment]
Maybe we can add a custom

**Comment by ch11ng** [comment]
This is fixed in 2597f74c7fb9ad290a45c89d0025bebcf739a976.  This should be the default behavior.
