### ISSUE TITLE
Is it possible to temp switch to other WM then switch back exwm

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#131]
I use words with the help of crossover, it has many problems when crossover run in the exwm, Is it possbile temp switch to another WM when i run crossover?

The crossover problem:
1. exim can't work
2. many menu popuped have become floating window with mode-line

**Comment by ch11ng** [comment]
> Is it possbile temp switch to another WM when i run crossover?

You need another application (a terminal for example) to launch/kill EXWM and other window managers.

> The crossover problem:
> 1. exim can't work

You can still use other input methods in EXWM.

> 2. many menu popuped have become floating window with mode-line

This is probably a bug.  I'll take a look when I get the time.

**Comment by tumashu** [comment]
```
You can still use other input methods in EXWM.
```
I can't let ibus's icon show in exwm's tray, and C-Return can't call ibus too, so ....

**Comment by tumashu** [comment]
![_004](https://cloud.githubusercontent.com/assets/67725/13458474/6347ecc0-e0a8-11e5-8b4a-b13182cccb61.png)

**Comment by tumashu** [comment]
QQ + crossover can work, but buggy

**Comment by ch11ng** [comment]
Are there any lightweight application running in Wine/CrossOver that has the same problem?

**Comment by tumashu** [comment]
QQ, a lightweight application :-)

**Comment by ch11ng** [comment]
> QQ, a lightweight application :-)

Does it have the same problem?

**Comment by tumashu** [comment]
Yes!

**Comment by tumashu** [comment]
![_009](https://cloud.githubusercontent.com/assets/67725/13492068/eb47af5c-e170-11e5-86a7-d7d2df394edc.png)

**Comment by ch11ng** [comment]
Fixed in 8706e490fb07617145a32ba9eaffd4ee37f67d87.

**Comment by tumashu** [comment]
我测试了一下，发现两个问题：
1.  QQ右键弹出菜单速度太慢了，但可以使用
2,  word2007右键弹出菜单不可以点击。。。

**Comment by ch11ng** [comment]
> QQ右键弹出菜单速度太慢了，但可以使用

I don't have an account (and I don't want to get one) so I can't test it.

> word2007右键弹出菜单不可以点击

I don't have a copy so I cannot test it either.

Please provide *lightweight* free software (or at least freeware) without the need of registration so I can investigate this problem further.

**Comment by tumashu** [comment]
WoW....

**Comment by tumashu** [comment]
I will open a new issue about Wine or crossover!
