### ISSUE TITLE
About "'Iceweasel' is not responding...."

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#132]
Open xfce4-terminal and iceweasel, when i kill xfce4-terminal's buffer, 
"'Iceweasel' is not responding. Would you like to kill it? (yes or no) " showed, why?

**Comment by ch11ng** [comment]
> Open xfce4-terminal and iceweasel, when i kill xfce4-terminal's buffer, 
"'Iceweasel' is not responding. Would you like to kill it? (yes or no) " showed, why?

Because Iceweasel was busy.  But how can I reproduce this issue?

**Comment by tumashu** [comment]
1. start iceweasel
2. start nautilus
3. kill nautilus's buffer
show: "'Iceweasel' is not responding. Would you like to kill it? (yes or no) "

**Comment by ch11ng** [comment]
Fixed in fe9be0b3efab284dae9eb1de37e97a70a9e08bd2.
