### ISSUE TITLE
About contrib package name

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#133]
我想把我的配置整理一下，做个package，下面是这个包可能的名字，你打算要保留哪个名字作为官方扩展包的名称，先告诉我一声。。。。。

1. exwm-ext
2. exwm-contrib
3. exwm-utils
4. exwm+
5. exwm-x
6. exwm-goodies
7. exwm-lib
8. exwm-tools 
9. exwm-extras
10. exwm-extension(s)

**Comment by ch11ng** [comment]
Actually no two packages should share a same prefix; it's confusing.  Just name it as something like '\<prefix\>-exwm' and use it as the prefix of all the functions/variables therein.

**Comment by tumashu** [comment]
```
Actually no two packages should share a same prefix; it's confusing. Just name it as something like '<prefix>-exwm' and use it as the prefix of all the functions/variables therein.
```
'<prefix>-exwm'  is not a common way, as i know.

**Comment by ch11ng** [comment]
> "prefix-exwm" is not a common way, as i know.

Or whatever prefix you considered appropriate but does not conflict with existing packages.

**Comment by tumashu** [comment]
Of course

**Comment by tumashu** [comment]
I have selected the name exwm-x: https://github.com/tumashu/exwm-x
