### ISSUE TITLE
Suggest add new local variable `exwm-id'

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#134]
Different exwm buffer has different exwm-id, which can as a primary key if we think exwm buffer is a kind of database.

**Comment by ch11ng** [comment]
It's now private (`exwm--id`).  You probably don't need it if you won't operate on it directly.  The buffer object itself can be used as an ID.

**Comment by tumashu** [comment]
```
The buffer object itself can be used as an ID.
```
我实际遇到的问题是： 我需要为一个按钮生成mouse-1的event代码，这个代码在生成的时候，必须确定一个Id，来定位需要切换或者删除的buffer，所以，这个id必须是数值或者字符串，buffer对象似乎不行，
(exwm--id)更不行。。。。

**Comment by ch11ng** [comment]
> 所以，这个id必须是数值或者字符串（有时候需要保存生成的event代码），buffer对象似乎不行

I don't see why.

> (exwm--id)更不行

`exwm--id` is a local variable (but please don't use it).

> 如果一个buffer的名字变了，buffer对象变不变？

No.

**Comment by tumashu** [comment]
我试试，然后再讨论

**Comment by tumashu** [comment]
It can work, thanks!
