### ISSUE TITLE
Firefox download window can't show YES button?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#136]
![_010](https://cloud.githubusercontent.com/assets/67725/13547821/c8ff9372-e31b-11e5-85c5-902cb0861fcf.png)

**Comment by fm4d** [comment]
Here is another glitch with firefox and buttons http://fm4d.net/out.ogv

**Comment by ch11ng** [comment]
Fixed in f0a5425f4c176c487a5c3e94319f0c2b3d3cc22a.
