### ISSUE TITLE
Startup error with emacs master

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#137]
https://gist.github.com/fm4d/9bfb88d39660b273e42d this error occurs with emacs master branch, 25.0.90 is ok.

**Comment by tumashu** [comment]
emacs-25 branch can work, please see https://github.com/ch11ng/exwm/issues/135

**Comment by tumashu** [comment]
By the way,  gist.github.com is blocked by author's country, please don't use it as reference...

**Comment by ch11ng** [comment]
> By the way, gist.github.com is blocked by author's country, please don't use it as reference...

I don't have the problem.  You can prepare logs in whatever reasonable way.

**Comment by tumashu** [comment]
... goodluck!

**Comment by ch11ng** [comment]
Fixed upstream.
