### ISSUE TITLE
Let exwm works better with windows apps by Wine and Crossover

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#138]
Windows apps launched by Wine or Crossover may not works well with exwm, this need more tester to test....

the below disscuss can be found: https://github.com/ch11ng/exwm/issues/131

**Comment by ch11ng** [comment]
Currently EXWM has some issues with undecorated X windows, and Wine is affected.

**Comment by ch11ng** [comment]
I'm closing this issue for it's too generic.  Basically there's no difference between X windows created by Wine applications and native programs from X11's perspective.  Please open issues for individual applications, and of course they should at least be freewares or we'll have a hard time validating the issues.
