### ISSUE TITLE
Suggest add exwm , xelb and exim to melpa

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#139]

**Comment by ch11ng** [comment]
EXIM will likely be merged into EXWM.  And distributing them through MELPA is not within my consideration.

**Comment by tumashu** [comment]
Please tell you reason, or just you don't like melpa?

**Comment by ch11ng** [comment]
I don't use it thus I won't maintain packages for it.

**Comment by tumashu** [comment]
..., I will pull melpa recipts if you nave no object....

**Comment by tumashu** [comment]
if you don't want to exwm and xelb showed in melpa, just comment in https://github.com/melpa/melpa/pull/3665

**Comment by tumashu** [comment]
```
Please close this PR because both packages are already in GNU ELPA, and I prefer distributing tested versions only.
```
It just a resonalbe reply than:

```
I don't use it thus I won't maintain packages for it.
```
