### ISSUE TITLE
Suggest add "exwm-contrib" project

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#14]
I want to add some utils to exwm, for example: debian-menu, suggest add a exwm-contrib project

**Comment by wkmanire** [comment]
Personally, I think this is a good idea but should probably wait until exwm becomes more mature. It's not even on any package repositories yet.

**Comment by ch11ng** [comment]
I agree with @wkmanire . We may change the internal design of EXWM rapidly, so utilities written for the current code may not work well in the future.

**Comment by tumashu** [comment]
ok.

**Comment by ch11ng** [comment]
Due to copyright restriction, we cannot accept arbitrary contributions into EXWM. A third-party project may be possible, but that would not be necessarily within my control.
