### ISSUE TITLE
Add a feature: when I focus a tilling window, hide all floating windows above it

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#141]

**Comment by ch11ng** [comment]
What's the point? If an X window is obscured then what you should do is to move it to another empty workspace -- just like what you would do with other tiling window managers.

**Comment by tumashu** [comment]
```
What's the point? If an X window is obscured then what you should do is to move it to another empty workspace -- just like what you would do with other tiling window managers.
```
Can it move it to another empty workspace when i check the below tilling window?

**Comment by ch11ng** [comment]
> Can it move it to another empty workspace when i check the below tilling window?

Sorry but I don't understand this sentence.  If my previous reply was not clear enough I mean moving the beneath tiling X window to another workspace.

**Comment by tumashu** [comment]
![_015](https://cloud.githubusercontent.com/assets/67725/13562116/7c493de4-e46f-11e5-827f-d55d8f9ea656.png)

I mean hide firefox when i shitch to xfce4-terminal...

**Comment by ch11ng** [comment]
> I mean hide firefox when i shitch to xfce4-terminal...

Yes, and I mean you should move xfce4-terminal to another empty workspace so that it won't be obscured.  Of course you should switch to that workspace to use it then.  Alternatively you may set xfce4-terminal floating or fullscreen.

**Comment by tumashu** [comment]
```
Yes, and I mean you should move xfce4-terminal to another empty workspace so that it won't be obscured. Of course you should switch to that workspace to use it then. Alternatively you may set xfce4-terminal floating or fullscreen.
```
This is not my expected answer, another question,  when I focus to xfce4-terminal, which hook will be run?

**Comment by ch11ng** [comment]
I won't implement this feature, so I'm closing it.

> when I focus to xfce4-terminal, which hook will be run?

EXWM uses `buffer-list-update-hook`, but you can try `focus-in-hook`; it might be simpler.
