### ISSUE TITLE
How to remove a keybinding from the default exwm-input-set-simulation-keys list

### ISSUE THREAD

**Issue by bvkchaitanya** [ch11ng/exwm#143]
For me, the (S-end delete) bound to C-k doesn't work inside the terminal. So, I would like to remove it from the default list.  Could you show me to do that?  Thanks.

**Comment by ch11ng** [comment]
There's no default simulation key; you must have set it using `exwm-input-set-simulation-keys` somewhere in your config file.  If you use `exwm-config-default` then you should remove it.
