### ISSUE TITLE
setxkbmap don't work in line mode

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#144]
impossible to switch the keyboard layout in line mode
work's in char mode

**Comment by ch11ng** [comment]
Can you reproduce it consistently? I tried `setxkbmap dvorak` and found no issue.  Maybe `xcb:keysyms:auto-update` is disabled?

**Comment by guskovd** [comment]
of course

I am trying to adjust the layout switch with:
setxkbmap -layout "us, ru" -option ctrl:nocaps -option grp:lctrl_toggle,grp_led:scroll

it work's in char mode, but does not work in line mode

my full .xinitrc

# Disable access control
xhost +SI:localuser:$USER

# Themes, etc
gnome-settings-daemon &

# Fallback cursor
xsetroot -cursor_name left_ptr

# Keyboard repeat rate
xset r rate 200 60

# Layout switch
setxkbmap -layout "us, ru" -option ctrl:nocaps -option grp:lctrl_toggle,grp_led:scroll

# Start Emacs
exec dbus-launch --exit-with-session emacs

**Comment by guskovd** [comment]
xcb:keysyms:auto-update enabled

**Comment by ch11ng** [comment]
I'm not a hundred percent sure why it happens, but it sounds to me like that it's an incompatibility issue with XKB.  EXWM cannot support XKB now because Emacs 24 does not support it, and it seems the server only sends legacy KeyPress events which are then forwarded to the X window.  The keyboard group info is lost during this process.  If this is the case then I'm afraid we have to wait at least a few months to fix it (when Emacs 25 is released).

**Comment by asafonov** [comment]
I  can confirm the issue.

GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9)
Emacs and exwm are current git version

Will be happy to provide any additional information if needed

**Comment by ch11ng** [comment]
@asafonov, does running setxkbmap before launching EXWM (in `.xinitrc`) and setting `xcb:keysyms:auto-update` to `nil` (in `.emacs`) make the new keyboard layout usable?

**Comment by asafonov** [comment]
@ch11ng No, it doesn't 
My xinitrc looks like
```
xscreensaver -no-splash &
setxkbmap -layout "us,ru" -option "grp:caps_toggle"
xhost +SI:localuser:$USER
xsetroot -cursor_name left_ptr
xset r rate 200 60
exec dbus-launch --exit-with-session emacs
```
`xcb:keysyms:auto-update` is set to `nil`

Keyboard layout works perfectly in any emacs buffer (gnus, rcirc, eshell)
But if I run browser (personally I can reproduce the issue with google-chrome every time) keyboard layout doesn't work in it
Running google chrome in fullscreen mode (C-c C-f) fixes the issue, but not in fullscreen mode layout stops working

**Comment by asafonov** [comment]
@ch11ng 
If I remove the line
```
setxkbmap -layout "us,ru" -option "grp:caps_toggle"
```
from my xinitrc, so Caps Lock key works its normal way, it works in google-chrome perfectly. So the issue is only occured when I use Caps Lock to switch keyboard layout

**Comment by ch11ng** [comment]
@asafonov, you can also use `char-mode`.  The cause of the problem is probably what I said in https://github.com/ch11ng/exwm/issues/144#issuecomment-197843082 , and to fix it we need to use the XKB X11 extension, which is a rather complicated protocol by itself.  Maybe we can adapt the code (xcb-keysyms.el) to use that extension sometime later.

**Comment by asafonov** [comment]
@ch11ng ok, thanks. I know about `char-mode` so it's a minor issue, I suppose.
Anyway, thank you a lot for the amazing work you've done, it definitely made my life better.
Cheers

**Comment by ch11ng** [comment]
I've managed to get XKB extension working in ch11ng/xelb@f5216dc13ff44a9f86bdff18272d9b8db1ee7cc5, and I believe this issue as a result is fixed.

**Comment by asafonov** [comment]
I confirm the fix

**Comment by pigmej** [comment]
From: Chris FengSent: wtorek, 19 lipca 2016 15:19To: ch11ng/exwmReply To: ch11ng/exwmSubject: Re: [ch11ng/exwm] setxkbmap don't work in line mode (#144)@asafonov, does running setxkbmap before launching EXWM (in .xinitrc) and setting xcb:keysyms:auto-update to nil (in .emacs) make the new keyboard layout usable?

**Comment by ch11ng** [comment]
@pigmej, it should work, and `xcb:keysyms:auto-update` has been removed.
