### ISSUE TITLE
EXWM assumes that we don't have any terminal emacsclients

### ISSUE THREAD

**Issue by wgreenhouse** [ch11ng/exwm#146]
EXWM has at least these two problems if the user creates a text-mode emacsclient:

Recipe 1:
- Run EXWM
- Start an ``emacsclient -t`` instance, for example in a Linux console.
- Attempt to run a command that reads from minibuffer, such as M-x or C-x b.
- ``exwm-layout--on-minibuffer-setup`` will run and error because we're not on an X frame and it calls ``x-focus-frame``.

Recipe 2:
- Run EXWM
- Start an ``emacsclient -t`` instance, for example in a Linux console.
- Switch back to your EXWM-managed X server
- Attempt to launch an X client program.
- XELB will error with "[XELB ERROR] (error "[XELB] No X display available")". Apparently this is because ``x-server-name`` is now ``nil``.
- Workaround: ``(setq x-display-name (frame-parameter (selected-frame) 'display))`` and we can again launch X clients. Perhaps EXWM should use the frame-local value by default to avoid this situation.

**Comment by ch11ng** [comment]
Thanks for reporting.  They're fixed in fa204e136718e106a87414dd145d16748d5b7262 and ch11ng/xelb@28c0579ff4f74a256f3fe8e6462b6c507848cec6.
