### ISSUE TITLE
Regression: can no longer abort ``exwm-char-mode`` from keyboard

### ISSUE THREAD

**Issue by wgreenhouse** [ch11ng/exwm#149]
As of fa204e136718e106a87414dd145d16748d5b7262 I am no longer able to use the ``s-r`` keybinding to abort ``exwm-char-mode``, even though I still have

```elisp
(exwm-input-set-key (kbd "s-r") #'exwm-reset)
```
in my Emacs init, as recommended by ``exwm-config``.

Clicking the EXWM item in my mode line is now necessary to return to line mode.

Resetting from keyboard still works for exiting fullscreen mode, however.

**Comment by ch11ng** [comment]
It was broken by a previous commit.  Fixed in c7c233bc356fc6a846a09aa5fb13710e6706fce1.
