### ISSUE TITLE
Programs do not get put into a buffer when re-opened

### ISSUE THREAD

**Issue by cadadr** [ch11ng/exwm#15]
When I close a program (i.e. Firefox), and re-open it with the `s-&`[1] command, it does not get assigned to a buffer, but it is ran in the background, i.e. I can see it w/ `list-processes`. I do not know if this is an issue merely with Firefox or all the GUI programs in general, as I do not have any other GUIs to run. I do not really know what to do to debug this, but I'd try to help if I was told how to do.

[1] I use the default config from the wiki, without any modifications.

**Comment by ch11ng** [comment]
I believe this problem was fixed in @3b9d0dd, try update your local repo and try again.

**Comment by cadadr** [comment]
Oh, yes it seems to be fixed, excuse me. And thank you for the project itself, it was something I wanted for years.
