### ISSUE TITLE
Multiple-monitors support

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#150]
Hi,

I have several questions about multiple monitors, sorry if this isn't the right place, but I don't know of any other :-)

- Is there a way to have a keyboard shortcut to switch monitor?
- I can't seem to spawn an X window on one of the monitors. When I try to `C-x b` to it, nothing happens. It works fine for normal emacs buffers.

I have setup the randr example in the wiki, and this works fine, but it's pretty limited by the 2 points above.

**Comment by ch11ng** [comment]
> - Is there a way to have a keyboard shortcut to switch monitor?
> - I can't seem to spawn an X window on one of the monitors. When I try to C-x b to it, nothing happens. It works fine for normal emacs buffers.

Just forget about monitors; there're only workspaces.  Basically you switch between workspaces and the corresponding monitors will be automatically selected.  And normally you cannot switch to an `exwm-mode` buffer on another workspace; you probably need to move it with <kbd>C-c C-m</kbd>.

**Comment by ralt** [comment]
You rock. Thanks!
