### ISSUE TITLE
Debugger error on startup

### ISSUE THREAD

**Issue by mhlr** [ch11ng/exwm#152]
I am running emacs25 (installed from `emacs-snapshot` ubuntu package) and EXWM installed from melpa.
When I log in I get a small emacs window (or frame in emacs terms) in the U-L corner of the display
with a `*Bactrace*` buffer containing
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  make-network-process(:name "XELB" :remote "/tmp/.X11-unix/X0")
  xcb:connect-to-socket()
  exwm-init()
  run-hooks(window-setup-hook)
  #[0 "	\203\306	!\n\2042\2032\f\307=\203'\310\311!\312\"\210\313\314!!\315P\2021\314\316\317\320 \321 $!
\204;\322\323\324\"\210!\204Q\"\203Q#\204Q\"\325=\203t$\300=\204`\326\327\330\331\332 $\210\333\334!\203i\334 \210\333\335!\203t\335\336 !\210\333\337!\203}\337 \210
?\205\205\322\340!\207" [(("-cdac$" . 1.3)) default-directory auto-save-list-file-name auto-save-list-file-prefix system-type inhibit-startup-hooks abbreviate-file-name ms-dos make-directory file-name-directory t make-temp-name expand-file-name "~" format "%s%d-%s~" emacs-pid system-name run-hooks emacs-startup-hook term-setup-hook pc set-face-attribute default nil :font font-spec fboundp frame-notice-user-settings frame-set-background-mode selected-frame font-menu-add-default window-setup-hook frame-initial-frame initial-window-system noninteractive face-font-rescale-alist] 6]()
  normal-top-level()

```

my init.el contains:

``` elisp
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
```

This sounds similar to #135, but I have installed everything from repository packages.
Both `emacs-shot` and EXWM have been updated within the last week.

**Comment by ch11ng** [comment]
> This sounds similar to #135

Yes if the Emacs version is 25.1 (<kbd>C-h v emacs-version RET</kbd>). Also there's another open issue (#137).

**Comment by mhlr** [comment]
Yes I am on 25.1.50.2, but I thought the problem in #135 and #137 was due to issues with 24 which were fixed in 25. What is the solution I am are already on 25?

**Comment by ch11ng** [comment]
Some changes were made in the master branch of Emacs repo and `make-network-process` seems broken since then.  Actually if you don't mind build Emacs yourself you should clone the emacs-25 branch; that is what will become Emacs 25.1.  You can also use Emacs 24 and it just works.  I'll look into this issue a little later.

**Comment by ch11ng** [comment]
Fixed upstream.
