### ISSUE TITLE
Workspace doesn't change when clicking on another monitor

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#153]
Setup: dual monitors, each one on its own workspace. The 2 workspaces have X windows.

How to reproduce the bug:

- Be on workspace 1 focusing an X window.
- Switch on workspace 2 using the mouse that focuses a non-X window (i.e. a file open in emacs)
- EXWM will still think you're on workspace 1, which means that `C-x b` doesn't find the X window of workspace 2. (And `s-w` is buggy.)

**Comment by ch11ng** [comment]
I have no external monitor at the moment so I'll check this problem a little later.  Also, did you mean <kbd>s-w</kbd> is buggy all the time or just in this case?

**Comment by ralt** [comment]
It's only buggy in this case, in the sense that the selected workspace is the wrong one.

**Comment by ch11ng** [comment]
Fixed in ddbbeda285b3b671ace99f1688e6bd3c3f84c742.

**Comment by ralt** [comment]
Awesome! I'll try it out.
