### ISSUE TITLE
Workspace offset (Feature Request)

### ISSUE THREAD

**Issue by yrdz** [ch11ng/exwm#155]
I'm interested in using an external program to display information along the top (or bottom) of my display. However, I would like to avoid having this program obscure parts of exwm. Would it be possible to add a variable to shrink the size of the workspace vertically? 

For example, could you make two variables `exwm-top-offset` and `exwm-bottom-offset` with default values of 0 and change the workspace configuration section of exwm-workspace.el from `:y 0` to `:y exwm-top-offset` and from `:height (x-display-pixel-height)` to `:height (- (x-display-pixel-height) exwm-top-offset exwm-bottom-offset)`?

I suppose for versatilitiy's sake these variables should also exist for horizontal offsets, but it's not as clear to me how that would be useful.

Thanks

**Comment by ch11ng** [comment]
May I ask what is the external program? If it's something like a panel or a dock then I think it's time to implement the rest part of EWMH.  The work would be tedious but not tricky basically.  I cannot assure you this will happen soon because I'm quite busy these days.

**Comment by yrdz** [comment]
Yeah it's a panel. Sorry, I didn't realise that EWMH included that sort of thing. 

With regards to future implementation: I am unfamiliar with EWMH and X in general, and not particularly interested in filling out the necessary paperwork to submit significant changes, but I would appreciate it if you could give me some insight into how to implement it so that I could attempt to do so for personal use/as a reference for future changes.

**Comment by ch11ng** [comment]
You might take a look at the specification (https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html), the property `_NET_WM_STRUT_PARTIAL` describes exactly what you requested.  By reading this property and calculate the usable area (and we should update `_NET_WORKAREA`) we can get Emacs properly placed.  You may use the `xprop` tool to check what properties an X window has set.
