### ISSUE TITLE
exwm doesn't know what to do when a fullscreen window starts another fullscreen window

### ISSUE THREAD

**Issue by razcampagne** [ch11ng/exwm#159]
Hi,

When using steam in big picture (in fullscreen), you can start a game which will probably start also in fullscreen, with steam itself still displaying a fullscreen window.

It seems (but I don't really know how to debug this behavior) exwm doesn't know how to handle the game's window and might even lose track of the first fullscreen window.

I'm sorry I don't have any more details, I'm mostly looking for pointers to look into the issue.

Thanks!

(sorry for the non-floss centric bug reports, but apart from that exwm does work pretty well)

**Comment by ch11ng** [comment]
Are there any error messages? If not please run the following command before and after opening the second fullscreen X window (you may need to switch to the console) and show me the outputs.

```
DISPLAY=:0 xwininfo -root -tree
```

**Comment by razcampagne** [comment]
I reproduced the issue and you can find the output of xwininfo in the following gist, before steam big picture, during and after launching a fullscreen game:
https://gist.github.com/razcampagne/1abc0b0629851b6c75b80b66f742cf7c

Steam seems to launch a lot of silent windows. I tried 2 times the same process and it seems steam exits fullscreen mode when launching a game but then, EXWM just hangs. I have no mouse, no keyboard and I can't start an emacsclient in another tty.
Using ssh I might be able to step into the code just before the hanging, if you have any idea which function I should enable edebug for :/

**Comment by ch11ng** [comment]
What if you first make the Steam X window floating and then make it fullscreen? It should make a difference because in this case the Steam X window won't get hidden after the game starts.  As for the output of xwininfo I'm not sure why both Steam and game X windows became floating.  Maybe it's because the Steam X window got hidden.

> Using ssh I might be able to step into the code just before the hanging, if you have any idea which function I should enable edebug for :/

Just use `pkill -SIGUSR2 emacs` after Emacs hangs.  If the input is still not usable, you can switch to a console and use emacsclient to connect.

**Comment by razcampagne** [comment]
I tried what you suggested but it didn't change exwm's behavior.
Actually, the way steam works is by having a normal window, tiled in exwm's frame. When I ask for Big Picture mode (a gaming console-like interface), It creates a fullscreen window, independant from the main, normal one.

After it freezed, I tried sending SIGUSR2 but that didn't unfreeze emacs. I regained the mouse cursor but I couldn't click anywhere. The keyboard was still unresponsive and emacsclient wouldn't respond either. 

All I could get is a "[XELB] Received Reply Timeout" message in *Warnings* buffer.

I'll try some other stuff when I have the time.

**Comment by mejine** [comment]
picture, during and after launching a fullscreen game:
https://gist.github.com/razcampagne/1abc0b0629851b6c75b80b66f742cf7c

Steam seems to launch a lot of silent windows. I tried 2 times the same process and it seems steam exits fullscreen mode when launching a game but then, EXWM just hangs. I have no mouse, no keyboard and I can't start an emacsclient in another tty.
Using ssh I might be able to step into the code just before the hanging,??????????"

**Comment by mejine** [comment]
reproduced the issue and you can find the!

**Comment by ch11ng** [comment]
> Actually, the way steam works is by having a normal window, tiled in exwm's frame. When I ask for Big Picture mode (a gaming console-like interface), It creates a fullscreen window, independant from the main, normal one.

I can't find the extra X window in outputs though.  And the output "no-fullscreen" seems to be taken before Steam was made floating, right?

> After it freezed, I tried sending SIGUSR2 but that didn't unfreeze emacs. I regained the mouse cursor but I couldn't click anywhere. The keyboard was still unresponsive and emacsclient wouldn't respond either.

When emacs hangs, it usually consumes 100% CPU usage.  Is that the case?  If SIGUSR2 doesn't work, you may also try sending the default SIGTERM (for only once).

> All I could get is a "[XELB] Received Reply Timeout" message in *Warnings* buffer.

Well this is an abnormal behavior.  Perhaps some error was made in a request.  Also could you visit the `*Messages*` buffer?

**Comment by ch11ng** [comment]
The fullscreen state was actually not even checked when an X window starts.  This has been fixed in ebcc9591f3c1210efda007bec6852369b75fa8ad.  Could anyone verify if this issue has been resolved?

**Comment by razcampagne** [comment]
Sorry for the delay, I couldn't even try to answer your earlier questions…
But I am pleased to tell you this issue has indeed been fixed!

Thank you very much for your hard work :)
