### ISSUE TITLE
Error on small screens

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#16]
I'm not sure whether this error solely due to my configuration, but it is reproducible _on my machine_, so there might be something to correct.

I use `Xephyr` to use `exwm` without having to _all-or-nothing_ on it.  When the screen height is smaller than `624` pixels, exwm loops in an error.  I don't seem to be able to capture the error backtrace as both keyboard and mouse are unusable.

Using the following command to start `exwm` fails:
~~~{.sh}
Xephyr -screen 800x623 :10 & sleep 2s; DISPLAY=:10 sh ./xinit
~~~

But the following is OK:
~~~{.sh}
Xephyr -screen 800x624 :10 & sleep 2s; DISPLAY=:10 sh ./xinit
~~~
Note that only the height has changed, from `623` to `624`.

The `xinit` script consists the following:
~~~{.sh}
exec dbus-launch --exit-with-session emacs -q --load ~/repos/exwm/init.el "$@";
~~~
Note that, contrary to the `xinit` script in the Wiki, `gnome-settings-daemon` is not started, as it tries itself to change the screen size.

The backtrace is as follows:
~~~
logand(nil 255)
...
xcb:-pack-u4-lsb(nil)
...
xcb:-marshal-field([eieio-class-tag--xcb:FreePixmap t 51 1 nil]  xcb:PIXMAP nil 2)
...
xcb:marshal
...
xcb:-cache-request
...
xcb:-+request
...
xcb:cursor:-load-cursor
...
xcb:cursor:load-cursor
...
exwm-floating--init
...
~~~

Thank you for sharing this package.

Best regards,
uu1101

**Comment by ch11ng** [comment]
Hi @uu1101. Thank you for helpful report. It's bug in [xelb-util/xcb-cursor.el](https://github.com/ch11ng/xelb-util/blob/2d78724580849d91a9b5a2b45180b21117d3a315/xcb-cursor.el). I'll push a fix later.

**Comment by uu1101** [comment]
This does fix it.  Thank you very much for your effort!
