### ISSUE TITLE
failed to start(Arch linux)

### ISSUE THREAD

**Issue by q120248681** [ch11ng/exwm#160]
Used exwm-config-default
Error Message:
error in process filter:[XELB]Connection failed:No protocol specified

**Comment by ch11ng** [comment]
Did you use the `xinit` file shipped with the source?

**Comment by q120248681** [comment]
I replaced my .xinitrc file with the xinit file in the source

**Comment by ch11ng** [comment]
Have you tried [this](https://github.com/ch11ng/exwm/wiki#one-last-thing)? Or do you have unconventional setup?

**Comment by q120248681** [comment]
Oh,sorry I didn't notice that. It works,thanks!
