### ISSUE TITLE
Focus is lost when you change the desktop

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#161]
Sometimes the window loses focus when switching desktop. If I try to enter text, it is sent to the previous workspace(frame)

it drives me crazy
I was able to reproduce the bug. 

This occurs when the first desktop usual emacs buffer. Second - x-window buffer in char/line mode
(from emacs buffer to x-window buffer)

**Comment by ch11ng** [comment]
I can confirm this but I have no solution yet because it cannot be reproduced reliably.

**Comment by guskovd** [comment]
maybe you can advise some workaround?

**Comment by ch11ng** [comment]
If you can reliably reproduce this bug, it'd be helpful if you make a bug report according to [ths](https://github.com/ch11ng/exwm/wiki#how-to-report-a-bug) (I only need the content of the `*Messages*` buffer).

**Comment by guskovd** [comment]
[EXWM] Refresh workspace #<frame emacs@localhost 0x116ee88>
[EXWM] Refresh workspace #<frame emacs@localhost 0x5558310>
[EXWM] Refresh workspace #<frame emacs@localhost 0x5583b50>
[EXWM] Refresh workspace #<frame emacs@localhost 0x4fa8050>
[EXWM] Refresh workspace #<frame emacs@localhost 0x51ced20>
[EXWM] Refresh workspace #<frame emacs@localhost 0x4e53798>
[EXWM] Refresh workspace #<frame emacs@localhost 0x5555930>
[EXWM] Refresh workspace #<frame emacs@localhost 0x586cc80>
[EXWM] Refresh workspace #<frame emacs@localhost 0x584eb60>
[EXWM] Refresh workspace #<frame emacs@localhost 0x5a8d920>
[EXWM] Try to manage #x600001
[EXWM] Manage #x600001
[EXWM] Floating geometry (original, absolute): 1050x1050+0+0
[EXWM] Floating geometry (original, relative): 1050x1050+0+0
[EXWM] Floating geometry (corrected): 1050x1018+435+0
[EXWM] Show #x600001 in #<window 23 on Xephyr>
[EXWM] Refresh workspace #<frame emacs@localhost 0x116ee88>
[EXWM] Refresh floating window #x600001
[EXWM] Show #x600001 in #<window 23 on Xephyr>
[EXWM] Refresh floating window #x600001
[EXWM] Show #x600001 in #<window 23 on Xephyr>
[EXWM] Try to manage #x1000059
[EXWM] Manage #x1000059
[EXWM] Refresh workspace #<frame *scratch* 0x116ee88>
[EXWM] Show #x1000059 in #<window 3 on Pidgin>
[EXWM] Refresh workspace #<frame *scratch* 0x116ee88>
[EXWM] Hide #x1000059
[EXWM] Refresh workspace #<frame *scratch* 0x5a8d920>
[EXWM] Show #x1000059 in #<window 21 on  Pidgin>
[EXWM] Refresh workspace #<frame *scratch* 0x116ee88>
[EXWM] UnmapNotify from #x1200e52
[EXWM] Unmanage #x1200e52 (buffer: nil, widthdraw: t)
[EXWM] Unhandled client message: [object xcb:ClientMessage xcb:ClientMessage t 32 613 380 [object xcb:ClientMessageData xcb:ClientMessageData t (0 0 0 0 164 1 0 0 1 0 224 1 0 0 0 0 0 0 0 0) (name data8 type xcb:CARD8 size 20) (0 0 420 0 1 480 0 0 0 0) (name data16 type xcb:CARD16 size 10) (0 420 31457281 0 0) (name data32 type xcb:CARD32 size 5)]]
[EXWM] Set focus on #x600001
[EXWM] Focus on #x600001 with SetInputFocus
[EXWM] (System Tray) Try to embed #x1000034
[EXWM] (System Tray) Embed #x1000034
[EXWM] (System Tray) Resize from 48x48 to 16x16
[EXWM] (System Tray) Map the window
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Focus on #<window 9 on *scratch*>
[EXWM] ConfigureRequest from #x2000082 (#xf) @1920x1042+0+0; border-width: 0; sibling: #x0; stack-mode: 0
[EXWM] ConfigureWindow (preserve geometry)
[EXWM] ConfigureRequest from #x2000082 (#x40) @1920x1042+0+0; border-width: 0; sibling: #x0; stack-mode: 0
[EXWM] ConfigureWindow (preserve geometry)
[EXWM] MapRequest from #x2000082
[EXWM] Try to manage #x2000082
[EXWM] Manage #x2000082
[EXWM] Refresh workspace #<frame *scratch* 0x4fa8050>
[EXWM] Show #x2000082 in #<window 9 on Mozilla Firefox>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Unhandled PropertyNotify: GDK_TIMESTAMP_PROP(558) [2 times]
[EXWM] UnmapNotify from #x20003a6
[EXWM] Unmanage #x20003a6 (buffer: nil, widthdraw: t)
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Unhandled PropertyNotify: _NET_WM_ICON_NAME(351)
[EXWM] Unhandled PropertyNotify: WM_ICON_NAME(37)
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Set focus on #x2000082
[EXWM] Focus on #x2000082 with SetInputFocus
[EXWM] Focus on #<window 7 on *scratch*> [3 times]
[EXWM] Refresh workspace #<frame  *Minibuf-1* 0x51ced20> [2 times]
[EXWM] Focus on #<window 7 on *Messages*>

**Comment by ch11ng** [comment]
@guskovd, it's preferable to use gists or include short messages as source code, otherwise the messages won't get rendered correctly.  In your case some numbers following the hashtag are missing.

So from what you commented I can't see in which way you were trying to reproduce the bug.  Also I wonder why there were no messages like `[EXWM] Focus on workspace 0` (they're generated when you switch to a workspace containing no X window).  I guess you meant the last few lines were wrong, but again they're not readable.

Could you please try another time and post the messages (please keep optional modules like systemtray / RandR disabled so we can focus on this issue)?

**Comment by guskovd** [comment]
>  Also I wonder why there were no messages like [EXWM] Focus on workspace 0 (they're generated when you switch to a workspace containing no X window)

for me:
(message "focus-in-hook: %s" focus-in-hook)
=> nil

exwm-workspace.el: 693 (add-hook 'focus-in-hook #'exwm-workspace--on-focus-in) 
seems to be never run

**Comment by guskovd** [comment]
I do not know why it happens,
but this is true for emacs24 and emacs25,
even if I use a simple configuration

**Comment by ch11ng** [comment]
Duh! I placed that line at a wrong place.  I've just fixed it.  It might not resolve this issue however.

**Comment by guskovd** [comment]
I can not no longer reproduce this bug
