### ISSUE TITLE
Fix or provide alternatives for frame parameters

### ISSUE THREAD

**Issue by wacossusca34** [ch11ng/exwm#163]
EXWM seems to only be able to operate with frames that cover the entire monitor -- frame parameters either don't work (dimension settings), or screw up EXWM's behaviour (frame positions other than (0, 0)) -- causing X windows to be misaligned with the actual buffer coordinates.

Might seem like a "why would you want to do that?" report, but I'm trying to write a panel (X window) for extra information (time, date, sound, network, tray) at the top of my monitor. Having some usable functions for positioning frames could also allow people to hack together multi-monitor setups that only use a single X screen.

(tested using `set-frame-parameter` with `exwm-init-hook` (buggy behaviour) and using `default-frame-alist` (no behaviour)).

**Comment by ch11ng** [comment]
There's also another proposal (#155).  EXWM currently does not respect these frame parameters, and it can be problematic to use them directly.  So the scheme in #155 seems to be more reasonable.

> Having some usable functions for positioning frames could also allow people to hack together multi-monitor setups that only use a single X screen.

Indeed this is not a problem.  You can just enable the RandR module and configure multiple monitors as a single output.  No hack is required.

**Comment by wacossusca34** [comment]
I'm not too familiar with EXWM/XELB's code (or elisp for that matter), so I'm not sure how I'm supposed to go about changing window properties suggested in #155. The proposal in #155 would be incredibly helpful if it were implemented.

**Comment by ch11ng** [comment]
Sorry but I have no free time to implement this at the moment.  This feature can be easy to implement, but I want to implement other features altogether so it is a lot of work.

**Comment by wacossusca34** [comment]
I had some free time and attempted at changing the window/WM properties (screwing with `_WM_WORKAREA` of the root window) -- I can't seem to get any effect. I also can't seem to resize emacs at all (but I can shift the x,y position of it with frame params)

It would really help if you could shed some light on the approach I would have to take to have emacs and EXWM buffers operating in a [x,y,w,h] area (I'm really not all too familiar with your code or elisp at all).

**Comment by ch11ng** [comment]
I'll see if I can find some free time and check out the specifications carefully.  Please note your panel application will also need to be EWMH-compliant, and perhaps multi-monitor panel is a little tricky to implement.

**Comment by ch11ng** [comment]
I've added initial support for this feature in 650ed0013c3fac9e88328086d1f4a029f4fb7221.  It may not work for certain set ups (RandR, multiple docks/panels, for example), and some features are still missing (workspace/application switching from panel) which I'll add in the future.  Please provide feedback if anything is not working for your application.

**Comment by ch11ng** [comment]
@wacossusca34, @yrdz, as of 4ac71a7ddc78d1485a7fca7a8dbf4c4f6b4016f2, this feature is almost complete.  Some tips on panel implementation (generally also apply to other window managers):

* It should be of type `_NET_WM_WINDOW_TYPE_DOCK`;
* It should also set `_NET_WM_STRUT_PARTIAL` correctly.

They're all descried in the EWMH specification.

**Comment by wacossusca34** [comment]
ch11ng: you are a saint -- thank you! I will get to testing this when I have some free time.

**Comment by wacossusca34** [comment]
So, I tested it a bit and I'm quite happy (I tested all of this with the tint2 panel, using code I pulled ~2 hours ago):

- Fullscreen applications work, moving the panel to the top, side, bottom all work without needing to restart emacs (although there are sometimes glitches with X window frames). Even some things I would expect to screw up EXWM worked perfectly (ie. setting weird margins/alignments)

- Panel _hiding_ doesn't seem to work correctly, as I noted above sometimes the frames do not correctly update and will overlay the (properly) updated emacs frame (ie. it will draw over the modeline). Example here: http://i.imgur.com/QHDxCOe.png

- In the above screenshot, I also have demonstrated that floating windows do not show the modeline. I'm not sure why, looks like this is a new bug since I did not get it before pulling the new code.

- Looks like switching between X windows via the panel works without any flaws (although tooltips displayed by tint2 don't want to render any text, this may be a tint2 bug: http://i.imgur.com/4qZeIcj.png)

- Tint2 always thinks it's in fullscreen mode, so if you configure it to allow all fullscreen windows to fill the entire screen, the panel will draw over emacs: http://i.imgur.com/JNxCR12.png .

- Tint2 doesn't seem to have a setting for a 'floating' panel (a panel that doesn't reserve any space, and just floats above or under all the windows). I know some other panels/docks can do this, so it might be worth testing. Interestingly, the behaviour in the above 'bug' can be used with tint2 to actually get the effect of a floating panel: http://i.imgur.com/n7LSa8x.png (bottom right corner)

Conveniently, all the bugs that I found don't actually affect what I intend to use a panel for (I want one with applets, time, system info/temps along the top of my screen).

Thank you so much for putting your time into getting EXWM to be EWMH compliant! I am closing this, because it solves my issue.

**Comment by wacossusca34** [comment]
A small update on the modeline missing on floating frames: the issue only starts to occur once I change some settings with the panel and cause emacs to update its working area, so it can be fixed by restarting emacs after any panel changes.

**Comment by ch11ng** [comment]
> + Panel *hiding* doesn't seem to work correctly, as I noted above sometimes the frames do not correctly update and will overlay the (properly) updated emacs frame (ie. it will draw over the modeline). Example here: http://i.imgur.com/QHDxCOe.png

Did you refer to the mode line of the bottom left window? And is the bottom bar also a tint2 panel?

> + In the above screenshot, I also have demonstrated that floating windows do not show the modeline. I'm not sure why, looks like this is a new bug since I did not get it before pulling the new code.

I can confirm this.

> + Looks like switching between X windows via the panel works without any flaws (although tooltips displayed by tint2 don't want to render any text, this may be a tint2 bug: http://i.imgur.com/4qZeIcj.png)

Does this work on other WMs?  If it is, please show me the text together with the `xprop` output.

> + Tint2 always thinks it's in fullscreen mode, so if you configure it to allow all fullscreen windows to fill the entire screen, the panel will draw over emacs: http://i.imgur.com/JNxCR12.png .

I don't quite get this one, and inherently the next one.  What does each "fullscreen" means here?

> + Tint2 doesn't seem to have a setting for a 'floating' panel (a panel that doesn't reserve any space, and just floats above or under all the windows). I know some other panels/docks can do this, so it might be worth testing. Interestingly, the behaviour in the above 'bug' can be used with tint2 to actually get the effect of a floating panel: http://i.imgur.com/n7LSa8x.png (bottom right corner)

Thanks for your feedback.  I'll continue improve this feature.

**Comment by wacossusca34** [comment]
> Did you refer to the mode line of the bottom left window? And is the bottom bar also a tint2 panel?

Yes, and the bottom is not a tint2 panel in this screenshot (just the emacs minibuffer and the modelines of the bottom two buffers)

> Does this work on other WMs? If it is, please show me the text together with the xprop output.

I will try with LXDE later, although this bug is the least concerning for me.

> I don't quite get this one, and inherently the next one. What does each "fullscreen" means here?

Sorry, I should have used the term "maximized", not fullscreen. Anything in fullscreen (ie. C-c C-f in EXWM buffer) covers everything as intended.

It's an option that Tint2 has and it's intended to make maximized windows (ie. a fullscreen browser) window draw/cover the panel (thus, taking up the entire screen except for window borders from the WM). It thinks it's always dealing with a mazimized window with EXWM.

**Comment by wacossusca34** [comment]
Seems to also work great with a half-custom panel (fork of a fork of `bar`), it doesn't do much yet but I'm starting to get the look I wanted out of emacs: http://i.imgur.com/dS8JSyv.png

Thanks again for providing EWMH compliance for EXWM.

**Comment by ch11ng** [comment]
I've tried tint2 and here are some updates.

> + In the above screenshot, I also have demonstrated that floating windows do not show the modeline. I'm not sure why, looks like this is a new bug since I did not get it before pulling the new code.

This has been fixed in c22f35620f0db3e86f4b0678a29dc3eee48df4d9, though I don't know the cause of the issue.

>> Did you refer to the mode line of the bottom left window? And is the bottom bar also a tint2 panel?

> Yes, and the bottom is not a tint2 panel in this screenshot (just the emacs minibuffer and the modelines of the bottom two buffers)

I failed to reproduce this one.  Can you reproduce it reliably? I noticed in that screenshot Emacs was probably busy uploading images.  Could that be the cause?

>> Does this work on other WMs? If it is, please show me the text together with the xprop output.

> I will try with LXDE later, although this bug is the least concerning for me.

It works here.  Perhaps you need to change the font color.

>> I don't quite get this one, and inherently the next one. What does each "fullscreen" means here?

> Sorry, I should have used the term "maximized", not fullscreen. Anything in fullscreen (ie. C-c C-f in EXWM buffer) covers everything as intended.

> It's an option that Tint2 has and it's intended to make maximized windows (ie. a fullscreen browser) window draw/cover the panel (thus, taking up the entire screen except for window borders from the WM). It thinks it's always dealing with a mazimized window with EXWM.

I don't know why tint2 provides such feature but there seems to be no way to make EXWM properly working with it.  BTW it's trivial to implement a "floating" dock/panel just by resizing the dock without updating struts.

**Comment by wacossusca34** [comment]
> I failed to reproduce this one. Can you reproduce it reliably? I noticed in that screenshot Emacs was probably busy uploading images. Could that be the cause?

It's not just that line there, anytime I update the panel dimensions/placement, the X windows fail to update unless I resize the buffer for the X window (or any other action in emacs that would cause it to update the working area for that X window). Example: http://i.imgur.com/c3mb2x9.png (note the modline under Firefox).

It occurs before I start taking a screenshot (which is an external process through `(start-process ...)`), so I doubt that's the issue.

The tooltip issue (which I doubt has anything to do with EXWM) and tint2's handling options for maximized windows is not concerning at all for me -- they are probably edge cases at best. I would ignore these bugs.
