### ISSUE TITLE
minibuffer interaction in char mode

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#164]
I use global binding for C-x C-f:
(exwm-input-set-key (kbd "C-x C-f") 'find-file)

if i press:
C-x C-f
~/ Tab Tab (for path completion)

focus returns to x-window and and i can not close minibuffer

**Comment by ch11ng** [comment]
Fixed in 2ec88bd32d0409f182e2532e0763ddb9bc8b21fc.
