### ISSUE TITLE
Can not assign M-: keybinding to eval-expression

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#165]
(exwm-input-set-key (kbd "M-:") 'eval-expression)

doesn't work for me in char mode

**Comment by ch11ng** [comment]
It seems working for me.  Could you double check that?

**Comment by zevlg** [comment]
Works for me too.  You might want to call `(exwm-input--update-global-prefix-keys)` after bound

**Comment by guskovd** [comment]
I apologize for the delay. I researched the problem

after removal of:
setxkbmap -layout "us, ru"
from my .xinitrc M-: keybindings was working normally

**Comment by ch11ng** [comment]
Thanks for your feedback!

**Comment by guskovd** [comment]
my workaround:

(defun my-exwm-init-hook ()
  (start-process "" nil "/usr/bin/setxkbmap" "-layout" "\"us, ru\"" "-option" "ctrl:nocaps" "-option" "grp:lctrl_toggle,grp_led:scroll")
  )

(add-hook 'exwm-init-hook 'my-exwm-init-hook)
