### ISSUE TITLE
Minibuffer is active: Why would `exwm-layout--show' resize the container but not it's content?  

### ISSUE THREAD

**Issue by farva** [ch11ng/exwm#167]
I noticed a problem using _**helm**_, where if I had helm window in a vertical composition with an EXWM window (X window), when the helm window would shrink when narrowing candidates, the windows would resize correctly, but the visible part that was left behind by the helm window and is now part of the EXWM window, is filled with graphical garbage (residues of the helm buffer), and it seems unapproachable X wise.

This of course does not happen with normal buffers, which means that it's related to the fact that resizing is taking place, while the minibuffer is active.

I must admit that I don't even know what container and it's content mean, apart from having something to do with X, but I did solve (from my point of view) the problem by advising **_exwm-layout--resize-container_** to be able to "refresh the content" even when minibuffer is active.

What's wrong with refreshing the content when minibuffer is active? why was this restriction there in the first place?

**Comment by ch11ng** [comment]
That was for the case when the minibuffer would resize itself very frequently (for example when one uses `ido-vertical-mode`).  Apparently it breaks helm.  Could you check whether replacing that `(active-minibuffer-window)` with `(and (active-minibuffer-window) (< 1 (window-height (active-minibuffer-window))))` works? Thanks!

**Comment by farva** [comment]
Works like a charm (at least with *Helm*)

**Comment by ch11ng** [comment]
Fixed in 38332925d0d5655e98416afaa7869bbaddb360b8.
