### ISSUE TITLE
how to set/push  alt or alt-space to prefix-keys

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#168]
I bought a chromebook and dont have a Menu key anymore, nor any other good solo key that makes to much sense to me as prefix key to emacs.

so I want to use Alt-Space as prefix keychord for stuff. It also does work fine inside emacs bound it to a keymap. But in X windows they "steal" tat keys.

So I tried to push Alt or Alt-Space to exwm-input-prefix-keys, I am not shure if I have to reload exwm after I set them or if I used the wrong key-descriptors.

Tried:

`(push 'M exwm-input-prefix-keys)`
and
`(push 'M-SPC exwm-input-prefix-keys)`

both seemed not to work, anything obvious I am doing wrong?

**Comment by ch11ng** [comment]
Perhaps it should be

```elisp
(push ?\M-\s exwm-input-prefix-keys)
```

A single modifier key is not supported yet.

**Comment by spiderbit** [comment]
ok works thanks, is there a way how I get the names of the keys? Neither emacs itself nor xev gives me that names, I would never guessed \s or s for space.

**Comment by ch11ng** [comment]
They are described in the info node `(info "(elisp)Character type")`.  I don't know if there is any easy way to get the names but expressions like `(kbd "M-SPC")` are quite close (you have to to know <kbd>SPC</kbd> is for space though; also `kbd` outputs vectors).
