### ISSUE TITLE
Error when connecting with `emacsclient` from the terminal and different DISPLAYs

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#17]
Using `emacsclient` to connect to the emacs instance running `exwm` fails, as it assumes the frames are floating ones.  The following change makes `exwm` ignore terminal frames and those in different displays.

The patch records the value of `x-display-name` upon startup, as `xcb:connect-to-socket` does not set the `:display` slot in the connection object.  It would probably be better to always set this slot and use that instead of the introduced `exwm--display` variable.

~~~{.patch}
diff --git c/exwm-layout.el i/exwm-layout.el
index 414aa37..39e64ce 100644
--- c/exwm-layout.el
+++ i/exwm-layout.el
@@ -163,12 +163,17 @@
         windows placeholder)
     (if (not (memq frame exwm-workspace--list))
         ;; Refresh a floating frame
-        (progn
-          (cl-assert (eq major-mode 'exwm-mode))
-          (let ((window (frame-first-window frame)))
-            (with-current-buffer (window-buffer window)
-              (exwm--log "Refresh floating window #x%x" exwm--id)
-              (exwm-layout--show exwm--id window))))
+	(cond
+	 ((not (display-graphic-p frame))
+	  (exwm--log "Non-graphical frame: %s" frame))
+	 ((not (eq exwm--display (frame-parameter frame 'display)))
+	  (exwm--log "Frame in a different display: %s" frame))
+	 ((eq major-mode 'exwm-mode)
+	  (let ((window (frame-first-window frame)))
+	    (with-current-buffer (window-buffer window)
+	      (exwm--log "Refresh floating window #x%x" exwm--id)
+	      (exwm-layout--show exwm--id window))))
+	 (t (exwm--log "Unexpected frame: %s" frame)))
       ;; Refresh the whole workspace
       ;; Workspaces other than the active one can also be refreshed (RandR)
       (exwm--log "Refresh workspace %s" frame)
diff --git c/exwm.el i/exwm.el
index 7c9fa59..ca54f4f 100644
--- c/exwm.el
+++ i/exwm.el
@@ -595,11 +595,15 @@
 (defvar exwm-init-hook nil
   "Normal hook run when EXWM has just finished initialization.")
 
+(defvar exwm--display nil
+  "DISPLAY of the initial frame.")
+
 (defun exwm-init (&optional frame)
   "Initialize EXWM."
   (if (not (eq 'x (framep (or frame (selected-frame)))))
       (exwm--log "Not running under X environment")
     (unless exwm--connection
+      (setq exwm--display x-display-name)
       (setq exwm--connection (xcb:connect-to-socket))
       (set-process-query-on-exit-flag (slot-value exwm--connection 'process)
                                       nil) ;prevent query message on exit
~~~

Best regards,
uu1101.

**Comment by ch11ng** [comment]
Thank you, @uu1101. Your analyses are always unique and of precision! I' will complete the missing conditions.

**Comment by ch11ng** [comment]
Hi @uu1101,
Currently there are still some horrible bugs related to `emacsclient -t` and `emacsclient -c` that make Emacs frozen. I think I should discourage the use of `emacsclient` with `-t` or `-c` option. The most convenient way is probably to let `emacsclient` use exiting frames created by EXWM. Anyway, This is a possible use case of EXWM and I should fix the remaining bugs.

**Comment by uu1101** [comment]
Hello,

I've been away these days.  Thank you very much for the fix.  I am using `emacsclient` in order to always have the `*Messages*` buffer open in other console.  This is outside the `EXWM` session.  In any case, the fix above works.  Thank you!

Best regards,
uu1101
