### ISSUE TITLE
Is "mini-frame" feature useful exwm?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#171]
I found a patch about "mini-frame" in emacs-devel mailling list: http://lists.gnu.org/archive/html/emacs-devel/2016-07/msg00719.html , is it useful for exwm?

**Comment by ch11ng** [comment]
I can't figure out how it's supposed to be used in EXWM.  BTW it won't be pushed into the emacs-25 branch so we can't use it even it proves useful.

**Comment by tumashu** [comment]
这个特性能不能进master还两说呢，我就是告诉你一下这个信息，如果确实对exwm有用,就在emacs-devel上支持一下patch的作者

**Comment by ch11ng** [comment]
I can't think of a usage of that patch in EXWM so it seems no useful in the first place.  I'm closing this issue now.
