### ISSUE TITLE
List of visible workspaces / frames

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#173]
Would it be possible to add a variable which would contain a list of frames currently visible on all workspaces (with xrandr)? It could be very handy for things like https://github.com/abo-abo/ace-window and https://github.com/noctuid/link-hint.el , to give them only currently visible frames instead of all frames.

**Comment by ch11ng** [comment]
What does it mean? All frames are considered visible, including workspace frames, floating frames, user-created frames and perhaps a standalone minibuffer frame.

**Comment by fm4d** [comment]
Well I mean that when I have 10 workspaces and 2 monitors, only 2 workspaces are visible and I would like to get a list of frames on those 2 workspaces.

**Comment by ch11ng** [comment]
Currently we don't record the stacking order of workspaces so we can't tell which is the top-most workspace on the other output (monitor).  Since this info is not immediately available, we can't provide it if there's no other use of it.

**Comment by spiderbit** [comment]
Can I reopen that or do I need to open a new bug. Just bought a second big monitor for dual-head and I think I have the same or a similar problem, now I don't use ace-window.

But why are workspaces that are internally as far as I understand implemented as frames counted as visible when they are not visible? I don't even think you need a special list a frame has the property of visibility, right?

So the workaround is to use only 2 buffers then you can use following to switch between all windows on both monitors:
```emacs-lisp
(defun sb/next-window ()
  "docstring"
  (interactive)
  (other-window 1 'visible))
```

The problem with that is if you want to use more than 2 workspaces it breaks and it needs more setup, for no good reason. I am now a bit confused if you display 2 buffers on 1 monitor does this count as 2 windows or 2 frames? In classic emacs termology that would be seen as 2 windows but 1 frame, right? But when I use:
(visible-frame-list) I get 2 frames for it.

So I am not sure in how to implement it then, you probably need some stacking information, not only the "current frame" of each monitor that you have to update on randr events and change-workspace events.

But I don't think breaking build-in emacs functionality is a good alternative like `other-window` and `(visible-frame-list)`
