### ISSUE TITLE
"Workspace index out of range" error when using Guake dropdown terminal

### ISSUE THREAD

**Issue by vedvyas** [ch11ng/exwm#175]
When showing a [Guake](https://github.com/Guake/guake) terminal, the following error appears in the \*Messages\* buffer:

> \[XELB ERROR\] (user-error "[EXWM] Workspace index out of range: 4294967295")

This usually doesn't cause any other problems besides the message. My EXWM session did become unresponsive once after showing the Guake term, and subsequently became responsive after switching to a VT and killing the Guake process. I can't reproduce that at the moment.

Setup: EXWM 0.7 + XELB 0.9 on Emacs 25.0.94.1. `xcb:debug-on` and `exwm-debug-on` were set to `t` prior to calling `exwm-enable`.

**Comment by ch11ng** [comment]
Fixed in ba0f41db1b377196af8aa6607ef215e48a3daa26.  BTW it seems to be a bug in Guake or its dependency libraries; there's no point setting `_NET_WM_DESKTOP` to the largest 32-bit unsigned integer.

**Comment by ch11ng** [comment]
I realized the meaning of that value, but EXWM doesn't support that feature any way.

**Comment by vedvyas** [comment]
Thanks!
