### ISSUE TITLE
How can I hide all floating window when i focus a tilling window?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#178]
When I switch focus from a floating window to tilling window,  the floating window will block the tilling window, How can I hide it when switch to a tilling window?

**Comment by ch11ng** [comment]
You can hide a floating X window with `exwm-floating-hide`.  As for hiding all floating X windows, I really doubt if it's necessary.  If your screen is full of floating X windows, why not switch to a stacking WM?

**Comment by tumashu** [comment]
到目前为止, 我仍然认为这是一个很有用的功能
