### ISSUE TITLE
How can I show headline of buffer of a x-window?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#179]
Is it possible show headline of emacs buffer, which assocated with a x-window?

**Comment by ch11ng** [comment]
You may want to set `header-line-format`.  See `(elisp)Header Lines`

**Comment by tumashu** [comment]
Thanks, this is more useful for x-window than modeline, I think

**Comment by tumashu** [comment]
when I eval (setq-default header-line-format "") , header lines are showed in tilling window, but  floating-x-window can't show header line, Am I miss something?

**Comment by tumashu** [comment]
And how can I predict a buffer is a floating-window buffer?

**Comment by tumashu** [comment]
![- 2016 08 03 - 12 43 54](https://cloud.githubusercontent.com/assets/67725/17354331/2a41dfc6-597a-11e6-8dfe-352994c02cfc.png)
