### ISSUE TITLE
write some help info to exwm buffer.

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#18]
All exwm buffers seem  to be blank,  I suggest write some info, for example, app name ,which is useful when external  app window can not show by some reason

**Comment by tumashu** [comment]
may be a beautiful asicc picture is a good idea

**Comment by ch11ng** [comment]
The underlying buffers are not supposed to be seen by users. If they do, there is probably a bug. Would you describe the situations where `exwm-mode` buffers are visible (but not related to `emacsclient` as I'm working on it)?

**Comment by tumashu** [comment]
ok， i will test future。。。 

By the way，I think we can use Wine QQ as a test app， if exwm can deal with it well， other app may deal with well too。

**Comment by tumashu** [comment]
add some info to exwm buffer， can help debug， i think

**Comment by ch11ng** [comment]
> add some info to exwm buffer， can help debug， i think

and perhaps only for debugging. I'll investigate this later.

**Comment by ch11ng** [comment]
Since users can actually modify the underlying buffers (in hooks for example), I'm closing this issue now.
