### ISSUE TITLE
header line of floating window buffer will be blocked by floating window

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#182]
![2a41dfc6-597a-11e6-8dfe-352994c02cfc](https://cloud.githubusercontent.com/assets/67725/17386027/35cd6e2e-5a19-11e6-8425-d188bb535e7b.png)

**Comment by ch11ng** [comment]
Fixed in dcec998bb446320c6029522a089800cbc6b73b55.

**Comment by tumashu** [comment]
现在可以显示 header-line 了，不过有一个小问题，看容易解决不：
当 header-line 混合显示中文和英文时，header-line 的宽度有时会增加一些，但 x-window 的位置不会相应的调整，所以导致显示的信息不全。
![- 2016 08 07 - 13 46 54](https://cloud.githubusercontent.com/assets/67725/17460806/834c784e-5ca7-11e6-8647-df8b21c67283.png)

**Comment by ch11ng** [comment]
You may try `(force-mode-line-update)`, or even `(select-window (selected-window))`.
