### ISSUE TITLE
Repainting the EXWM system tray

### ISSUE THREAD

**Issue by vedvyas** [ch11ng/exwm#184]
Is it possible to automatically repaint the tray when it is damaged (is that the correct term?) by tool-tips, floating frames, etc., as shown here:

![exwm-systemtray-painting](https://cloud.githubusercontent.com/assets/384205/17458511/af1650d4-5be0-11e6-93c3-c7dbec5af89f.gif)

Currently, I have added `exwm-systemtray--refresh` to several EXWM hooks and have a timer to fire it off periodically.

**Comment by ch11ng** [comment]
Fixed in 06c1b0485a1815d13ded7bd717adf5d9735be3df.

**Comment by vedvyas** [comment]
Thanks!
