### ISSUE TITLE
IntelliJ IDEA (and other pop-up window) issues

### ISSUE THREAD

**Issue by pmiddend** [ch11ng/exwm#185]
There are actually two issues I want to address (both of which prevent me from using exwm full-time). First, the pop-up window that appears when you press Ctrl+n (search for class):

![2016-08-08-092706_1920x1080_scrot](https://cloud.githubusercontent.com/assets/178496/17472424/13c4c9b4-5d4b-11e6-8fa0-8b354210daa1.png)

When I switch to char mode, open it, and then close it again (with Escape or by selecting a class from the drop-down), the main application doesn't receive the input focus so I cannot type anymore.

Second, it seems all the other dialogues are displayed correctly for a millisecond or so, and are then resized to a 1x1cm square, like so:

![2016-08-08-092839_1920x1080_scrot](https://cloud.githubusercontent.com/assets/178496/17472463/57676794-5d4b-11e6-8369-74588da8e886.png)

This doesn't seem to be a Java issue, though. It happens here in my browser file selector, too.

**Comment by ch11ng** [comment]
> When I switch to char mode, open it, and then close it again (with Escape or by selecting a class from the drop-down), the main application doesn't receive the input focus so I cannot type anymore.

This problem exists in many window managers.  I'll try to fix it.

> it seems all the other dialogues are displayed correctly for a millisecond or so, and are then resized to a 1x1cm square

This reminds me of a bug in Emacs fixed a few months ago.  Which version of Emacs are you currently working with?

**Comment by pmiddend** [comment]
I'm currently using 25.0.95.1 (at least that's what emacs --version outputs).

The focus bug doesn't occur with i3, which is my current WM. Tell me if I can help in any way.

**Comment by ch11ng** [comment]
> I'm currently using 25.0.95.1 (at least that's what emacs --version outputs).

This was released in February.  Please do a upgrade and see if the issue disappears.

> The focus bug doesn't occur with i3, which is my current WM. Tell me if I can help in any way.

I guess this is probably a timestamp problem.  I already saw how it was fixed in KDE.

**Comment by pmiddend** [comment]
Okay, with the latest emacs-25.1.50.1, it works (although the mode line on floating dialog windows is annoying, I'm sure this can be disabled?).

**Comment by ch11ng** [comment]
The problem should be fixed by 810b4716a10169e1de29c52cf2e3aeb2e79f2018, and perhaps other Java-related issues are also fixed.

> although the mode line on floating dialog windows is annoying, I'm sure this can be disabled?

You can not disable it completely, but you may try `exwm-layout-hide-mode-line` to hide it.

**Comment by tjackson** [comment]
Regarding floating decorations, I recall doing something like (setq-default exwm--mwm-hints-decorations nil) but I can't test this at the moment. Not sure if that's intended to work or has any negative side effects.

**Comment by ch11ng** [comment]
> Regarding floating decorations, I recall doing something like (setq-default exwm--mwm-hints-decorations nil) but I can't test this at the moment. Not sure if that's intended to work or has any negative side effects.

It works as long as we don't change that variable.  Maybe we should add a public interface for this.
