### ISSUE TITLE
System tray menus don't work on multi monitor setups

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#187]
I noticed that when using EXWM (commit 8e3fc36) and XELB (commit 8197598) on external monitors using xrandr the right click menus on system tray icons does not work. Also the menus of GUI programs and the select drop down boxes in chromium don't work on these external screens.

If I move the GUI programs over the main screen then all these menus work.

In my test I went to http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select in chromium 46.0.2490.71 and it displayed nothing in the drop down. When I move that window (using C-c C-m) to my main monitor (the screen listed first in the XRANDR) then it works as expected.

**Comment by ch11ng** [comment]
I'm not sure if what you reported are actually one single issue.  I can confirm the one with Chromium, but it seems to be a bug of Chromium/GTK itself (see: https://bugs.chromium.org/p/chromium/issues/detail?id=515451 and https://bugs.chromium.org/p/chromium/issues/detail?id=510079).  I noticed in the second report they mentioned the [_NET_WORKAREA](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472697552) property; if there's any way to workaround this bug (which might affect many GTK programs) by setting this property an actually incorrect value, I'd be glad to take it even if it'd violate the EWMH specification.

Also, I'd like to know which tray applications can reproduce this issue.

**Comment by map7** [comment]
Not all tray icons have a problem. volti (volume application) and virt-manager tray icon menus work great on all monitors. The problems seem to happen with my other applications such as Spotify, Dropbox and Insync (google sync), all are not open source :(. I have noticed that the menus for these three applications work only on the main screen and the menu is a floating context menu rather than a fixed menu. It floats at the point of the mouse cursor, whereas the volti and virt-manager have a fixed position just above the system tray.

**Comment by map7** [comment]
Found an open source package which the menu doesn't work in the system tray (on external screens) and that is x2goclient. I have 3 screens using exwm and only the main one will show the menu for this application.

**Comment by ch11ng** [comment]
It also seems all Qt applications are affected.

I have removed the support for `_NET_WORKAREA`, though the specification says this property SHOULD be set by window managers, but in reality it causes more problems than it solves.  Besides in certain circumstances the value of this property can't be correctly calculated.
