### ISSUE TITLE
M-x in exwm-input-prefix-keys not working for x window buffer in line mode

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#189]
I bind M-x to helm-M-x in my emacs buffers, I want the same binding for all exwm window. But it's not working in all three cases below.
1 The default setting doesn't work.
2 Removing M-x from the input prefix keys also doesn't work, I tried with:

    (setq exwm-input-prefix-keys '(?\C-h ?\M-` ?\M-& ?\C-x))

3 Set global keybinding doesn't work.
I tried with:

     (exwm-input-set-key (kbd "M-x") #'helm-M-x)

Is there a workaround?
Thank you!

**Comment by QiangF** [comment]
Alt doesn't seems to be the meta key, I have this setting:

    (defun exwm-toggle-fullscreen()
      (interactive)
      (if (memq xcb:Atom:_NET_WM_STATE_FULLSCREEN exwm--ewmh-state)
        (exwm-layout-unset-fullscreen) (exwm-layout-set-fullscreen)))

    (exwm-input-set-key (kbd "C-M-<return>") #'exwm-toggle-fullscreen)

When press the key binding in a x window buffer,I got this error, <A-C-return> is undefined

**Comment by ch11ng** [comment]
It seems the meta key is not correctly detected.  Could you show me the output of `xmodmap` and the value of `xcb:keysyms:meta-mask` and `xcb:keysyms:alt-mask`?

**Comment by QiangF** [comment]
@ch11ng The relevant information is :

    xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

    shift       Shift_L (0x32),  Shift_R (0x3e)
    lock        Caps_Lock (0x87)
    control     Control_L (0x25),  Control_L (0x42),  Control_R (0x69)
    mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
    mod2        Num_Lock (0x4d)
    mod3      
    mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
    mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

    xcb:keysyms:meta-mask's value is 8
    xcb:keysyms:alt-mask's value is 0

**Comment by QiangF** [comment]
Below is the content of ~/.Xmodmap, it is based on abo-abo's original file.

    keycode  10 = 1 exclam exclam U2081
    keycode  11 = 2 at at U2082
    keycode  12 = 3 numbersign numbersign U2083
    keycode  13 = 4 dollar dollar U2084
    keycode  14 = 5 percent percent U2085
    keycode  15 = 6 asciicircum asciicircum U2086
    keycode  16 = 7 ampersand ampersand U2087
    keycode  17 = 8 asterisk asterisk U2605
    keycode  18 = 9 parenleft parenleft U2089
    keycode  19 = 0 parenright parenright U2080
    keycode  23 = Tab ISO_Left_Tab parenleft ISO_Left_Tab
    keycode  24 = q Q parenright U0398
    keycode  25 = w W question bar
    keycode  26 = e E equal F11
    keycode  27 = r R F11 F11
    keycode  28 = t T asciitilde U03A4
    keycode  29 = y Y grave U03A5
    keycode  31 = i I backslash U03CA
    keycode  32 = o O bar U039F
    keycode  33 = p P U03C0 U03A0
    keycode  37 = Control_L NoSymbol Control_L
    keycode  38 = a A plus F1
    keycode  39 = s S minus F2
    keycode  40 = d D F4 F3
    keycode  41 = f F Delete F5
    keycode  42 = g G semicolon F5
    keycode  43 = h H Left U0397
    keycode  44 = j J Down Next
    keycode  45 = k K Up Prior
    keycode  46 = l L Right U039B
    keycode  47 = Mode_switch Mode_switch Mode_switch
    keycode  48 = apostrophe quotedbl U2014 quotedbl
    keycode  49 = grave asciitilde 0 asciitilde
    keycode  52 = z Z braceleft U0396
    keycode  53 = x X braceright U03A7
    keycode  54 = c C colon U03A3
    keycode  55 = v V Return U03DE
    keycode  56 = b B BackSpace U0392
    keycode  57 = n N bracketleft U039D
    keycode  58 = m M bracketright U039C
    keycode  59 = comma less U2023 less
    keycode  60 = period greater U2022 greater
    clear Control
    clear Lock
    keysym Caps_Lock = Control_L
    !keycode 66 = Control_L
    add Control = Control_L Control_R
    keycode 135 = Caps_Lock
    add Lock = Caps_Lock
    keycode  30 = u U Caps_Lock U03A8

**Comment by ch11ng** [comment]
The output and variable values seem okay.  The meta key is correctly detected (at least for its mask).  I installed your `xmodmap` script but can't seem to reproduce this issue.  Could you try without the `xmodmap` script?

Also a test with `xev` might help reveal the problem.  For instance, if you press <kbd>M-a</kbd> when the `xev` X window has the focus, you'll get one event like this:

```
KeyPress event, serial 34, synthetic NO, window 0x2400001,
    root 0xb2, subw 0x0, time 46555902, (139,626), root:(779,626),
    state 0x8, keycode 38 (keysym 0x61, a), same_screen YES,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False
```

Note (on the third line) the value of state (8), keycode (38) and keysym (must be "a").  If everything goes right then you'll get the following results:

```elisp
(xcb:keysyms:keycode->keysym exwm--connection 38 8)
  => (97 . 3)

(xcb:keysyms:keysym->event exwm--connection 97 8)
  => 134217825 (this is ?\M-a)
```

Are your results same with these?

**Comment by QiangF** [comment]
@ch11ng  No, the result of the last expression doesn't agree with yours.
The events generated by "M-a" are:

    KeyPress event, serial 40, synthetic NO, window 0x1600001,
        root 0xa2, subw 0x0, time 8700542, (417,262), root:(417,262),
        state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1600001,
        root 0xa2, subw 0x0, time 8700733, (417,262), root:(417,262),
        state 0x8, keycode 38 (keysym 0x61, a), same_screen YES,
        XLookupString gives 1 bytes: (61) "a"
        XmbLookupString gives 1 bytes: (61) "a"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1600001,
        root 0xa2, subw 0x0, time 8700849, (417,262), root:(417,262),
        state 0x8, keycode 38 (keysym 0x61, a), same_screen YES,
        XLookupString gives 1 bytes: (61) "a"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1600001,
        root 0xa2, subw 0x0, time 8700867, (417,262), root:(417,262),
        state 0x8, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

The other two results are:

    (xcb:keysyms:keycode->keysym exwm--connection 38 8)
    => (97 . 3)
    (xcb:keysyms:keysym->event exwm--connection 97 8)
    => 4194401 (#o20000141, #x400061)

**Comment by ch11ng** [comment]
The last result is `?\A-a`.  Did you set `x-meta-keysym` to `'alt`?

**Comment by QiangF** [comment]
@ch11ng  Yes, I get that one from milky man's init.el. Problem solved. Thank you so much!
