### ISSUE TITLE
Question: how to start exwm with Xsession

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#190]
Hello everyone,
I am using x2go to remote log in to my computer with openbox, lightdm and exwm installed.
In x2go I set the session type to custom desktop, the command for the session is

    /etc/X11/Xsession

In my home directory, I have .xsession as

    #!/usr/bin/env bash
    source ~/.xinitrc
    export exwm_enable="yes"

    # Emacs X input method (exim) setting
    export XMODIFIERS=@im=exim
    export GTK_IM_MODULE=xim
    export QT_IM_MODULE=xim
    export CLUTTER_IM_MODULE=xim
    export LC_CTYPE="zh_CN.UTF-8"

    # xhost +
    xhost +SI:localuser:$USER
    exec dbus-launch --exit-with-session emacs 

~/.xinitrc contains:

    xsetroot -cursor_name left_ptr
    export VISUAL=emacsclient
    export EDITOR="$VISUAL"
    xmodmap ~/.Xmodmap
    xcape -e 'Control_L=Escape;Shift_L=Control_L|x;Shift_R=Control_L|c' 
    tint2&

I can't make the desktop connection. ssh -X and single applications are OK. Could this be possibley related to exwm?

**Comment by QiangF** [comment]
Or is there a way to start exwm without using xsession?

**Comment by ch11ng** [comment]
I'm not familiar with x2go but can you start other WMs with it? With Xorg you just start a local server and let remote clients connect to it (via ssh for example).  You might want to relax some conditions first, like using `xhost +` instead of `xhost +SI:localuser:$USER` and `ssh -Y` instead of `ssh -X`.

**Comment by QiangF** [comment]
Remote openbox session also doesn't work. The problem is not related to EXWM. I can connect to local desktop running openbox or EXWM. From this line in the x2go log file:

    Session: Session started at 'Tue Aug 30 04:33:43 2016'.
    Info: Established X server connection.

The connection seems fine, but the session is terminated immediately even with xhost +. I will ask the x2go developers for help.
Thank you!

**Comment by ch11ng** [comment]
Perhaps you should run the WM locally and make it manage remote clients.
