### ISSUE TITLE
libreoffice buffer unintended termination

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#192]
Libreoffice buffer closed unexpectedly when opening a file, saving file or after some user interaction. And soon it will even be impossible to start the application window.
I am using EXWM 0.10 on Debian Jessie, emacs version is 24.5. The libreoffice is from the stable repository. I have two computers that have the same issue.

Edit:
When run in a terminal, I get this error:

    X-Error: BadValue (integer parameter out of range for operation)
            Major opcode: 2 (X_ChangeWindowAttributes)
            Resource ID:  0x3fff97f
            Serial No:    12392 (12392)
    These errors are reported asynchronously,
    set environment variable SAL_SYNCHRONIZE to 1 to help debugging
    Application Error

**Comment by ch11ng** [comment]
I can reproduce this with `export SAL_USE_VCLPLUGIN=gen`, but I'm not sure where the problem is.

**Comment by QiangF** [comment]
One workaround is to use Xephyr.  But I ran into another issue: I can't switch to a floating xephyr buffer after using exwm-floating-hide. The following is the method I use to run libreoffice now.

    xhost +local:username
    Xephyr -screen 800x600 -reset -terminate -extension GLX 2>/dev/null :1 &
    export DISPLAY=:1
    libreoffice

**Comment by ch11ng** [comment]
Using Xephyr can't be called a workaround; it basically bypasses the window manager.  I'll try to solve the problem.

**Comment by ch11ng** [comment]
There are actually two issues.

1. With no advanced VCL UI installed, or with `SAL_USE_VCLPLUGIN=gen`, libreoffice would crash just as described here.  It turns out to be an XIM issue.  Do you use EXIM? What if you turn it off?

2. With an advanced VCL UI (libreoffice-gtk3 for example) installed there was another bug which has been fixed in 43af6bb6a295fc843bd8b1f890cca1c246293e90.  I think this is the preferred way to use libreoffice.

**Comment by QiangF** [comment]
Yes, turing EXIM off makes libreoffice happy. But I need exim to type chinese characters. I will try libreoffice-gtk3. Thank you!

**Comment by ch11ng** [comment]
libreoffice-gtk3 is actually merely a UI so it is easy to install.  I've not tried other flavors but they should also work.

There seems to be a memory leak when libreoffice is started with the vanilla UI.  From the `xtrace` log I can see it (or some library on which it depends) ends up making an X request with out-of-range value, and the value is different every time.  EXIM may also be to blame; I'm not sure if something is wrongly implemented but at least it helps trigger that memory leak bug.

**Comment by QiangF** [comment]
With libreoffice-gtk3 everything works! Thank you!
