### ISSUE TITLE
Window is missing property _NET_WORKAREA

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#193]
I have two seperate monitors, each one has its own workspace. When I use rdesktop in full screen mode with either '-g workarea' or '-f' full screen option, both monitor are occupied. With the '-g workarea' option I get this error:

    Window is missing property _NET_WORKAREA
    WARNING: Failed to get workarea: probably your window manager does not support extended hints
    ERROR: CredSSP: Initialize failed, do you have correct kerberos tgt initialized ?

Is it possible to set the missing property in exwm?

**Comment by ch11ng** [comment]
No.  This property was poorly designed and simply cannot be correctly calculated in some situations.  Setting this property can break some applications (Chromium and literally all Qt applications).  Is it possible to use the `-g` option of `rdesktop` to make it fullscreen? Also isn't `redesktop` superseded by `xfreerdp`?

**Comment by QiangF** [comment]
Indeed xfreerdp doesn't have this issue.
Thank you for the tip.
