### ISSUE TITLE
Regular buffers and minibuffer lose keyboard input focus when mouse cursor is over systray

### ISSUE THREAD

**Issue by vedvyas** [ch11ng/exwm#195]
If one starts typing in a regular (not X window) buffer or in the minibuffer, then moves the mouse cursor over an icon in the EXWM system tray, the keyboard input focus seems to go to that icon. Things return to normal once the mouse cursor is moved away from system tray icons. This is with EXWM 4287d31 on Emacs 25.1.1.

**Comment by ch11ng** [comment]
See https://github.com/ch11ng/exwm/issues/194#issuecomment-245251642.

**Comment by ch11ng** [comment]
Sorry for the long delay.  The problem is at least solvable.  I'll determine which is the best solution.

**Comment by vedvyas** [comment]
Cool, thanks!

**Comment by ch11ng** [comment]
I made a fix in 0833e8dc4a3fdb6f0ea9651ece2e7d2d4fae97ec, which I consider imperfect.  Key events should get redirected but you'll probably notice the buffer flickers on every key press.

**Comment by vedvyas** [comment]
I just wrapped up a long-running session and got a chance to try this out. Thanks! I actually don't get any buffer flickering aside from the cursor briefly displaying as inactive (outline only) during key-presses. Another observation is that quitting a minibuffer prompt with C-g does require holding C-g down or moving the mouse cursor away from the tray first.
