### ISSUE TITLE
magit shortcuts block emacs

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#196]
magit shortcuts work weirdly in exwm, for example after I `C-c C-c` a commit message, emacs blocks, and I have to `C-g`, followed by `C-c` to confirm the commit. I don't have this issue in gnome, so it's certainly related to exwm, although it's surely an issue in my setup.

Is there anything I can do to debug this issue? I completely understand that the issue, as is, is clearly incomplete, but that's as far as I can explain.

**Comment by ch11ng** [comment]
See https://github.com/ch11ng/exwm/issues/194#issuecomment-245251642.

**Comment by ch11ng** [comment]
Sorry for the long delay.  I actually use magit quite often recently but have not encountered your problem.  You may try turning on `debug-on-error` and `debug-on-quit` to see where Emacs blocks.

**Comment by ralt** [comment]
No problem for the delay, I hope you enjoyed your vacation!

Thanks for the tips, I'll try to get something.

**Comment by ralt** [comment]
Thanks for the tips! I immediately found an odd hook in `server-done-hook` which was blocking.

It now works flawlessly. Cheers!
