### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#197]
It would be really great if macros could be used to save keystrokes sent to an exwm buffer and then send them back when rerunning the macro. Right now it seems that the keystrokes aren't even seen by emacs because they don't appear in edit macro buffer afterwards.

**Comment by ch11ng** [comment]
I think it's possible.  There're some useful variables such as `defining-kbd-macro` and `executing-kbd-macro` that can be used for this purpose.

**Comment by jtamagnan** [comment]
When I was experimenting it seemed like none of the keys that were pressed in the exwm buffer were even sent to emacs to be recorded. It appeared like none of those keys were even pressed upon inspection of the macro using `C-x C-k <F4>`

**Comment by ch11ng** [comment]
I've added keyboard macro support in f96f565d548521a87e0f3a23bfab7f5b836e4640.  I don't know what is bound to <kbd>C-x C-k \<f4\></kbd> but I suppose it should work.  Please report if there're anything left out.

**Comment by jtamagnan** [comment]
From the very limited testing that I've done it seems to work! Thank you! I had meant `C-x C-k e <f4>` which allows you to see edit and see the keys that the macro is using
