### ISSUE TITLE
Show window title in EXWM buffer name?

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#198]
When I open several document in libreoffice and try to switch to one of them, I will try many times to get to the right one, because the window title is not diaplayed in EXWM buffer name.

**Comment by vedvyas** [comment]
Including `exwm-title` in EXWM buffer names helps with that. For example:

    (defun exwm-rename-buffer ()
      (interactive)
      (exwm-workspace-rename-buffer
       (concat exwm-class-name ":"
               (if (<= (length exwm-title) 50) exwm-title
                 (concat (substring exwm-title 0 49) "...")))))
    
    ;; Add these hooks in a suitable place (e.g., as done in exwm-config-default)
    (add-hook 'exwm-update-class-hook 'exwm-rename-buffer)
    (add-hook 'exwm-update-title-hook 'exwm-rename-buffer)

**Comment by QiangF** [comment]
Perfect!
Thank you!
