### ISSUE TITLE
User interaction blocked by unfinished task in minibuffer

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#199]
It happens in three cases:
1 when the user is typing something in the minibuffer, and a floating buffer pops up asking for some text input. I click on the floating buffer trying to type something but I can't,  the minibuffer is flickring, I click inside the minibuffer, but I can't get back to it.

2 when a program freezes, the minibuffer display a message, saying something like "XX in not responding, kill it Y/N", a careless user may use mouse to click somewhere, eg. I often tries to close the application on the tint2 task bar. Then I can't get back to the minibuffer anymore, EXWM freezes. This has happend twice when I am using libreoffice 5.

3 in the middle of a helm command, the user clicked on another buffer, the helm buffer is left open.

Is it possible to always follow the user's intent, if the user clicked somewhere and there are unfinished task in the minibuffer, abort it by force or kill the program waiting for an answer, and switch focus to the clicked buffer immediately.

**Comment by ch11ng** [comment]
Thanks for the report! This is a problem of course but I think it should not be fixed in the way you proposed.  Emacs allows the minibuffer to be active while some other window getting selected, and we should make this behavior consistent.  I'll fix this issue after the release of version 0.11.

BTW you may be able to use <kbd>C-]</kbd> to recover sometimes.

**Comment by QiangF** [comment]
Thank you for the tip!

**Comment by ch11ng** [comment]
Sorry but I've not fixed this issue yet.  Everything concerning input focus is a bit tricky.  Please leave this issue open.

**Comment by ch11ng** [comment]
Fixed in 089afdc8ccbd37647f3b9d3b6181db5bcf3e43e9.
