### ISSUE TITLE
 frames lose focus periodically

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#20]
Sometimes they lose focus very frequently, like for every second, that it became very difficult to write this bug report.  Things become normal after couple I switched workspaces couple of times -- not sure what exactly happened behind the scenes.

Also, could we log focus switches to *Messages* buffer with the window names? It would be helpful in debugging.

**Comment by bvk** [comment]
It seems, focus is switching to windows in other (possibly,
previously active) workspace because I can see some characters
typed in other windows which I didn't type.

Also, this seems to happen when commands are running in the ansi-term
window in other workspace.

**Comment by bvk** [comment]
I turned exwm-debug-on and I got the following logs in *Messages*


[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>
[EXWM] Focus on workspace 3
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>
[EXWM] Focus on workspace 3
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>
[EXWM] Focus on workspace 3
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x180000a [2 times]
[EXWM] Focus on #x180000a with SetInputFocus
[EXWM] Focus on workspace 3
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>
Quit
[EXWM] Refresh layout [3 times]
Mark set
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *Messages* 0x39e4518>
[EXWM] Focus on workspace 2
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *Messages* 0x39e4518>
Mark set [2 times]

**Comment by bvk** [comment]
OK, I can confirm: focus is back to stable when the long running command in ansi-term window has finished.

**Comment by marcushg** [comment]
that's timing - i am experiencing what i think to be the exact same thing, which is kinda hard to reproduce right now. most of the time i am trying to run an external program by "s-&" (start-process-shell-command) which activates the minibuffer and once i am switching to another workspace and doing my stuff there it will hang "up" - i.e. loose focus to emacs. so i guess it's related to being in the minibuffer while switching workspaces and doing stuff that otherwise would refocus the current window on the current workspace..... i would usually get error msgs akin to "Command attempted to use minibuffer while in minibuffer"

**Comment by bvk** [comment]
In my case, I am not actively using the minibuffer. I started google-chrome *once* using s-& on workspace-2.

I have ansi-term active in workspace-1.

Now, I start a long-running command in the ansi-term window and when I switch to workspace with google-chrome I notice that it starts to lose focus.

So, no mini-buffer activity is involved.

**Comment by marcushg** [comment]
ok, in that case it might be unrelated - but it seems there are still some focus issues.

**Comment by bvk** [comment]
I just ran "sleep 10" in ansi-term and immediately switched to google-chrome workspace.  I noticed that it lost focus once just about at the end of 10 seconds. I had to type s-1 twice to get back to workspace-1 because workspace-2 (with google-chrome) steals the focus back after first the s-1. Here are the relevant debug logs for this test:

[EXWM] Refresh layout [2 times]
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>
[EXWM] Focus on workspace 2
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Workspace was switched unexpectedly
[EXWM] Set focus ID to #x1200001 [2 times]
[EXWM] Focus on #x1200001 with SetInputFocus
[EXWM] Focus on workspace 2
[EXWM] Set focus ID to #x0
[EXWM] Focus on workspace #<frame *ansi-term* 0x39e4518>

**Comment by ch11ng** [comment]
Hi @bvk,
As a heavy `ansi-term` user, I admit this long-existing bug is quite annoying. I'll look into this issue later.

**Comment by ch11ng** [comment]
Hi @marcushg,
I think what you described is a normal behavior of Emacs. If you invoke `M-x` twice, you will also get the same error message. Perhaps `C-]` will get you out there.

**Comment by bvk** [comment]
Thanks @ch11ng 

I noticed that a similar issue happens with eshell as well. With eshell, display switches from active workspace to the eshell workspace and comes back immediately. We get a flashing effect -- but focus is not lost, so it is better than ansi-term.
