### ISSUE TITLE
Floating window disappears for ever after hiding

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#204]
After using exwm-floating-toggle-floating to make a float window and hiding it
with exwm-floating-hide, I can't bring it up again by switching to the buffer.
I am using EXWM 0.11 on emacs 24.5.1.

**Comment by ch11ng** [comment]
How did you switch to that buffer? The vanilla `switch-to-buffer` does not handle frame switch.  `ido-switch-buffer` does.

**Comment by QiangF** [comment]
I bind C-x b to helm-mini. ido-switch-buffer works!
