### ISSUE TITLE
Clarify compositing section of user guide

### ISSUE THREAD

**Issue by zabbal** [ch11ng/exwm#205]
There' note in user guide:

There're also some standalone solutions designed for working with lightweight window managers. But since EXWM does not (and probably will never) work with any of these, a compositing manager module is provided.

But it does not explain why exwm can't possibly work wth external compositors like compton. Would be nice to learn technical details.

**Comment by ch11ng** [comment]
Here are two reasons I can recall at the moment:

1. You may know that X windows are organized in a tree hierarchy.  Standalone compositing managers assume they only need to paint top-level X windows (direct children of the root) which is not true for EXWM.  With `exwm-debug-on` set, you can check the tree with `xwininfo -tree -root` and you'll find that X windows to be composited are quite deep in the tree.  It's possible to invalidate this reason by making EXWM a non-reparenting window manager, but I might cause other problems plus it requires lots of work.
2. Emacs frames need to be clipped by some X windows to prevent the frames from occluding them.  I don't think it's possible to tell other compositing managers to do this.

**Comment by zabbal** [comment]
Thanks for detailed explanation.
