### ISSUE TITLE
Some applications do not allow Emacs to intercept the commands

### ISSUE THREAD

**Issue by Myrl** [ch11ng/exwm#206]
Reproduction:

Run DotA2, any C-* commands won't work. s-* commands still do.

**Comment by Myrl** [comment]
Closing until I make a proper report

**Comment by ch11ng** [comment]
Is this related to #207?

**Comment by Myrl** [comment]
Yeah, I realized that DotA was started in fullscreen mode since fullscreen mpv did not allow it either.
