### ISSUE TITLE
some global keybinds have unexpected behaviour

### ISSUE THREAD

**Issue by mrosset** [ch11ng/exwm#212]
Hello this may not be an issue, but I'm not sure where else to get more information on this expected behaviour.

I have set these global keybindings.

  (exwm-input-set-key (kbd "s-j") 'evil-window-next)
  (exwm-input-set-key (kbd "s-k") 'evil-window-prev)

They work as intended.

This binding though, does not work as intended.

  (exwm-input-set-key (kbd "s-m") 'spacemacs-cmds)

When I use the binding in an X window, it will show in the minibuffer as being pressed, but no popup window will activate. The keybind will work with a normal emacs window though.

If this is an error on my part please let me know, how I can bind s-m to spacemacs-cmds properly.

**Comment by ch11ng** [comment]
I have no much idea about spacemacs or the behaviors you described.  I checked its source but cannot find where `spacemacs-cmds` was defined (I don't have it installed).  Could you show me the definition of this command?

**Comment by mrosset** [comment]
Seems spacemas-cmds is not actually a function but a varible to a key-map.
I will close this issue I think. At this point it's more of an issue with me finding the right function to call within spacemacs then an issue with exwm. Thank you for your time.
