### ISSUE TITLE
Plasma5

### ISSUE THREAD

**Issue by arkhan** [ch11ng/exwm#215]
hello,

how to integrate EXWM to Plasma5 with ksmserver or KDEWM...?

Thanks

**Comment by ch11ng** [comment]
I've not tried something similar but it seems it's possible to use a third-party window manager with plasma 5 (https://awesome.naquadah.org/wiki/KDE_and_awesome for example).  Just make sure the binary to be executed is Emacs.

**Comment by arkhan** [comment]
Thanks

**Comment by ch11ng** [comment]
> If a Plasma panel is present EXWM doesn't make any space for it. At first the panel is behind the main Emacs frame, but after a bit the panel somehow comes to the front and sits on top of the frame, obscuring the echo area.

This sounds like the panel is treated as a conventional X window.  Please inspect it with `xwininfo` and `xprop`.  We'll see if we can do something with it.

> After removing all panels from KDE and restarting EXWM with support for a systray I get this warning:
>
> `Warning (emacs): [EXWM] Other system tray detected`
>
> I cannot figure out how to make KDE release the system tray.

This has nothing to do with the system tray.  It's not required to have the systemtray module enabled.

> I'm running EXWM 0.17 without a compositor.

You may want to upgrade to 0.18.

**Comment by pjones** [comment]
I may have spoken too soon.

I played around with the panel settings and after using the "Always Visible" setting EXWM seem to consistently make space for it.

As for the system tray: I was trying to experiment with using a system tray in EXWM instead of using a Plasma panel.  However, no system tray appeared in EXWM, only the warning I posted above.

**Comment by ch11ng** [comment]
In X11 there can be only one system tray.  Unless one find a way to disable the tray of Plasma it's not possible to use the systemtray module of EXWM.

**Comment by natask** [comment]
@pjones don't mean to reopen a dead issue. I am facing the same issue but I am not sure where the "Always Visible" setting is. How did you go about it?

**Comment by pjones** [comment]
> @pjones don't mean to reopen a dead issue. I am facing the same issue but I am not sure where the "Always Visible" setting is. How did you go about it?

@natask I no longer use EXWM or KDE.

However, you should be able to find that setting by editing the panel (I think if you right-click the panel and choose "Configure" and you'll get there) and then locate the "More Settings" button which gives you a menu for selecting "Always Visible".

**Comment by natask** [comment]
@pjones  ty. found it. 
out of curiosity, what do you use instead.

**Comment by pjones** [comment]
@natask I went back to [a plain XMonad setup](https://github.com/pjones/tilde).

I really like the idea of EXWM but at the end of the day Emacs is too slow and limited to be what I need.
