### ISSUE TITLE
Error when handling any EXWM window

### ISSUE THREAD

**Issue by wacossusca34** [ch11ng/exwm#217]
As of the time of this error report, I am using the latest EXWM and XELB sources from git and emacs 25.1.1. After pulling said sources, EXWM is usable and raises an error on every window creation. Unfortunately it's beyond my knowledge to debug most elisp code -- here's some debug info:

Emacs backtrace: https://transfer.sh/G2mxW/xcb-error.txt
Screenshot: https://i.imgur.com/aP0nbTe.png

I can provide any further information on request.

**Comment by ch11ng** [comment]
Sorry for the silly bug.  It has been fixed in b11ac2e6dc0821a5b1c6079cf24771fde3aeb4d4.

**Comment by wacossusca34** [comment]
You are a saint, thanks for the quick fix.
