### ISSUE TITLE
Add close-application option to the EXWM mode-line menu

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#219]
I just noticed that EXWM menu is displayed when I press Mouse-1 on the EXWM major mode on the mode-line.  

It would be nice to have an option to close the X11 application in there so that users don't need to switch to keyboard from using the mouse.

**Comment by ch11ng** [comment]
Added in d69e7075ad1198034b0ea3264e0159373375a0a9.

**Comment by bvk** [comment]
Thank you.
