### ISSUE TITLE
switching workspace resets previous workspace's window layout

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#22]
This may be related to #21, but this test is at workspace level:

1. Split the initial scratch buffer window vertically
2. Open a file in the first window.
3. Open another file in the second window.

Now workspace-1 has two windows with two files that are not scratch buffers.

4. Switch to workspace-2 which has nothing but scratch buffer.
5. Now, if you switch back to workspace-1, the previous two-windows are replaced with single scratch buffer window.

**Comment by ch11ng** [comment]
I can't seem to reproduce this issue. Did you switched to a wrong workspace (as workspaces in EXWM are indexed starting at 0)?

**Comment by bvk** [comment]
Oh, that explains it. Yes, I switched to wrong workspace. Sorry :(
