### ISSUE TITLE
which-key doesn't work

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#222]
In case you don't know about it, the which-key package displays a list of next available keys in a key chord (sequence). Unfortunately, it doesn't appear to work in EXWM buffers (in `line-mode` at least).

**Comment by ch11ng** [comment]
It seems the idle timer that is responsible for invoking `which-key--update` never gets a chance to run in an `exwm-mode` bufffer.  Perhaps it's because EXWM makes use of idle timers intensively and aggressively.  I'll look into this issue a bit later.

**Comment by Stebalien** [comment]
Thanks!

**Comment by Stebalien** [comment]
Duplicate of #203. The workaround is to manually remove the `which-key--{start,stop}-timer`s from the `focus-{in,out}-hook`s.
