### ISSUE TITLE
exwm inkscape export window

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#224]
When dealing with the export window within inkscape if I try to kill that floating window it will kill inkscape itself. I have to click on the export multiple times and then toggle the floating window to then kill this. It only seems to be this window which plays up.

Is there a way to force some floating windows to always toggle to tiled windows.

**Comment by ch11ng** [comment]
When I do an export in inkscape 0.92 it just pops up a sidebar.  Which version of inkscape has that behavior.

**Comment by map7** [comment]
I"m using 0.91, I'll give 0.92 a go thanks.

**Comment by map7** [comment]
I just installed 0.92 and it works a treat, thanks for the suggestion 
you can close this issue.
