### ISSUE TITLE
systemtray offset doesn't take struts into account

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#225]
When the emacs frame is offset by a strut window (e.g., a task bar), the system tray gets pushed off the screen. To reproduce, start statusbar application (e.g., lemonbar) at the top of the screen and observe the tray disappear.

**Comment by ch11ng** [comment]
Fixed in f299ca5ed7056842aa59e9978061bca650316a71.

**Comment by Stebalien** [comment]
Thanks!
