### ISSUE TITLE
Input Passthrough Hook

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#226]
So, when getting spacemacs up and running with exwm, I ran into a problem with hydra/transient states. To get them working properly, I'd need to either:

1. Set `exwm--input-line-mode-passthrough` before entering a hydra state and unsetting it afterwards. Unfortunately, there doesn't appear to be a good way to do this (there's no global `hydra-enter-hook`/`hydra-exit-hook`).

2. Modify exwm to check if a hydra is active (`(bound-and-true-p hydra-curr-map)`). Unfortunately, this means modifying exwm to deal with every special case like this.

Then I thought of a third option, a general purpose hook:

```elisp
(or exwm-input--line-mode-passthrough
    exwm-input--during-command
    (run-hook-with-args-until-success 'exwm-input-line-mode-passthrough-hook event)
    ; ...
)
```

Thoughts? I'm worried that running user specified code in the keyboard handler could cause weird race conditions/deadlocks.

**Comment by ch11ng** [comment]
The code snippet in the third option is too important to be modified.  You may try to a) ask the author of hydra to add such hooks or b) make use of more generic hooks like `pre-command-hook` / `post-command-hook`.

**Comment by Stebalien** [comment]
`pre-command-hook`/`post-command-hook` aren't really relevant here. Hydra enters a temporary mode with some extra keybindings.

I've asked for an issue about hooks to be revived: https://github.com/abo-abo/hydra/issues/12. Unfortunately, `pre-command-hook`/`post-command-hook` aren't really relevant here as hydra enters a temporary mode with some extra keybindings (that lasts beyond the end of the "command").

**Comment by Stebalien** [comment]
For future reference, I've gotten hydra working with EXWM with the following advice:

```elisp
(define-advice hydra-set-transient-map (:around (fun keymap on-exit &optional foreign-keys) exwm-passthrough)
  (setq exwm-input-line-mode-passthrough t)
  (let ((on-exit (lexical-let ((on-exit on-exit))
                    (lambda ()
                      (setq exwm-input-line-mode-passthrough nil)
                      (when on-exit (funcall on-exit))))))
    (funcall fun keymap on-exit foreign-keys)))
```
