### ISSUE TITLE
Unreading events is buggy on emacs 26

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#227]
* `yes-or-no-p` doesn't work (it keeps saying "Please answer y or n." indefinitely).
* `read-key` returns `(t . event)` (I believe this is why `yes-or-no-p` doesn't work).
* Sometimes, when I hit a prefix key (usually after using an X window for a while), I'll see `<t>` in the echo area (which I assume means it's reading `t` as an event) and nothing will happen. I haven't been able to confirm this is related (I can't reliably reproduce it) but I haven't noticed this behavior since fixing the code below:

So, I think this code should be updated to be `(< emacs-major-version 27)` :disappointed: :

```elisp
;; FIXME: Putting (t . EVENT) into `unread-command-events' does not really work
;;        as documented in Emacs 24.  Since inserting a conventional EVENT does
;;        add it into (this-command-keys) there, we use `unread-command-events'
;;        differently on Emacs 24 and 25.
(eval-and-compile
  (if (< emacs-major-version 26)
      (defsubst exwm-input--unread-event (event)
        (setq unread-command-events
              (append unread-command-events (list event))))
    (defsubst exwm-input--unread-event (event)
      (setq unread-command-events
            (append unread-command-events `((t . ,event)))))))
```

**Comment by ch11ng** [comment]
It's sad.  The upstream bug is still there.  I've updated the workaround in eebf764edd1eebcd40c71dc61ab08f8ddb9e517f.

**Comment by Stebalien** [comment]
Thanks.
