### ISSUE TITLE
Resizing (non-floating) windows with mouse

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#228]
For some reason, I can't resize right edge of non-floating X windows with mouse. I can resize the left/top/bottom, but not the right.

Doesn't work:

```
| Xorg  | emacs |
        ^ can't move with mouse
````

Works:

```
| emacs | Xorg  |
        ^ can move with mouse
````

If I had to guess, I'd say that the X window is overlapping the emacs mouse grip. Is there any way to add a tiny gap/border?

**Comment by Stebalien** [comment]
So, this isn't an issue when `window-divider-mode` is enabled. It might be a good idea to suggest enabling it in the tutorial.

**Comment by 11111000000** [comment]
confirm that

**Comment by ch11ng** [comment]
This workaround is acceptable.  I've added it [here](https://github.com/ch11ng/exwm/wiki#unable-to-resize-an-x-window-by-dragging-its-right-edge).  Thanks!
