### ISSUE TITLE
EXWM toggle input method not working in chroot environment

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#229]
I take the hard drive of my desktop computer on travel, and use schroot to get to my normal working environment. The input method (chinese-pyim) doesn't work in applications started in the schroot.  Is this a limitation of EXWM? Or can anyone suggesting a better way to stay in my desktop environment? The desktop and laptop have different hardware configurations, so boot from the desktop hard drive doesn't work well.

**Comment by ch11ng** [comment]
Did you set the relevant environment variables?

**Comment by QiangF** [comment]
Problem solved! The environment variable is set in my .cdmrc
file. By adding the folllowing to my bashrc. Everything works
now! Thank you

    export LC_CTYPE="zh_CN.UTF-8"
    export XMODIFIERS=@im=exim
    export GTK_IM_MODULE=xim
    export QT_IM_MODULE=xim
    export CLUTTER_IM_MODULE=xim
