### ISSUE TITLE
exwm crashes when plugging charger.

### ISSUE THREAD

**Issue by mohamed-aziz** [ch11ng/exwm#230]
Hello,
exwm crashes when I plug the charger into my laptop, I don't know how to debug this?
so how to post a backtrace?
Thanks

**Comment by jtamagnan** [comment]
Is this still happening? What kind of crash happens? Does your computer instantly turn off, are you unable to type or unable to click? Does your mouse pointer still move but can't interact with anything? Does this happen if you use a different window manager? Have you tried to set debug on error to true, `toggle-debug-on-error`?

**Comment by mohamed-aziz** [comment]
@jtamagnan I'm using debian now and no this is not happening anymore, the mouse pointer was moving but I could not interact with anything so I had to do killall -CONT emacs.

**Comment by ch11ng** [comment]
@mohamed-aziz  It was not something crashed but your Emacs froze according to your report.  There's unlikely any backtrace.  Unless it's reproducible it'd be quite hard to debug.
