### ISSUE TITLE
simulation key shadowed by minor mode key binding

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#231]
This issue happens to C-/, I tried the following:

    (exwm-input-set-simulation-keys
     '(([?\C-/] . (?\C-z))))

When I tries to undo in leafpad, I got the error: "Buffer is readonly ...."
Looks like C-/ is still binded to undo-tree-undo.

Does keys set with exwm-input-set-simulation-keys sit on top of all other bindings?
How could it be shadowed by keybindings of a minor mode?

**Comment by ch11ng** [comment]
I tried it and it worked. Does `(read-key)` report the same value with `?\C-/` on your Emacs? Or did you modify your keyboard mapping?

**Comment by QiangF** [comment]
Typing "C-/" after executing (read-key) gives the following 

    67108911 (#o400000057, #x400002f)

Which is the same when I run emacs with "emacs -Q" and reset keymapping with

    setxkbmap -layout us 

67108911 appears on the local-function-key-map, and seems to be undo by default.

But when I login to another tty without X and run emacs with "emacs -Q",
Typing "C-/" after executing (read-key) gives the following 

127 (#o177,#x7f, ?\C-?)

My emacs version is 24.4.1, EXWM version is 0.13.

I have changed some environment variables before starting EXWM.

    export LC_CTYPE="zh_CN.UTF-8"
    export LC_ALL="en_US.UTF-8"
    export LANG="en_US.UTF-8"

**Comment by ch11ng** [comment]
<kbd>C-h k C-/</kbd> should say something like:

```
C-/ runs the command exwm-input-send-simulation-key (found in
exwm-mode-map), which is an interactive Lisp closure in
‘exwm-input.el’.
```

Is that right?

Also check if it's a problem with your input method.

**Comment by QiangF** [comment]
C-/ runs the command undo-tree-undo. When I disable undo-tree-mode, everything's right. 
There might be something wrong with undo-tree-mode. Here is a link to my settings.

https://github.com/QiangF/my_dotfiles.git

I use outline extensively. The heading format is "comment-start *", for lisp it is "; * heading".

**Comment by ch11ng** [comment]
Then just disable undo-tree for `exwm-mode` in `undo-tree-incompatible-major-modes`.

**Comment by QiangF** [comment]
Maybe there is a bug in undo-tree,  adding exwm-mode to that variable doesn't work.

    (add-to-list 'undo-tree-incompatible-major-modes 'exwm-mode)
