### ISSUE TITLE
Feature request: sticky modifiers

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#232]
For some key combinations, when you hold the modifier key you partly cover the
second key with your hand so it's much more comfortable to have sticky keys.
With stiky keys, the next key pressed will be modified by the previously
tapped modifier.

Sticky keys can be set with 

    # turn on stickykeys. don't let two keys pressed at the same time disable it.
    # don't turn on "latch lock", ie pressing a modifier key twice "locks" it on.
    xkbset accessx sticky -twokey -latchlock
    # don't expire these settings. (run xkbset q exp for details.)
    xkbset exp 1 =accessx =sticky =twokey =latchlock

But the above setting doesn't seem to work under EXWM. Is there a way to support
stiky modifier natively in EXWM?

**Comment by ch11ng** [comment]
I tried your setting and it seems working for me: native Emacs key sequences, globally defined keys, mode-specific keys and simulation keys.  Perhaps you have other settings conflicting with this?

**Comment by QiangF** [comment]
I am now satisfied with xcape, I think it is better than sticky modifiers.
