### ISSUE TITLE
Failed to add exwm-input-prefix-keys

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#233]
I am using xcape to change short press and release of a modifier to a key sequence with this setting

    xcape -e 'Control_R=Escape;Super_L=Super_L|c;Shift_L=Control_L|x;\
              Shift_R=Control_L|c;Alt_L=Alt_L|x;Alt_R=Alt_L|c'&

In EXWM I have added M-c to the prefix-keys with

    (push ?\M-c exwm-input-prefix-keys)
    (push ?\s-c exwm-input-prefix-keys)
    (push ?\M-c exwm-input--global-prefix-keys) 

but still

    M-c runs the command capitalize-word
    s-c is undefined

How can I fix it?

**Comment by ch11ng** [comment]
What are these settings suppose to do? For example, what should <kdb>s-c</kbd> run? I tried your settings and at least `Alt_L` (<kbd>M-x</kbd>) seemed to work.

BTW, there's no need to modify `exwm-input--global-prefix-keys`.

**Comment by QiangF** [comment]
I upgraded EXWM to 0.13 and it works! Now when I press and release the windows key, xcape send "s-c" as a modifier. I am binding many of EXWM related functions to key sequences started with "s-c", this makes use emacs with EXWM easier, because I some times lauch several emacs session, eg. when I need root privilege "sudo -E emacs".

**Comment by QiangF** [comment]
I upgraded EXWM to 0.13 and it works! Now when I press and release the windows key, xcape send "s-c" as a modifier. I am binding many of EXWM related functions to key sequences started with "s-c", this makes use emacs with EXWM easier, because I some times lauch several emacs session, eg. when I need root privilege "sudo -E emacs".
