### ISSUE TITLE
Pointer warps when clicking

### ISSUE THREAD

**Issue by paul-donnelly** [ch11ng/exwm#234]
Any time I click in the Emacs window my pointer warps to the upper right corner of the rightward of my two monitors (I have not tested yet with only one monitor connected). It also warps there if the pointer crosses the line between two Emacs windows. This happens with both the version in ELPA (0.13) and the latest from GitHub (52dc261). This doesn't happen if I click within a non-Emacs window which EXWM is managing.

**Comment by Stebalien** [comment]
Disable `focus-follows-mouse` and `mouse-autoselect-window`.

**Comment by ch11ng** [comment]
@paul-donnelly Which version of Emacs did you test? It's very suspicious since EXWM never warps the pointer itself.

**Comment by paul-donnelly** [comment]
First of all, Stebalien's instructions above do fix the problem. It must have something to do with `mouse-autoselect-window`. I wasn't sure if this was a known fix or a suggestion.

The version is "GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7) of 2017-02-07".

**Comment by ch11ng** [comment]
Sorry for the misleading info.  Yes, you have to disable `mouse-autoselect-window`; this behavior is by design: https://github.com/emacs-mirror/emacs/blob/65eee8392ff95f58f7b0bd036e1fe065523658c6/lisp/frame.el#L814-L818 .

**Comment by Stebalien** [comment]
@ch11ng This still shouldn't be happening. If one moves the pointer from one window to another, the focus should change windows. Instead, the mouse jumps back to the previous window. The code you pointed to handles the case where the frame isn't focused at all and Emacs needs to bring the mouse into the Emacs frame.

**Comment by ch11ng** [comment]
@Stebalien There were some input focus changes between Emacs frames that I couldn't fully understand so such changes are forbidden unless EXWM is made aware of them explicitly.  The scenario you described is no exception --- EXWM can't tell it from other strange events.
