### ISSUE TITLE
[SOLVED (I'm dumb)]Exwm doesn't work with ace-window - "Unknown key j"

### ISSUE THREAD

**Issue by kahrkunne** [ch11ng/exwm#236]
Essentially what it says on the tin. Running ace-window while in exwm gives the rather particular error of "Unknown key j".

It looks like it wants to jump to window "j" automatically, but I have tested splitting Emacs into many windows (more than 30) and it still gives the same error.

**Comment by ch11ng** [comment]
I just tried ace-window and it seemed working fine.  Could you provide the steps of reproducing this issue? The error doesn't seem to be reported by ace-window BTW.

**Comment by kahrkunne** [comment]
Sorry for not getting back to you for so long!

I just tried EXWM again, and now the behaviour is different. Ace-window works just fine with 1 to 4 windows. A fifth window will not have a tag, and with six or more windows it will once again give the "unknown key j" error.

Steps to reproduce are:

1. startx Emacs with exwm

2. open 6 windows

3. M-x ace-window

**Comment by kahrkunne** [comment]
You can find my entire emacs config at https://github.com/kahrkunne/Emacs/blob/master/org-init.org, by the way.

Also, I just changed my configuration to have more workspaces (10 instead of 3) and it now gives the "Unknown key j" error with just two windows.

**Comment by ch11ng** [comment]
Thanks! I didn't have time to investigate this problem though.
