### ISSUE TITLE
Exwm changes keyboard layout

### ISSUE THREAD

**Issue by mohamed-aziz** [ch11ng/exwm#237]
While I'm not in an emacs buffer (for example in firefox) and in line mode, exwm changes layout to querty (from azerty) only when entering a keybinding like C-x 1.

**Comment by kennymalac** [comment]
This concerns me as a colemak user. :+1:

**Comment by ch11ng** [comment]
How did you setup your keyboard layouts? Perhaps there's a bug in XELB.  And if possible, I'd suggest you to change the layouts of your systems (to azerty/colemak) directly.

**Comment by mohamed-aziz** [comment]
@ch11ng this doesn't appear to be a bug with XELB because changing the keyboard layout to azerty (using setxkbmap fr) worked for me, but I think it's weird, Thanks.

**Comment by ch11ng** [comment]
@mohamed-aziz All keycode <-> keysym conversions are done by XELB.  So IIUC you setup your keyboard layout with `setxkbmap fr`, is that right?

**Comment by mohamed-aziz** [comment]
@ch11ng yes setting setting my keyboard layout using <code>setxkbmap</code> works for me.
