### ISSUE TITLE
Don't split mode-line when window split vertically (C-x 3)

### ISSUE THREAD

**Issue by pksadiq** [ch11ng/exwm#239]
It would be nice if only a single mode-line is shown when the window is split vertically and both window have exwm-mode.

Say for example I have opened firefox, and evince.  I have splitted the window (C-x 3) such that the left one have evince, and the right one have firefox. In this case, there should be only one mode-line at the bottom of the screen displaying the information of the current focused window (and other modes like time, battery charge, and whatever the user have configured). Say if I focus evince, the name 'Evince' shall be shown, and if firefox is focused it shows 'Firefox'. Almost all other data in mode-line may be the same.

Splitting the mode line hides the overflown information on my screen. And usually there is always duplicate information on both (That is, both mode-line is having time, battery %, etc.) which is unnecessary.

Thanks.

**Comment by mohamed-aziz** [comment]
+1
I agree but sadly this is how Emacs windows works, I think this is not feasible.
But I hope someone solves this problem.

**Comment by Stebalien** [comment]
Personally, deal with this by not putting extra info in the mode line. Instead, I put it in a separate statusbar (outside of emacs).

**Comment by ch11ng** [comment]
I'd agree with @Stebalien.  If the mode-lines bother you, just make changes to them.  Perhaps you'll want to hide them if you have a separate system panel.  Also I believe some settings are not specific to one buffer (such as `display-time-mode`).

**Comment by medranocalvo** [comment]
One disadvantage of making Emacs your window manager is that your window manager *is* Emacs ;-).  Your proposal would need to be implemented in Emacs; then EXWM would pick it up.  The external statusbar is always an option.
