### ISSUE TITLE
GUI app steals focus

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#240]
I'm using Emacs master branch (commit: aa0fb4f) and exwm 0.13 I'm having an issue where sometimes the focus gets stolen from which ever buffer I'm on to Workspace 0 with the first GUI application it can find. I've tested starting Thunderbird, Firefox and even xcalc on Workspace 0 whilst this problem is happening.

I don't know as yet how to get into this error state, but it seems to happen every few days and only with GUI applications on Workspace 0. I run three screens on my setup and if I have Workspace 0 with xcalc open full screen, then go over to Workspace 1 and save a .org file, straight away the xcalc program on Workspace 0 gets the focus for some reason. 

Once in this error state it doesn't matter what I do I cannot fix it without logging out and back in.

A work around is to stop using Workspace 0.

**Comment by map7** [comment]
It tends to happen when I save files. I've got autosave turned on for org-mode and now that has stopped working, but if I save it manually with C-x C-s then sometimes (about 1 in 3) it will focus the GUI app on Workspace 0, sometimes switching that screen from Workspace 2 to 0 just to do the focus.

**Comment by ch11ng** [comment]
It's strange that the focus only reverts to Workspace 0.  Does it matter what is focused on Workspace 0 before you switch to another workspace? Does putting an X window in floating or fullscreen mode make any difference?

Could you provide a debug log? It should tell what really happens.

**Comment by map7** [comment]
If I have multiple GUI apps on Workspace 0 then move to another Workspace and re-enact the problem then the bug selects the last focused GUI app on Workspace 0 to focus on. 
When the problem happens again I'll test the other things you suggested and try and get a debug log.

**Comment by taohansen** [comment]
I can confirm this is happening for me but on any workspace.

**Comment by taohansen** [comment]
I use every GUI app on any other workspace than 1 for precisely this reason.

**Comment by ch11ng** [comment]
@taohansen Do you use multiple monitors?

**Comment by taohansen** [comment]
@ch11ng No just the laptop's.

**Comment by ch11ng** [comment]
Can this problem be reproduced even with the minimal configuration?

**Comment by map7** [comment]
It's very hard to reproduce. I've upgraded to exwm 0.15 and it has happened again. I'll try and leave it in this state so that any tests you want done can be done.

**Comment by ch11ng** [comment]
Does this problem affect Emacs 25?  If not I think it's caused by a frame redirection problem in Emacs 26 and I have pushed 71a39840b239a51eed7455877517ebe612892eff to fix it.  Please test whether the problem is resolved.

**Comment by taohansen** [comment]
Emacs 25 here. tested with a few different X window apps. appears to be resolved for me at least.

**Comment by WorldsEndless** [comment]
Confirmed problems here. exwm 0.19, Emacs 25.3.1, running on multi-screen systems (3 monitors on desktop, or two on laptop) and in both cases browsers or other gui apps steal focus. Doesn't matter which workspace those apps are in (0, 1, or 2), and doesn't matter if they have a non-gui split on the screen. The values of vars   `mouse-autoselect-window` and `focus-follows-mouse` don't appear to matter. Note that splitting the screen to have a GUI window AND non-GUI window in the same workspace does not cause the GUI to steal focus from that non-GUI; however, it continues to steal focus from non-GUI in other workspaces (other screens). 

This is extremely annoying since, as a web-developer, I always have a browser in one window and code in the others (and now, having a browser in one window effectively causes me to have just one monitor).

**Comment by ch11ng** [comment]
@WorldsEndless That sounds unusual for an ordinary configuration.  Have you ever tried a minimal configuration?

**Comment by WorldsEndless** [comment]
I've tried removing certain elements from my config and so far it seems to be working. I'll post an update after another day or two of practice.

**Comment by medranocalvo** [comment]
@WorldsEndless, assuming this is resolved.  Please, reopen if you still find issues.
