### ISSUE TITLE
Suggest add a .desktop file

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#242]
Display manager need a .desktop file to let user select a wm,  suggest add an example .desktop file.

**Comment by tumashu** [comment]
maybe we can add a shell-wrap command: exwm,  and let "~/.config/exwm" or "~/.exwm" as default configure,

**Comment by ch11ng** [comment]
> maybe we can add a shell-wrap command: exwm, and let "/.config/exwm" or "/.exwm" as default configure file instead of .emacs.

Could you work on that? I don't use a display manager and I don't know what are exactly required in that file.

> maybe we can add a shell-wrap command: exwm, and let "/.config/exwm" or "/.exwm" as default configure file instead of .emacs.

How can users customize the shell script? And what's benefit of splitting the configuration file?

**Comment by tumashu** [comment]
now, i think this work should be done by linux package contributer :-)

**Comment by wmealing** [comment]
tumashu: do you have a working .desktop file ?

**Comment by tumashu** [comment]
i use guixsd， it auto generate a desktop file

**Comment by wmealing** [comment]
Cool, ok.. i dont think i have that.
