### ISSUE TITLE
Can't open a terminal frame when the Xorg TTY isn't focused.

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#244]
If I sign into a second TTY (command line) and try to open an emacs frame, it hangs until I switch back to my Xorg TTY. Presumably this is because EXWM is trying to communicate with Xorg when it's effectively suspended.

**Comment by ch11ng** [comment]
How did you try to open a frame? I suppose you were referring to something other than `emacsclient -t`.

**Comment by Stebalien** [comment]
Switch to a different TTY, login, and run `emacsclient -t`. It hangs until I switch back to X (and when it finally runs, there's no color).

**Comment by ch11ng** [comment]
I still believe it works.  Could you try with a minimal configuration?

**Comment by Stebalien** [comment]
You're right, I'll debug my config. Sorry about that.

**Comment by Stebalien** [comment]
This appears to be caused by some weird interaction between persp-mode and EXWM (they both mess with frame creation).
