### ISSUE TITLE
The problem of creating a floating window with header-line-format

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#248]
I use the following code to create a floating window with header-line-format

https://github.com/tumashu/exwm-x/blob/e5665a4fceb62ffdc8703db49c4007acfb93a9ee/exwm-x-buttons.el

The problem is that, after I switch back tilling mode from floating mode, a useless blank will be placed
on the top of tilling window.

**Comment by ch11ng** [comment]
Perhaps your hook is run too late and requires a refresh.

**Comment by tumashu** [comment]
I have switched to use mode-line again  for easy

**Comment by tumashu** [comment]
Using header-line as the floating window's titlebar is more beautiful, I want to solve this problem now, so I reopen the issue.

**Comment by tumashu** [comment]
the problem maybe:   if a floating window's header-line-format is not nil, exwm-floating--unset-floating will not do properly, it may not consider header-line

**Comment by tumashu** [comment]
After I toggle fullscreen, the useless space dispear

**Comment by tumashu** [comment]
The below hack can solve the problem :-)
```
(defun exwm-floating-toggle-floating ()
  "Toggle the current window between floating and non-floating states."
  (interactive)
  (with-current-buffer (window-buffer)
    (if exwm--floating-frame
        (progn
          (setq header-line-format nil)
          (exwm-layout--refresh)
          (exwm-floating--unset-floating exwm--id))
      (exwm-floating--set-floating exwm--id))))

```

**Comment by tumashu** [comment]
The below hack can solve the problem :-)
```
(defun exwm-floating-toggle-floating ()
  "Toggle the current window between floating and non-floating states."
  (interactive)
  (with-current-buffer (window-buffer)
    (if exwm--floating-frame
        (progn
          (setq header-line-format nil)
          (exwm-layout--refresh)
          (exwm-floating--unset-floating exwm--id))
      (exwm-floating--set-floating exwm--id))))

```

**Comment by tumashu** [comment]
This problem seem to be solved by new exwm code :-)

**Comment by ch11ng** [comment]
Could you confirm that?

**Comment by ch11ng** [comment]
From your last comment I'd assume this issue was fixed.  So I'm closing it now.
