### ISSUE TITLE
Floating window part block its mode-line 

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#249]
When first switch to floating mode from tilling mode,  floating window's mode-line is partily blocked ....

**Comment by tumashu** [comment]
![Uploading 1.png…]()




![Uploading 1.png…]()

**Comment by tumashu** [comment]
![1](https://cloud.githubusercontent.com/assets/67725/25257990/b500f05e-266e-11e7-8fe8-f2f8ddf089ec.png)

**Comment by ch11ng** [comment]
The mode-line font in use is significant larger than the default.  When is that updated? Perhaps a refresh is required?

**Comment by tumashu** [comment]
I use chinese-fonts-setup to set my fonts, it is run the following two hooks to config font.

```
  (add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
  (add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)
```

**Comment by ch11ng** [comment]
So here is the problem: `after-make-frame-functions` is run after the X window is resized.  You need to manually refresh the X window in that hook.

**Comment by tumashu** [comment]
I have tried to run exwm-layout--refresh after run cfs-set-font-with-saved-step, but have no effect. I don't know the reason, may be the below is a simpler solution:

```
;; Override exwm's exwm-floating-toggle-floating
(defun exwm-floating-toggle-floating ()
  "Toggle the current window between floating and non-floating states."
  (interactive)
  (with-current-buffer (window-buffer)
    (if exwm--floating-frame
        (progn
          (exwm-floating--unset-floating exwm--id)
          (exwm-layout--refresh))
      (exwm-floating--set-floating exwm--id)
      (exwm-layout--refresh))))

```

**Comment by tumashu** [comment]
上面的hack, 可以解决我的大部分问题, 不过自动弹出的浮动窗口,比如gtk的文件选择器之类的, 怎么也搞不定

**Comment by ch11ng** [comment]
Perhaps you should do a refresh in `exwm-floating-setup-hook`?

**Comment by tumashu** [comment]
I have tested with the below code, but no effect for popup floating window
```
(add-hook 'exwm-floating-setup-hook
          #'exwm-layout--refresh)
```

**Comment by ch11ng** [comment]
What if you do `(redisplay t)` in `cfs-set-font-with-saved-step`?

**Comment by tumashu** [comment]
Wow, seem to work, thanks!
