### ISSUE TITLE
Cannot manage java based jnlp programs

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#25]
Thanks a lot for your work Chris.

I sometimes use java based apps, like IPMIViewer, etc. and exwm cannot manage these apps. They don't show up even though window (or a sub-window) is created by the jnlp program. This behavior is reproducible with other java web-start apps as well.

A simplified test is as follows:

1. Install openjdk and icedtea-netx packages to get java environment.

2. Running 'javaws -about' brings up a java window which is not displayed even though command is running in the background. I tested that window shows up using sawfish window manager.

3. Running 'javaws -viewer' brings up certificate store which is displayed by exwm, but exwm keybindings do not work. For example, I cannot do 'C-x b' to switch to other windows.

**Comment by ch11ng** [comment]
Hi @bvk,
Thank you for your detailed bug report. This bug is not specific to JNLP applications and is fixed in 7bfd429d5252e8df43d1b19b836a6c4970290fa0.
