### ISSUE TITLE
Add an option to hide mode-line for floating windows

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#250]
Some applications like gimp and ug NX create a lot of small windows, and each one showing a mode-line is not pretty. What about add a function to toggle mode-line of all floating windows?

**Comment by ch11ng** [comment]
Is putting `exwm-layout-hide-mode-line` into `exwm-floating-setup-hook` and `exwm-layout-show-mode-line` into `exwm-floating-exit-hook` enough for this?

**Comment by QiangF** [comment]
I have create a function template, it is not working now.

    (defun my-toggle-exwm-floating-modeline ()
        (interactive)
        (if (member 'exwm-layout-hide-mode-line 'exwm-floating-setup-hook)
        (progn
            (if current-buffer-is-floating
                (exwm-layout-hide-mode-line))
            (remove-hook 'exwm-floating-setup-hook 'exwm-layout-hide-mode-line)
            (remove-hook 'exwm-floating-exit-hook 'exwm-layout-show-mode-line))
        (add-hook 'exwm-floating-setup-hook 'exwm-layout-hide-mode-line)
        (add-hook 'exwm-floating-exit-hook 'exwm-layout-show-mode-line)
        (if current-buffer-is-floating
            (exwm-layout-show-mode-line))))

**Comment by QiangF** [comment]
The modeline is noly useful to show window title and guide key. For people likes mouse clicking, how to set middle mouse click to close the buffer that is clicked by force without asking question?

**Comment by ch11ng** [comment]
> I have create a function template, it is not working now.

I think you only need these `add-hook` lines and should use `exwm-layout-toggle-mode-line` to toggle the mode-line.

> how to set middle mouse click to close the buffer that is clicked by force without asking question and Ctrl + middle click to hide floating window?

For the first question, you'll need to let-bind `kill-buffer-query-functions` to nil.  For the second one, just call `exwm-floating-hide`.

**Comment by QiangF** [comment]
Do we need two more mouse down event?

    (defvar exwm-input-close-event 's-down-mouse-2
    "Emacs event to close a window.")

    (defvar exwm-input-hide-floating-event 'c-s-down-mouse-2
    "Emacs event to hide a floating window.")

**Comment by ch11ng** [comment]
Instead we can make `exwm-input-set-key` accept mouse events.

**Comment by medranocalvo** [comment]
You can already close a floating window with the mouse by clicking on the "EXWM" menu on the mode-line and clicking on "Close window".

If you really want to do it with mouse events, please try #485 and something like the following:

```elisp
(with-current-buffer ??? ;; the `exwm-mode' buffer
  (use-local-map (copy-keymap (current-local-map)))
  (local-set-key (kbd "<mouse-2>") 'exwm-floating-toggle-floating))
```

**Comment by medranocalvo** [comment]
@QiangF, I noticed your 👍, does it mean you tried #485 and it works for you?

**Comment by QiangF** [comment]
@medranocalvo I tried this, but it didn't work.

    (add-hook 'exwm-mode-hook
        (lambda () (use-local-map (copy-keymap (current-local-map)))
                    (local-set-key (kbd "<mouse-2>") 'exwm-floating-toggle-floating)))

**Comment by ch11ng** [comment]
@QiangF It should be added to `exwm-manage-finish-hook`.  `exwm-mode-hook` is simply too early; simulation keys would override your setting.

**Comment by QiangF** [comment]
I think the middle click is intercept by the graphical system, it does pasting. I have changed the setting to:

    (add-hook 'exwm-manage-finish-hook
        (lambda () (use-local-map (copy-keymap (current-local-map)))
                    (local-set-key (kbd "<mouse-2>") 'exwm-floating-toggle-floating)))

**Comment by medranocalvo** [comment]
Indeed, it seems to only work with `down-mouse-2`, as @ch11ng discovered. @QiangF, please try it with the newly updated code in #485.

**Comment by ch11ng** [comment]
This issue should be fixed with @medranocalvo's latest commits which are already in release 0.20 .  So I'm closing it now.
