### ISSUE TITLE
Active hydra detection

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#254]
When the current buffer is an EXWM window, call a hydra and subsequent keys are
not handled by the hydra. One example is:

    (use-package switch-window
    :ensure t
    :defer 1
    :bind (("C-x o" . my-switch-window))
    :config
    (setq switch-window-shortcut-style 'qwerty
            switch-window-qwerty-shortcuts
            '("a" "d" "f" "j" "k" "l" "e" "i" "o" "c" "v")
            switch-window-increase 6 ;Increase or decrease this number.
            switch-window-threshold 1
            switch-window-minibuffer-shortcut nil) ; "z"
    (defun my-switch-window ()
        (interactive)
        (progn
            (hydra-window/body)))

    (when (package-installed-p 'hydra)
        (defhydra hydra-window-size (:color pink)
            "Windows size"
            ("<escape>" nil "quit" :color blue) ;; quit with esc
            ("h" shrink-window-horizontally "shrink horizontal")
            ("j" shrink-window "shrink vertical")
            ("k" enlarge-window "enlarge vertical")
            ("l" enlarge-window-horizontally "enlarge horizontal"))

        (defhydra hydra-window-scroll (:color pink)
            "Scroll other window"
            ("<escape>" nil "quit" :color blue) ;; quit with esc
            ("n" joe-scroll-other-window "scroll")
            ("p" joe-scroll-other-window-down "scroll down"))

        ;; [^w^] windows size         [^r^] winner redo           [^u^] winner undo  [^s^] scroll window
        ;; [^x^] switch & del. window [^z^] switch mini-buf       [^m^] max window"
        (defhydra hydra-window ()
        ("<escape>" nil "quit" :color blue) ;; quit with esc
        ("x" switch-window-then-delete "switch-window-then-delete" :color blue) ;; contract is z
        ("w" hydra-window-size/body "current window resize/scroll" :color blue)
        ("m" switch-window-then-maximize "switch-window-then-maximize" :color blue)
        ("s" switch-window "switch-window" :color blue)
        ("u" winner-undo "winner undo" :color pink)
        ("r" winner-redo "winner redo" :color pink)))
    )

Would be nice if EXWM can detect if there is an active hydra and send key to the hydra.

**Comment by Stebalien** [comment]
See https://github.com/ch11ng/exwm/issues/226

**Comment by QiangF** [comment]
@Stebalien Your original has an error. I tried the following without success.

    (defadvice hydra-set-transient-map (around exwm-passthrough (fun keymap on-exit &optional foreign-keys))
    (setq exwm-input-line-mode-passthrough t)
    (let ((on-exit (lexical-let ((on-exit on-exit))
                        (lambda ()
                        (setq exwm-input-line-mode-passthrough nil)
                        (when on-exit (funcall on-exit))))))
        (funcall fun keymap on-exit foreign-keys)))

**Comment by tumashu** [comment]
By the way, if you want to switch-window work well with exwm, suggest read #247

**Comment by QiangF** [comment]
@tumashu I am using the newest switch-window. This is the code I have now, still not working.


    (defun exwm-passthrough (orig-fun keymap on-exit &optional foreign-keys)
        (setq exwm-input-line-mode-passthrough t)
        (let ((on-exit (lexical-let ((on-exit on-exit))
                        (lambda ()
                        (setq exwm-input-line-mode-passthrough nil)
                        (when on-exit (funcall on-exit))))))
        (apply orig-fun keymap on-exit foreign-keys)))

    (advice-add 'hydra-set-transient-map :around #'exwm-passthrough)

**Comment by QiangF** [comment]
The problem is even with  setting exwm-input-line-mode-passthrough to t golobally, hydra still doesn't seem to have the key.

**Comment by QiangF** [comment]
Ah! I got the variable name wrong, it should be    exwm-input--line-mode-passthrough

**Comment by ch11ng** [comment]
Thanks for your work! The variable is called `exwm-input-line-mode-passthrough` on the master branch.
