### ISSUE TITLE
Killing a non-responsive GUI application results in a mini buffer question

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#255]
At the moment when I try and kill a non-responsive GUI application within exwm I get the following question in the mini-buffer

Please answer y or n. 'Vlc' is not responding. Would you like to kill it? (y or n).

The problem is I cannot answer 'y' or 'n' until the frozen GUI app has been killed and I cannot kill it as I cannot get access to any buffer in exwm at this time or answer the question to kill it. The only way I fix this problem is to got to VT1 and kill all the GUI's in that workspace until I'm on an emacs buffer and then I can answer the question and continue on.

**Comment by ch11ng** [comment]
Some similar problems had be reported before but we didn't have reliable way to reproduce them.  How can we reproduce this one?

**Comment by map7** [comment]
I've been able to reproduce this error

Within exwm do the following
1. Start gtk_unresponsive program (s-&)
2. Click on 'Hello' button
3. Within a few seconds try and kill the buffer with C-x k
4. Answer the first question in the mini buffer
5. Now you should have the second question in which it's impossible to answer and you have to go to a virtual terminal to kill the original GUI application.

A pre-compiled version is included and also the source code. This is just the GTK gui example with a sleep in the correct place to re-enact this issue.
[exwm_unresponse_problem.tar.gz](https://github.com/ch11ng/exwm/files/1000077/exwm_unresponse_problem.tar.gz)

**Comment by ch11ng** [comment]
Thanks! Your tool revealed a problem, but it does not seems to be the one your reported.  Here is my discovery:

1. If I run this tool as root, then after Step 4 I would get a empty `exwm-mode` buffer (the X window is unmapped but the application is not killed).
2. If I run this tool normally it would get killed every time after Step 4.

Did I miss something?

**Comment by map7** [comment]
You must click the hello button and then quickly try and kill it. I run it as a normal user. I just tried it again and it failed.

**Comment by ch11ng** [comment]
No idea but it seems I can kill it every time no matter how quickly I try.  Basically for this application EXWM would send it a SIGKILL signal followed by a KillClient X request sent in a timer.  According to your description the SIGKILL signal probably didn't take effect, and the KillClient X request was perhaps not sent at all.  I wonder if Emacs was busy in step 5.  If so, can you interrupt it with SIGUSR2?

**Comment by map7** [comment]
Would I send the SIGUSR2 to the emacs process by doing the following?
$ kill -SIGUSR2 <pid of emacs>

Emacs doesn't seem to be busy during step 5 because if I click on
different screens (I run 3 on this system) then the question in the
minibuffer moves, but I still cannot answer it until I get rid of all
the GUI screens on that monitor.

**Comment by map7** [comment]
I did just try the kill -SIGUSR2 on emacs and it didn't really help. I
interupted and then not even emacs default key bindings worked. Then I
had to kill the gtk_unresponsive program through the command line anyway
to answer the question in step5 and then emacs went back to normal.

**Comment by map7** [comment]
Just compiled the latest emacs and applied all updates and this problem has gone now. Could of been a library, or X.

**Comment by ch11ng** [comment]
Which version of Emacs were you using? I think this problem has to be the fault of EXWM.

**Comment by map7** [comment]
I compiled from the emacs master branch yesterday. Before that it would
of been about 2 months since the last recompile.

**Comment by demokritos** [comment]
I had the same issue in spacemacs + exwm. If I add 
`(call-interactively 'exwm-input-grab-keyboard)` into exwm-manage.el,
this issue is solved. Inputting 'y' immediately kills the unresponsive application.

```elisp
--- exwm-manage.el.orig	2019-05-16 04:51:25.555148344 +0900
+++ exwm-manage.el	2019-05-16 04:54:18.162347785 +0900
@@ -511,9 +511,11 @@
                                  exwm--connection)))
       (xcb:flush exwm--connection)
       (with-timeout (exwm-manage-ping-timeout
-                     (if (y-or-n-p (format "'%s' is not responding.  \
+                     (if (progn
+                           (call-interactively 'exwm-input-grab-keyboard)
+                           (y-or-n-p (format "'%s' is not responding.  \
 Would you like to kill it? "
-                                              (buffer-name)))
+                                             (buffer-name))))
                          (progn (exwm-manage--kill-client id)
                                 ;; Kill the unresponsive X window and
                                 ;; wait for DestroyNotify event.
```
Emacs version : 27.0.50
Spacemacs : develop branch, using exwm layer from https://github.com/timor/spacemacsOS,
                     vim keybinding
EXWM: 0.22.1

**Comment by ch11ng** [comment]
Thanks @demokritos .  This case is missed indeed.  Could you make a PR for this? I think it'd better to just let-bind `exwm-input-line-mode-passthrough` in case the user regrets.

**Comment by demokritos** [comment]
@ch11ng Do you mean that I let-bind `exwm-input-line-mode-passthrough` without calling `exwm-input--grab-keyboard`? I just tried this, but this does not work except that I first change line mode and try killing the process. If I try killing in char mode, I cannot change to line mode and 'y' or 'n' is not passed to the minibuffer.

**Comment by ch11ng** [comment]
> Do you mean that I let-bind exwm-input-line-mode-passthrough without calling exwm-input--grab-keyboard? I just tried this, but this does not work except when I first change to line mode and try killing the process.

Sorry for the misinformation.  I can confirm this.
