### ISSUE TITLE
XELB Error

### ISSUE THREAD

**Issue by Zarig** [ch11ng/exwm#256]
When I try opening VLC or Nautilus or File-Roller , I get XELB error and the window is completely transparent.

`[XELB ERROR] (cl-assertion-failed (null (exwm-cm--xwin->attr window)))
[XELB ERROR] (wrong-type-argument number-or-marker-p nil)`

**Comment by ch11ng** [comment]
Did you have compositor enabled (with `(exwm-cm-enable)`)? The module is optional and is not loaded by default.

**Comment by Zarig** [comment]
I do have it enabled.

**Comment by ch11ng** [comment]
Sorry but I wasn't able to reproduce this problem.  I tested vlc 2.2.5, nautilus 3.22.3 and file-roller 3.22.3 and I configured this module like this:

```elisp
(require 'exwm-cm)
(setq window-system-default-frame-alist '((x . ((alpha . 100)))))
(setq exwm-cm-opacity 80)
(exwm-cm-enable)
```

What is your setup?

**Comment by ch11ng** [comment]
EXWM now supports third-party compositors so I'm closing this issue.
