### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#257]
That is necessary to use keynav, which totally frees people from touch the
mouse. Keynav can only draw on the monitor that the mouser pointer is on. So an
option to move the mouse pointer to the current monitor (workspace) is requried
sometimes. Maybe set a default position like (x_max, y_max).

**Comment by ch11ng** [comment]
There is an internal variable called `exwm-workspace--workareas` that stores the workareas (a list of [x, y, width, height]) for each workspace.  BTW `exwm-workspace-current-index` stores the index of the current workspace so it's already possible to figure out where to place the pointer.

**Comment by QiangF** [comment]
After all keynav is not as convenient as the mouse. So I am closing this issue.
