### ISSUE TITLE
Is it possible to add a command:  exwm-input-send-string?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#258]
Is it possible to add a command:  exwm-input-send-string, so I can send string to app, Now I use 
exwm-input--fake-key, but it only deal with ascii char and can not send  CJK char

**Comment by ch11ng** [comment]
You can not send unicode characters with X11 core protocol.  Perhaps it's only possible with XIM but still there're some limitations like there must be an active input context.  Depending on what you want to achieve it might be more straightforward to implement another input method.

**Comment by tumashu** [comment]
I know, thanks!

**Comment by tumashu** [comment]
I use  "kill-ring + send \C-v" to solve this problem,  hack but work :-)
