### ISSUE TITLE
Multimonitor with proprietary NVIDIA driver

### ISSUE THREAD

**Issue by VK3FNG** [ch11ng/exwm#262]
I'm currently using EXWM on Ubuntu with the proprietary NVIDIA driver. I've added:

```
(require 'exwm-randr)
(setq exwm-randr-workspace-output-plist '(0 "DVI-I-1"
					    1 "DP-1"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output DP-1 --left-of DVI-I-1 --auto")))
(exwm-randr-enable)
```

To my .emacs configuration. Both screens activate, and I can move the mouse pointer from one screen to another, but only DVI-I-1 appears managed and I can't display any windows on the other. 
![screenshot](https://cloud.githubusercontent.com/assets/19335912/26674066/5877904a-4702-11e7-97ed-237f8fd17de9.png)
Is there any further configuration I need to do?

**Comment by ch11ng** [comment]
You need to make sure the display output names are correct and create extra workspaces with `exwm-workspace-switch-create` or by redefining `exwm-workspace-number`.

**Comment by medranocalvo** [comment]
Your definition of `exwm-randr-workspace-output-plist` means that the workspace number 1 shall be displayed in output `DP-1`. In order to create this second workspace, follow @ch11ng's advice or simple make a new frame (<kbd>C-x 5 2</kbd>).

Please reopen if you still find difficulties.
