### ISSUE TITLE
pinentry-gtk2

### ISSUE THREAD

**Issue by fhdhsni** [ch11ng/exwm#263]
`pinentry-gtk2` sometimes works, sometimes doesn't. Sometimes it pops up for the first time but not for the second time (re-enter of passphrase). Same system in `i3wm` doesn't have this problem. I recorded a [video](https://www.youtube.com/watch?v=nhGIddw1tZo) to show what I mean.  `pinentry-qt` doesn't have this problem.

I'm on Arch linux.
GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22
For `exwm` I'm using master branch.
And for `pinentry-gtk-2` it's
pinentry-gtk2 (pinentry) 1.0.0
Copyright (C) 2016 g10 Code GmbH

**Comment by ch11ng** [comment]
Emacs has native support for `pinentry-tty` (might not be this name on Arch) so I'd encourage you to switch to that.  Anyway this is a problem and I'll try to fix it.

**Comment by tumashu** [comment]
If you open a new emacs session,  pinentry-gtk2 seem to work.

**Comment by Stebalien** [comment]
On arch, there's `pinentry-emacs` (although I believe you to enable pinentry in emacs first with `(pinentry-start t)`).

**Comment by ch11ng** [comment]
Just tried to reproduce the problem but failed.  I also tried hiding the mode line of floating X windows but it didn't make any difference.  Do you have issue with other floating X window?

**Comment by fhdhsni** [comment]
@ch11ng No. I haven't encounter any problem other than that.

**Comment by ch11ng** [comment]
Just an update: I didn't reproduced the problem with the same version of pinentry-gtk2 and Emacs 25.2.1 built according to the instructions from Arch's PKGBUILD.

Could you try a minimal configuration (with other features and optional EXWM modules disabled)?

**Comment by tumashu** [comment]
My machine have the same problem, pinentry-gtk2 can input password, but if I open a new emacs, it works

**Comment by taohansen** [comment]
I was able to route around this issue by adding `pinentry-program /usr/bin/pinentry-emacs` to $HOME/.gnupg/gpg-agent.conf

**Comment by tumashu** [comment]
https://emacs.stackexchange.com/questions/32881/enabling-minibuffer-pinentry-with-emacs-25-and-gnupg-2-1-on-ubuntu-xenial

**Comment by arunisaac** [comment]
Unlike fhdhsni, pinentry-gtk-2 **never** works for me -- not even once or twice...

I have made a little progress debugging it. Perhaps, someone here can say more.

On executing

`echo GETPIN | /path/to/pinentry-gtk-2`

I get the following error message:

```
OK Pleased to meet you

** (pinentry-gtk-2:23241): CRITICAL **: could not grab keyboard: not viewable (3)

** (pinentry-gtk-2:23241): WARNING **: it took 4097 tries to grab the keyboard

** (pinentry-gtk-2:23241): CRITICAL **: could not grab pointer: not viewable (3)

** (pinentry-gtk-2:23241): WARNING **: it took 4097 tries to grab the pointer
ERR 83886179 Operation cancelled <Pinentry>
```

**Comment by ch11ng** [comment]
@arunisaac pinentry-gtk-2 also complains on my machine that it has to retry several times before grabbing the keyboard.  This is one possible cause for the original issue.  Does the problem persist when calling pinentry-gtk-2 with `-g` (which disables the grabbing behavior)?

**Comment by arunisaac** [comment]
Indeed, it works now with `-g` flag. I also tested with `no-grab` added to my `~/.gnupg/gpg-agent.conf`. It works with that too. :-)

However, `man gpg-agent` warns that `no-grab` "should in general not be used to avoid X-sniffing attacks". So, it remains important to fix the underlying issue in exwm.

**Comment by ch11ng** [comment]
I'm on Debian and Debian has patched pinentry in response to the following bug reports:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850708
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851707

This explains why I have never reproduced the issue.  @fhdhsni @arunisaac you probably get fast machines so pinentry-gtk-2 easily fails.  I believe this is not a bug of EXWM.  You need to push your distro or upstream to fix the problem.

**Comment by fhdhsni** [comment]
@ch11ng Thank you for all you've done and the time you put on this awesome project. :heart:

**Comment by arunisaac** [comment]
@ch11ng Sure, I'll do that. Thank you!
