### ISSUE TITLE
[XELB error] Selecting deleted buffer

### ISSUE THREAD

**Issue by drej2k** [ch11ng/exwm#265]
Firstly, thank you for exwm, I really love it!

### My setup
-Emacs v26.0.50.1 (commit 4c4a1b3 off master branch)
-XELB v0.12
-exwm v0.14
-tramp v2.3.1pre (built-in)
-tramp-term v20141104
-ivy v20170606
-counsel v20170605
-swiper v20170606

### The error:
[XELB error] Selecting deleted buffer

### How to produce the error
Error occurs when tramp has opened a buffer to a remote server, I have lost connection to that server, and exwm selects that buffer (the buffer with the lost connection). 
I then am unable to M-x tramp-cleanup-all-buffers (to close buffers with lost connections). 
When i M-x i can see the menu popup then automatically close... 
I am also unable to C-x C-f (menu pops up and instantly closes). I end up being stuck and resorting to kill process to get out of error state.

**Comment by ch11ng** [comment]
Here is what I've tried:

1. Open a file in a buffer on a remote SSH server with tramp.
2. Disconnect the network interface.
3. Switch among buffers (including that buffer)... works.
4. Make changes to that buffer... Emacs hangs but <kbd>C-g</kbd> works and then `tramp-cleanup-all-buffers` works.

Apparently the problem is I didn't delete that buffer.  How did you managed to get it deleted?

**Comment by drej2k** [comment]
Hi Chris, 
Thanks very much for trying testing this out :-)
I agree its the deleted part that is the issue. I will try and determine how to replicate the error state. 
Let me get back to you with more details :-)

**Comment by kriyative** [comment]
Hi Chris - I just recently discovered `exwm` - it is very cool, thanks for sharing.

I ran into a similar issue as @drej2k - getting the `"[XELB] Selecting deleted buffer"` when closing floating windows. I think I may have a fix for it (see PR - https://github.com/ch11ng/exwm/pull/319). Let me know if you need any further info.

Thanks.

**Comment by ch11ng** [comment]
@drej2k I've merged @kriyative's fix.  Does it resolve the problem?

**Comment by drej2k** [comment]
@ch11ng 
I have not encountered this problem since @kriyative's patch was merged into the master branch.
