### ISSUE TITLE
wiki addition

### ISSUE THREAD

**Issue by ernobe** [ch11ng/exwm#266]
Hi
The wiki says:

"An exwm-mode buffer has two input modes: line-mode and char-mode (these phrases are borrowed from ansi-mode). They define how key events should be processed. In line-mode, EXWM intercepts all key events and makes nearly all Emacs key bindings available to you except those you explicitly assigned to EXWM. Whereas in char-mode, EXWM does no interception but only responds to those globally grabbed key sequences. exwm-mode buffers are created in line-mode by default. We will discuss how to switch input mode later."

In the default installation this is not the case.  You have to put  (setq exwm-input-line-mode-passthrough t) in your .emacs file to achieve it.   The default is that in line-mode the apps receive the simulation keys, in char-mode they don't.  In either case, all the other keys go to the apps (except for those defined with exwm-input-set-key).

**Comment by ch11ng** [comment]
Thanks! It was misleading.  I've updated the wiki to clarify that.
