### ISSUE TITLE
Weirdness with vlc fullscreen

### ISSUE THREAD

**Issue by jabranham** [ch11ng/exwm#267]
Steps to reproduce:

`(start-process-shell-command "vlc" nil "vlc")`

In the VLC buffer, press `f` to  make it fullscreen, then watch a video file. At the end of the file, vlc kind-of-but-not-really exits fullscreen and leaves that workspace very difficult to work with.

**Comment by taohansen** [comment]
This also happens with Netflix or anything that does the fullscreening for you and it is a pain. Try to fullscreen the window using EXWM instead.

**Comment by ch11ng** [comment]
I don't seem to have this problem.  I believe I'm using the latest VLC 2.2.6.  This is what I did to try to reproduce this problem:

1. Play a video with VLC.
2. Press 'f' to make the video fullscreen.
3. Wait till video finishes.

After Step 3 I got a normal VLC window.  Tried on Emacs 25 & 26.

What if you check `Video > Fullscreen` before you play a video?

**Comment by jabranham** [comment]
Closing this since the problem seems to have been resolved in the last few EXWM updates.
