### ISSUE TITLE
Steam games launch outside EXWM

### ISSUE THREAD

**Issue by taohansen** [ch11ng/exwm#269]
Steam opens into an EXWM buffer but any games launched from within Steam cannot be found in any buffer or window. EXWM complains of a rename error.

**Comment by ch11ng** [comment]
Sorry but I have no experience with Steam.  I think the games launched should be filtered out so that they won't be managed by EXWM.  Could you inspect them with `xprop`?

**Comment by taohansen** [comment]
this was an issue using exwm-x, paring down to a cleaner configuration fixed.

**Comment by tumashu** [comment]
Which exwm-x version do you used?  do you enable exwmx-xfce? @taohansen

**Comment by taohansen** [comment]
@tumashu latest and no i didn’t. should i have?

**Comment by tumashu** [comment]
@taohansen  NO, I suggest you issue in https://github.com/tumashu/exwm-x/issues ,and send the error message.
