### ISSUE TITLE
When a floating-window have header-line, if switch it to other workspace, header-line dispear.

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#270]

**Comment by ch11ng** [comment]
How did you set up the header line? I manually set up one with

```elisp
(with-current-buffer "BUFFER-NAME"
  (setq header-line-format "HEADER-LINE-CONTENT"))
```

and invoked `exwm-reset` after that but was not able to reproduce the problem.

**Comment by tumashu** [comment]
I use exwm-x, header-line is set with the help of exwmx-button.

**Comment by tumashu** [comment]
我这里浮动窗口的反应比较奇怪,  如果一个 浮动窗口有 header-line, 我用 exwm-workspace-move-window 将其移动到其他 workspace 后, 在最开始的1秒, 它是有 header-line 的, 然后 header-line 就消失了. 难道是因为我在 tilling和 floating 两种模式下设置不同的 mode-line 导致的?

**Comment by tumashu** [comment]
我找到原因了, 是因为我启动 exwm 后, 又启动了 xfce4-session, 如果不启动 xfce4-session, 不存在这个问题.
