### ISSUE TITLE
Suggest add exwm-tilling-mode-line-function, exwm-floating-mode-line-function and exwm-floating-header-line-function

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#272]
the usage may be like the below:
```
(setq exwm-floating-header-line-function
      #'(lambda (buffer id ... and other useful info)
          "This is my own header-line"))

```

**Comment by ch11ng** [comment]
Did you mean you want to make mode-line/header-line work differently on tilling and floating mode?

**Comment by tumashu** [comment]
Yes, I want to this feature to deal with exwmx-button: https://github.com/tumashu/exwm-x/blob/master/exwmx-button.el, the feature's pic is in README: https://github.com/tumashu/exwm-x

**Comment by tumashu** [comment]
我使用 header-line 作为 floating 窗口的标题栏, 这样我可以在不使用键盘的时候,实现窗口的关闭, 缩放和移动. 非常方便.

**Comment by tumashu** [comment]
刚刚我突然想到，也许我可以试着 setq-default 一个超大的 mode-line-format， 来适应所有的需要。。。只是不知道这种方式将来好不好维护。。。。

**Comment by tumashu** [comment]
我试了一下 setq-default 一个大 mode-line-format 的方式, 发现这种方式行不通, 主要原因是: mode-line-format 是一个 buffer 变量, 默认值经常被覆盖

**Comment by tumashu** [comment]
exwm-tilling-header-line-function 估计也需要

**Comment by tumashu** [comment]
另外, 由于 mode-line 和 header-line 是使用变量来设置的, 在任何时候都有可能被覆盖, 我担心即时使用上面四个设置, 也有可能达不到效果

**Comment by ch11ng** [comment]
`exwm-floating-setup-hook` / `exwm-floating-exit-hook` is promised to run at last when switching to/from floating mode.  So I think it's quite safe to modify the format of mode-line / head-line in these hooks.

**Comment by ch11ng** [comment]
I thinks this is totally achievable with `exwm-floating-setup-hook` / `exwm-floating-exit-hook`.  So I'm closing it now.
