### ISSUE TITLE
Suggest add a command which let user set floating-window's size is num% of screen

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#273]

**Comment by tumashu** [comment]
maybe a center optional arg is a good idea, put the window to the center of screen

**Comment by ch11ng** [comment]
Where should we put the X window if it's not centered?

**Comment by tumashu** [comment]
I mean is : after the window is resized, center it again :-)

**Comment by ch11ng** [comment]
One problem we are facing now is resizing an X window in EXWM is somewhat inefficient and awkward.  Perhaps migrating to the subframe feature would solve the problem.

**Comment by ch11ng** [comment]
This is now possible by customizing `exwm-manage-configurations`.
