### ISSUE TITLE
Customize starting number for workspaces

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#276]
Given that there are some shortcuts to switch between workspaces using the numbers, it makes sense to start with 1. I'm fine with the default being starting from 0, but if this were overrideable, it'd be great.

**Comment by tumashu** [comment]
override this function:
```
(defun exwm-workspace--prompt-for-workspace (&optional prompt)
  "Prompt for a workspace, returning the workspace frame."
  (exwm-workspace--update-switch-history)
  (let* ((current-idx (exwm-workspace--position exwm-workspace--current))
         (history-add-new-input nil)  ;prevent modifying history
         (history-idx (read-from-minibuffer
                       (or prompt "Workspace: ")
                       (elt exwm-workspace--switch-history current-idx)
                       exwm-workspace--switch-map nil
                       `(exwm-workspace--switch-history . ,(1+ current-idx))))
         (workspace-idx (cl-position history-idx exwm-workspace--switch-history
                                     :test #'equal)))
    (elt exwm-workspace--list workspace-idx)))

```

**Comment by ch11ng** [comment]
Not possible yet because we hard-coded it in https://github.com/ch11ng/exwm/blob/master/exwm-workspace.el#L156.  Perhaps someone other would prefer Roman numerals so it has to be a generic way.

**Comment by ralt** [comment]
Ok, thanks. Closing this issue then.

**Comment by ch11ng** [comment]
I've added it in 7d967e73619e3628848b711f482b5db816636bda.  You can achieve what you want with

```elisp
(setq exwm-workspace-index-map (lambda (i) (number-to-string (1+ i))))
```

**Comment by ralt** [comment]
Lovely! Thanks.

**Comment by therockmandolinist** [comment]
This seems a bit unintuitive, it will only change the workspaces to be _displayed_ as 1-indexed, but they are not truly 1-indexed. The initial workspace remains workspace 0, bound to `s-0` or `s-w 0`, but is shown as 1. Is there any way to get actual 1-indexing for workspaces? This makes more sense to me only because of how the numbers are ordered on the keyboard.

**Comment by therockmandolinist** [comment]
On second thought, I can make enough changes (bindings, how the workspace is displayed in mode line) to make myself believe workspaces are 1-indexed, no need for the index itself to start at 1.

**Comment by ch11ng** [comment]
@dieggsy EXWM has no default bindings for switching workspace.  The 0-based index is just an internal implementation.  You are free to define your own ones.

**Comment by WJCFerguson** [comment]
switching with `exwm-workspace-index-map` broke `exwm-workspace-move-window` for me.  I tweaked it with:
``` elisp
(defun jf/shift-workspace--list (org-fun &rest args)
  "Run ORG-FUN with ARGS on a workspace list shifted to match +1 indexing."
  (let ((exwm-workspace--list (cons nil exwm-workspace--list)))
    (apply org-fun args)))

(advice-add #'exwm-workspace--prompt-for-workspace :around
            #'jf/shift-workspace--list)
```
