### ISSUE TITLE
After-suspend hook?

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#277]
Whenever I resume from suspend, my setxkbmap layout is lost, so I need to rerun it. Finding the root cause would be nice, but meanwhile, having a hook where I can re-run the setxkbmap command would be a workaround. Does that exist?

**Comment by tumashu** [comment]
Maybe you should code a  setxkbmap command, and bind it to a keybinding, when layout lost, just run type the keybinding :-)

**Comment by ralt** [comment]
That means I have to do something manual every time I resume from suspend, which is far less than ideal.

**Comment by tumashu** [comment]
buffer-list-update-hook?

**Comment by ralt** [comment]
Not running `setxkbmap` every second during normal emacs usage would be nice.

**Comment by tumashu** [comment]
you can let your hook function only run setxkbmp only once by a global variable

**Comment by ralt** [comment]
Sorry for the snide remark, I didn't mean it.

That said, `buffer-list-update-hook` is far from being optimal.

**Comment by ralt** [comment]
The global variable wouldn't be reset when I suspend, so it'd never run after resuming. Suspending or hibernating dumps the process state, which includes global variables.

**Comment by ch11ng** [comment]
Just checked the core protocol and I don't think there is an X11 event for this so EXWM won't be aware of such state.

**Comment by ralt** [comment]
Yeah, I'm guessing there isn't a "resume" hook, but something more generic like "redraw everything", I'm not sure. Where is the list of these hooks? Can I play with them in exwm to see if any of them works?

**Comment by ch11ng** [comment]
There are `pre-redisplay-function` and `pre-redisplay-functions`.  There's also a list of standard hooks in `(info "(elisp) Standard Hooks")`.  Note that the `suspend-*` and `resume-*` hooks are not relevant here.

**Comment by ralt** [comment]
Thanks, I'm going to play with that. Meanwhile, I'm closing this issue.
