### ISSUE TITLE
EXWM and dzen2 (or any other status bar)

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#281]
I'd like to run dzen2, but when I start it from my `.xinitrc`
```
echo foo | dzen2 &
exec emacs
```
I see it in the background during Emacs initialization, until it gets covered by Emacs. Any way to work around that?

A more general question to EXWM users: how do you get a permanent status display on screen? (Such as time, CPU usage, etc.) Typically Emacs can display this in the mode-line but I find it rather inconvenient when the modeline gets too long and the right part does not fit the window anymore.

**Comment by tumashu** [comment]
I use xfce4-panel

**Comment by Ambrevar** [comment]
I'd rather stick to something lighter like the aforementioned bars. But why xfce4-panel in the first place?

**Comment by tumashu** [comment]
Just because I use xfce :-)

**Comment by tumashu** [comment]
Maybe you can try to launch dzen2 after exwm start.

**Comment by Ambrevar** [comment]
Then dzen2 covers the Emacs frame...

**Comment by tumashu** [comment]
you can try this: https://github.com/zk-phi/symon

**Comment by Ambrevar** [comment]
Yep I found that one a while back, I haven't given it a try yet. Looks neat though.

It does not solve the problem _per se_, but it might solve the problem for me.

**Comment by tumashu** [comment]
```
Typically Emacs can display this in the mode-line but I find it rather inconvenient when the modeline gets too long and the right part does not fit the window anymore.
```
Normal mode-line setup is not suitable exwm, you can override it.

**Comment by tumashu** [comment]
![tim 20170727170933](https://user-images.githubusercontent.com/67725/28662964-9440fad6-72ee-11e7-8e43-40ea3c8bee72.png)
I override it like above.

**Comment by Ambrevar** [comment]
Still, it won't scale: with the emms track, the date, the weather and whatnot, my 1280-pixel-wide screen feels very overwhelmed...

**Comment by ch11ng** [comment]
Just checked the source of dzen2 and it seems you have to specify the `-dock` option.

**Comment by Ambrevar** [comment]
The `-dock` parameter is curiously undocumented. I've reported the issue: https://github.com/robm/dzen/issues/43.

The following works for me:
```
echo foo | dzen2 -p -dock &
```

During my tests, I got bitten by an Eshell difference in the `echo` command: dzen2 needs a terminating newline, so then the Eshell command is `echo -n foo | dzen2 -p -dock`.

**Comment by lyr3** [comment]
lemonbar works out of box...
