### ISSUE TITLE
Calling `exwm-layout-toggle-fullscreen` non-interactively

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#282]
`(exwm-layout-toggle-fullscreen)` does nothing when called without args.
This is because the `id` is nil.  I think you should set a default value or document this behaviour.

**Comment by ch11ng** [comment]
It's a command so it's intended be called interactively:

* M-x exwm-layout-toggle-fullscreen
* M-: (call-interactively #'exwm-layout-toggle-fullscreen)

**Comment by Ambrevar** [comment]
A command can also be relevant as a function.  Why not making it usable directly from lisp?  It comes at no cost.
