### ISSUE TITLE
Documentation: Emacs server (--daemon) and exwm-enable

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#284]
I avoid putting `(server-start)` in my config as I like to start stand-alone Emacs instances too.
So I use `emacs --daemon` instead.

Similarly, I'd like to retain an Emacs config that works on WM other than EXWM, so I don't put `(exwm-enable)` in my config either.
(Note: calling `exwm-enable` from within another WM seems to have no effect. To be confirmed.)

If you are in the same situation as me, you'd be tempted to add this to your `.xinitrc`:
```
exec emacsclient -a "" -c --eval "(exwm-enable)"
```
or
```
emacs --daemon
exec emacsclient -c --eval "(exwm-enable)"
```

To your utter dismay, it won't work.  This, I believe, because the Emacs frame (`-c`) must be spawned _after_ `exwm-enable` was called.

The solution is very straightforward:
```
emacs --daemon -f exwm-enable
exec emacsclient -c
```

I think it might be worse documenting this in the wiki. Any comment?

**Comment by ch11ng** [comment]
It's always safe to call `exwm-enable`.  EXWM will just complain it's unable to start if there is another window manager.

BTW `exwm-enable` simply add the hooks.  EXWM is actually launched by `exwm-init`, which is triggered when a frame is created.

**Comment by Ambrevar** [comment]
Thank you for the details.  I'll add this to the wiki then.

**Comment by Ambrevar** [comment]
Done.
