### ISSUE TITLE
It seems some windows can escape EXWM control

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#286]
I noticed that when some apps change or create/destroy windows in rapid succession, some windows seem to escape EXWM control.

For example, in this video (https://www.youtube.com/watch?v=BzbMN2vfr_0 @ 1:00) you can see window resizing itself out of EXWM control even though my EXWM configuration has the force-tiling mode enabled with the following:

(setq exwm-manage-force-tiling t)

I noticed this with very few applications. In this example, I am using IPMIView application which I believe is a Java Applets based app, which may not be conforming to X11 guidelines.

**Comment by bvk** [comment]
Also, when I run the same application without exwm-manage-force-tiling, I see the following behavior: when the application changes (or creates) the window with different sizes, some of them do not have surrounding mode-line (or emacs frame) -- which I suspect represents escaping from EXWM control.

**Comment by ch11ng** [comment]
I can't see very clearly but did it have an associated buffer? I don't think it's managed at all.  Java's implementation of X is quite unconventional BTW.

**Comment by bvk** [comment]
Application window gets resized (or destroyed and created) several times. Sometimes I can see the emacs mode-line sometimes and sometimes I don't.  When there is a mode-line visible, I can see the window name in the buffer list, otherwise, i.e. when the window doesn't have mode-line I don't see any associated buffer.

**Comment by bvk** [comment]
A better quality video is here: https://vimeo.com/227635943

**Comment by ch11ng** [comment]
I tested IPMIView against VirtualBMC since I have no server to test with at home, but that did not seem to work.  Perhaps IPMIView can only connect to Supermicro (or real) servers.  I notice IPMIView comes with JRE bundled.  Does it make any difference if you replace that?

**Comment by ch11ng** [comment]
There is now a 'managed' per-application configuration that can force managing any X window.  So I'm closing this issue now.

**Comment by ch11ng** [comment]
There is now a 'managed' per-application configuration that can force managing any X window.  So I'm closing this issue now.
