### ISSUE TITLE
Pinentry freeze

### ISSUE THREAD

**Issue by dieggsy** [ch11ng/exwm#288]
I believe https://github.com/ecraven/pinentry-emacs/issues/7 is related to this too. It seems like EXWM isn't able to handle pinentry windows, for some reason. 

`gpg --version`: `gpg (GnuPG) 2.1.15`
`pinentry --version`: `pinentry-gnome3 (pinentry) 1.0.0`

Using `password-store-get` from the `password-store` package (an emacs interface to [pass](https://www.passwordstore.org/)) causes emacs to just freeze. When I quit the process, _then_ the pinentry dialog shows up (usually not immediately).

Similar things happened whenever I tried to provoke a pinentry dialog in other ways, too - for example, decrypting a file from the command line with `gpg -d` (for the first time, gpg-agent not running yet) causes a freeze, `C-c`-ing it gives me control back, and some time later the pinentry dialog pops up. 

I'm not really sure what the cause of this is or how to debug. I know there was mention about gpg emacs integration with `allow-emacs-pinentry` and/or using `pinentry-tty`, but I haven't quite gotten that to work, and would really like to fix this problem. Any ideas?

**Comment by therockmandolinist** [comment]
On second thought, I think it's only actually freezing when called from `password-store`, which may be due to emacs calling a synchronous process while having to handle the window popping up as a result of that process at the same time.

**Comment by ch11ng** [comment]
Use pinentry-tty and put `(setq epa-pinentry-mode 'loopback)` in your .emacs.  The graphic version of pinentry easily times out on EXWM.

**Comment by dieggsy** [comment]
@ch11ng is there any other trick to this? I tried that and the password-store command just gave me a gpg failure error.

**Comment by ch11ng** [comment]
Sorry but it seems password-store does not work in loopback mode.  Emacs supports directly encrypting files through `epa` but this package does not utilize it.

**Comment by dieggsy** [comment]
Hmm, I can't even seem to get EPA to use emacs for the pinentry prompt, but that's not an EXWM issue at that point. Regarding password-store, I suppose I can talk with them and just bind an external program (with e.g. rofi) in the meantime. Thanks!

**Comment by sarg** [comment]
I have spent some time tackling this issue and can confirm that the behaviour is caused by synchronous call by `password-store.el` as @dieggsy said. If I understood everything correctly, `password-store.el` starts `pass show <pass_entry>` using `call-process`. This causes emacs to block until the command returns, effectively disabling process of xcb events.

The good news is that auth-source supports password-store without resorting to using `pass` binary. Take a look at `auth-source-pass-parse-entry` or just get working code from https://github.com/hlissner/doom-emacs/tree/develop/modules/tools/password-store

**Comment by madnificent** [comment]
@sarg The provided link is dead.  Do you have an alternative link and/or can you attach your solution to this issue?

**Comment by sarg** [comment]
It lives [here](https://github.com/hlissner/doom-emacs/blob/157348ba9b7c42e05bd35645432225ba012f6344/modules/tools/pass/autoload.el). Those functions use `auth-source-pass-parse-entry` from [auth-source-pass](https://github.com/DamienCassou/auth-password-store).
