### ISSUE TITLE
Support for desktop notifications

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#289]
Are they supported?

Reference: http://www.galago-project.org/specs/notification/

**Comment by therockmandolinist** [comment]
Notifications work just fine for me using `dunst` and either `notify-send` from shell or `notifications-notify` in emacs.

**Comment by ch11ng** [comment]
@Ambrevar The notification spec is not relevant for a window manager.  Just as @dieggsy pointed out somethings like dunst would work.

**Comment by Ambrevar** [comment]
I did not know that.  Great, problem solved!
