### ISSUE TITLE
Mouse click in imagej main window is not working

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#291]
ImageJ is a image processing application in Java. I make the main
menu window floating with the following configuration :

    (defun my-exwm-set-floating ()
      (interactive)
        (mapc (lambda (window-name)
                (let ((window-class-name (car window-name))
                      (window-title (cdr window-name)))
                      (when (and exwm-class-name
                                 (string= exwm-class-name window-class-name)
                                 (string-prefix-p window-title exwm-title))
                        (exwm-floating--set-floating exwm--id))))
                      '(("ij-ImageJ" . "ImageJ"))))

    (add-hook 'exwm-manage-finish-hook #'my-exwm-set-floating)

Now the menus and dialogue box buttons are not clickable.

**Comment by ch11ng** [comment]
I installed ImageJ 1.51i from Debian's repo and it seemed working fine with your snippet.

**Comment by QiangF** [comment]
Maybe my version or oracle java 7 is too old. I will update to debian stretch when I have the time.
