### ISSUE TITLE
[DISCUSSION] Can a parent WM instruct emacs to manage a window?

### ISSUE THREAD

**Issue by mitch-kyle** [ch11ng/exwm#292]
Just wondering if anyone has tried this or has any insights before I dig into xcb code

## The Question
Can I instruct my window manager in certain situations to delegate the task of opening  window to a running emacs instance with exwm enabled? If so how, if not why?

## What I am trying to do
Have the ability to 'Dock' and 'Undock' windows from a parent window manager to emacs

**Comment by ch11ng** [comment]
EXWM won't work If there's a already running window manager because the X protocol does not allow it.  You may turn to use Xephyr (running EXWM in a nested X server) or XEmbed (EXWM is not relevant here but you can still use XELB to do embedding; not every X window supports being embeded though).
