### ISSUE TITLE
high CPU use and poor performance when switching workspace from org-mode doc

### ISSUE THREAD

**Issue by taohansen** [ch11ng/exwm#294]
here's an example of a keybind i have to switch to workspace 1:
`  (exwm-input-set-key (kbd "s-1")
                      (lambda () (interactive) (exwm-workspace-switch 0)))
`
if my cursor is on an org-mode line of text (any text, not just code) and i attempt to switch my workspace, all interactivity locks, fans kick in, and my CPUs max out until i move my cursor off the busy line and onto any empty line at which point all commands execute in serial. 

to achieve good performance, i must first move my cursor onto an empty-line in whatever org-mode doc i am working on, then switch.

**Comment by ch11ng** [comment]
I find it hard to reproduce.  Which versions of Emacs and Org do you use? Does it also happen when you invoke `M-x exwm-workspace-switch 0`? And what if you remove all customizations to Org?

**Comment by taohansen** [comment]
a number of issues i was experiencing appear to have been the result of a poorly configured init.el. i can no longer reproduce this issue myself so i will close it.
