### ISSUE TITLE
Handle dedicated windows.

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#297]
Emacs allows one to mark a window as "dedicated" to a buffer (see `set-window-dedicated-p`, and `window-dedicated-p`). Unfortunately, EXWM will currently attempt to map new X windows into dedicated windows and fail (leaving it in an inconsistent state where the keymaps aren't properly configured). It should:

1. Do what the rest of emacs does when does when displaying the buffer. If the current window is dedicated, it should display the X window in a different emacs window (it should be fairly straightforward to re-use the logic emacs uses for handling other buffers/windows).
2. Stealing X windows from dedicated windows puts them into a bit of a funky state. EXWM should either undedicate these windows or somehow avoid moving the X window. IMO, the second option is better but probably difficult to implement robustly.

**Comment by ch11ng** [comment]
It's of course a bug.  I'll push a fix.

**Comment by ch11ng** [comment]
It's fixed in 46dfaeb0310e4a331ffe5d19c0774c64e786ff27.
