### ISSUE TITLE
Some bindings escape EXWM in line mode and are passed to the underlying program

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#298]
The following binding does not work in Qutebrowser / Xterm (and maybe any X program).

```
(exwm-input-set-key (kbd "s-O") #'exwm-layout-toggle-fullscreen)
```

If, instead, I bind it to `s-o` or `s-R`, then it works.  Am I missing something?

**Comment by ch11ng** [comment]
I think it's related to #283.

**Comment by Ambrevar** [comment]
Why?
I don't seem to be able to reproduce this.  Can you?  If not, feel free to close it.

**Comment by ch11ng** [comment]
There was a bug relating to numeric keys.  I should have been fixed in response to that issue.
