### ISSUE TITLE
exwm not filling display

### ISSUE THREAD

**Issue by cinder88** [ch11ng/exwm#299]
I am trying to get exwm working on GuixSD. I've installed:

- xhost
- xset
- xsetroot
- gnome-settings-daemon
- dbus
- xelb
- and of course, exwm

I then placed the provided xinitrc file in ~/.xsession and made it executable.

Currently exwm starts and mostly works fine. The problem is that the exwm frame does not take up the entire display. Instead, it only takes up the upper left corner.

Passing --fullscreen to emacs in ~/.xsession makes exwm _look_ like it's going to take up the entire display when starting, but after startup the frame is still the same size as before.

I'm convinced this is an exwm issue because my other X window managers work fine, and the mouse can move outside of the exwm frame when running.

Also, I run exwm in Gentoo, where it works fine.

**Comment by ch11ng** [comment]
Could you provide the output of `xwininfo -root -tree`?

**Comment by cinder88** [comment]
I'm not sure what happened, but I just tried installing things again and the problem has gone away. What I did:

- Uninstall everything from the list above
- Install exwm from melpa
- Install xhost (and xwininfo, not sure if relevant)

Then things worked fine.

Thank you for the excellent package, it's very creative!

**Comment by ch11ng** [comment]
Did you modify the configuration?

**Comment by cinder88** [comment]
I removed the dbus-launch part so that the last line of the config is `exec emacs'. I think it's possible that the display manager (slim) calls dbus-launch on its own, so that my second call was messing things up. Usually I don't have a display manager, and the default config works fine.

**Comment by tumashu** [comment]
Do you use the newest exwm? If not, exwm on GuixSD is not work properly, I suggest you install exwm with "guix package -i", it will add a exwm command.  add this command to  .xsession may work

**Comment by tumashu** [comment]
by the way,  exwm in GuixSD is use  ~/.exwm as it config file.

**Comment by cinder88** [comment]
I will try that when I have time. Also, thank you for providing GuixSD support.

**Comment by emacsomancer** [comment]
Is there any update on the state of exwm on guixsd? (I was planning on setting up a machine with guixsd+exwm at some point and wanted to be pre-armed.)

**Comment by tumashu** [comment]
Not at moment,  exwm change too many in new version, maybe should wait to more stable.

**Comment by prosoitos** [comment]
I am having a similar issue:

**on Arch Linux, with LXDE**

exwm does not fill the bottom of the display. If I change workspace, that fixes it. So, after each reboot, I go to a 2nd workspace, then come back to my 1st workspace and the display is fine.

**Comment by ch11ng** [comment]
Have you enabled the RandR module? With it workspaces should get another resize on startup.

**Comment by prosoitos** [comment]
I have. But here is what I get:

![image](https://user-images.githubusercontent.com/4634851/40590638-cf6de4ea-61b6-11e8-8ce8-8f09bf105057.png)

It is not far off, but you can see that the display is not filled at the very bottom. As I said earlier, if I switch to another workspace, this gets corrected.

In case my setting or randr is wrong, here is what I have in my init file:

```elisp
(require 'exwm-randr)
(setq exwm-randr-workspace-output-plist '(1 "eDP1"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output eDP1 --below eDP2 --auto")))
(exwm-randr-enable)
```

**Comment by ch11ng** [comment]
@prosoitos Could you turn on debugging and check if the size in the message `[EXWM] Setting #x???? to ?x?+?+?` on startup correct? You can check the actually size with the xwininfo utility.

Also how did you launch that bar?

**Comment by prosoitos** [comment]
Sorry for my late reply. It turned out that my `exwm-randr` function was not correct. Now that it is correct, the display fills in as expected when `exwm` starts.

> Also how did you launch that bar?

Are you referring to the top bar? If so, this is part of [qutebrowser](https://github.com/qutebrowser/qutebrowser) and has nothing to do with `exwm`.

Now... this issue forced me to experiment quite a bit with `exwm-randr` and I have 2 questions (I am happy to open new issues if this has no place here):

- is there a way to have the mouse follow the selected workspace while using `exwm-randr` with multiple monitors? Right now, jumping from one monitor to another works great, but the mouse stays put and I have to move it manually

- I have failed to get `exwm-randr` to work with 3 monitors. The 3rd monitor is detected by `randr` but there is no display

Thank you!!!

**Comment by prosoitos** [comment]
Note: here is my `exwm-randr` settup:

```elisp
(require 'exwm-randr)

(setq exwm-randr-workspace-output-plist '(0 "eDP1" 9 "HDMI1" 8 "HDMI2"))

(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output eDP1 --auto --output HDMI1 --above eDP1 --auto --output HDMI2 --right-of HDMI1 --auto")))

(exwm-randr-enable)
```

**Comment by ch11ng** [comment]
> * is there a way to have the mouse follow the selected workspace while using exwm-randr with multiple monitors? Right now, jumping from one monitor to another works great, but the mouse stays put and I have to move it manually

Considering different monitors are not necessarily of the same size, where should we place the cursor after switching to another monitor? It shouldn't be hard to implement if there is a general accepted rule.

> * I have failed to get exwm-randr to work with 3 monitors. The 3rd monitor is detected by randr but there is no display

It's always possible to inspect RandR settings with `xrandr`.  Is the third monitor connected and correctly resized/placed? And are you able to move cursor to that area?

**Comment by prosoitos** [comment]
> Considering different monitors are not necessarily of the same size, where should we place the cursor after switching to another monitor? It shouldn't be hard to implement if there is a general accepted rule.

Great! I am really glad that you are open to the idea of potentially implementing this!

If not too hard to implement, having it jump back to its last position on that workspace/screen would be ideal for situations that require a lot of jumping back and forth between screens. If too hard to implement, the centre of the screen would also be pretty good since that is what will probably, on average, lead to the minimum "mouse travel" to get to a point of interest. But any placement would already be a lot less "travel" than having to move the mouse all the way across to the 2nd monitor.

> It's always possible to inspect RandR settings with xrandr. Is the third monitor connected and correctly resized/placed? And are you able to move cursor to that area?

`xrandr` tells me that it is connected. But it may not be active though. I can move the mouse to it, but nothing shows on that monitor, so I do not see the mouse once it gets to it (but it does not get stuck on the edge of the previous monitor and I can move it out in the right direction. Except that it falls into a big black hole there).

**Comment by prosoitos** [comment]
I finally got things to work with exwm, exwm-randr, and 3 monitors.

**Comment by ch11ng** [comment]
@prosoitos The cursor warping feature can now be turned on by customizing `exwm-workspace-warp-cursor`.

**Comment by prosoitos** [comment]
Oh great! I imagine that I have to install from source to check this feature? (I installed from ELPA).

**Comment by ch11ng** [comment]
Yes, this feature is currently only available when installing from source.  There was some issues blocking an ELPA release, but I think it won't get too long this time.

**Comment by prosoitos** [comment]
Thank you!

**Comment by medranocalvo** [comment]
0.19 has been released since long.  Please, reopen if you find issues.

**Comment by prosoitos** [comment]
I started having the same problem a week or two ago (on startup, the display does not fill in the screen entirely: as shown in my previous picture, there is a little gap at the bottom). As when it was happening months ago, switching to a different workspace immediately fixes it (so it isn't a big problem).

**Comment by prosoitos** [comment]
Question:

When I map different monitors to different workspaces with:
```elisp
(setq exwm-randr-workspace-output-plist '(1 "HDMI1" 8 "HDMI2" 9 "DP2"))
```I can plug and unplug monitors and everything works right away.

Now, when I want external monitors to mirror my primary monitor, I change the code
```elisp
(add-hook 'exwm-randr-screen-change-hook
             (lambda ()
               (start-process-shell-command
                "xrandr" nil "bla bla bla")))
```
accordingly. But the line of code with `exwm-randr-workspace-output-plist` used to be fine and I used to always leave it in my init file. Now, it messes things up when I have a mirroring setup. And in that mirroring setup, if I plug an external monitor, it is detected by xrandr, but nothing is displayed until I reboot.

I am not sure how I could set `exwm-randr-workspace-output-plist` to have the display show without reboot in a mirroring situation.

**Comment by prosoitos** [comment]
In case my 2 different setups are not clear, when I want external monitors to show different workspaces, I have:

```elisp
(setq exwm-randr-workspace-output-plist '(1 "HDMI1" 8 "HDMI2" 9 "DP2"))

(add-hook 'exwm-randr-screen-change-hook
	  (lambda ()
	    (start-process-shell-command
	     "xrandr" nil "xrandr --output eDP1 --auto --output HDMI1 --above eDP1 --auto --output HDMI2 --right-of HDMI1 --auto --output DP2 --right-of HDMI1 --auto")))
```
and all works beautifully.

(Note: `HDMI2` and `DP2` are redundant in that setup, but this is done on purpose as this allows things to work without changing anything whether I use a VGA or a DVI cable).

Now, my setup to have an external monitor mirrors my primary monitor is:

```elisp

(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output eDP1 --auto --output HDMI1 --scale-from 1366x768 --same-as eDP1 --output HDMI2 --scale-from 1366x768 --same-as eDP1 --output DP2 --scale-from 1366x768 --same-as eDP1")))
```

And it works, but I have to reboot each time I plug a cable.

So my question was:

Is there a way to set `exwm-randr-workspace-output-plist` in this mirroring situation to have external monitors display automatically, without reboot.

```elisp
(setq exwm-randr-workspace-output-plist '(1 "HDMI1" 8 "HDMI2" 9 "DP2"))
```
used to work in both settings, but I recently had to take it out, in the mirroring situation, to have things work.

**Comment by ch11ng** [comment]
> I started having the same problem a week or two ago (on startup, the display does not fill in the screen entirely: as shown in my previous picture, there is a little gap at the bottom).

Nothing relevant has been changed in EXWM I'm afraid.  Have you upgraded Emacs?

> Also, not sure if this is due to a recent change in exwm or in xrandr, but I had to change my xrandr settings (in my init file, through `exwm-randr-screen-change-hook`) to have things work again.

EXWM now uses RandR 'monitors' instead of 'outputs' (and `exwm-randr-workspace-output-plist` is renamed to `exwm-randr-workspace-monitor-plist` accordingly).  They are basically identical in most cases but 'monitors' are more flexible in that they can be defined as arbitrary rectangular areas.  You can use `xrandr --listmonitors` to check them out.

> Is there a way to set `exwm-randr-workspace-output-plist` (or set something else) in this mirroring situation to have external monitors display automatically, without reboot.

`exwm-randr-workspace-monitor-plist` can be changed on the fly, but it won't take effect until some event is detected (an external monitor plugged for example) or `exwm-randr-refresh` is invoked manually.
