### ISSUE TITLE
Some X windows (e.g. Qutebrowser) freeze randomly until window configuration is changed

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#300]
Using:

- Gentoo
- GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.15) of 2017-08-28
- xorg-server 1.19.3
- Qutebrowser: 0.11

Randomly and quite often, a Qutebrowser window will stop rendering.  I can still use Emacs as usual in the other windows.  To resume rendering, I have to change the window configuration (splitting, resizing, anything).  If I type something when the frozen window is selected, the key sequence gets transfered to Qutebrowser properly.

I don't have much details about that one, feel free to help me debug this further :)

**Comment by ch11ng** [comment]
How to reproduce this? Does it have any log about this? And does this affect other Qt-based applications?

**Comment by Ambrevar** [comment]
I managed to get more details:
- It only freezes the rendering of the webpage. The rest of Qutebrowser works as expected.
- Thus it has nothing to do with Qt.

Steps to reproduce:

- Bind that function to `s-TAB`.
```
(defun switch-to-last-buffer ()
  "Switch to last open buffer in current window."
  (interactive)
  (switch-to-buffer (other-buffer (current-buffer) 1)))
```

- Open a Qutebrowser window where something is moving (blinking cursor, video, gif, you name it).

- Press `s-TAB` twice so that you come back to that Qutebrowser window.  The rendering should be frozen.  If not, repeat pressing `s-TAB` until it does.

The point of using the binding is that you don't change the window configuration while going back to the Qutebrowser window.  If you invoke some before menu window, the issue won't be triggered.

**Comment by ch11ng** [comment]
I don't think I was able to reproduce it.  Are you experiencing high CPU usage or something abnormal with this issue?

**Comment by Ambrevar** [comment]
No, CPU is fine. Everything else seems to be normal.  Any other idea?

**Comment by ch11ng** [comment]
Then I have no idea.  Qutebrowser is a normal WebKit-based application I think.  You may try with different configurations and see if the problem persists.

**Comment by Ambrevar** [comment]
If that helps, it seems that I can only reproduce this with Qutebrowser _and_ the QtWebengine backend.  With QtWebkit the rendering freeze does not seem to occur.

**Comment by Ambrevar** [comment]
At last some progress!  See https://github.com/qutebrowser/qutebrowser/issues/3158.
Could be that EXWM is blame-free, stay tuned!

**Comment by ch11ng** [comment]
Thanks for the info! But I'm afraid EXWM may contribute to the problem.

**Comment by Ambrevar** [comment]
I can't report the issue on the latest Qt and qutebrowser.  Closing.
