### ISSUE TITLE
<XF86AudioMute> and friends do not work in X buffers

### ISSUE THREAD

**Issue by kahrkunne** [ch11ng/exwm#302]
Binding keys like <XF86AudioMute, <XF86Launch1> etcetera works fine in Emacs buffers, but simply do nothing when pressed in buffers belonging to X applications.

**Comment by ch11ng** [comment]
You have to do

```elisp
(push 'XF86AudioMute exwm-input-prefix-keys)
```

**Comment by kahrkunne** [comment]
Will try that tomorrow, thanks
