### ISSUE TITLE
Creating named buffers in char-mode

### ISSUE THREAD

**Issue by B2RN** [ch11ng/exwm#303]
Hey,

Trying to figure out if it's possible to create a buffer (on startup) that starts up in char-mode and can be renamed on creation.

Basically for spawning a few terminals on startup that I'd use. Right now I'm at being able to spawn a few ST instances via:

```(start-process "st" nil "st")```

The second arg for ```(start-process ...)``` is BUFFER, thought that might be it but that's the buffer the process is associated with. Which is, different, I guess.

Tried something like the below, but no go:

```(progn (start-process "st" nil "st") (switch-to-buffer "xterm") (rename-buffer "test"))```

There an easy way to go about this that I'm missing, or?

**Comment by ch11ng** [comment]
You can do it in `exwm-manage-finish-hook` (see the wiki for examples).  BTW you can switch to char-mode with `exwm-input-release-keyboard`.

**Comment by B2RN** [comment]
Gave this a go, but doesn't seem to work:

```
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "URxvt"))
              (progn
                (message "Hi")
                (exwm-input-release-keyboard)))))
```

The "Hi" does pop up, however. And I matched the class name in IELM just in case, looks to be correct.

Does `exwm-input-release-keyboard` need the ID? It's specified as optional, but can't say I'm sure if my call to it is correct.

**Comment by ch11ng** [comment]
`exwm-input-release-keyboard` is a command and should be called with

```elisp
(call-interactively #'exwm-input-release-keyboard)
```

**Comment by B2RN** [comment]
Ah, alright.

Works like a charm, now. Appreciate the help.
