### ISSUE TITLE
Different Eamcs frame fonts/sizes per each workspace

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#304]
Hi,

Can we assign different emacs fonts to different workspaces?  If yes, could anyone knowledgeable please add an example to the wiki?

My specific use case is as follows:

I use EXWM with XRANDR on my laptop. Laptop is connected to monitors of different sizes every day (eg: monitor at home, another monitor at work, etc.). When laptop is connected to high resolution display (eg: 4K monitor) emacs frame becomes too big and fonts become very small and the opposite happens when laptop is connected to monitor with smaller resolution, etc.

If we have the ability to pick different font sizes (or adjust DPI) with each workspace I could dynamically adjust the font settings based on the resolution of the connected display.

A solution to this use case would be helpful.

Thanks,
Chaitanya

**Comment by ch11ng** [comment]
You can modify the font and the font size of a particular frame.  For example

```elisp
(set-frame-parameter (selected-frame) 'font "Monospace-12")
```
