### ISSUE TITLE
Restarting emacs crashes X clients with tray icons

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#306]
On emacs exit, EXWM needs to nicely remove these icons. I'm not sure how one does this, but other trays don't seem to have the same problem.

---

To reproduce, enable the tray, start a tray application, restart emacs (without restarting X).

**Comment by ch11ng** [comment]
Thanks.  I've fixed it in 3edf2e8880aff11803f4d4889914e05c3543e6e7.
