### ISSUE TITLE
`helm-buffers` input hangs in follow-mode with EXWM 

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#308]
This is a cross-issue between Helm and EXWM.  I've opened an issue on Helm's issue tracker: https://github.com/emacs-helm/helm/issues/1889.

> With helm-buffers and helm-follow-mode on, after going up/down over the buffers a few times the input hangs. To resume activity, I've got to click on the non-Helm buffer then other-window to the minibuffer to stop Helm.

I can reproduce on a barebone config:
```
(require 'helm-config)
(require 'exwm)
```
I start EXWM with this from my `.xinitrc`:
```
	emacs --daemon -f exwm-enable
	exec emacsclient -c
```

There is no CPU hog or anything.

It seems to only happen when Emacs is run as EXWM.

The issue seems to occur only when at least one EXWM buffer is present. I've tried with different X programs.

I think an EXWM buffer has to be hovered at least once before it triggers the issue.

**Comment by Ambrevar** [comment]
Update:
https://github.com/emacs-helm/helm/issues/1889#issuecomment-337834655

**Comment by ch11ng** [comment]
@Ambrevar Is the problem still there?

**Comment by Ambrevar** [comment]
I believe it is, although I can't test at the moment.

**Comment by ch11ng** [comment]
Not a helm user by now but I think it's time to try it out at least for this problem.

**Comment by medranocalvo** [comment]
Just tried this: it works fine here, with my config.  Please, check again with the bare-bones recipe you gave above.

Helm works fine for me with EXWM, except when using the minibuffer frame.

**Comment by Ambrevar** [comment]
Can't reproduce indeed.  Well, problem solved!

**Comment by medranocalvo** [comment]
Great!  Thank you for reporting.
