### ISSUE TITLE
Automatically switch to char mode on window creation

### ISSUE THREAD

**Issue by timor** [ch11ng/exwm#309]
What is the correct way to automatically start all EXWM buffers in char mode?

I have tried
`(add-hook 'exwm-manage-finish-hook 'exwm-input-release-keyboard)`, but that still opens new windows in line mode.

**Comment by ch11ng** [comment]
The following code should work:

```elisp
(add-hook 'exwm-manage-finish-hook (lambda () (call-interactively #'exwm-input-release-keyboard)))
```

**Comment by timor** [comment]
That works.  Thank you.
