### ISSUE TITLE
Do not allow toggling floating in minibuffer

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#314]
Calling `exwm-floating-toggle-floating` on a minibuffer will confuse Emacs real bad.
You can test it with Helm: open any Helm buffer and press a global binding associated to the offending function.

My suggested fix: wrap the code in 
```
  (unless (minibufferp)
```

**Comment by ch11ng** [comment]
Actually this command shouldn't be called on any buffer other than the `exwm-mode` ones.  It's better to use the mode-specific key, or some other mode-specific key you defined yourself.

**Comment by Ambrevar** [comment]
Before:

	(exwm-input-set-key (kbd "s-SPC") #'exwm-floating-toggle-floating)

After:

	(define-key exwm-mode-map (kbd "s-SPC") #'exwm-floating-safe-toggle-floating)

Fixed! Thanks!

I think you should add to the docstring of the function that it is meant to be non-global.

Also I believe here the safety measure comes at zero cost, so why not adding it?  Your call :)

**Comment by Ambrevar** [comment]
I forgot that `exwm-input-prefix-keys` must be modified accordingly:

	(push ?\s-  exwm-input-prefix-keys)
