### ISSUE TITLE
Prefix Keys

### ISSUE THREAD

**Issue by ghferrari** [ch11ng/exwm#315]
Hi all,

First of all, great work on exwm. I'm trying out a migration from stumpwm and the extra emacs integration is fantastic. 

I'd like to set up and new global prefix key, C-#, which I can then use to switch between applications. For example, I want "C-# c" to launch Chrome, "C-# r" to launch rhythmbox, etc, to allow fast application switching. 

My problem is that the things I've tried only work in emacs buffers. So, if I'm in an emacs buffer I can launch Chrome with"C-# c", but once Chrome is open and displayed, my "C-#" prefix is no longer recognised. Please can you advise how to achieve this?

As a side query, I'm also interested in mimicking stumpwm's run-or-raise command. With this command, you can e.g. switch to an application if it's already open or run it if it's not.  Is there anything in exwm that provides that kind  of functionality?

Thanks in advance, and once again, thanks for all your work on this great project.

**Comment by tumashu** [comment]
```
As a side query, I'm also interested in mimicking stumpwm's run-or-raise command. With this command, you can e.g. switch to an application if it's already open or run it if it's not. Is there anything in exwm that provides that kind of functionality?
```
You can try this tool: https://github.com/tumashu/exwm-x/blob/master/exwmx-quickrun.el

**Comment by tumashu** [comment]
```
My problem is that the things I've tried only work in emacs buffers. So, if I'm in an emacs buffer I can launch Chrome with"C-# c", but once Chrome is open and displayed, my "C-#" prefix is no longer recognised. Please can you advise how to achieve this?
```
Do you config like the below?
```
(push ?\C-# exwm-input-prefix-keys)
(exwm-input-set-key (kbd "C-# ;") #'XXXXXXX)
```

**Comment by ghferrari** [comment]
Thanks tumashu,

Yes, that's what I've tried but it doesn't work. The key sequences
beginning "C-#" are just not recognised when non-emacs applications are
foregrounded. I don't know why it's not working. The only question that it
occurs to me to ask is, does this kind of configuration need to come before
or after the call to (exwm-enable)? In my config it currently comes before.

On a related note, is there any way to enable "C-#" to be a regular keymap
prefix? For example, can I set up my own my-exwm-keymap with C-# as its
prefix, and then define keys directly into my-exwm-keymap?

Many thanks for your help,

Geoff

**Comment by tumashu** [comment]
@ghferrari  you can try "C-t", if "C-t" can work, the problem may Chrome

**Comment by tumashu** [comment]
"\C-#" or C-S-3 ?

**Comment by ghferrari** [comment]
The problem isn't limited to chrome. The key sequences beginning "C-#"
aren't recognised in rhythmbox or gnome-terminal either.

My # is on a key on it's own, not above the 3 key, so I don't think binding
C-S-3 would work either. (I've tried it and it doesn't work).

Should these key sequences be bound before or after (exwm-enable)? Or does
it make no difference?

Geoffrey

**Comment by ch11ng** [comment]
> My # is on a key on it's own, not above the 3 key, so I don't think binding C-S-3 would work either.

It must be an interesting keyboard.  You can try with <kbd>C-t</kbd> or some other conventional prefix keys just as @tumashu pointed out and see if it's the key not recognized or there is any configuration error.  Do remember to push these keys into `exwm-input-prefix-keys`.  If it's the key that is not recognized, please detect its keysym with the xev utility.

> Should these key sequences be bound before or after (exwm-enable)? Or does
it make no difference?

It does not matter actually.

**Comment by ghferrari** [comment]
It's a standard UK keyboard, as shown in the lower half of this image. The
# key is next to enter.




I'll see if I can work out what's happening and get back to you all.

Thanks for the help so far,

Geoff

**Comment by ghferrari** [comment]
Here's what I've found so far.

When I'm in a regular emacs buffer and eval (read-event) and then press C-#, emacs reports
67108899 (#o400000043, #x4000023)

But when I then change to a different application window (e.g. gnome-terminal or chromium), repeating the same test gives the result:

28 (#o34, #x1c, ?\C-\\)

So it looks like C-# is being read as C-\ by emacs in non-emacs-buffers. However, I can still use the # key to type # in gnome-terminal or chromium. So there seems to be a mismatch between how emacs is reading the key and how other applications are reading the key.

I've no idea why this would happen or how to work around it. Any help would be appreciated, include pointers to further tests to run.

**Comment by ch11ng** [comment]
Did you mean when you place the pointer in an X window `read-event` reports <kbd>C-\\</kbd>? It looks like the keyboard layout is mismatched.  You can use the `xev` utility to get their keycodes.

As a workaround for the moment, perhaps you can use both <kbd>C-#</kbd> and <kbd>C-\\</kbd> as prefix keys?

**Comment by ghferrari** [comment]
Many thanks, Chris. What I mean is:

When I'm in an emacs buffer: I run (read-key) and press the # key and it
reports #.

But when I open an xwindows buffer (e.g. chromium or rhythmbox or
gnome-terminal) and do the same thing, it reports \. (Well, actually it
reports "\\" but I think this means backslash.

So it seems the same physical key is getting interpreted differently
depending on which buffer I'm on.

I've got a partial workaround going, but it means I'm not able to use C-\
for anything else.

Geoff

**Comment by ghferrari** [comment]
I'm still mystified about the cause of the problems, but here's some extra info and a workaround that seems to work.

The output from xev when I press Left Ctrl key and # was "Control Control_L". Somehow, my # key was getting interpreted as left control.

I ran xmodmap --pke to get the current keymappings. The key in question for me was keycode 37. I tried remapping this to "numbersign asciitilde numbersign asciitilde dead_grave dead_breve dead_grave", but while this solved the problem with my # key, it also reassigned by left control key!

Currently, I have keycode 37 assigned to "Control_L" and nothing more. I've only tested for ten mins, but this seems to be working with no unintended side effects. I've made this permanent by saving the output of xmodmap -pke into a file and then using xmodmap to read that file in my exwm session script.

I've still no idea about the underlying problem.

**Comment by ch11ng** [comment]
@ghferrari Here is my result:

```
KeyPress event, serial 34, synthetic NO, window 0x2000001,
    root 0xe2, subw 0x0, time 10170820, (-200,250), root:(352,543),
    state 0x1, keycode 12 (keysym 0x23, numbersign), same_screen YES,
    XLookupString gives 1 bytes: (23) "#"
    XmbLookupString gives 1 bytes: (23) "#"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x2000001,
    root 0xe2, subw 0x0, time 10170948, (-200,250), root:(352,543),
    state 0x1, keycode 12 (keysym 0x23, numbersign), same_screen YES,
    XLookupString gives 1 bytes: (23) "#"
    XFilterEvent returns: False
```

Note the keycode is `12` and the state is `0x1` (because I have to press <kbd>shift</kbd>).  Then I can verify the keysym is `0x23` (35):

```elisp
(xcb:keysyms:keycode->keysym exwm--connection 12 #x1)
    => (35 . 1)
```

Please test without any key remapping.
