### ISSUE TITLE
[request] display date and time in exwm-systemtray

### ISSUE THREAD

**Issue by jabranham** [ch11ng/exwm#316]
I'd like EXWM to show the date and time in the echo are at the bottom right of the screen, then the system tray icons to the left of the time. the built-in `display-time-mode` doesn't work for this because it puts the time on the mode line, which is then duplicated across various windows.

**Comment by ch11ng** [comment]
Then we would be divided over in which way the time should be displayed (size/font/color or even whether numerical).  I think it's better to leave it to the user (perhaps there are already some tray applications out there?).

**Comment by Ambrevar** [comment]
I recommend `dzen`, it works well with EXWM:
https://github.com/ch11ng/exwm/wiki#what-about-a-status-bar

**Comment by jabranham** [comment]
Thanks, I'll look into that. Out of curiosity, how does that look then? Are there then three bars at the bottom --- the mode line, the minibuffer area, and then dzen?

**Comment by Ambrevar** [comment]
I prefer docking dzen at the top to avoid having 3 bars stacked together.
