### ISSUE TITLE
<t> is undefined

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#317]
When pressing a global hotkey, I'll occasionally see `<t> is undefined` printed in the message line (and the hotkey won't do anything). This usually only happens when I haven't switched buffers in a while.

Any ideas? Unfortunately, it's a rare event so I can't give you a specific repro.

**Comment by Ambrevar** [comment]
Yup, got that too!  This only happens when I first start EXWM and press a global key.  If I repeat the binding, then it works.
I haven't narrowed down a precise recipe yet.

**Comment by ch11ng** [comment]
It's a known issue with `unread-command-events`.  The version of Emacs has recently been increased to 27 so there has to be another workaround.  I'll see if I can push a fix for this.

**Comment by Stebalien** [comment]
The old workaround doesn't appear to be working as far as I can tell :(.

**Comment by Stebalien** [comment]
Nevermind, it does (needed to restart emacs, not just re-evaluate that section).

**Comment by Ambrevar** [comment]
Which workaround?

**Comment by Stebalien** [comment]
@Ambrevar https://github.com/ch11ng/exwm/issues/227 (yes, I somehow forgot that I've already reported this bug in the past).

Note, you'll need to use `(< emacs-major-version 28)`, not `(< emacs-major-version 27)`

**Comment by Ambrevar** [comment]
Was this bug reported upstream? Bug number?

**Comment by ch11ng** [comment]
@Ambrevar 23980.

**Comment by ch11ng** [comment]
I've pushed a fix upstream.
