### ISSUE TITLE
exwm-workspace-move-window on dedicated-window enters broken state

### ISSUE THREAD

**Issue by WJCFerguson** [ch11ng/exwm#318]
Attempting to move a window that is set dedicated is only partially executed, leaving the system into a bad state.  To reproduce, set window dedicated:

``` elisp
(set-window-dedicated-p (selected-window) t)
```

Then try to move the window to another workspace with `exwm-workspace-move-window`.  The Emacs window thinks it has switched to another buffer, the other workspace thinks it has the X window, but the X window is rendered on the original workspace/monitor.  It seems there's some sort of error triggered when the move is half-way done.

(I've been trying to use window-dedicated-p to preserve X windows that I don't want Emacs to tramp all over, with limited success, but then hit this issue.  If there's a good way to prevent X windows from being fair game for Emacs to pop buffers into, I'd love to know it - Thanks!)

**Comment by ch11ng** [comment]
Which version did you installed? I think the issue with dedicated buffers was fixed in 46dfaeb0310e4a331ffe5d19c0774c64e786ff27.

**Comment by WJCFerguson** [comment]
I seem to have "Version: 0.15" from melpa.  I'll pull from git and give it a try tomorrow.  Sorry, I should have reported the version.

**Comment by WJCFerguson** [comment]
Sorry - I forgot to come back to this.  It is indeed fixed in the current code.
