### ISSUE TITLE
XF86* keys don't work if on a non-Emacs buffer

### ISSUE THREAD

**Issue by deech** [ch11ng/exwm#321]
Hi,
I have code to control the brightness/volume like:
```
    (exwm-input-set-key (kbd "<XF86MonBrightnessUp>")
                        (lambda ()
                          (interactive)
                          (start-process-shell-command  "light -A 5" nil "light -A 5")))
```
If focus is on an Emacs buffer it works fine but on any window (eg. Firefox/Chrome) it appears the application swallows it.

I have verified that this gets evaluated before `(exwm-enable)`. I'm installing from Melpa, the versions are `exwm-0.14` and `xelb-0.12`.

Thanks for a great window manager!

**Comment by ch11ng** [comment]
Is there any error message like `[EXWM] Failed to grab key:`? What if you invoke `(exwm-input--update-global-prefix-keys)` manually?

**Comment by kriyative** [comment]
@deech - I was able to use the following to enable media keys:
```emacs-lisp
(dolist (k '(XF86AudioLowerVolume
             XF86AudioRaiseVolume
             XF86AudioPlay
             XF86AudioStop
             XF86AudioPrev
             XF86AudioNext))
  (pushnew k exwm-input-prefix-keys))
```
However, these still don't take effect in a full-screen'ed player window.

**Comment by ch11ng** [comment]
If those keys only work in line-mode then they are not grabbed properly.  Please do the following test:

```elisp
(xcb:keysyms:event->keysym exwm--connection 'XF86MonBrightnessUp)
    => (269025026 . 0)
```

Note the keysym is `269025026`.

```elisp
(xcb:keysyms:keysym->keycode exwm--connection 269025026)
    => 233
```

Note the keycode is the same as that reported by `xev`:

```
KeyPress event, serial 35, synthetic NO, window 0x2000001,
    root 0xe2, subw 0x0, time 11641738, (-208,429), root:(344,722),
    state 0x0, keycode 233 (keysym 0x1008ff02, XF86MonBrightnessUp), same_scree
n YES,                                                                        
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x2000001,
    root 0xe2, subw 0x0, time 11641738, (-208,429), root:(344,722),
    state 0x0, keycode 233 (keysym 0x1008ff02, XF86MonBrightnessUp), same_scree
n YES,                                                                        
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by IQubic** [comment]
I just wanted to say that this issue still hasn't been fixed. I have the following in my .emacs:
`(defun brighter ()
  (interactive)
  (start-process-shell-command "xbacklight + 10" nil "xbacklight + 10"))
(exwm-input-set-key (kbd "<XF86MonBrightnessUp>") 'brighter)`

This only works if I am in a non X buffer. This binding does not work in an X buffer, either in line mode or char mode. I have no output in *Messages*  related to EXWM.

**Comment by dakra** [comment]
@IQubic I have a similar function in my config but for easier maintainance I
[packaged it](https://github.com/dakra/xbacklight) and bind the keys with use-package.

``` emacs-lisp
(use-package xbacklight
  :bind (("<XF86MonBrightnessUp>" . xbacklight-increase)
         ("<XF86MonBrightnessDown>" . xbacklight-decrease)
         :map exwm-mode-map
         ("<XF86MonBrightnessUp>" . xbacklight-increase)
         ("<XF86MonBrightnessDown>" . xbacklight-decrease)))
```

This works for me in all buffers.

**Comment by ch11ng** [comment]
Does `exwm-restart` help? For some keyboards XELB 0.14 has a problem in initializing the mapping.

**Comment by timor** [comment]
Just wanted to add into the mix that my configuration looks pretty much the same as @IQubic's, and I would say it works like expected.  No idea what the difference could be, though.

**Comment by ch11ng** [comment]
The problem @IQubic is experiencing is likely relevant to  #418.

**Comment by IQubic** [comment]
Pulling the latest version of XELB and EXWM fixed this issue. I can now use my media keys in X applications.

**Comment by medranocalvo** [comment]
It seems to me that this is fixed.  Please, reopen if you still find issues.
