### ISSUE TITLE
kill-buffer returns nil on EXWM windows

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#322]
This might be related to #147. Quoting @ch11ng:

> exwm-mode buffers are often not killed directly until the corresponding X windows get destroyed (exwm-manage--kill-buffer-query-function).

This can cause unexpected behaviour in functions expecting a return value.
Any clue if that can be fixed?

**Comment by ch11ng** [comment]
An X window can't be destroyed immediately as it might hold something pending to be saved.  OTOH we can't wait till it get destroyed (or the user decides not to destroy it), or Emacs would be frozen during that time.  So usually we just tell Emacs the buffer can not be killed.

**Comment by Ambrevar** [comment]
Isn't it possible to add a sentinel to the process?

**Comment by ch11ng** [comment]
@Ambrevar I don't get the point.

**Comment by Ambrevar** [comment]
I'm not sure how X windows work, but if the process held by the window is  terminated, then it's safe to say that we killed the buffer, isn't it?
In that case, we can add a sentinel to the underlying process to know when it terminates, so that we tell `kill-buffer` whether or not the kill was successful.

I haven't looked at the implementation so I might have no clue at all.

**Comment by ch11ng** [comment]
The point is we have to finish the function right away and you will get the return value.  Whether the X window finally getting destroyed is monitored by EXWM already.

**Comment by ch11ng** [comment]
The return value can't be altered in the current implementation so I'm closing this issue for now.
