### ISSUE TITLE
exwm freeze when exwm-cm enabled

### ISSUE THREAD

**Issue by hying-caritas** [ch11ng/exwm#323]
If I enabled exwm-cm, and used the system for long time, the X will be freezed, keyboard/mouse has no response.  I can still connect to emacs server with emcsclient on console, and the error message in "*Messages*" buffer is as follow,

[XELB ERROR] (error "[XELB] Unable to allocate new X resource ID") [3 times]

Run exwm-restart inside emacsclient console can solve the problem.

So I added some function advice to xcb:generate-id to find out who is creating X resource ID, and found exwm-cm will create many X resource IDs.  After taking a look at the source code, I find the X resource IDs are created but not reclaimed.

After disabled exwm-cm, the original problem disappears, I can use the system for several days without reboot.

**Comment by ch11ng** [comment]
There are indeed some X resources not getting freed by EXWM especially the pixmaps created for rendering translucent X windows.  I've pushed 55626530f4a523cccd1d24c8819f7e80543e0276 to fix this.  Please try if it fix your problem.

**Comment by hying-caritas** [comment]
Yes.  It fixed my problem!  Thanks a lot!
