### ISSUE TITLE
Mystery: keys 1, w, r don't work 

### ISSUE THREAD

**Issue by ieure** [ch11ng/exwm#324]
I have a real mystery with exwm.  When I have an X11 window open, pressing the 1, w, or r key doesn't send the corresponding key.  The window appears to lose focus, then regain it.  Other keys work fine.

This happens in both line-mode and char-mode.  In char-mode, I receive an error in the echo area:

"Buffer Google-Chrome is read-only"

I tried enabling `toggle-debug-on-error`, but I didn't get a backtrace.  I'm not sure why.  I don't get any errors in line-mode.

This is using the default exwm configuration.  This is my `.emacs.d/init.el`:

```elisp
(package-initialize)

(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/ime-lisp"))
(add-to-list 'load-path "/opt/local/lib/erlang/lib/tools-2.6.6.4/emacs/")

(require 'exwm)
(require 'exwm-config)
(exwm-config-default)

(require 'ime-top)
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
```

I'm using exwm 0.15, installed with ELPA.

Of three machines I set up exwm on, two of them have had this problem.

**Comment by ieure** [comment]
This behavior is consistent no matter what client I use.  Running xev shows:

```
FocusIn event, serial 34, synthetic NO, window 0xa00001,
    mode NotifyGrab, detail NotifyPointer

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  4294967276 4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

FocusOut event, serial 34, synthetic NO, window 0xa00001,
    mode NotifyUngrab, detail NotifyPointer
```

Other keys send the expected key events.

I'm not sure why this would be happening, do you have any pointers?

**Comment by ch11ng** [comment]
In which mode was the `xev` results captured?  It sounds like those keys are globally grabbed.  Should they be <kbd>s-1</kbd>, <kbd>s-w</kbd> and <kbd>s-r</kbd> instead?  Is the <kbd>super</kbd> key correctly recognized or does the keyboard even have it?

**Comment by ieure** [comment]
Closing in favor of #329.
