### ISSUE TITLE
How is display sleep handled under EXWM?

### ISSUE THREAD

**Issue by ajakk** [ch11ng/exwm#326]
When I leave my computer, after a time the video output turns off. How can I change this display sleep function to never occur under EXWM?

**Comment by kriyative** [comment]
Have you tried `xset -dpms` to disable display power management and `xset +dpms` to re-enable?

**Comment by ajakk** [comment]
That does not work for me, for whatever reason. I'm guessing this would be something independent of EXWM, then?

**Comment by kriyative** [comment]
See what `xset q` reports. For instance, on my laptop I get:
```
....
DPMS (Energy Star):
  Standby: 600    Suspend: 1200    Off: 1800
  DPMS is Enabled
  Monitor is On
```
See the `xset` man page for more details on those values.

**Comment by ch11ng** [comment]
DPMS is definitely not handled by a WM.  BTW You could also try if `xset dpms 0 0 0` works.
