### ISSUE TITLE
Cannot input in X Window

### ISSUE THREAD

**Issue by hying-caritas** [ch11ng/exwm#327]
Sometimes, I cannot input in X Window, the error message is "buffer is read-only".  Normal Emacs buffer works normally.  I found there is " *temp*" buffer in Emacs, which prevent X window to be focused.  And after

(kill-buffer (get-buffer " *temp*))

I can input in X window again.  And after

(get-buffer-create " *temp*")

I cannot input in X window again.

So I want to know whether we can relief the condition in exwm-input--on-buffer-list-update to prevent this?  For example,

(not (eq (current-buffer) (get-buffer " *temp*")))

Any idea?

**Comment by ch11ng** [comment]
The problem should have been fixed by 71a39840b239a51eed7455877517ebe612892eff.
