### ISSUE TITLE
Can't bind Hyper-modified keys

### ISSUE THREAD

**Issue by ieure** [ch11ng/exwm#329]
I use Hyper as a modifier for all my keybindings, since I've never found another thing which conflicts with that.

I use H-e/s/d/f (ala WASD) for windmove, and have been struggling to get this to work in exwm.  This is how I have it configured:

```elisp
(exwm-input-set-key (kbd "H-s") #'windmove-left)
(exwm-input-set-key (kbd "H-f") #'windmove-right)
(exwm-input-set-key (kbd "H-e") #'windmove-up)
(exwm-input-set-key (kbd "H-d") #'windmove-down)
```

When I launch Emacs/EXWM, if I have this in the configuration file, many keys generate no events to client applications.  If I comment them out, start up, and eval that block, all keys are sent, but the Hyper-bound keys do nothing once I enter an X11 client window.

If I change the bindings to use Super instead of Hyper, they work fine.

**Comment by ch11ng** [comment]
How do you setup the <kbd>hyper</kbd> key(s)? What's the output of `xmodmap`? And what's the results of the following forms?

```elisp
(xcb:keysyms:event->keysym exwm--connection ?\H-s)
(xcb:keysyms:keysym->keycode exwm--connection (car (xcb:keysyms:event->keysym exwm--connection ?\H-s)))
```

**Comment by ieure** [comment]
Okay, I think this is a race/startup issue of some sort.  I'm not sure where the actual problem is, so I'm going to dump as much as I can and hopefully one of us will be able to make sense of it.

I've modified the `pc` symbols file that ships with xkb to separate the modifiers:

```diff
--- /usr/share/X11/xkb/symbols/pc	2017-07-18 00:38:55.000000000 -0700
+++ symbols/pchyp	2017-11-19 09:26:36.387784790 -0800
@@ -1,3 +1,4 @@
+// PC keyboard, but with super/hyper as separate modifiers
 default  partial alphanumeric_keys modifier_keys
 xkb_symbols "pc105" {
 
@@ -53,7 +54,8 @@
     modifier_map Mod4   { <SUPR> };
 
     key <HYPR> {	[ NoSymbol, Hyper_L	]	};
-    modifier_map Mod4   { <HYPR> };
+    // Put Hyper on Mod3, instead of Mod4, with Super.
+    modifier_map Mod3   { <HYPR> };
     // End of modifier mappings.
 
     key <OUTP> { [ XF86Display ] };
```

Then, I have some additional symbols which remaps some keys on the internal keyboard:

```
// For Dell XPS13, make the right control key a Hyper modifier
partial modifier_keys
xkb_symbols "xps13" {
    replace key <RCTL> { [ Hyper_R ] };
    modifier_map Mod3 { Hyper_R };
    modifier_map Mod4 { Super_L };

    include "altwin(meta_alt)"
};
```

This is tied up into an xkb keymap:

```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pchyp+us+inet(evdev)+ctrl(nocaps)+xps13"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

And it's all loaded up in my `.xsessionrc`:

```shell
# -*- mode: shell-script -*-

gnome-settings-daemon &
sleep 1

HOST=`hostname`
if [ $HOST = "fermion" -o $HOST = "alpha" ]; then
   KB=`xinput list | grep "AT Translated Set 2 keyboard" | cut -d= -f2 | cut -f1`
   xkbcomp -w0 -I$HOME/.xkb -i $KB $HOME/.xkb/keymap/xps13 $DISPLAY
fi

if [ $HOST = "fermion" ]; then
    xinput set-prop 12 296 0, 1
    xinput set-prop 12 288 1
fi

STARTUP="/usr/bin/emacs -f exwm-enable"
```

I'm logging in via a pty console and running `startx`, since this has been faster to work with than logging in/out with a display manager.

What I see is:

Immediately after launching X, the hyper key doesn't work in Emacs.  If I run `xev`, I see the correct events being generated, but Emacs sees the unmodified key events.  Behavior in X11 clients is unpredictable.  Sometimes, some keys fail to generate any events (#324).  Sometimes they work, but the Hyper modifier does not.

If I immediately issue `exwm-restart`, everything works fine, both in Emacs and X clients.

I'm wondering if this is an issue of Emacs creating its first frame before exwm is correctly initialized.  I don't know how to tell if that's the case, or how to ensure that it doesn't happen.

**Comment by ch11ng** [comment]
Your method of remapping keyboard is completely new to me.  It sounds like XELB has a problem handling `MapNotify` / `NewKeyboardNotify` event.  I'll try to figure it out.

**Comment by ch11ng** [comment]
Does evaluating (some of) the following forms also work?

```elisp
(xcb:keysyms:-update-keytypes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-keycodes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-modkeys exwm--connection xcb:keysyms:-device)
```

**Comment by ieure** [comment]
I'm on XELB 0.12, and I don't see a newer version.  I updated to EXWM 0.16 (and removed 0.15), and the problem is unchanged.

I also noticed that when I first start exwm, if I press E/S/D/F (without modifiers), the Emacs frame loses focus -- I see the block cursor become a hollow square, and the mouse pointer appears.

xkb is kind of a hassle, but it's the only way to have different per-device keymaps.  When I'm using an external keyboard, I want the right control key to be control, but on the internal one, it should be hyper.

**Comment by ch11ng** [comment]
I meant installing from git.  The fixed are not released yet.  BTW there may be a delay after switching from one keyboard to another, and I'll push a fix later.

**Comment by ieure** [comment]
I installed from Git this morning.  I removed the ELPA packages, then cloned the xelb/exwm repos, opened those in dired, and ran `package-install-from-buffer` on them.

Behavior is identical, inside Emacs, E/S/D/F cause the focus to flash, H-E/S/D/F produces no modifier, and things work fine if I restart exwm.

**Comment by ch11ng** [comment]
Then could you try (some of) the following forms? I'm not sure which one is necessary for your setup now.

``` elisp
(xcb:keysyms:-update-keytypes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-keycodes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-modkeys exwm--connection xcb:keysyms:-device)

(exwm-input--on-keysyms-update)
```

**Comment by ch11ng** [comment]
@ieure Is this still a problem?

**Comment by medranocalvo** [comment]
Closing due to lack of feedback.

**Comment by HumHongeKamyaab** [comment]
#817 seems to be same issue. I can give further feedback.

**Comment by HumHongeKamyaab** [comment]
@ieure  did you manage to solve this issue, 3 years back?

**Comment by ieure** [comment]
> @ieure did you manage to solve this issue, 3 years back?

Mostly.  The crux of the issue seems to be that X doesn't propagate keymap changes to clients started before the keymap was changed, and that includes EXWM.  The "Warning (emacs): Key unavailable: H-t" error is telling you that there is no Hyper modifier in the keymap when EXWM starts, which means you can't bind it to anything.

You can either move the keybinding earlier in your init process (mine is in `.xsessionrc`, but I know this isn't universal across distros), or `M-x exwm-restart` after you initially log into the session.

**Comment by HumHongeKamyaab** [comment]
Hi, Thanks for the response. Can you please look at #817, I have given `~/.xinitrc, ~/.xmodmap` configs there.
I use `startx ~/.xinitrc` in the `tty` to launch X. 
xmodmap ~/.xmodmap is already defined before `exec emacs` call in `~/xinitrc`
