### ISSUE TITLE
Keyboard doesn't work

### ISSUE THREAD

**Issue by jmgrosen** [ch11ng/exwm#33]
I tried setting up my Emacs/X config files as suggested, and things seemed to work... except the keyboard. Pressing keys on either my internal (laptop) keyboard or my external (USB) keyboard does nothing. My mouse moves the cursor around, though, and I can click on the buffer name to switch buffers, so Emacs is definitely responding. Enabling `exwm-debug-on` produced no helpful output.

Any ideas?

**Comment by ch11ng** [comment]
Does it work without the external keyboard? If you click to switch to the `*Messages*` buffer, what will be logged after keys are pressed?

**Comment by jmgrosen** [comment]
It does not work without the external keyboard. Nothing is logged in `*Messages*` after keys are pressed.

I got some more information, though: I tried launching my normal window manager (xmonad) with `xinit` rather than my usual `startx`, and the keyboard didn't work there, either. When I tried starting exwm with `startx`, the keyboard worked! However, it gave some errors in `*Messages*`:
```
error in process filter: let: [XELB] Connection failed: No protocol specified

error in process filter: [XELB] Connection failed: No protocol specified

progn: [XELB] Connection timeout
```
Perhaps expectedly given these errors, none of the actually window manager-y features worked. Any ideas as to the differences between `startx` and `xinit` that would be causing these discrepancies?

**Comment by jmgrosen** [comment]
This is on Emacs 24.5.1., BTW, not the officially supported Emacs 25.

**Comment by ch11ng** [comment]
Perhaps the latter problem is the same as that reported in #4. `startx` is a wrapper of `xinit` and does some extra work.

**Comment by jmgrosen** [comment]
Adding the `xhost +` seems to have fixed things, thanks! I'm posting this from Firefox, inside Emacs :)

Definitely still buggy, but worth working on! Thanks for all your awesome work -- this has been a dream of mine for a while!
