### ISSUE TITLE
Issues when focusing X windows

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#330]
When I open a new X window from an X window (without doing anything within emacs), the new X window isn't properly focused (input goes to emacs). For example, opening a new Firefox window with `ctrl+n`. If, however, I emacs is focused when I open the window (e.g., with an emacs hotkey), everything works fine.

Likely caused by https://github.com/ch11ng/exwm/commit/71a39840b239a51eed7455877517ebe612892eff, related to #310.

**Comment by Stebalien** [comment]
I was able to "fix" this by *not* adding the current idle time to the delay in exwm--defer. However, I'm sure an actual fix will be more nuanced.

**Comment by ch11ng** [comment]
Please test if dd6596b1f41a02021d5b60e823a3ae7e5664c92a fixes the problem.
