### ISSUE TITLE
Emacsclient and buffer kill deadlock

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#331]
I forward my shell's CWD to emacs by running the following in a chpwd hook (zsh):

```
emacsclient -n -e "(with-current-buffer (exwm--id->buffer $WINDOWID) (setq default-directory $(quote_emacs "$PWD/")))"
```

After updating, my exwm hangs a bit (then asks me if I want to kill the unresponsive terminal process) if I close it with emacs (`kill-buffer`) instead of exiting the shell. This happens even if I background and then disown that command (??).

Note: While haven't reliably reproduced this behavior before updating today, I have occasionally noticed EXWM hang when closing buffers with `kill-buffer` so this may have been happening before but now it's happening every time.

If you use ZSH and a terminal that sets the WINDOWID variable, you should be able to reproduce this by adding the following to your zshrc:

```bash
__exwm_chpwd() {
    emacsclient -n -e "(with-current-buffer (exwm--id->buffer $WINDOWID) (setq default-directory $(quote_emacs "$PWD/")))" >/dev/null
}
chpwd_functions+=(__exwm_chpwd)
```

**Comment by ch11ng** [comment]
What's `quote_emacs`?

**Comment by Stebalien** [comment]
Sorry, ignore that part. It's a local function for escaping strings for emacs.

**Comment by Stebalien** [comment]
This appears to have been fixed. Thanks!
