### ISSUE TITLE
Unkillable Phantom Buffers for Trayed Applications

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#332]
Recently, I've noticed that pithos (an unofficial desktop client for pandora) is leaving behind phantom buffers whenever I unhide/hide it from the tray. I'm guessing this has to do with the fact that the window is still "there", just unmapped.

**Comment by ch11ng** [comment]
Please test if 589b84040980504f0de7d80771b4ccfd63af4eef fixes the problem.
