### ISSUE TITLE
defcustom instead of defvar

### ISSUE THREAD

**Issue by yegortimoshenko** [ch11ng/exwm#333]
It'd be neat to be able to customize EXWM via `custom-set-variables`.

**Comment by ch11ng** [comment]
This has been proposed before.  I seldom use the customization feature but I'll try.

**Comment by osmoc** [comment]
I'd like to second that. In addition to much nicer UI it has benefit of integrated documentation and things like selection from pre-defined list of values for a given option which reduce the chance of configuration mistakes.

**Comment by ch11ng** [comment]
Done.
