### ISSUE TITLE
Problem with hydras and focus

### ISSUE THREAD

**Issue by ecraven** [ch11ng/exwm#335]
When starting a hydra from an exwm-mode buffer, the hydra is shown, but focus returns to the X window, so you cannot actually use the hydra. Clicking into the minibuffer (which shows the hydra), closes the hydra.
I'm not sure whether this is fixable, but it would be great to keep focus in the minibuffer until the hydra is finished.

**Comment by WJCFerguson** [comment]
See https://github.com/abo-abo/hydra/issues/243 - you need the latest v0.16 and to add advice around the hydra body, or as in the comment on that link, a `:body-pre` and `:post` entry in the hydra.

**Comment by ecraven** [comment]
thanks, #254 fixes it!
