### ISSUE TITLE
Tint2 doesn't work if started before emacs (EXWM)

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#336]
Tint2 is one of the best system tray app. The two launching methods of tint2 are:

1. launch in ~/.xinit before emacs

    tint2&
    sleep 10
    exec dbus-launch --exit-with-session emacs;;

2. run command in ansi-term or in init.el

    (start-process "tint2" nil "tint2")

Using method 1, tint2 sometimes disappear but the process is still running.
The problem with method 2 is tint2 doesn't survive an exwm-restart.

Can anyone confirm this?

**Comment by ch11ng** [comment]
What's the use of `sleep 10` here? Does it help reproducing this issue?

**Comment by QiangF** [comment]
No. It helps to show that tint2 is working before emacs start up.

**Comment by tumashu** [comment]
try exwm-init-hook
```
(defun exwmx-xfce--startxfce4 ()
  "A command used to run startxfce4."
  (interactive)
  (if (executable-find "startxfce4")
      (progn
        (message "EXWM-X: starting Xfce ...")
        (exwmx-shell-command "startxfce4"))
    (message "EXWM-X: xfce is not installed, abort!")))

(add-hook 'exwm-init-hook #'exwmx-xfce--startxfce4)
```

**Comment by QiangF** [comment]
Here is another solution:(I highly recommend phwmon and tint2)

    (if (string= (getenv "exwm_enable") "yes")
        (if (string= (getenv "auto_start_done") "no")
        (progn  (require 'exim)
                (require 'exwm)
                (require 'exwm-input)
                (exwm-enable)
                (exwm-init)
                (start-process "tint2" nil "tint2")
                (start-process-shell-command "phwmon" nil
"/home/q/.dotfiles/bin/phwmon.py --cpu --mem --net --io --bg 333 --fg_cpu
f00 --fg_mem 0f0 --fg_net ff0 --fg_io f0f --net_scale 1 --io_scale 10")
                (start-process-shell-command "slock" nil "xautolock -time
15 -locker slock")
                (setenv "auto_start_done" "yes"))))

**Comment by QiangF** [comment]
I am settled with using systemd to start X11 applications.

    (start-process-shell-command "environment import" nil "systemctl --user import-environment")
    (start-process-shell-command "start X11 appss" nil "systemctl --user start X11.target")

more infomation can be find at : https://www.lukeshu.com/blog/x11-systemd.html
