### ISSUE TITLE
[Feature request] Customizable tray?

### ISSUE THREAD

**Issue by dieggsy** [ch11ng/exwm#337]
I'm not familiar with the internals of `exwm-systemtray`, but would it be possible to create a customizable system tray?

I really like the placement of exwm's tray, but I generally don't like default system tray icons/arrangement, and it'd be neat to be able to be able to run something similar to e.g. https://github.com/vivien/i3blocks in that place instead, which has customizable text and color (icons are usually just unicode in that example).

If this is out of exwm's scope, could you give any pointers for where one might start if this is possible?

**Comment by ch11ng** [comment]
Do you mean displaying some text in the echo area and make it right aligned? I think instead of using the X11 library you should hack Emacs which would be more consistent with your Emacs setup.

**Comment by dieggsy** [comment]
@ch11ng I could try that, though wouldn't it be blocked/hidden when getting any messages? I think that's an advantage of using X11

**Comment by ch11ng** [comment]
With EXWM's systemtray the message displayed in echo area is simply blocked if it's too long which I think is not an ideal solution.

**Comment by dieggsy** [comment]
@ch11ng huh I agree. In any case, thanks for the idea. I've been putting something together with [minibuffer-line](https://elpa.gnu.org/packages/minibuffer-line.html) and some advice to `message`, and it seems to be working so far.
