### ISSUE TITLE
xelb error and a few other issues

### ISSUE THREAD

**Issue by kinleyd** [ch11ng/exwm#338]
I have a setup that appears to be mostly working barring a few hiccups. firefox, urxvt, emacs itself, etc. all work. However, there are a couple of apps that instantly freeze the system. One of them is fbreader, which sometimes gives me an error while freezing out:

[XELB ERROR] (wrong-type-argument (or eieio-object class) nil obj) [2 times]

Another app, xfe, a file manager, also freezes the system (occasionally only) but provides no clues.

Additionally, I use slim as my login manager. I consistently get "failed to execute login command" on the first attempt, but on the second it always works. I realize slim is no longer being maintained so I'm not sure if this is a slim or an exwm issue, although with herbstluftwm I never get this error.

I'm on Arch Linux and start exwm with the following .xinitrc config:

xrdb -load ~/.Xresources &
udiskie &
xbindkeys &
nitrogen --restore &
compton --config ~/.compton.conf -b &
mpd &                           
emacs --daemon &
exec emacsclient -c

and in my init.el:

;; exwm 
(require 'exwm)
(require 'exwm-config)
(exwm-enable)
(exwm-config-ido)

(setq exwm-workspace-show-all-buffers t) ;

;; You may want Emacs to show you the time
(setq display-time-default-load-average nil)
(setq display-time-day-and-date t)
(display-time-mode t)

;; setup workspaces
(setq exwm-workspace-number 3)

;; multimonitor setup
(require 'exwm-randr)
(setq exwm-randr-workspace-output-plist '(0 "DVI-I-1" 1 "DVI-D-0" 2 "HDMI-0"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output DVI-I-1 --output DVI-D-0 --output HDMI-0 --auto")))
(exwm-randr-enable)

;; exwm compositing manager
(require 'exwm-cm)
(exwm-cm-enable)

;; In the following example, we use class names for all windows expect for
;; Java applications and GIMP.
(add-hook 'exwm-update-class-hook
          (lambda ()
            (unless (or (string-prefix-p "sun-awt-X11-" exwm-instance-name)
                        (string= "gimp" exwm-instance-name))
              (exwm-workspace-rename-buffer exwm-class-name))))
(add-hook 'exwm-update-title-hook
          (lambda ()
            (when (or (not exwm-instance-name)
                      (string-prefix-p "sun-awt-X11-" exwm-instance-name)
                      (string= "gimp" exwm-instance-name))
              (exwm-workspace-rename-buffer exwm-title))))

;; exwm system tray -- I don't see much happening with this
(require 'exwm-systemtray)
(exwm-systemtray-enable)
(setq exwm-systemtray-height 16)

**Comment by kinleyd** [comment]
The slim "failed to execute login command" error goes away when I remove the trailing & from 'emacs --daemon &' in .xinitrc.

**Comment by kinleyd** [comment]
I just upgraded to Linux kernel 4.14.4-1 and now fbreader works just fine. exwm still at v. 0.16 - so something must have been fixed on the system side. Happy here and greatly enjoying exwm. :)

**Comment by ch11ng** [comment]
> compton --config ~/.compton.conf -b &

I don't think there is any third-party compositor compatible with EXWM yet.

> emacs --daemon &
> exec emacsclient -c

This is problematic since when emacsclient tries to establish a connection the server is not necessarily ready.  Instead you could simply do `exec emacsclient -a "" -c` .

PS.  I just tried fbreader 0.12.10 with the latest build of Emacs and couldn't seem to reproduce the bug. 
 Perhaps you should try with a minimal configuration?

**Comment by kinleyd** [comment]
Thanks for the response, Chris. 

I've removed the compton setup from xinitrc (I'd left it there for reference - it didn't seem to make any difference either way). 

I'm also now starting emacs with 'exec emacsclient -a "" -c' as you recommended. However, the startup time is about the same as when starting with the --daemon flag - which seems quite long (in seconds though I haven't properly timed it). Should I be expecting a faster start up?

I will try fbreader with a minimal setup. FYI I'm on emacs 25.3-1.

**Comment by ch11ng** [comment]
> Should I be expecting a faster start up?

It depends on how fast Emacs starts up on you machine.

**Comment by tumashu** [comment]
```
It depends on how fast Emacs starts up on you machine.
```
and how fast org-server starts up on your machine :-)

**Comment by kinleyd** [comment]
Lol, yes, I do use org extensively.

At the moment with exwm it's taking a full 14s after my background screen setting to get to my emacs buffers. Previously when using herbstluftwm I may not have noticed any lag because I'd start the emacs daemon early, let hlwm do its thing, and only then display and layout the buffers.

With exwm the setup order has changed, and it looks like I need to optimize my settings, including my init.el. I'll start by seeing how much faster a minimal emacs config affects load up time.

I do want to say that exwm is looking good!

**Comment by kinleyd** [comment]
I tested my setup with minimal settings in init.el. Despite that fbreader continues to freeze the system instantly.

exwm startup time dropped significantly so clearly I'll still have to seek optimizations for init.el.

**Comment by kinleyd** [comment]
My system has become very unstable with frequent system freezes, so I've been scratching my poor head to see what else I should consider. fbreader, puddletag, xfe, firefox, etc. have all been causing the freezes, with the first two being instant freezes upon application load.

The first thing I want to note is that the only difference between my previous and present config is the change in wm: herbstluftwm --> exwm. None of the malfunctioning apps ever froze with herbstluftwm, so I'm thinking that something unstable has been introduced with exwm.

One thing I tried was disabling the exwm compositing manager. Things improved after this: neither fbreader nor puddletag instantly freeze the system. I am actually able to use these apps for a while, but later I get an error (below) without a system freeze: 

Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  slot-value(nil x)
  exwm-floating--set-floating(41943653)
  exwm-manage--manage-window(41943653)
  exwm-manage--on-MapRequest([20 0 78 9 164 2 0 0 101 2 128 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] nil)
  xcb:-connection-filter(#<process XELB> "

**Comment by kinleyd** [comment]
Just received an update to emacs 25.3-2, along with other package and system updates. I've now had fbreader, puddletag and a number of offenders all running together for a while. and I played around with moving the buffers around within and across workspaces. So far no error or system freeze. 

I'm keeping my fingers crossed and will report back after a day or so.

**Comment by kinleyd** [comment]
The update to emacs 25.3-2 (or perhaps some other elements updated recently on Arch) seems to have covered most of the issues here. The system doesn't freeze like before and the apps for which I faced instant lockups are now chugging along smoothly. Yay, I will stick with exwm!

The only issue which remains is that if exwm-cm is enabled, the apps crash as before. As I don't have a need for transparency at the moment, this isn't an issue for me, but it may be for others.

**Comment by ch11ng** [comment]
Glad to hear that your issues are resolved.  I think Emacs 25.3-1 and 25.3-2 are identical except for some distribution-specific patches so it's probably due to something else.

As for the exwm-cm module, it's really not efficient enough for daily use.  I'm considering making EXWM compatible with other compositors but that's a lot of work.

**Comment by kinleyd** [comment]
Thanks Chris. I am thoroughly enjoying exwm as my new wm - Keep up the good work!
