### ISSUE TITLE
EXWM and term-mode

### ISSUE THREAD

**Issue by Sbozzolo** [ch11ng/exwm#339]
Hello,

I am using `multi-term` and I've just realized that I cannot send some combinations to the terminal, even if I am in the terminal `char-mode`. For example, I would like to send `C-s`. When I start Emacs with `-nw` the combination is correctly sent, but with X (and thus EXWM) the combo is caught by Emacs. I tried to play with `exwm-input-send`, but since this is not an `exwm-mode` buffer they don't work. When I use `term-send-raw` the key is not sent either. Am I missing something crucial?

Best,
sbozzolo

**Comment by ch11ng** [comment]
You can check if something is bound to it by invoking <kbd>C-h k C-s</kbd>.  In my setup <kbd>C-s</kbd> can correctly stop shell output.

**Comment by medranocalvo** [comment]
Works fine here as well. @Sbozzolo, could you check again?

**Comment by Sbozzolo** [comment]
I am probably misunderstanding something. 
I have my term open, the commands I try to send are caught by Emacs. So in the case of `C-s` `isearch-forward` would be invoked.

**Comment by medranocalvo** [comment]
@Sbozzolo, which terminal is that? XTerm? Could you answer https://github.com/ch11ng/exwm/issues/339#issuecomment-352239032?

**Comment by Sbozzolo** [comment]
I am using XTerm(327). `C-h k C-s` returns that the command is bound to swiper.

**Comment by ch11ng** [comment]
> `C-h k C-s` returns that the command is bound to swiper.

It seems swiper is globally bound to <kbd>C-s</kbd> (found from swiper's doc)

```elisp
(global-set-key "\C-s" 'swiper)
```

So you either have to remove that or make a local binding for `term-send-raw`.

Besides I'm confused.  We were talking about Emacs's builtin terminal simulator, right?

**Comment by Sbozzolo** [comment]
My bad, I had `(C-s . isearch-forward)` in `term-bind-key-alist`, and I don't remembery why. However, how do I send `C-z`?

**Comment by medranocalvo** [comment]
If we are talking about `term-mode`, you can send `C-z` as follows:

* in `line-mode` press <kbd>C-c C-z</kbd>
* in `char-mode` press <kbd>C-z</kbd>

This is out of EXWM's scope, so I'm closing this issue.
