### ISSUE TITLE
About system tray.

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#34]
who know which tray can work  well with exwm?

**Comment by ch11ng** [comment]
I have no plan to support system tray in EXWM yet. Hopefully somebody will make one with XELB.

**Comment by tumashu** [comment]
I just want to know how to let EXWM works well with external tray app, for example, xfce-panel, lxde-panel and so on? is it unsupport?

**Comment by tumashu** [comment]
```
Hopefully somebody will make one with XELB.
```
With the help or XELB, we may can manager tray icon with a emacs buffer

**Comment by ch11ng** [comment]
> I just want to know how to let EXWM works well with external tray app, for example, xfce-panel, lxde-panel and so on? is it unsupport?

Not supported yet, but it's possible (through EWMH).

**Comment by tumashu** [comment]
lxde  can works with exwm, the issue:

1. emacs frame will be blocked by panel.
2. the keybinding of input method doesn't work..

**Comment by tumashu** [comment]
is it possible add a custom variable ,by which the space of panel can be preserved.

**Comment by ch11ng** [comment]
EXWM is not fully EWMH-compliant yet. Many EWMH features, especially those dealing with interactions between a window manager and other desktop elements (e.g. a pager) are not implemented since they are less useful in a keyboard-centric WM. But I don't object to such ideas; any contributions are welcomed.

**Comment by tumashu** [comment]
stalonetray is a system tray app which can work well with exwm, 


```
xset b off &
xfce4-power-manager &
xscreensaver -no-splash &
nm-applet &
volti &
xmodmap -e 'keycode 135 = Super_R' &
stalonetray &
xhost +
exec dbus-launch --exit-with-session /home/feng/.guix-profile/bin/emacs
```

**Comment by ch11ng** [comment]
* I want to make EXWM more stable and hopefully make a usable release in the near future, so new feature requests would hardly be considered at present.
* AFAIK stalonetray does not work as intended with EXWM.

**Comment by tumashu** [comment]
```
I want to make EXWM more stable and hopefully make a usable release in the near future
```
a good news

**Comment by tumashu** [comment]
stalonetray in exwm, just common float window,

**Comment by tumashu** [comment]
trayer is a good system tray for exwm:

```
xfce4-power-manager &
xscreensaver -no-splash &
nm-applet &
volti &
trayer --edge bottom --align right --width 10 --height 20 --transparent true --alpha 0 --tint 0x00000000 &
xhost +
exec dbus-launch --exit-with-session /home/feng/.guix-profile/bin/emacs

```

**Comment by ch11ng** [comment]
Implemented in fdfdabf95ae75a2f7af2758594b5d0246882f5a0.  You may check out the usage at https://github.com/ch11ng/exwm/wiki#system-tray.

**Comment by bvk** [comment]
How do I test this?

I did (exwm-systemtray-enable) and ran "nm-applet -n" (for network-manager
system tray app) in the background, but I don't see network-manager icon
anywhere.


Thanks,
Chaitanya

**Comment by TLATER** [comment]
It's working for me for both skype and nylas. Have you tried an eval on this?

**Comment by bvk** [comment]
hmm.... my bad, it is actually working, you are correct.


Thanks,
Chaitanya

**Comment by tumashu** [comment]
good job, thanks!

**Comment by tumashu** [comment]
volit can't show the icon in tray:

```
#<process volti>
[EXWM] (System Tray) Try to embed #x2c00003
[EXWM] (System Tray) Embed #x2c00003
[EXWM] (System Tray) Resize from 200x200 to 20x20
[EXWM] (System Tray) #x2c00003 visible? t
[EXWM] Refresh workspace #<frame *scratch* 0xa019028> [2 times]
```

**Comment by tumashu** [comment]
Is it possible show the icons launchd from .xinitrc or .xsession file before exwm

**Comment by ch11ng** [comment]
> volit can't show the icon in tray:
> ...

I tried and the icon shows up.  Does `(setq exwm-systemtray-height 16)` in your init file fix the problem?

> Is it possible show the icons launchd from .xinitrc or .xsession file before exwm

The protocol is initiated by the client side so the answer fully depends on the application in use.  You may start the application in `exwm-init-hook` instead (do set the third argument of `add-hook` to `t`).

**Comment by tumashu** [comment]
(setq exwm-systemtray-height 16)  can fix my problem, thanks!

**Comment by ch11ng** [comment]
What if set it to 8 or 32?

**Comment by tumashu** [comment]
xfce4-power-manager can't show
```
#<process xfce4-power-manager>
[EXWM] (System Tray) Try to embed #x3000003
[EXWM] (System Tray) Embed #x3000003
[EXWM] (System Tray) Resize from 200x200 to 16x16
[EXWM] UnmapNotify from #x3000003
[EXWM] Unmanage #x3000003 (buffer: nil, widthdraw: t)
[EXWM] Focus on #<window 3 on *scratch*>
```

**Comment by tumashu** [comment]
8 and 32 work well

**Comment by ch11ng** [comment]
> xfce4-power-manager can't show

Which version? I tried 1.4.4 and it won't start without a session manager.

**Comment by tumashu** [comment]
My xfce4-power-manager version is 1.4.1,  no error ruturn when I run this command, but i don't know its work status.

**Comment by ch11ng** [comment]
If xfce4-power-manager requires a session manager then it's too heavy weight and should be considered not compatible with EXWM.  `display-battery-mode` is preferred I think.  The tray icon issue is still worth investigating though.

**Comment by tumashu** [comment]
I will try display-battery-mode, thanks
