### ISSUE TITLE
How does one confine certain new and “raised” buffers to certain workspaces?

### ISSUE THREAD

**Issue by akater** [ch11ng/exwm#341]
I use erc to connect to some external program, and the connection on the other side is not particularly good. ERC reloads chat buffers on reconnect, they are either created anew, or are maybe brought to foreground (“raised”, as I'm unaware of a better term) which interrupts normal workflow. I don't know how to check if a buffer was created or raised.

There are probably multiple other ways to deal with this but since we have workspaces, one approach would be to only allow erc buffers to be created or raised on the specific workspace. In fact, I use different exwm workspaces for different sorts of tasks to minimize distraction and to preserve special layouts without additional hassle.

So,
- How does one make new erc buffers appear on, say, workspace 6 only?
- How does one make raised erc buffers appear on, say, workspace 6 only?

**Comment by ch11ng** [comment]
> brought to foreground (“raised”, as I'm unaware of a better term)

It's called displaying a buffer.

I think you can achieve what you want by customizing `display-buffer-alist`.  See `exwm-workspace--display-buffer` for a reference.
