### ISSUE TITLE
Top-align exwm windows

### ISSUE THREAD

**Issue by ecraven** [ch11ng/exwm#343]
At the moment, all X applications that don't automatically resize to the full emacs window size are bottom-aligned (to the modeline). This sometimes "offsets" the mouse, because the application itself believes to be top-aligned. Is there some way to actually top-align it?
There are a few references to window gravity in the sources, but nothing implemented :-/
Thanks for any help with this ;)

**Comment by ch11ng** [comment]
> This sometimes "offsets" the mouse

I don't quite get this.  Could you please give us an example?

**Comment by medranocalvo** [comment]
@ecraven, please name a program suffering from this issue.
