### ISSUE TITLE
Keys simulation doesn't work for translated keys.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#344]
I'd like to use C-h as backspace.
Using the latest git versions (18 dec 2017), I am experiencing this behavior.

```    
(exwm-input-set-simulation-keys
     (mapcar (lambda (c) (cons (kbd (car c)) (cdr c)))
     '(("C-h" . backspace))))
```
Doesn't work with
```
  (define-key key-translation-map [?\C-h] [?\C-?])
```

Using this config C-h works in emacs but not in X applications.

**Comment by ch11ng** [comment]
I guess you didn't define <kbd>C-h</kbd> as a prefix key.  You can do this with the following form.

```elisp
(push ?\C-h exwm-input-prefix-keys)
```

**Comment by sarg** [comment]
Despite that suggested fix didn't help I am closing the ticket. Seems that the problem is related to my emacs configuration and have nothing to do with EXWM. Sorry to bother you.

**Comment by sarg** [comment]
I've got the solution. I should've use translated key in exwm-input-set-simulation-keys.
```lisp
  (define-key key-translation-map [?\C-h] [?\C-?])
  (push ?\C-h exwm-input-prefix-keys)
  (exwm-input-set-simulation-keys '(([?\C-?] . backspace)))
```
