### ISSUE TITLE
Help debugging no protocol specified?

### ISSUE THREAD

**Issue by dieggsy** [ch11ng/exwm#345]
I like to start EXWM from lightdm as an xsession with the following desktop file:
```
[Desktop Entry]
Name=EXWM
Comment=Emacs Window Manager
Exec=env INSIDE_EMACS=1 dbus-launch --exit-with-session emacs
Type=Application
X-LightDM-DesktopName=exwm
DesktopNames=exwm
Keywords=tiling;wm;windowmanager;window;manager;emacs;
```

This was working fine until recently, when I changed my default shell to fish shell. Now I get the `Error in process filter:[XELB]Connection failed:No protocol specified` error. I tried adding variations of `xhost +` including the one in the included xinit file to no avail. Do you have any insight into why this might be happening?

**Comment by dieggsy** [comment]
This can be "fixed" by globally setting `shell-file-name` to `sh` or similar. I think this might be unavoidable, but I'll wait to hear what @ch11ng thinks before closing.

**Comment by ch11ng** [comment]
Perhaps there are some environment variables not exported in fish by default.  You can get a list of environment variables by invoking `export`, and by comparing the results from different shell you may be able to find out the culprit.

**Comment by dieggsy** [comment]
I think in the end I just went with _not_ making fish my default shell, but `exec`ing it in `.bashrc`
