### ISSUE TITLE
Complex simulation keys do not work

### ISSUE THREAD

**Issue by baums** [ch11ng/exwm#348]
In issue #148, you discourage the use of simulation keys starting with C-x, but leave the choice to the user and give the impression that they should work. You say nothing about simulation keys starting with C-c, which I therefore take to be non-discouraged, and which should presumably also work.

Nonetheless, neither of the following rules works for me (EXWM 0.16 on Emacs 25.2.2) when I try them in a Firefox window under EXWM:

```lisp
   ([?\C-x?\C-s] . ?\C-s)
   ([?\C-c?\C-p] . ?\C-p)
```

C-h k in the Firefox window describes both input key combinations as running the command exwm-input-send-simulation-key.

**Comment by ch11ng** [comment]
This works on Emacs 27.  On Emacs 25/26 you can only set simulation keys with a single key event due to a bug in Emacs.

**Comment by baums** [comment]
Thanks for letting me know! I will just keep the rules in my config then and wait for them to start working when I upgrade to Emacs 27.

**Comment by NicolasPetton** [comment]
@ch11ng what bug are you referring to? Do you know the debbugs number?

**Comment by ch11ng** [comment]
It was 23980.  The fix was simple and you can backport it to Emacs 26.
