### ISSUE TITLE
Binding C-i as prefix key

### ISSUE THREAD

**Issue by jtbm37** [ch11ng/exwm#349]
How do you bind C-i as a prefix key ?

I managed to bind it but it only works within an emacs buffer. When in a GUI application, the prefix is correctly sent to exwm but not the following keys. 

Here is my config https://gist.github.com/jtbm37/163779b52238c883cc32adf0f612fb39

Here is where I attempt to bind C-i
```
;; C-i and TAB share the same value in ASCII
;; C-i is indistinguishable from TAB
;; See https://stackoverflow.com/questions/1792326/how-do-i-bind-a-command-to-c-i-without-changing-tab
;; (setq local-function-key-map (delq '(kp-tab . [9]) function-key-map))
;; (keyboard-translate ?\C-i ?\H-i)
;; (push ?\H-i exwm-input-prefix-keys)
(define-key input-decode-map [?\C-i] [C-i])
(push ?\C-i exwm-input-prefix-keys)

(add-hook 'exwm-init-hook
	  (lambda ()

	    ;; You have to register this key in this hook otherwise 
            ;; EXWM will not be able to grab C-i on startup

	    (exwm-input-set-key
	     (kbd "<C-i> k")
	     (lambda ()
	       (interactive)
	       (my-exwm-switch-or-launch "keepassx")))

	    (exwm-input-set-key
	     (kbd "<C-i> w")
	     (lambda ()
	       (interactive)
	       (my-exwm-switch-or-launch "firefox")))
	    ))
```

As you can see from the commented line I tried quite a few things already. However only the non commented lines got me as close to where I want.

I come from stumpwm and built up quite a lot of functionality around C-i so I'd like to port that whole configuration over to exwm.

Thank you for your great software.

**Comment by jtbm37** [comment]
(version)
 "GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2017-09-19, modified by Debian"

**Comment by tumashu** [comment]
C-i seem to equal TAB

**Comment by tumashu** [comment]
I use C-t,  and works well

**Comment by jtbm37** [comment]
> C-i seem to equal TAB

Well I know. I even said so in my post :smile: 

I am wondering how to get around it.

**Comment by tumashu** [comment]
You can try the below command to define global key
```
(defun my-exwm-input-set-key (key command)
  "This function is similar with `exwm-input-set-key', the
different is that `exwmx-input-set-key' protect `key' from
being override by other minor modes with the help of `bind-key*'."
  (exwm-input-set-key key command)
(bind-key* key command))
```

**Comment by jtbm37** [comment]
Thanks @tumashu. I just tried that but still doesn't work. 

In my setup I have `which-key` package. When using `C-i k` I can see the prefix `C-i` is sent to emacs because the minibuffer pops up with the other possible keys (ie w and k). However when typing the other keys they are sent to the GUI app not emacs.

**Comment by tumashu** [comment]
The problem maybe that which-key can not work well with exwm, for it use many  event relate function

**Comment by jtbm37** [comment]
Disabled `which-key`, still same issue.

**Comment by tumashu** [comment]
well, we need to wait the maintainer's help

**Comment by ch11ng** [comment]
I've added key translation support in 6b4bfad87bdf8b4cf13cdfb211ae6c8c24c415ff (an update of XELB is also required).  Please give it a try.

PS. You should make the keybinding this way (and there's no need to put it inside `exwm-init-hook`):

```elisp
(define-key input-decode-map (kbd "C-i") (kbd "<C-i>"))
(push ?\C-i exwm-input-prefix-keys)
(exwm-input-set-key (kbd "<C-i> k") (lambda () (interactive) (message "Prefix C-i works")))
```

**Comment by jtbm37** [comment]
@ch11ng Thank you for the support. This works really great.
ELPA is not yet updated so I had to use the repo directly instead.
