### ISSUE TITLE
The problem when i delete mode-line of float window

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#35]
I use the below code to remove the stalonetray's mode-line, the problem is that
the blue space is hold when mode-line is deleted.

```
(add-hook 'exwm-floating-setup-hook
          #'(lambda ()
              (when (string-match-p "stalonetray" exwm-instance-name)
                (setq mode-line-format nil))))
```

**Comment by ch11ng** [comment]
* Stalonetray should not be managed by EXWM. As I said, I does not work well with EXWM right now.
* Perhaps you also need to resize/refresh it.

**Comment by tumashu** [comment]
in my machine, stalonetray seem to be regard as float window...

**Comment by tumashu** [comment]
i test with gnome-terminal (switch it to float window), when delete mode-line, some unexpected blue blank is exist.

```
...
    (xcb:flush exwm--connection)
    ;; Set window/buffer
    (with-current-buffer (exwm--id->buffer id)
      (setq window-size-fixed t        "这个地方的问题吗？"
            exwm--frame original-frame
            exwm--floating-frame frame)
      (set-window-buffer window (current-buffer)) ;this changes current buffer
      (set-window-dedicated-p window t))
    (select-window window))
  (run-hooks 'exwm-floating-setup-hook))
...
```

**Comment by ch11ng** [comment]
Yes, `window-size-fixed` is always set to `t` for floating windows. So some tweaks are required here.

**Comment by tumashu** [comment]
另外一个问题是，当我手动调整Stalonetray窗口的大小后，exwm没有响应了。。。。

**Comment by ch11ng** [comment]
I've added `exwm-floating-hide-mode-line` / `exwm-floating-show-mode-line` to hide/show mode-line. You might add them to corresponding hooks.
