### ISSUE TITLE
Problem with VirtualBox

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#354]
VirtualBox has a tendency to not render properly within Exwm.

![2018-01-19-182111_2556x1079_scrot](https://user-images.githubusercontent.com/217543/35163108-ed131540-fd45-11e7-8428-64ad8aae8fc2.png)

**Comment by DamienCassou** [comment]
A workaround is to deactivate "auto-resize guest display" in VirtualBox "View" menu.

**Comment by dakra** [comment]
I had the same problem when I was still using i3 and apparently it's a VirtualBox/(qt?) bug not behaving according to specs.
https://www.virtualbox.org/ticket/15863?cversion=0&cnum_hist=2

**Comment by ch11ng** [comment]
It seems VirtualBox always assumes its X window can be resized?

**Comment by DamienCassou** [comment]
Chris Feng <notifications@github.com> writes:
> It seems VirtualBox always assumes its X window can be resized?

I have no clue. How can I help?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by ch11ng** [comment]
>> It seems VirtualBox always assumes its X window can be resized?

> I have no clue. How can I help?

I meant VB tends to resize its top window with a conventional WM which is simply not possible with tiling WMs.

**Comment by mipuha** [comment]
VB's auto resize works very well in tiling Xmonad.

**Comment by ch11ng** [comment]
What's the status of this problem with the latest source?

**Comment by DamienCassou** [comment]
I can't reproduce anymore with latest master. I'm closing for now and will reopen if the problem reappears.
