### ISSUE TITLE
Screen flickering after making window float in exwm-manage-finish-hook.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#355]
I am using this hook to make some windows floating:
```elisp
  (add-hook 'exwm-manage-finish-hook
            (lambda ()
              (when (string= exwm-class-name "TelegramDesktop")
                (exwm-floating--set-floating exwm--id))))
```
It makes screen flicker, because `exwm-manage--manage-window` calls `(exwm-floating--unset-floating id))` first. 

Am I doing this right? Or maybe there should be the way to tell `exwm-manage--manage-window` that window will be floating beforehand?

**Comment by sarg** [comment]
Here is a demonstration https://youtu.be/Mmqxv70NqqQ

**Comment by ch11ng** [comment]
Perhaps #359 is related.

**Comment by ch11ng** [comment]
I think this has been fixed with the last release.

**Comment by ch11ng** [comment]
Please customize `exwm-manage-configurations` to make an X window floating.

**Comment by sarg** [comment]
Thanks! The problem resolved with your suggestion.
