### ISSUE TITLE
emacsclient -nw from terminal doesn't work

### ISSUE THREAD

**Issue by WJCFerguson** [ch11ng/exwm#358]
My use-case is ssh'ing into a remote exwm machine.  

`emacsclient -nw` briefly flashes the terminal background colored, but then the terminal returns to a normal looking state and doesn't respond.  On killing the emacsclient process with `C-c` terminal output is hidden until I type `reset<RET>`.

I don't see any obvious clues in `*Messages*` etc...

**Comment by ch11ng** [comment]
What if you do `emacsclient -nw` in the console of that remote machine directly? And which version of Emacs were you trying?

**Comment by WJCFerguson** [comment]
Version is 25.3.1.  On another machine I have a non-exwm Emacs running with my same config, and I can get emacsclient sessions to it no problem, so I think it's exwm related.  

I take it this isn't a problem you can reproduce - so it's probably something about my config?

**Comment by ch11ng** [comment]
The behavior on 25.3 seems to be identical with that on master.  Could you try with a minimal configuration?

**Comment by WJCFerguson** [comment]
I'll try to work it out some time to do that, but if it's just my setup then please feel free to close the issue.

**Comment by WJCFerguson** [comment]
Apologies, I bisected my config and found it there.  Something, IIRC, where I was setting the face height on all new frames.
