### ISSUE TITLE
Warn when compiled without X support

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#360]
I just lost an hour desperately trying to set up EXWM on a new system... Until I realized I had installed the wrong Emacs package compiled (the one without X support).

Maybe EXWM could throw an error/warning in that case?

**Comment by ch11ng** [comment]
If you turn debug on then there will be a message telling you EXWM is not able to startup.  It's hidden by default.

**Comment by Ambrevar** [comment]
What I get is a black screen for X, and midly garbled output on the TTY.  I don't remember seeing any error there with `--debug-init`.

**Comment by ch11ng** [comment]
No that.  I mean `(setq exwm-debug-on t)`.

**Comment by Ambrevar** [comment]
Oh, I had missed that from the wiki.  Thanks!
