### ISSUE TITLE
Deja Dup window hidden/inaccesible

### ISSUE THREAD

**Issue by taohansen** [ch11ng/exwm#362]
running the GUI backup-tool Deja-Dup I receive the following error on Arch Linux: `[XELB ERROR] (wrong-type-argument window-live-p #<window 13>`.

all other X windows run without complaint. can you reproduce?

**Comment by ch11ng** [comment]
I installed deja-dup 36.3 and found no such error after starting it.  Are there any extra steps required to reproduce this?

**Comment by taohansen** [comment]
i have tested with a cleaner Emacs and the window now creates correctly.
