### ISSUE TITLE
empty frame when magit opens Ediff mode

### ISSUE THREAD

**Issue by sj4** [ch11ng/exwm#363]
When in magit, when pressing 'e' to open ediff mode for the selected hunk, magit seems to create a new frame (??), but instead of showing something, the screen goes black.
From EXWM point of view a new workspace has been created, but it is very difficult to go back to the original workspace, because the minibuffer etc are all missing.
Please let me know if this description is enough to reproduce

**Comment by ch11ng** [comment]
This feature seems working for me.  I'm using the default configuration of mgit.

**Comment by Reasonable-Solutions** [comment]
I seem to recall having to customise this: '(ediff-window-setup-function (quote ediff-setup-windows-plain))

**Comment by ch11ng** [comment]
Yes, it seems we have to set `ediff-window-setup-function` as `ediff-setup-windows-plain`.

**Comment by sj4** [comment]
Is the mentioned workaround something that needs to be set by the users of EXWM, or can it be part of EXWM itself?

**Comment by sj4** [comment]
updated wiki
