### ISSUE TITLE
Cursor gets lost when `save-selected-window` is used

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#366]
Create the following and bind to, say, `s-f`:

```elisp
(defun foo ()
  (interactive)
  (switch-to-buffer "*scratch*")
  (save-selected-window
    (split-window-horizontally)
    (other-window 1)))

(exwm-input-set-key (kbd "s-f") 'foo)
```

Make sure `*scratch*` exists and switch to an EXWM buffer.
Press `s-f`: cursor should be lost, no keypress should work.
The only way to recover from this is to click in some buffer.

**Comment by zevlg** [comment]
I have another case for this error.  I have special binding to make focus follow mouse

```lisp
(defun lg--exwm-kbd-quit ()
  "Make focus follow mouse."
  (interactive)
  (xcb:+request exwm--connection
      (make-instance 'xcb:SetInputFocus
                     :revert-to xcb:InputFocus:PointerRoot
                     :focus xcb:InputFocus:PointerRoot
                     :time xcb:Time:CurrentTime))
  (xcb:flush exwm--connection))

(exwm-input-set-key (kbd "H-G") 'lg--exwm-kbd-quit)
```

Then, while browser is active, I can press `H-G` and move pointer to minibuffer and press `C-h k C-c C-c` for example, help window pops up, and if I press any key then error occurs

```
funcall-interactively: Buffer is read-only: #<buffer  Chromium-browser: Cursor gets lost when `save-selected-window` is used · Issue #366 · ch11ng/exwm - Chromium>
```

**Comment by ch11ng** [comment]
@Ambrevar Your code seems working for me.  Please try with the newest code.

@zevlg Your case is actually different.  Currently EXWM does not handle the case when unexpected key goes to Emacs.  It's not quite elegant to implement this but possible.

**Comment by Ambrevar** [comment]
Indeed, seems like it got fixed after 0.16 then!
Any plan for the next stable release?

**Comment by ch11ng** [comment]
> Any plan for the next stable release?

In days I think.

**Comment by ch11ng** [comment]
@zevlg To make focus follow mouse you only need to set `mouse-autoselect-window` and `focus-follows-mouse`(Please refer to the wiki for details).
