### ISSUE TITLE
Is it possible add a function exwm-layout-set-window-size ?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#367]
Is it possible add a function exwm-layout-set-window-size, which may like:
```
(defun exwm-layout-set-window-size  (width height delta-x delta-y)
    ...
)
```
I want to use this feature to coding commands like: exwm-50%window exwm-90%window

**Comment by ch11ng** [comment]
`exwm--set-geometry` can be used with absolute position.

**Comment by tumashu** [comment]
I use exwm-layout-enlarge-window now, not beautiful but works well :-)
