### ISSUE TITLE
X windows on unfocused workspaces aren't visible

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#368]
When using multiple monitors (one workspace per monitor), X windows on unfocused workspaces (monitors) aren't visible.

**Comment by rayslava** [comment]
83c0a2db works fine.

**Comment by ch11ng** [comment]
Please verify if 5c5729c0d4832a870a928d6d7cc2f990a7e8f649 fixes this.

**Comment by Stebalien** [comment]
Works for me. Thanks!
