### ISSUE TITLE
C-x makes current window loose focus

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#369]
With latest update on a dual-monitor setup: on one of the two monitors, if I press `C-x 3`, a window of the other monitor is divided. I was expecting the current window to be divided. In fact, as soon as I press `C-x`, the current window looses focus.

**Comment by NicolasPetton** [comment]
I confirm the issue on commit `d22e674`.

**Comment by ch11ng** [comment]
Does it happen all the time? I can not seem to reproduce it.

**Comment by DamienCassou** [comment]
I can still reproduce after your last fixes. Here is more information to reproduce:

- on the small monitor, put one application window (e.g., Firefox)
- on the large monitor, put one non-application window (e.g., Magit)

Use `C-x o` to make the Firefox window current. Press `C-x`, the focus in now on Magit. I expect that the focus is still on Firefox.

Now, replace Magit on the large monitor by another application window (e.g., Evince). Give Firefox the focus and press `C-x`. The focus stays within Firefox, which is expected.

**Comment by ch11ng** [comment]
Please verify if 86f2215be3db25a6b6aacd6f8b0cb132b049e034 fixes this.

**Comment by tumashu** [comment]
When switch to floating-mode with global key,  the focus seem to lost?

**Comment by DamienCassou** [comment]
> Please verify if 86f2215 fixes this.

it does. I'm now using the HEAD of the master branch again, thank you.

> When switch to floating-mode with global key, the focus seem to lost?

I confirm

**Comment by ch11ng** [comment]
I've pushed another fix (6200417697544317ee91badd702654def9a1d645).

**Comment by ch11ng** [comment]
The release is out so I'm closing it.
