### ISSUE TITLE
Question: how to set key combination correctly with exwm-input-set-simulation-keys?

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#371]
1. Popular browsers has a shortcut (Ctrl+pageup) to go to previous tab. I am trying to send the shortcut by pressing
Ctrl-Meta-h. I can 't find the correct format.

`
    (exwm-input-set-simulation-keys
        '( ("C-M-h" . [C-prior])
        ("C-M-h" . [\C-prior])
        ("C-M-h" . C-<prior>)
        ("C-M-h" . "C-<prior>") ))
`

2.  what is the correct format for key sequences? such as :

`
    (exwm-input-set-simulation-keys
        '(("C-M-1" . "C-c C-c")
        ("C-c C-x" . "C-c C-c")))
`

**Comment by zevlg** [comment]
You can use `kbd`, fi: `(kbd "C-M-h") ==> [134217736]`

**Comment by QiangF** [comment]
The problem seems to be with "C-<prior>".

**Comment by ch11ng** [comment]
You can now customize `exwm-input-simulation-keys` instead of using `exwm-input-set-simulation-keys`.  It uses the same syntax of `kbd`.  If you are unsure about the syntax, just evaluate the following form and press the key.

```elisp
(key-description (vector (read-key)))
```

**Comment by QiangF** [comment]
The problem seems to be with "C-\<prior\>".

**Comment by QiangF** [comment]
But I tried both the following and neither works. 

    (setq exwm-input--simulation-keys
       '(([134217736] . C-prior)))

    (setq exwm-input--simulation-keys
       '(("C-M-h" . C-prior)))

**Comment by ch11ng** [comment]
You can try customizing `exwm-input-simulation-keys` (not `exwm-input--simulation-keys`).  If you set `exwm-input-simulation-keys` directly you will still need to use the key sequence syntax (refer to https://github.com/ch11ng/exwm/blob/master/exwm-config.el#L55 for an example).

It should be `([?\C-\M-h] . [C-prior])` BTW.
