### ISSUE TITLE
what about add exwm-loader?

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#372]
Similar: https://github.com/tumashu/exwm-x/blob/master/exwmx-loader.el,

**Comment by ch11ng** [comment]
What does it do?

**Comment by tumashu** [comment]
This is useful to package exwm in linux distribution
1. add .exwm as exwm config file
2. use emacs --eval '(require (quote exwm-loader))' to start exwm, so it can be used as exwm.desktop file

**Comment by ch11ng** [comment]
This breaks backward compatibility I'm afraid.  Currently we put configurations in `~/.emacs`.

**Comment by tumashu** [comment]
It just add a option to user,  user can choose which one they use

**Comment by ch11ng** [comment]
It's totally feasible to start EXWM from a `.destop`.  So I'm closing this issue now.
