### ISSUE TITLE
XTerm won't accept non-latin characters in EXWM

### ISSUE THREAD

**Issue by akater** [ch11ng/exwm#374]
I use multiple keyboard layouts, namely latin and cyrillic.

When I start X with `exec xterm`, it reads cyrillic input just fine. However, when run in exwm, it doesn't react to cyrillic input at all. Emacs itself, as well as other programs (firefox, pidgin) also deal with cyrillic input in a perfectly normal way.

This is weird but looks like exwm might have caused it.

**Comment by sarg** [comment]
I can confirm this. Btw `urxvt` iss not affected.

**Comment by ch11ng** [comment]
You need to enable allowSendEvents for XTerm.  One way to do it is to hold <kbd>C-mouse-1</kbd> in XTerm and select 'Allow SendEvents'.

**Comment by akater** [comment]
Thank you. Menu is not totally reliable (XTerm crashes in my case trying to display it). I added the following line
```
XTerm*allowSendEvents: true
```
to Xresources, and it solved the problem. Was almost sure I tried this before but no matter.

**Comment by akater** [comment]
Note: enabling `AllowSendEvents` breaks window title update as it is implemented here https://github.com/ch11ng/exwm/issues/198#issuecomment-249723369 for XTerm. (Can be tested interactively.)
