### ISSUE TITLE
Application loses focus when switching workspace

### ISSUE THREAD

**Issue by jtbm37** [ch11ng/exwm#375]
Version: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian

Consider the following
```
(require 'exwm-randr)
(setq exwm-randr-workspace-output-plist '(0 "DP-4" 1 "DP-0"))
(add-hook 'exwm-randr-screen-change-hook
          (lambda ()
            (start-process-shell-command
             "xrandr" nil "xrandr --output DP-4 --left-of DP-0 --auto")))
(exwm-enable)
(exwm-randr-enable)
```

Steps:
- Switch off monitor DP-4
- Boot computer
- Open application A (eg terminal) in workspace 1
- Switch to workspace 2
- Application A is still shown AND without focus (ie does not receive input).

Expected:
- Application A should not be shown at all when switching to workspace 2.

Commit c821f76dfef9d7592b263f8fea789b6da7fbddf4 introduced the regression.

**Comment by ch11ng** [comment]
What's the output of `xrandr`? By switching off DP-4 did you mean you ended up with only one monitor?

**Comment by jtbm37** [comment]
`xrandr` output is just one monitor (`DP-0` in this case).
Note that in that example I never switched on `DP-4` monitor, at least while the computer was on.

**Comment by ch11ng** [comment]
Please wait for the merge of #378 to actually fix this problem.  You can also make a change to your configuration as a workaround (the `1 "DP-0"` part is redundant):

```elisp
(setq exwm-randr-workspace-output-plist '(0 "DP-4"))
```

**Comment by ch11ng** [comment]
Please check if this problem is fixed with the latest source.

**Comment by jtbm37** [comment]
@ch11ng Thank you. In the latest, 57328b439fdc367519e3ce9f7c6ef2d3a4934cbc,  this is now fixed.
