### ISSUE TITLE
Floating window grows when mode-line is hidden.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#376]
Telegram implements 'hide to tray' behaviour.
I have a major-mode hook which disables mode-line for `exwm-mode`.
Something like that will work too:
```elisp
(setq-default mode-line-format nil) 
```

Every time i close/open Telegram, it's window grows vertically for the mode-line height.
Also it grows horizontally, but I haven't found the reason yet.

Here is the demonstration: [https://imgur.com/a/KmCyg](https://imgur.com/a/KmCyg)

**Comment by ch11ng** [comment]
How did you manage to hide the mode-line? Does it happen after you invoke `exwm-layout-toggle-mode-line` to hide/show the mode-line?

**Comment by sarg** [comment]
I think minimal config for reproduction is:
```elisp
(require 'exwm-systemtray)
(exwm-systemtray-enable)

(setq-default mode-line-format 'nil) 

(add-hook 'exwm-manage-finish-hook
	  (lambda ()
	    (when (string= exwm-class-name "TelegramDesktop")
	      (exwm-floating--set-floating exwm--id))))
```

Then launch Telegram and click on system tray icon several times to show/hide the window.
I also tried irc client hexchat - it also shows this behavior.

**Comment by sarg** [comment]
Here is log with `exwm-debug-on t`
```
[EXWM] Setting #x1c00004 to 1600x881+0+0
[EXWM] Setting #x1c00004 to nilxnil+616+149
[EXWM] Setting #x1800033 to 676x770+nil+nil
[EXWM] Setting #x1c00004 to 676x770+613+150
[EXWM] Setting #x160123b to nilxnil+0+0
[EXWM] Setting #x1800033 to 676x770+nil+nil
[EXWM] Setting #x1c00004 to 676x770+613+150
[EXWM] Setting #x1c00004 to 1600x881+0+0
[EXWM] Setting #x1c00004 to nilxnil+613+150
[EXWM] Setting #x1800034 to 692x788+nil+nil
[EXWM] Setting #x1c00004 to 692x788+610+151
[EXWM] Setting #x160139a to nilxnil+0+0
[EXWM] Setting #x1800034 to 692x788+nil+nil
[EXWM] Setting #x1c00004 to 692x788+610+151
[EXWM] Setting #x1c00004 to 1600x881+0+0
[EXWM] Setting #x1c00004 to nilxnil+610+151
[EXWM] Setting #x1800035 to 708x806+nil+nil
[EXWM] Setting #x1c00004 to 708x806+607+152
[EXWM] Setting #x16014fa to nilxnil+0+0
[EXWM] Setting #x1800035 to 708x806+nil+nil
[EXWM] Setting #x1c00004 to 708x806+607+152
```

You can see how window grows from 676x770 to 708x806.

**Comment by ch11ng** [comment]
I tried hexchat and couldn't reproduce this problem.  But making an X window floating this way is sort of clumsy.  I've added a feature to let users specify whether an X window should be tiling/floating on startup.  You can use it like this:

```elisp
(setq exwm-manage-configurations '(((equal exwm-class-name "TelegramDesktop")
                                    floating t)))
```

Please try if the problem persists.

**Comment by sarg** [comment]
`exwm-manage-configurations` works, but the problem persists.
I have just realized, that even without hiding modeline the window grows **horizontally** for few pixels (approximately one character width) after each hide/show.

**Comment by ch11ng** [comment]
I've just added another option to hide the mode-line.  Please remove `(setq-default mode-line-format nil) ` or anything that helps hiding the mode-line and try the following snippet instead.

```elisp
(setq exwm-manage-configurations '(((equal exwm-class-name "TelegramDesktop")
                                    floating t
                                    floating-mode-line nil)))
```

**Comment by sarg** [comment]
Unfortunately it didn't help. Please note that the problem seems to be unrelated to mode-line visibility. As I stated in previous comment - it still persists even when mode-line is visible.

**Comment by ch11ng** [comment]
You can also make its geometry fixed:

```elisp
(setq exwm-manage-configurations '(((equal exwm-class-name "TelegramDesktop")
                                    floating t
                                    floating-mode-line nil
                                    x 0.3
                                    y 0.1
                                    width 0.4
                                    height 0.8)))
```

**Comment by sarg** [comment]
@ch11ng woah, now it works as I want it to be. Thank you.

When I remove `x` and `y` then the window behaviour is the same as in this comment https://github.com/ch11ng/exwm/issues/220#issuecomment-370012029
(That comment really was meant to be here, I have just mixed up browser tabs.)

**Comment by ch11ng** [comment]
Then let's keep tracking of the original issue.
