### ISSUE TITLE
Floating window content is not drawn

### ISSUE THREAD

**Issue by jtbm37** [ch11ng/exwm#377]
`M-x version`
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian

When loading software that shows a floating window, the content is not shown.

![selection_002](https://user-images.githubusercontent.com/536407/36694475-70aa374a-1b36-11e8-8cbe-b4372b6fc17e.png)

Software used: Jetbrains Rider (free trial [available](https://www.jetbrains.com/rider/)).
Just after load, a popup is shown to select projects/solutions.

Regression introduced in commit 7823eb988c22f5dc804ef862d91a0fcf474ca718

**Comment by sarg** [comment]
You need this in you `.xinitrc`
```
export _JAVA_AWT_WM_NONREPARENTING=1
```

**Comment by ch11ng** [comment]
Yes, this is the old problem with Java.  Nothing to do with floating window actually.

**Comment by jtbm37** [comment]
@sarg Thank you so much ! That solved it.

**Comment by jtbm37** [comment]
@ch11ng Note that before that commit mentioned earlier that variable was not necessary which is why I thought the issue was with exwm.

**Comment by ch11ng** [comment]
EXWM was a reparenting WM but it's changed since version 0.17 .
