### ISSUE TITLE
Hourglass windows created by Emacs

### ISSUE THREAD

**Issue by pipcet** [ch11ng/exwm#38]
I noticed that Emacs creates an unnamed 32000×32000 InputOnly window for each frame, whose sole purpose is to change the cursor to an hourglass shape:

	     unsigned long mask = CWCursor;
	     XSetWindowAttributes attrs;
	     attrs.cursor = x->hourglass_cursor;

             x->hourglass_window = XCreateWindow
               (dpy, parent, 0, 0, 32000, 32000, 0, 0,
                InputOnly, CopyFromParent, mask, &attrs);
           }

         XMapRaised (dpy, x->hourglass_window);
         XFlush (dpy);

Currently we create an `*EXWM*` buffer for these windows, which seems wrong to me, but I'm not sure what the right way to fix it is. Here's some test code that will make Emacs create the hourglass window:

    (let ((display-hourglass t)
          (beg (float-time)))
      (while (< (float-time) (+ beg 10.0))
        (redisplay)
        (accept-process-output nil 1)))

(Is there a possibility of deadlocking when Emacs creates the hourglass window while running EXWM code? I think there isn't, because we don't wait for a response after mapping the hourglass window, but I'm not a hundred percent sure).

**Comment by ch11ng** [comment]
I've always been wondering what are behind those `*EXWM*` buffers. They are quite annoying because they cause input focus lost. Now that we have located the source of this problem, we can solve it by simply ignoring those windows. But those featureless windows are hard to match.

**Comment by pipcet** [comment]
Indeed. The cleanest way would probably be to create a separate X window for each Emacs frame to act as its virtual root window, but that would reduce EXWM's simplicity somewhat. For now, it might be best just to match `(and (= width 32000) (= height 32000))` and ignore such windows; at least that approach appears to work, though of course it prevents the hourglass cursor from being shown.

**Comment by ch11ng** [comment]
> For now, it might be best just to match `(and (= width 32000) (= height 32000))` and ignore such windows; at least that approach appears to work, though of course it prevents the hourglass cursor from being shown.

It certainly works. I don't know where you put this condition but put it in `exwm-manage--manage-window` allows the cursor to be shown. Anyway, it's a bad idea to match a window by size.

**Comment by pipcet** [comment]
> Anyway, it's a bad idea to match a window by size.

Okay, I've had a look at the WM spec, and I think we're safe ignoring any window that has its parent set to one of our desktop windows before we reparent it: we're (i.e. Emacs) the only ones who are allowed to create such windows.

However, implementing that requires listening to CreateNotify events, I think, and managing a list of all top-level windows, not just those with buffers, to remember those that are in withdrawn state. I've hacked up some code that turns exwm--id-buffer-alist into a more general alist of (id . <emacs object>) pairs, where the emacs object is a buffer (for clients), a frame (for desktop Emacs frames) or the symbol `withdrawn`, for windows that are top-level windows according to the ICCCM spec but not currently mapped; I think we have to do something like that for ICCCM compliance, but there is probably a much better way. If you can think of one, please let me know.

Code is at https://github.com/ch11ng/exwm/compare/master...pipcet:id-alist. No PR since I really don't think the complication is worth it for those few windows (but if you disagree, let me know and I'll open one). Sorry this got a bit long.

**Comment by ch11ng** [comment]
I realized this issue is actually due to a mistake. Now things should work well.

**Comment by pipcet** [comment]
Oh! I never realized we reparented unmapped windows back to `exwm--root`. That makes the fix much simpler, of course. Thanks!
