### ISSUE TITLE
[Suggestion] Support numeric prefix argument in exwm-workspace-switch and friends

### ISSUE THREAD

**Issue by akater** [ch11ng/exwm#382]
`C-u n exwm-workspace-switch` switches to nth workspace.
`C-u exwm-workspace-switch` switches to 0th workspace.

Other functions prompting for workspace number could use this as well: `exwm-workspace-move`, `exwm-workspace-move-window`. (Maybe some others too.) Selecting workspace from a list in minibuffer is awkward. Numeric prefix argument is certainly more convenient if `universal-argument` is captured.

**Comment by ch11ng** [comment]
Thank you for the suggestion! The prefix key is not used so it's perfectly possible.

**Comment by akater** [comment]
Theoretically I could handle this but I'm quite bad at Emacs Lisp. It probably won't be much better than this: https://github.com/ch11ng/exwm/compare/master...akater:prefix-arguments-for-workspace-numbers?expand=1 I had to switch order of the arguments.

**Comment by ch11ng** [comment]
Done.
