### ISSUE TITLE
Unexpected window position after (split-window-horizontally)

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#385]
I am trying to use this snippet to open browser side-by-side with current window.

```elisp
(defun sarg/with-browser ()
  "Opens browser side-by-side with current window"
  (interactive)
  (delete-other-windows)
  (set-window-buffer (split-window-horizontally) "qutebrowser"))
```

Documentation for `split-window-horizontally`
> The selected window is on the left.  The newly split-off window
> is on the right and displays the same buffer.  Return the new
> window.

So selected window should remain intact in the left position and browser should go to the right side.
In EXWM browser goes to the left and becomes active. After second call of the `sarg/with-browser` it works as expected. Seems that something goes wrong when window is moved from another workspace.

**Comment by ch11ng** [comment]
What's the buffer originally selected? Is qutebrowser shown or hidden before that?

**Comment by sarg** [comment]
Originally it was another X11 window. qutebrowser was hidden (e.g. on another workspace).

**Comment by ch11ng** [comment]
What about

``` elisp
(with-selected-window (split-window-horizontally)
  (set-window-buffer nil "qutebrowser"))
```

**Comment by sarg** [comment]
Thanks, it works! btw, how did you come up with this solution?
There is one ingredient missing - it's needed to move mouse pointer to the "left" window, so it remains selected. (I have `focus-follows-mouse t`).

**Comment by ch11ng** [comment]
Because you move qutebrowser from another workspace.

**Comment by sarg** [comment]
So, is it EXWM's quirk? Non-exwm buffers behave as stated in documentation and my original snippet works for them.

**Comment by ch11ng** [comment]
With 57328b439fdc367519e3ce9f7c6ef2d3a4934cbc the original snippet should work.

**Comment by sarg** [comment]
It works, thanks a lot.
