### ISSUE TITLE
Windows lose fullscreen when workspace changes

### ISSUE THREAD

**Issue by paulbdavis** [ch11ng/exwm#388]
Starting with version 0.17, I experience the following problem

Start an X application and full screen it

Switch workspaces

Swicth back, and the application is no longer in fullscreen (for EXWM) but still has it's fullscreen appearance (like a fullscreen video on youtube will fill the whole window, but the status lines and minibuffer and yabar show up like a non fullscreen window)

I actually find this behavior desirable when it comes to firefox, since I can make video windows that can be easily put on any workspace, but it really breaks other things, like games, where the input can be off after the window position has moved when leaving fullscreen

If this change was intentional, it would be good to have a way to disable it for certain apps (or enable for certain apps only). If it's a bug, maybe it can become a feature??

**Comment by ch11ng** [comment]
This is no where near a feature.  Fixed.
