### ISSUE TITLE
Use of `read-event`

### ISSUE THREAD

**Issue by pipcet** [ch11ng/exwm#39]
I'm very suspicious of the use of `read-event` in 

    (defun exwm--make-emacs-idle-for (seconds)
      "Put Emacs in idle state for SECONDS seconds."
      (with-timeout (seconds) (read-event)))

It's causing problems when it is called from a buffer switch hook which is itself called in the middle of processing events. I also think we actually dropped those events that we did read.
    
In my experiments, I've been seeing errors like the following happen a lot with EXWM when switching back and forth between frames with the mouse pointer:
    
        Debugger entered--Lisp error: (wrong-type-argument listp #<frame *GNU Emacs* 0x4718c00>)
          handle-select-window((switch-frame #<frame *GNU Emacs* 0x4718c00>))
          funcall-interactively(handle-select-window (switch-frame #<frame *GNU Emacs* 0x4718c00>))
          call-interactively(handle-select-window nil nil)
          command-execute(handle-select-window)
    
What's happening, as far as I can work out, is that we're in the middle of reading an event from the keyboard when a buffer switch happens, and the buffer switch hook calls exwm code which calls `exwm--make-emacs-idle-for`, which in turn calls `read-event` and causes Emacs to overwrite some of the global event data.

Can we change that code to use either `sit-for` or `sleep-for`? Neither causes problems for me, and `sit-for` properly saves the events that it does read.

Of course it's best to avoid synchronous waits entirely, but I understand that might not always be possible.

**Comment by ch11ng** [comment]
The intention of `exwm--make-emacs-idle-for` is to put the Emacs command loop into idle state and create opportunity for Emacs to carry out other tasks like finishing its UI initialization. `read-event` is the only way I can think of to make Emacs idle; `sit-for` and `sleep-for` merely freeze Emacs I'm afraid. Perhaps `exwm--make-emacs-idle-for` is abused and is incorrectly used in this case. Maybe we can fix it by putting the event read back to `unread-command-event`.

**Comment by pipcet** [comment]
Hmm. I don't think it actually works that way, to be honest. `exwm--make-emacs-idle-for` will exit as soon as the first event is read, which I found a little confusing. `sit-for` shouldn't freeze emacs, though! Maybe that's something that only happens with an input method?

FWIW, here's the relevant code from `sit-for`:

    (let ((read (let ((input-method-function nil))
                  (read-event nil t seconds))))
      (or (null read)
	  (progn
	    (push (cons t read) unread-command-events)
	    nil))))))

which appears to do precisely what you suggest `exwm--make-emacs-idle-for` should do.

I think it would be best to convert the two places where `exwm--make-emacs-idle-for` is used to use timeouts instead, that should ensure control properly returns to the emacs command loop for the specified time. Would you consider such a patch?

**Comment by ch11ng** [comment]
Interesting. So it seems `exwm--make-emacs-idle-for` works in a similar way with `sit-for`. But they do behave differently.

`exwm--make-emacs-idle-for` was first introduced to fix a fullscreen issue with workspace frames. I can still reproduce this issue by removing the call to `exwm--make-emacs-idle-for` or replacing it with e.g. `sit-for` in `exwm-workspace--init`.

> I think it would be best to convert the two places where exwm--make-emacs-idle-for is used to use timeouts instead, that should ensure control properly returns to the emacs command loop for the specified time.

What does *timeout* means here?

**Comment by pipcet** [comment]
Sorry, I meant using `run-with-timer`, though I would at present limit this to the first (and much more frequent) appearance of `exwm--make-emacs-idle-for`.

It turns out I had a configuration issue which was preventing `exwm-workspace--init` from doing its job. However, even with that fixed, I can't seem to reproduce the fullscreen issue—things work just fine without the delay. Maybe that's because of the Emacs version I'm using (25.0.50.26) or the use of an X toolkit (GTK) in my build?

**Comment by ch11ng** [comment]
I can reproduce the fullscreen problem with both Emacs 25.0.50.1 and 24.5.1 (both are gtk builds):
* On 25.0.50.1, the first 2 workspace frames are not fully maximized; they are a bit smaller than the screen size.
* On 24.5.1, the default settings work fine. But if I add `(setq exwm-workspace-number 10)`, workspace 9 would remain in its original size.

Timer is of course an alternative. But we may want to block the execution of Elisp code sometimes.

**Comment by pipcet** [comment]
Okay, I've finally been able to reproduce the problem (I hope it's the same one, at least) using a minimal .emacs and emacs -Q. In my case, a call to `redisplay` instead of the `exwm--make-emacs-idle-for` call appears to work just as well, but I'll try tracking this down further. We might also want to try

    (while (not (sit-for 0.1)))

instead of `sit-for`, though that might loop endlessly...

**Comment by pipcet** [comment]
Okay, I believe I have been able to track down this issue: setting `frame-resize-pixelwise` does not take effect until the next call to `x_wm_set_size_hint`; however, `x_wm_set_size_hint` has no effect on maximized and full screen windows due to an old KWin bug. Furthermore, `x_check_fullscreen` does not call `x_wm_set_size_hint` when there is no window manager, even though `x_set_window_size_1` does.

It's all a bit of a mess, but the workaround is simple: before calling `(set-frame-parameter frame 'fullscreen 'fullboth)`, perform a dummy resize on the frame whose sole purpose is to add GDK hints corresponding to the `frame-resize-pixelwise` flag: `(set-frame-height (car exwm-workspace--list) (1+ (frame-pixel-height (car exwm-workspace--list))) nil t)` works here.

However, with the setup I have, that's the only workaround that works: `exwm--make-emacs-idle-for` has no effect, and neither do `redisplay` and `sit-for`.

This solution isn't really satisfactory for what's essentially an Emacs bug, but it works on my setup.

**Comment by ch11ng** [comment]
> In my case, a call to `redisplay` instead of the `exwm--make-emacs-idle-for` call appears to work just as well, ...

It does not work here.

> We might also want to try
> 
> ```
(while (not (sit-for 0.1)))
```
> 
> instead of `sit-for`, though that might loop endlessly...

It freezes Emacs in my case.

> It's all a bit of a mess, but the workaround is simple: before calling `(set-frame-parameter frame 'fullscreen 'fullboth)` perform a dummy resize on the frame whose sole purpose is to add GDK hints corresponding to the `frame-resize-pixelwise flag`: `(set-frame-height (car exwm-workspace--list) (1+ (frame-pixel-height (car exwm-workspace--list))) nil t)` works here.

Neither does this work.

> However, with the setup I have, that's the only workaround that works: `exwm--make-emacs-idle-for` has no effect, and neither do `redisplay` and `sit-for`.

So it seems we are experiencing two different problems. In my case, the frame is 6 and 5 pixels shorter in width and height respectively.

**Comment by pipcet** [comment]
Thanks for testing. I am a bit confused now, because that certainly sounds like `frame-resize-pixelwise` is not taking effect. Are you running this with a minimal .emacs and emacs -Q, or is there anything in your .emacs that might affect things?

That `(while (not (sit-for .1)))` freezes Emacs suggests something is generating input events during initialization, which sounds like it might be due to an XIM input method to me.

Anyway, it sounds like we should definitely keep `exwm--make-emacs-idle-for` around for the workspace initialization, if it's the only thing that works for you. I've reported the Emacs issue I have discovered and hopefully that will be fixed soon, one less thing to worry about.

**Comment by ch11ng** [comment]
I had tested with a minimal .emacs. It seems `frame-resize-pixelwise` does not come into effect early enough; I can resize it with `F11` afterwards.

**Comment by pipcet** [comment]
Hmm. Have you tried running this code:

    (progn
      (setq frame-resize-pixelwise t)
      (set-frame-height (selected-frame) (1+ (frame-pixel-height (selected-frame))) nil t)
      (redisplay)
      (set-frame-parameter (selected-frame) 'fullscreen 'fullboth))

with the extra `redisplay` call? That appears to make things work for me in all cases.

The Emacs bug report is at http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21317, FWIW.

**Comment by ch11ng** [comment]
Unfortunately it does not work either. I did the following tests, none succeeded:
1. I substituted the corresponding code in `exwm-workspace--init` with yours and tested with a minimal `.emacs`.
2. The test in your bug report.
3. Same as *2* but using `Xephyr` instead of `Xnest`.

Perhaps I should gdb Emacs like you did in the report.

**Comment by ch11ng** [comment]
I meant the test with `(redisplay)` of course. I also tested with real X server and the problem remained.

**Comment by pipcet** [comment]
That would be great! I suspect you'll see the same results as me if you set a breakpoint on `XResizeWindow`: one correct call from Emacs, then an incorrect one from GDK.

I'd suggest breakpoints on `XResizeWindow` and `gdk_window_constrain_size`, and printing ("p *geometry") the `geometry` argument to `gdk_window_constrain_size` when it is hit.

So the complete input at the command line would be (make sure to have debug symbols for GTK installed; on debian, that's package `libgtk+-3-0-dbg`):

    Xnest :3 -geometry 877x877+0+0 &
    DISPLAY=:3 gdb --args emacs -Q --eval "(progn (setq frame-resize-pixelwise t)  (set-frame-parameter (selected-frame) 'fullscreen 'fullboth) (redisplay) (set-frame-height (selected-frame) (1+ (frame-pixel-height (selected-frame))) nil t))"
    b XResizeWindow
    command 1
    bt
    c
    end
    b gdk_window_constrain_size
    y
    command 2
    bt
    p *geometry
    c
    end
    run

**Comment by ch11ng** [comment]
[Here](https://gist.github.com/ch11ng/f272f301ebaf8dc4cb7e) is the debug output. In my case, the resulting frame is 877x809 in size. Any ideas?

**Comment by pipcet** [comment]
Wait, how did you measure that size? `(frame-pixel-height (selected-frame))` does not count the toolbar and menu bar, and with those 809 sounds like it might well be the correct size (it's 813 here). Is the mini-window actually in the wrong place for you relative to the Xnest window?

Hmm. That looks essentially identical to the output here, which is most curious. The 877x809 size hints that what is happening might be that the window is created with a toolbar first, and then resized when that is removed.

Do you have X resources set in ~/.Xresources? Does `xrdb -query` show anything relevant, or `DISPLAY=:3 xrdb -query` when Xnest is running on display :3?

My next suggestion would be to do the following:
 - install debug symbols for libX11 (libx11-xcb1-dbg, libx11-6-dbg) and emacs (emacs24-dbg)
 - set additional breakpoints as follows

```
    Xnest :3 -geometry 877x877+0+0 &
    DISPLAY=:3 gdb --args emacs -Q --eval "(progn (setq frame-resize-pixelwise t) (set-frame-height (selected-frame) (1+ (frame-pixel-height (selected-frame))) nil t) (redisplay) (set-frame-parameter (selected-frame) 'fullscreen 'fullboth))"
    b XResizeWindow
    command 1
    bt
    c
    end
    b gdk_window_constrain_size
    y
    command 2
    bt
    p *geometry
    c
    end
    b x_set_window_size
    command 3
    bt
    c
    end
    b change_frame_size
    command 4
    bt
    c
    end
    b x_check_fullscreen
    command 5
    bt
    c
    end
    set pagination off
    run
```

The output might be somewhat voluminous, but should be fine as a gist.

Thanks!

**Comment by ch11ng** [comment]
Yes, you're right. The height was reported by `(frame-pixel-height)` and was actually 877 in pixels. I should have noticed it since the frame was obviously taller than the `Xnest` window.

Now the problem seems to have something to do with `gnome-settings-daemon`. Without it, your fix works just fine here and all frames are in correct sizes. Do you have `gnome-settings-daemon` or something similar started before launching EXWM?

**Comment by pipcet** [comment]
Thanks for thinking of that, it hadn't occured to me!

I don't have `gnome-settings-daemon` installed, and I'm not sure whether emacs -Q uses it; it probably shouldn't! I'll install it and have a look around to see whether I'm finally able to reproduce the issue.

**Comment by pipcet** [comment]
Sorry for taking so long, but I think I've finally worked out what's happening: it's another bug in `x_check_fullscreen`: we never store the fullscreen frame parameter, so when the GNOME settings code tells us there's a new font to use, we resize the frame without inhibiting the resize code, thus causing the unpleasant rounding. The patch at https://gist.github.com/pipcet/592df95aa6fd22c014ce should finally fix things.

(In other words, if you execute `(progn (set-frame-parameter (selected-frame) 'fullscreen 'fullboth) (redisplay) (frame-parameter (selected-frame) 'fullscreen)`, the result is `nil`. That allows us to detect broken Emacs versions (all the current ones), but I'm not sure how to actually work around this bug.)

Anyway, what `exwm--make-emacs-idle-for` was doing was reading the "font changed" event and throwing it away, but I don't think that's the right course of action.

It might be best to avoid using the no-WM code entirely; register our window manager to deal with fullscreen events, then resize the frame when we're done, then special-case the root frames in exwm-layout-set-fullscreen.

**Comment by ch11ng** [comment]
> It might be best to avoid using the no-WM code entirely; register our window manager to deal with fullscreen events, then resize the frame when we're done, then special-case the root frames in exwm-layout-set-fullscreen.

I think it's a good idea. It should allow us to make the frames fullscreen in a reliable way. I've read your commit and I think we should also take RandR into consideration when calculating the geometries of these frames.

**Comment by pipcet** [comment]
We certainly cannot use `x-display-pixel-width`, which uses the wrong connection to the X server. Let me write something better.

**Comment by pipcet** [comment]
Okay, I've finally got this working the way I want to. PR created for convenience, but feel free to close it if you're not happy with this solution.

**Comment by pipcet** [comment]
Okay, that leaves the other `exwm--make-emacs-idle-for`: it reads and discards the mouse-1-up event that would otherwise result in selected text because the click and the release happened at different positions.

I think the best solution is not to warp the mouse pointer at all: call `x-focus-frame` instead of `select-frame-set-input-focus`, and remove the "move mouse pointer if necessary" code: it's almost never necessary, I believe, at least not if the event that triggered us was a click. Would you be okay with a change that included that condition?

**Comment by ch11ng** [comment]
> I think the best solution is not to warp the mouse pointer at all

In a multi-screen setting, switching to a workspace without warping the pointer raises an issue: you will still use the minibuffer on the frame which contains the pointer. Perhaps there are other issues but this is most immediate reason I made such code. Besides, an active workspace should contain the pointer, right?

**Comment by pipcet** [comment]
New suggestion: create an `exwm--select-frame' function that only warps the mouse pointer (or calls `select-frame-set-input-focus', which warps the mouse pointer) when it's not already in the right frame. I might be missing something, but that seems like the simplest solution that might work.

https://github.com/pipcet/exwm/commit/90189429954d499f9cd1ed6cbe46a7055ba6d06a

> In a multi-screen setting, switching to a workspace without warping the pointer raises an issue: you will still use the minibuffer on the frame which contains the pointer.

I can't reproduce that, but if you say so it's most likely correct. Without any pointer warping, things appear to just work for me, but there's an important point to be made here: I'm on a laptop, so I never send tiny mouse movements without wanting to. Users with mice would find the focus shifting back to the old workspace seemingly at random, so that's unacceptable.

> Perhaps there are other issues but this is most immediate reason I made such code. Besides, an active workspace should contain the pointer, right?

I must admit that my local setup is very special: I have a global "Emacs" key that always raises my main Emacs frame and displays a menu there, then restores the original stacking order and input focus when I've either entered a command or released the "Emacs" key, whichever comes last. I don't want that to affect my mouse position at all. So, I'd say there are special cases, but in general you're right. The patch does that.

Note that in the (rather pathological) case that the mouse pointer is on the root window but no longer on the frame, (mouse-pixel-position) returns (FRAME nil), which used to crash us but has been fixed in the patch. I think this can happen with misconfigured RandR setups where we have frames on one screen but not the other.

**Comment by ch11ng** [comment]
> New suggestion

We must limit the frames to those acting as workspaces.

> I have a global "Emacs" key that always raises my main Emacs frame and displays a menu there, then restores the original stacking order and input focus when I've either entered a command or released the "Emacs" key, whichever comes last.

It's quite complicated. Why don't you just display the menu in the selected window / a new window in the current workspace?

> I think this can happen with misconfigured RandR setups where we have frames on one screen but not the other.

This can actually happen very often since RandR outputs are unlikely to fill the screen. It's worth fixing.

**Comment by pipcet** [comment]
> We must limit the frames to those acting as workspaces.

Is that the right thing to do for floating frames? Or should we test whether the mouse is in the frame area, even if (car mouse-posn) isn't the right frame? I think the latter might make most sense, but I'm not a hundred percent certain.

> It's quite complicated. Why don't you just display the menu in the selected window / a new window in the current workspace?

I use VNC and want the same key to work (but affect the remote Emacs session) from both the local and the remote computer. Also, this was before I discovered EXWM so I was using two different window managers and things were generally more complicated.

> This can actually happen very often since RandR outputs are unlikely to fill the screen. It's worth fixing.

You mean when they run at different resolutions? I was wondering about that.

**Comment by ch11ng** [comment]
> Is that the right thing to do for floating frames? Or should we test whether the mouse is in the frame area, even if (car mouse-posn) isn't the right frame? I think the latter might make most sense, but I'm not a hundred percent certain.

We should certainly not warp the pointer when we change focus to / from a floating frame so long as there is no workspace switching concerned. To be specific, we should allow
* focusing a floating frame even if it does not contains the pointer, and
* moving focus away from a floating frame even if it contains the pointer.

> I use VNC and want the same key to work (but affect the remote Emacs session) from both the local and the remote computer. Also, this was before I discovered EXWM so I was using two different window managers and things were generally more complicated.

Alright.

> You mean when they run at different resolutions? I was wondering about that.

Yes. Monitors usually have different resolutions so they can hardly form a rectangle exactly.

**Comment by pipcet** [comment]
>  focusing a floating frame even if it does not contains the pointer, and
>  moving focus away from a floating frame even if it contains the pointer.

But not moving or resizing a floating frame without having the pointer in it, surely?

I'm afraid I'll have to ask you not to apply the exwm-select-frame PR until I've tested it more, I've seen some misbehaviour while looking at the GTK issue.

**Comment by ch11ng** [comment]
> > focusing a floating frame even if it does not contains the pointer, and
moving focus away from a floating frame even if it contains the pointer.

> But not moving or resizing a floating frame without having the pointer in it, surely?

I only mentioned some important cases here. Moving/resizing a floating frame requires the frame (or more precisely, the X window) contains the pointer, so there is no need to warp the mouse I think.

> I'm afraid I'll have to ask you not to apply the exwm-select-frame PR until I've tested it more, I've seen some misbehaviour while looking at the GTK issue.

Which issue and what are the misbehaviors?

**Comment by pipcet** [comment]
I think you're right. The issue was that mozilla and gitk modal dialogues as floating frames got stuck with one cursor position that the mouse kept warping back to, but that seems to be all better with the most recent change.

I'll test some more to be sure.

**Comment by pipcet** [comment]
Okay, I found the bug, and it turned out to be unrelated (my XELB code had a typo in it). Feel free to apply #45 now, if you want to.

**Comment by ch11ng** [comment]
Hi @pipcet,

I think removing the second `exwm--make-emacs-idle-for` is far easier than we had thought.  I've removed it in e8bc51280dba18dc394e15dd544e70ad27176f82.  BTW, I'll keep PR #45 open until we make some progress on it.
