### ISSUE TITLE
Odd behavior when restarting a bar

### ISSUE THREAD

**Issue by paulbdavis** [ch11ng/exwm#391]
I have yabar running with exwm

It is triggered as follows

``` elisp
       (defun ds/restart-bar ()
         "Restart whatever bar is being used."
         (interactive)
         (start-process-shell-command
          "startpanel" nil (expand-file-name (concat user-emacs-directory "exwm/bin/start-bar"))))
```

In the `start-bar` script

``` bash
#!/usr/bin/env bash

killall yabar && echo "Restaring bar" || echo "Starting bar"

cd "$HOME/.emacs.d/exwm/yabar"
exec yabar -c yabar.conf
```

Whenever the `ds/restart-bar` function is called, the display of X windows becomes mixed up somehow. As I change through the workspaces, I can see the bottom states bar change to reflect what is there, buit a single X window is displayed over everything (presumably the last one I had open.. not sure).

Once I have cycled through *all* of my workspaces (or maybe just the ones with frames containing exwm buffers...) the display returns to normal

**Comment by ch11ng** [comment]
Which version of yabar are you using? I just install 0.4.0 and it seems the struts are filled with garbage (uninitialized?).

```shell
$ xprop -id 0x1e00001
WM_NAME(STRING) = "yabar"
_NET_WM_STRUT(CARDINAL) = 3735804160, 2456445226, 20, 0
_NET_WM_STRUT_PARTIAL(CARDINAL) = 3735804160, 2456445226, 20, 0, 3804698136, 22023, 3804698112, 22023, 10, 1270, 3804695040, 22023
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
```

**Comment by paulbdavis** [comment]
I am using the [`yabar-git`](https://aur.archlinux.org/packages/yabar-git/) package on Arch. 

This is the output when I use xprop on my running instance

```
 $ xprop 
WM_STATE(WM_STATE):
		window state: Iconic
		icon window: 0x0
WM_NAME(STRING) = "yabar"
_NET_WM_STRUT(CARDINAL) = 0, 0, 0, 20
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 8, 2551
_NET_WM_DESKTOP(CARDINAL) = 4294967295
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
```

**Comment by ch11ng** [comment]
I built yabar from its latest source and tried your scripts but could not seem to reproduce this issue.  Is Emacs frames resized correctly after yabar exits and starts again? Perhaps a screenshot can be helpful.

**Comment by paulbdavis** [comment]
The emacs frame *does* resize correctly

I'll try to add some screenshots later when I have a chance.

Possibly important, I am using nvidia graphics, but this was not happening on 0.16 on the same machine

**Comment by ch11ng** [comment]
> The emacs frame does resize correctly

Then this problem is beyond my imagination.

> Possibly important, I am using nvidia graphics

This is unlikely relevant.

**Comment by ch11ng** [comment]
@paulbdavis Is this problem still there?

**Comment by medranocalvo** [comment]
Assuming it's resolved.  Please, reopen if that's not the case.
