### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by WorldsEndless** [ch11ng/exwm#393]
I noticed in my package manager that a new version of exwm is available, but I don't see anything like a change log to let me know what the effects of upgrading will be. A simple changelog file would be marvelous.

**Comment by ch11ng** [comment]
Perhaps I'll just start to mark in the wiki in which version a feature is introduced.  But as long as the major version is not changed (current 0) EXWM promises backward compatibility.

**Comment by WorldsEndless** [comment]
I guess backward compatibility is the biggest concern, so that's 
good. But I would also like to know as new features or 
functionality are added.

**Comment by ch11ng** [comment]
Now available from https://github.com/ch11ng/exwm/wiki#changelog .
