### ISSUE TITLE
350950abfce892a1f6f6fc5023ae576801a253ca caused an emacsclient regression on Windows and interesting behavior on Linux.

### ISSUE THREAD

**Issue by jaccarmac** [ch11ng/exwm#394]
Yes, I know...

I use the same configuration at home (Gentoo) and at work (Win7). So there are a few OS-specific things I've had to tweak, but for the most part everything plays nice on both systems.

Today I upgraded my packages and all the sudden emacsclient stopped working. The culprit looks to be the named commit (350950abfce892a1f6f6fc5023ae576801a253ca). Since it changes the output of a few checks from using `message` to `user-error` emacsclient refuses to start up.

I just came home to make sure the regression didn't happen for Linux and indeed, it looks like there's a prompt to replace the existing window manager or not.

So I suppose in both cases the question is: Is this considered a regression so the error messages should be changed to not break emacslcient on Windows, or do I need to update my initialization code to check if I *actually* want EXWM before requiring and starting it? (I haven't found any such conditional loading code in the wild on my own, if there's a good example I will happily scavenge from it when pointed.)

**Comment by ch11ng** [comment]
Sorry about that.  Please check out 3f6c609a2b1580d77a9863e205718cbba3872bcb if this regression is fixed.

**Comment by jaccarmac** [comment]
Thank you, I'll check on Monday.

**Comment by jaccarmac** [comment]
It's solved beautifully, thanks so much!
