### ISSUE TITLE
Autohide minibuffer & echo area function: Standalone Melpa package

### ISSUE THREAD

**Issue by lyr3** [ch11ng/exwm#395]
Is it even possible to use that function in Emacs without Exwm?

If so, could you be so kind to do us this BIG favor! 

I still think that is the only flaw in GNU Emacs! ...

Anyway, thanks!

Loving Exwm!

**Comment by ch11ng** [comment]
I think this has been discussed in the emacs-devel list before.  Personally I'd prefer a platform independent implementation, but EXWM does it in a non-portable way.  If someone must make such a package (which will be unlikely compatible with EXWM), here's the list of codes that can be helpful:

* `exwm-workspace--on-minibuffer-setup`
* `exwm-workspace--on-minibuffer-exit`
* `exwm-workspace--on-echo-area-dirty`
* `exwm-workspace--on-echo-area-clear`

**Comment by lyr3** [comment]
I will try! Thanks!
