### ISSUE TITLE
IME (specifically, mozc) in EXWM

### ISSUE THREAD

**Issue by kahrkunne** [ch11ng/exwm#396]
How do I use an IME such as mozc in Emacs? Emacs doesn't conventionally work with an IME, it seems. There does exist a package called `mozc-mode` and it works, but only in Emacs buffers; not in X windows. 

How do I get a functional IME in X windows on EXWM?

**Comment by jamcha-aa** [comment]
uim-mozc works well.

I tried fcitx-mozc and mozc with exim, but I couldn't figure out how to configure correctly on EXWM.

**Comment by ch11ng** [comment]
You can use any Emacs input method to interact with X windows thru the aid of [exim](https://github.com/ch11ng/exim).  There are definitely some Japanese input methods built-in, but I don't know if mozc is available (if not, it should be easy to create one).

**Comment by medranocalvo** [comment]
@kahrkunne It seems to me the above answers offer solutions to your question.  Please reopen if you still find difficulties.

**Comment by QiangF** [comment]
@kahrkunne I may have a solution here https://github.com/orgs/emacs-exwm/discussions/183
