### ISSUE TITLE
Screen tearing in Firefox with smooth scrolling

### ISSUE THREAD

**Issue by TatriX** [ch11ng/exwm#397]
The only [solution](https://wiki.archlinux.org/index.php/EXWM) I found is to disable smooth scrolling.
But I really like the smooth scrolling, so this a blocker issue for me.
Is it possible to fix that somehow? Thanks! 

```
exwm 0.17 from the melpa
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-02-09
nvidia proprietary driver 390.25-15
```

**Comment by ch11ng** [comment]
Even after upgrading to 0.17? I'll Investigate that.

**Comment by ch11ng** [comment]
Does running a compositing manager fix this problem? For example

```shell
compton --backend glx --vsync opengl-swc
```

**Comment by TatriX** [comment]
Yes, compton helps, thanks!
I run it like this to disable fading:
```sh
compton -CG --no-fading-openclose
```
Then to actually [fix flicker](https://wiki.archlinux.org/index.php/Compton#Flicker) I added `~/.config/compton.conf` with
```
unredir-if-possible = false;
```

**Comment by ch11ng** [comment]
I have no idea how the smooth scrolling feature works, but it seems it does rely on a compositor.

**Comment by TatriX** [comment]
I'm using `awesome`. As far as I know it doesn't have built-in compositor, but still it works fine.
Also I should mention that I have nvidia settings changed to make it work.
In my `Screen` section of the`xorg.conf` I have:
```
    Option         "metamodes" "nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
```

**Comment by ch11ng** [comment]
Is the GPU setting required for EXWM, awesome or both?

**Comment by TatriX** [comment]
Both.

**Comment by ch11ng** [comment]
@TatriX Since it's the GPU setting that matters here and there is nothing can be done on our side, I'm closing this issue now.
