### ISSUE TITLE
god-mode not working with exwm

### ISSUE THREAD

**Issue by shobute** [ch11ng/exwm#398]
I am trying to use evil-god-state which temporarily switches to god-mode for one command. I can trigger the state with key bindings, but when on an X buffer, any subsequent keys are sent to the X application, instead of god-mode.

Are there any workarounds? It works perfectly when I'm on a regular Emacs buffer.

**Comment by shobute** [comment]
I am trying to use evil-god-state which temporarily switches to god-mode for one command. I can trigger the state with key bindings, but when on an X buffer, any subsequent keys are sent to the X application, instead of god-mode.

**Comment by shobute** [comment]
I apologise, I must have not read through the documentation clearly enough, reading through the code I found `exwm-input-line-mode-passthrough`, and was able to do:

```
(add-hook 'god-mode-enabled-hook (lambda () (setq exwm-input-line-mode-passthrough t)))
(add-hook 'god-mode-disabled-hook (lambda () (setq exwm-input-line-mode-passthrough nil))
```

I haven't had time to experiment with this much, but at first glance it seems to work. Please let me know if I am doing anything silly here, but otherwise feel free to close this issue, and thank you for the wonderful package! :)

**Comment by ch11ng** [comment]
Perhaps it is the only way to achieve this.  At least it looks good to me.
