### ISSUE TITLE
EXWM 0.18 makes modeline invisible on X windows when it is made displayed on top

### ISSUE THREAD

**Issue by akater** [ch11ng/exwm#399]
I'm using the following hack to display modeline on the top of buffers:
```lisp
(setq-default header-line-format mode-line-format)
(setq-default mode-line-format nil)
```
and with exwm-0.18 update, the header became invisible for X windows if this approach is used. All X windows are affected, floating and tiled alike. Native Emacs buffers not affected.

This might be not worth fixing. Modeline repositioning should be done on lower level in Emacs. The approach mentioned here has clear drawbacks: mouse events not supported, minor mode lists aren't folded (smart-mode-line feature only? I'm not sure), there may be other issues. Repositioning [has been discussed](https://lists.gnu.org/archive/html/emacs-devel/2017-11/msg00618.html) on emacs-devel mailing list not a long time ago, with references to older discussions too, and it was agreed that it would be an important feature, but it is yet unimplemented. Current solution and related issues are discussed in [this Emacs StackExchange question](https://emacs.stackexchange.com/questions/2418/moving-the-mode-line-and-minibuffer-to-the-top).

Environment details: `GNU Emacs 26.0.91`, `xorg-server 1.19.5-r1`, with following Emacs build options `--with-x --with-x-toolkit=no`.

Probably unimportant detail: I used to employ a more direct method:
```lisp
(setq-default header-line-format
  '("%e" mode-line-front-space mode-line-mule-info mode-line-client mode-line-modified mode-line-remote mode-line-frame-identification mode-line-buffer-identification "   " mode-line-position
(vc-mode vc-mode)
"  " mode-line-modes mode-line-misc-info mode-line-end-spaces))
(setq-default mode-line-format nil)
```
but I don't remember the reasons already. Maybe it fixed something, maybe it didn't. EXWM doesn't work with that, too. (There probably is no difference.)

**Comment by ch11ng** [comment]
It's now easier to tweak the mode-line and header-line:

```elisp
(setq exwm-manage-configurations `((t
                                    floating-mode-line nil
                                    tiling-mode-line nil
                                    floating-header-line ,mode-line-format
                                    tiling-header-line ,mode-line-format)))
```

**Comment by akater** [comment]
Yes, that solved it.

However, “Box around text” parameter is ignored for floating windows. Maybe it used to happen before, I'm not sure. Anyway, that's a separate issue and not a very important one.
