### ISSUE TITLE
Input methods does not work in GUI applications

### ISSUE THREAD

**Issue by ssbb** [ch11ng/exwm#400]
Hi! First of all thank you for this work! Dreams come true.

I am trying to get input method switching with EXIM. My config is: https://github.com/ssbb/emacs.d/blob/master/lisp/init-wm.el

When I toggling input method (`russian-computer`, tried many others) in applications like Firefox I got nothing printed at all. looks like keys are ignored. I don't think it's fonts issue since I have Noto fonts installed and it works fine with setxkbmap (except emacs keys broken then).

**Comment by ssbb** [comment]
Sorry, looks like my envs caused an issue:

```(setenv "LC_ALL" "C")
(setenv "LANG" "en_US.UTF-8")
```

working with empty LC_ALL

**Comment by ch11ng** [comment]
Let's focus on ch11ng/exim#5.
