### ISSUE TITLE
C-x b no longer work after swapping C-x and C-t

### ISSUE THREAD

**Issue by YorkZ** [ch11ng/exwm#406]
Let's say I have a window for `gnome-terminal`, I could press `C-x b` to switch buffer in this window which is really cool. However, after swapping `C-x`  and `C-t` by:

```
(keyboard-translate ?\C-x ?\C-t)
(keyboard-translate ?\C-t ?\C-x)
```
Neither `C-x b` nor `C-t b` work in the `gnome-terminal` window, although `C-t b` (having translated to `C-x b`) still works in regular Emacs buffers.

**Comment by ch11ng** [comment]
Fixed with fbdcd42b0a2aadb4f3e27cd2a75c863d2f67eb39 .
