### ISSUE TITLE
8 seconds delay after each XF86* keypress

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#409]
It seems that exwm/xelb (`master` branch) recently introduced a delay for each XF86* keypress.

I have a [bunch of lines](https://github.com/DamienCassou/emacs.d/blob/master/init.el) like this one to configure volume and brightness:

```emacs
(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>") (my/volume-command "5%+"))
```

Volume management is defined like this:

```emacs
    (defun my/adjust-volume (delta)
      "Adjust sound volume by DELTA."
      (message "1. %S before amixer set" (decode-time))
      (shell-command-to-string (format "amixer set Master %s" delta))
      (message "2. %S after amixer set" (decode-time))
      (message "Volume: %s" (my/volume-get))
      (message "3. %S after amixer get" (decode-time)))

    (defmacro my/volume-command (delta)
      "Return a command modifying sound volume by DELTA."
      `(lambda () (interactive) (my/adjust-volume ,delta)))
```

The log shows that exwm takes 8 seconds to start executing my function:

```
(34 22 14 4 4 2018 3 t 7200)  <--- just before pressing the key
1. (42 22 14 4 4 2018 3 t 7200) before amixer set <-- already 8s have passed
2. (42 22 14 4 4 2018 3 t 7200) after amixer set
Volume: 80%
3. (42 22 14 4 4 2018 3 t 7200) after amixer get
```

**Comment by dakra** [comment]
I wanted to write the same thing but not only XF86 Keys that are laggy but almost every key.. I couldn't quite put my finger on it when exactly but the whole system after my last update was lagging. I rolled back all my updates and added them back one after one.. So for me, with https://github.com/ch11ng/xelb/commit/eda5f25b14959592cb4c75ea52fe7526fe13d91f the system seems to "lag" and before that commit is fine.

**Comment by lyr3** [comment]
Cool

**Comment by ch11ng** [comment]
Sorry about that.  I've pushed a workaround.  The actual fix requires more work though.

**Comment by dakra** [comment]
I'm running it since a few hours and your workaround seems to have fixed my issue.

Thanks.

**Comment by DamienCassou** [comment]
@ch11ng: The fix works fine for me for a few days. No need to be sorry. Thanks. We can close the ticket.
