### ISSUE TITLE
Can I use exwm to open X11 apps in emacs without being a window manager?

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#41]
This is more of a question than a bug, so please feel free to close it with an answer.

I am wondering if we can be able to run arbitrary X11 apps in a new emacs window without making exwm behave like a window manager? From the documentation in how-it-works section in exwm.el file, it seems applications are started with an exwm container as the parent window. So, isn't it possible to just do the same when emacs is a regular application managed by some other window manager? Can it be displayed in the emacs window? Can exwm pass along all keyboard events received to the X11 application displayed in the window?

Just curious.

**Comment by ch11ng** [comment]
Unlikely.

> ...
> it seems applications are started with an exwm container as the parent window. So, isn't it possible to just do the same when emacs is a regular application managed by some other window manager?

The window manager will receive a `MapRequest` event fist and manage it (perhaps also reparent it). So there is no chance for us to do a another management.

`XEmbed` works such case, but Emacs does not support it (there is an xwidget patch) and many applications do not allow being embedded.
