### ISSUE TITLE
(kill-this-buffer)  wont work if  (exwm-workspace-minibuffer-position)  is enabled

### ISSUE THREAD

**Issue by j3ky** [ch11ng/exwm#410]
Hi, I tried to find any similar issue without success:

If I enable `(setq exwm-workspace-minibuffer-position 'bottom)` to hide the minibuffer renders unefective the  `kill-this-buffer`  function

Am I missing anything? 

My exwm config: https://gitlab.com/lyr3/dots/tree/master/home/.emacs.d/exwm

Keybind: `(exwm-input-set-key (kbd "s-K") 'kill-this-buffer)`

------------------
Emacs 26 RC1
Debian Unstable

**Comment by ch11ng** [comment]
`kill-this-buffer` won't work here.  It merely exits the minibuffer.  You can use `(exwm-input-set-key (kbd "s-K") (lambda () (interactive) (kill-buffer)))` instead.

**Comment by lyr3** [comment]
haha, Thanks!

**Comment by ch11ng** [comment]
I think the problem described here is fixed.  I'm closing it now.
