### ISSUE TITLE
Send C-v manually

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#413]
In any application, I would like to be able to select an element from the `kill-ring` and paste it where the focus is. I'm then experimenting with `M-: (exwm-input--fake-key ?\C-v) RET`. This works fine in Firefox (e.g., in the url bar) but not in Slack. 

Nevertheless, typing `C-y` with the following works fine in both Firefox and Slack:

```
(setq exwm-input-simulation-keys
      `(([?\C-y] . [?\C-v])))
```

What is the difference between the 2 approaches that make the second one working but not the first?

**Comment by DamienCassou** [comment]
I can't make it work in Slack either but it works great in Firefox:

```emacs
(exwm-input-set-key (kbd "M-y") #'my/exwm-counsel-yank-pop)

(defun my/exwm-counsel-yank-pop ()
  "Same as counsel-yank-pop and paste into exwm buffer."
  (interactive)
  (let ((inhibit-read-only t)
        ;; Make sure we send selected yank-pop candidate to
        ;; clipboard:
        (yank-pop-change-selection t))
    (call-interactively #'counsel-yank-pop))
  (when (derived-mode-p 'exwm-mode)
    (exwm-input--fake-key ?\C-v)))
```

**Comment by kriyative** [comment]
I wrote the following two commands to try and narrow this behavior:
```emacs-lisp
(defun exwm-send-paste-key1 ()
  (interactive)
  (exwm-input--fake-key ?\C-v))

(defun exwm-send-paste-key2 ()
  (interactive)
  (read-key "Press any key: ")
  (exwm-input--fake-key ?\C-v))
```
Interestingly, `exwm-send-paste-key2` works with Chrom(e|ium) while `exwm-send-paste-key1` does not. Both commands work with Firefox. The call to `read-key` is the only material difference between the two.

**Comment by ch11ng** [comment]
How about redefining `exwm-input--fake-key` as the following one and passing the X window ID as the second argument?

```elisp
(defun exwm-input--fake-key (event id)
  "Fake a key event equivalent to Emacs event EVENT."
  (let* ((keysym (xcb:keysyms:event->keysym exwm--connection event))
         keycode)
    (when (= 0 (car keysym))
      (user-error "[EXWM] Invalid key: %s" (single-key-description event)))
    (setq keycode (xcb:keysyms:keysym->keycode exwm--connection
                                               (car keysym)))
    (when (/= 0 keycode)
      (dolist (class '(xcb:KeyPress xcb:KeyRelease))
        (xcb:+request exwm--connection
            (make-instance 'xcb:SendEvent
                           :propagate 0 :destination id
                           :event-mask xcb:EventMask:NoEvent
                           :event (xcb:marshal
                                   (make-instance class
                                                  :detail keycode
                                                  :time xcb:Time:CurrentTime
                                                  :root exwm--root :event id
                                                  :child 0
                                                  :root-x 0 :root-y 0
                                                  :event-x 0 :event-y 0
                                                  :state (cdr keysym)
                                                  :same-screen 1)
                                   exwm--connection)))))
    (xcb:flush exwm--connection)))
```

**Comment by DamienCassou** [comment]
@ch11ng I don't understand how this new version is going to help pasting test in some windows while it already work on others.

**Comment by ch11ng** [comment]
@DamienCassou Just to make sure the synthesized events are forwarded to the correct destinations.  Never mind, the root cause is the input focus is temporary shifted from the application so the following (ugly) form should work any way.

```elisp
(progn (exwm-input--set-focus (exwm--buffer->id (window-buffer (selected-window)))) (exwm-input--fake-key ?\C-v))
```

**Comment by DamienCassou** [comment]
Thank you for your fix @ch11ng. It seems to work well the first time I use the command: the selected text is written inside Slack! But after the first time, the selected text is not written anymore :-(.

**Comment by ch11ng** [comment]
What did you mean by "after the first time"? I tried evaluating that form consecutively and it seemed every time the copied content got pasted.

P.S. Just to be sure, is [this](https://slack.com/) the Slack you referred to?

**Comment by DamienCassou** [comment]
> What did you mean by "after the first time"? I tried evaluating that form consecutively and it seemed every time the copied content got pasted.

I confirm. It now works fine all the times. I've upgraded Slack in the meantime.

> P.S. Just to be sure, is this the Slack you referred to?

yes.

I'm closing the issue now. Thanks
