### ISSUE TITLE
Gimp "open file" dialog flickering

### ISSUE THREAD

**Issue by 11111000000** [ch11ng/exwm#414]
Gimp "open file" dialog flickers, until <C-x 2> (split window)

**Comment by ch11ng** [comment]
We used to have this issue but I think it has been fixed.  Which version of Emacs and XELB/EXWM do you use?

**Comment by 11111000000** [comment]
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.8) of 2017-11-04
exwm Version: 0.18
xelb Version: 0.14

**Comment by ch11ng** [comment]
Tested against the latest emacs-25 branch (GNU Emacs 25.3.50.4 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-04-29), GIMP 2.10.0, XELB 0.14 and EXWM 0.18.  No problem.  IIRC I also tested GIMP 2.8 a few weeks ago.

**Comment by 11111000000** [comment]
I'll try after upgrading to nixos-unstable

**Comment by 11111000000** [comment]
full system upgrade, emacs packages upgrade - no effect,
 Gimp -> "open file" -> infinity flickering

**Comment by ch11ng** [comment]
Perhaps there's a conflict with some other package? Please test against a minimal configuration if possible (`emacs -Q -L /path/to/xelb -L /path/to/exwm --eval "(require 'exwm)" --eval "(exwm-init)"`).  Also which version of Gimp are you on now?

**Comment by 11111000000** [comment]
Gimp 2.10.0
minimal config - same result

**Comment by ch11ng** [comment]
I just find out the "Search and Run a Command" window won't show up in tiling mode.  It appears GIMP does not specify whether it should be created in floating mode and in EXWM it would replace the buffer of the main window.  This causes the latter iconized, which again causes the "Search and Run a Command" window iconized.  The workaround is to make the main window floating.

GIMP has a strong control over the X windows it created.  This issue might be relevant.  I'd suggest you try the following possible workarounds (and their combinations) and see if this issue can be reproduced:

* Remove the configuration files of GIMP (in `~/.config/GIMP` I think).
* Enable/Disable single-window mode.
* Make the GIMP main window floating.

Also please refer to the wiki to turn on `exwm-debug-on` and send the debug messages logged while the dialog is flickering.

**Comment by 11111000000** [comment]
No any informative trace results. But solved with custom float rules for Gimp dialogs.

**Comment by techquila** [comment]
also happening on Solus OS using i3WM and Gimp.  unable to find useful data on issue.

**Comment by 11111000000** [comment]
@techquila I fix it with custom popwin rules :
```
  (setq popwin:special-display-config
                '(...
                  ("^Gimp<.+$" :regexp t :noselect nil :position right :width 50 :stick nil)
....
)))
