### ISSUE TITLE
Opening a way to send you money

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#415]
Hi @ch11ng,

I would like to send you some money (not much) to show my support to your project. Would you mind adding a link to your favorite payment platform somewhere? I suggest liberapay but you might want to read that first https://oremacs.com/2017/12/10/patreon/.

**Comment by ch11ng** [comment]
Thank you but I don't accept financial support.  You may as well make a donation to FSF for this is an FSF project and without FSF this wouldn't even be possible.

**Comment by DamienCassou** [comment]
Well received, thank you.
