### ISSUE TITLE
Fix clipboard

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#416]
I wrote the [gpastel package](https://gitlab.petton.fr/DamienCassou/gpastel) to make sure that I can copy as much as I want in external applications and each text is added to the kill-ring at the appropriate position. This package, when used with EXWM, lets the user access the kill-ring from any application and paste any copied text to the application.

I thought the package could be useful to other EXWM users.

**Comment by kriyative** [comment]
@DamienCassou - thanks, this is a very useful contribution to `exwm` users.

Here's a minor customization to make `gpastel` work with [browse-kill-ring](https://github.com/browse-kill-ring/browse-kill-ring) and exwm.

```emacs-lisp
(defun browse-kill-ring-insert-and-highlight--around (old-function str)
  (if (derived-mode-p 'exwm-mode)
      (progn
        (kill-new str)
        (exwm-input--fake-key ?\C-v)
        (exwm-input--fake-key ?\C-e))
    (old-function str)))

(advice-add 'browse-kill-ring-insert-and-highlight
            :around
            #'browse-kill-ring-insert-and-highlight--around)

(use-package gpastel
  :config
  (gpastel-start-listening)
  (exwm-input-set-key (kbd "\C-x\C-y") 'browse-kill-ring))
```

**Comment by QiangF** [comment]
There is also clipmon, which doen't need an exteranl app.
https://github.com/bburns/clipmon

**Comment by DamienCassou** [comment]
@QiangF 

> There is also clipmon, which doen't need an exteranl app.

true. I was using something similar before but didn't like the fact that the code was polling every X seconds as it was missing some texts sometimes (also I don't like polling). The gpaste approach is inherently better because it relies on events and not on pulling.

**Comment by kriyative** [comment]
@DamienCassou - of course, either way works. Feel free to commit directly, or post the Git repo and I'll fork and generate a PR. Cheers.

**Comment by DamienCassou** [comment]
@kriyative for now I have added your snippet to the README. Can you please check? I rewrote it a bit. Moreover, I removed the `(exwm-input--fake-key ?\C-e)` part because I didn't know what it was used for. If you tell me, I will add it back (you can also send a PR against the README).

**Comment by kriyative** [comment]
@DamienCassou - looks good. The `?\C-e` was to move the insertion cursor after a paste - `browse-kill-ring` has a feature where you can paste multiple past selections from within the kill-ring browser buffer. It probably should be a `End` keycode - this relies on exwm simulation keys being setup. It's not super important, so your snippet is fine. As I posted in the other issue, it only works in Firefox - every other X window (Chromium and others), requires and explicit paste (`?\C-v`) key stroke to insert the selection.

**Comment by DamienCassou** [comment]
@ch11ng Is there something you want to do about this ticket (e.g., advertise gpastel in the README) or should I just close it?

In the meantime, I have also release [desktop-environment](https://gitlab.petton.fr/DamienCassou/desktop-environment) which helps you control your GNU/Linux computer from Emacs.

**Comment by ch11ng** [comment]
@DamienCassou I think you can advertise it [here](https://github.com/ch11ng/exwm/wiki#third-party-extensions).

**Comment by DamienCassou** [comment]
@ch11ng I advertised both of my packages there. Thanks.
