### ISSUE TITLE
Simulation Key Issue

### ISSUE THREAD

**Issue by paulbdavis** [ch11ng/exwm#417]
Using version 0.18 from MELPA stable

When I set up local simulation keys for an application, any keys not defined in the local map do not pass through.

For example:

```elisp
  (defun ds/exwm-keyrules-termite ()
    (if (and exwm-class-name
             (string= exwm-class-name "Termite"))
        (exwm-input-set-local-simulation-keys
         '(
           ([?\C-b] . left)
           ([?\M-b] . C-left)
           ([?\C-f] . right)
           ([?\M-f] . C-right)
           ([?\C-p] . up)
           ([?\C-n] . down)
           ([?\C-w] . [?\C-\S-x])
           ([?\M-w] . [?\C-\S-c])
           ([?\C-y] . [?\C-\S-v])))))

  (add-hook 'exwm-manage-finish-hook #'ds/exwm-keyrules-termite)
```

With these settings, when I press `C-a`, `C-e`, or `C-d` I would expect that key to pass through to the application (in this case, a terminal emulator) and have the application respond to these as it normally would.

However, I have to add the following to the key list for them to work properly

```
           ([?\C-a] . [?\C-a])
           ([?\C-e] . [?\C-e])
           ([?\C-d] . [?\C-d])
```

**Comment by ch11ng** [comment]
This is a known problem with 0.18 and has been fixed (not released yet).

**Comment by medranocalvo** [comment]
EXWM 0.20 has just been released.  Please, reopen if the issue is still present in that version.
