### ISSUE TITLE
Bindings that create new windows don't work in X application buffers

### ISSUE THREAD

**Issue by IQubic** [ch11ng/exwm#418]
So I have the following in my .emacs
```
(exwm-input-set-key (kbd "s-s") 'shell)
(exwm-input-set-key (kbd "s-c") 'calc)
```

Both of these bindings create new windows. These bindings only work when I am a non-X application buffer. I have verified that binding things to s-s and s-c actually works by evaluating this: 
```
(exwm-input-set-key (kbd "s-s") 
    (lambda () (interactive) (start-process-shell-command "scrot" nil "scrot")))
```
That allows me to take screenshots of X buffers, even in fullscreen (c-c c-f).
\*Messages\* is giving me no output related to exwm.
What I have noticed is that which-key's popup is being shown just fine when an X application has the focus. But that is just using the minibuffer instead trying to spawn another window.

**Comment by ch11ng** [comment]
Which version of XELB do you use? And does `exwm-restart` help?

**Comment by IQubic** [comment]
@ch11ng  I have to run exwm-restart after I create a keybinding of this type in order to get it to work, so that's not the most ideal.

**Comment by ch11ng** [comment]
Do you have an unconventional keyboard mapping? If so, how do you set it up? It's recommended to bring the relevant settings into effect _before_ launching Emacs for the moment.

**Comment by IQubic** [comment]
I'm running EXWM on NixOS on a Dell Latitude 5480. The keymapping is the standard QWERTY layout. I'm not doing anything strange to set it up.

**Comment by ch11ng** [comment]
Have you tried the lasted XELB from source? There is an unreleased fix for this.

**Comment by IQubic** [comment]
How can I go about installing XELB from source? Sorry that I'm asking basic questions here.

**Comment by ch11ng** [comment]
Please refer to the wiki.  Basically you just need to clone the source and modify `load-path`.

**Comment by IQubic** [comment]
Pulling the latest versions of XELB and EXWM didn't actually solve this issue.  

While I can bind "s-c" to 'calc, as show in the first post, I can't actually use that binding until I run exwm-restart. C-x C-e works to set the keybinding, but it only works in non X application buffers. Once I run exwm-restart then I use the binding anywhere.

The above is how things were working before pulling the latest version of XELB and EXWM. It is also how things are working after pulling the latest versions.

**Comment by ch11ng** [comment]
What's the value of `xcb:keysyms:super-mask`?

**Comment by IQubic** [comment]
The value of that variable is 64.

**Comment by IQubic** [comment]
Here is what xmodmap returns:
```
/home/avi/.nix-profile/bin/xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

**Comment by ch11ng** [comment]
It seems you removed <kbd>caps-lock</kbd>.  How did you set that up?

**Comment by IQubic** [comment]
@ch11ng Sorry I took so long to respond. 
I modified my `/etc/X11/xorg.conf.d/00-keyboard.conf`to have the following content:
```Section "InputClass"
  Identifier "Keyboard catchall"
  MatchIsKeyboard "on"
  Option "XkbModel" "pc104"
  Option "XkbLayout" "us, gr"
  Option "XkbOptions" "grp:shift_toggle, grp_led:caps, caps:escape, compose:menu"
  Option "XkbVariant" ""
EndSection
```

**Comment by IQubic** [comment]
Yeah, sorry about that. I edited my post, to reflect what I am doing to bind scrot.
```
(exwm-input-set-key (kbd "s-s") 
    (lambda () (interactive) (start-process-shell-command "scrot" nil "scrot")))
```
I am not using set-key-to-command. That is not and has not ever been a valid function. Not sure where I got that name from. 

`shell` and `calc` are commands that are defined in shell.el and calc.el respctively. I didn't write them myself. I have no idea how they are defined.

**Comment by ch11ng** [comment]
If creating a binding for 'scrot' in the same way works then it doesn't seem to be an EXWM issue.  Perhaps you forget to explicitly load them first (`(require 'shell)` for example)?

**Comment by medranocalvo** [comment]
This works fine here.  @IQubic, could you test again with the latest EXWM release?

**Comment by medranocalvo** [comment]
Please reopen if latest release does not work for you.
