### ISSUE TITLE
Exim Input methods broken

### ISSUE THREAD

**Issue by 11111000000** [ch11ng/exwm#419]
no any cyrillic input with X applications.

default input method works as expected in X apps and all methods works in text buffers.

GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.8) of 2017-11-04
exwm-0.18

emacs config:
```
(use-package exim
  :load-path "~/elisp/exim/"       
  :init
  (push ?\C-\\ exwm-input-prefix-keys)
  (add-hook 'exwm-init-hook 'exim-start)
  )
```
.xprofile:
```
  export XMODIFIERS=@im=exim  
  export GTK_IM_MODULE=xim    
  export QT_IM_MODULE=xim     
  export CLUTTER_IM_MODULE=xim

```

**Comment by 11111000000** [comment]
firefox - input method broken 
chromium - input method broken
urxvt - input method works 

GTK issue?

**Comment by ch11ng** [comment]
Let's focus on ch11ng/exim#5.
