### ISSUE TITLE
fullscreen VirtualBox invisible 

### ISSUE THREAD

**Issue by 11111000000** [ch11ng/exwm#421]
0) Start VirtualBox and press <C-x 1> 
1) Run some linux image inside VirtualBox (text mode or graphics mode - no difference)
2) `RCtrl + f`

 VirtualBox window is invisible, but  continue to grab keys

`RCtrl + f` again  - no effect

**Comment by 11111000000** [comment]
* when VirtualBox in split window, fullscreen works as expected

**Comment by ch11ng** [comment]
Please verify if 0037cba87b1ceefc3a65fa3c458aa685689e7e27 resolves it.

**Comment by medranocalvo** [comment]
@11111000000, could you try @ch11ng's fix?

**Comment by 11111000000** [comment]
All works
