### ISSUE TITLE
Switching to other workspaces while hovering an X window fails when focus follows mouse is enabled

### ISSUE THREAD

**Issue by medranocalvo** [ch11ng/exwm#422]
Switching to other workspaces fails when _focus follows mouse_ is enabled `(setq mouse-autoselect-window t)` when the mouse pointer is hovering an X window.

# Recipe
1. Start EXWM
```
emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ \
        --eval '(setq mouse-autoselect-window t)' \
        --eval '(setq focus-follows-mouse t)' \
        --eval '(require 'exwm)' \
        --eval '(exwm-init)'
```
2. Start XTerm, delete all other emacs windows in the frame.
3. Create a second EXWM workspace, switch to it.
4. Switch back to the first workspace. Before switching, make sure the mouse pointer stays around the center of the buffer, so that upon switching to the first workspace it will be over the XTerm window.
5. Without moving the mouse out of the XTerm window, nor clicking anywhere, switch to the 2nd workspace.  The workspace switch reverts back to the first workspace.

Let me know if the description is not clear.

# Workaround
Clicking on the X window before switching to other workspace lets the switch happen.

**Comment by ch11ng** [comment]
Tested against Emacs 25/26/27 and could not reproduce it.  I think I've done exactly what you instructed.  Are the two workspaces on different monitors or are there anything else special involved?

P.S. Setting `mouse-autoselect-window` alone doesn't actually work in EXWM.  Setting `focus-follows-mouse` is also required.

**Comment by medranocalvo** [comment]
Thank you for going through all the trouble; I'm sorry I omitted the version information from the original post.  I'm using Emacs 26.0.90, and EXWM master (missing a couple of commits at the moment, 87db8b42a33876818ad8ee6b950c1f2aaa73d3d5) and, noteworthly, I'm using it in my rogue XQuartz setup on Mac OS X.

I could reproduce using the steps above and setting `focus-follows-mouse` to `t`.  (Will update the ticket.)

It's probably due to XQuartz.  I already tried debugging it back then (it has something to do with the Enter event), will go deeper.

**Comment by medranocalvo** [comment]
Some progress investigating this.  I would appreciate your input.

The following behaviour confuses me deeply, and I think it might the root cause: in step 4, when returning to the workspace with the XTerm window (remember, with the mouse pointer over the XTerm X window), no `EnterNotify` event is received at all.  One would think that mapping the XTerm X window (on `exwm-layout--show`) would cause that event to fire, but that's not the case.

Then, in step 5 (switching to the other workspace), something equally curious happens quite early in the evaluation of `exwm-workspace-switch`: restacking the workspace (see snippet below) causes an `EnterNotify` event to fire.  This `EnterNotify` event is only handled after the workspace switching has ended, and causes EXWM to switch back to the XTerm workspace (`exwm-input--on-EnterNotify`).

```elisp
      (xcb:+request exwm--connection
          (make-instance 'xcb:ConfigureWindow
                         :window (frame-parameter frame 'exwm-container)
                         :value-mask (logior xcb:ConfigWindow:Sibling
                                             xcb:ConfigWindow:StackMode)
                         :sibling exwm--guide-window
                         :stack-mode xcb:StackMode:Below))
```

Note that moving the mouse over the XTerm X window after step 4 fires the `EnterNotify` event therefore avoiding this event from being fired in step 5.  Workspace switching works all right in this case.

-----

The workaround I'm using is placing the following two lines after the `ConfigureWindow`, so that the EnterNotify event is handled before switching to the other workspace.  Ugly.

```elisp
                         ...
                         :stack-mode xcb:StackMode:Below))
      (xcb:flush exwm--connection)
      (accept-process-output nil 0.02)
```

-----

Do you have any idea of what could be causing the `EnterNotify` event not being fired when switching to the XTerm workspace with the pointer ending up over the XTerm window?

**Comment by ch11ng** [comment]
Thanks, @medranocalvo.  This would explain many weird behaviors.  According to the X specification, mapping an X window under the pointer does not necessarily generate an EnterNotify event.  It seems there's no good way to force that.  But I'm still wondering why that event would be generated when switching workspace.  For now your workaround seems to be reasonable but is that call to `accept-process-output` necessary? Or does `(accept-process-output nil 0)` work?

**Comment by ch11ng** [comment]
We'll need to find another way then.  Have you checked the EnterNotify events (their detail/mode fields)? Perhaps we can filter them out.

> One last question; with:
>
>> This would explain many weird behaviors.
>
> do you refer to just the ones mentioned in this ticket, or are you thinking of other ones?

I've encountered such behavior before, but thought it was a quirk of multi-frame Emacs.  So I simply installed workarounds.

**Comment by medranocalvo** [comment]
Just wanted to note that I'm still seeing this issue (with 0.19), but have not yet had the time to debug it further.

**Comment by medranocalvo** [comment]
Please, perform the following test:

1. Checkout the branch https://github.com/medranocalvo/exwm/tree/test-422.  This branch logs EnterNotify and LeaveNotify events.
2. Start EXWM as follows:
~~~
emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ \
        --eval '(setq exwm-log-on t)' \
        --eval '(setq mouse-autoselect-window t)' \
        --eval '(setq focus-follows-mouse t)' \
        --eval '(require 'exwm)' \
        --eval '(exwm-init)'
~~~
3. Split the frame, start XTerm in one window, switch to `*Messages*` in the other.
4. Click on XTerm and keep the mouse pointer over the XTerm window in the following steps.
5. <kbd>M-: (setq xterm-id exwm--id)</kbd>
6. <kbd>M-: (exwm-layout--hide xterm-id)</kbd>
7. <kbd>M-: (exwm-layout--show xterm-id)</kbd>
8. Move the mouse pointer slightly.

* Did step 6 generate an `exwm-input--on-LeaveNotify` log entry?
* Did step 7 generate an `exwm-input--on-EnterNotify` log entry?
* Did step 8 generate an `exwm-input--on-EnterNotify` log entry?

**Comment by ch11ng** [comment]
The results are as follows.  Note that the tests are performed against the latest commit.  I think operating thru <kbd>M-:</kbd> might have some side-effects.

> Did step 6 generate an exwm-input--on-LeaveNotify log entry?

No.

> Did step 7 generate an exwm-input--on-EnterNotify log entry?

Yes.

> Did step 8 generate an exwm-input--on-EnterNotify log entry?

Nothing.

**Comment by medranocalvo** [comment]
(Corrected the script above as it had an error. It should have been: `--eval '(setq exwm-debug-on t)'`)

Used the following in order to avoid potential interference of <kbd>M-:</kbd>:
```
(progn
  (run-with-timer 4 nil (lambda () (exwm-layout--hide xterm-id)))
  (run-with-timer 6 nil (lambda () (exwm-layout--show xterm-id))))
```

With regards to the results, I get:

6. No.
7. No.
8. Yes.

My X server (XQuartz) does not emit EnterNotify after an X window is mapped :-/.  I have a fix consisting on forcing restacking upon MapNotify.  Will post a patch for review shortly.

**Comment by ch11ng** [comment]
> (Corrected the script above as it had an error. It should have been: --eval '(setq exwm-debug-on t)')

I already did that when performing the test.  Besides it should be `"(require 'exwm)"` in the command line.

The results are the same here with timers.  Perhaps there is a difference between our X servers.
