### ISSUE TITLE
Teamviewer 13 won't start

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#424]
I've recently upgraded Teamviewer to version 13 in 64bits and it doesn't start anymore:

```
> teamviewer 

Init...
CheckCPU: SSE2 support: yes
Checking setup...
Launching TeamViewer ...
Launching TeamViewer GUI ...
```

The previous version was running fine through Wine. The new version is supposed to run natively with QT but nothing is displayed.

**Comment by NicolasPetton** [comment]
I can reproduce the issue.

**Comment by ch11ng** [comment]
From its log file it turns out a session manager is required to run which we (and some other WMs) don't have.

**Comment by DamienCassou** [comment]
I guess there is nothing we can do about it then :-(.

**Comment by DamienCassou** [comment]
Thanks for trying
