### ISSUE TITLE
buffer-local exwm-mode-map

### ISSUE THREAD

**Issue by ecraven** [ch11ng/exwm#426]
I'm pretty sure that before 0.18, buffer-local exwm-mode-map used to work, but I haven't been able to get it working since :-/ 
I'd like to have certain keybindings only in some exwm buffers, not all of them, and not global.
Has there been any change here? I've tried the following:
````
(setq-local exwm-mode-map (copy-keymap exwm-mode-map))
(define-key exwm-mode-map ...)
````
But all bindings I add there are ignored.

**Comment by ch11ng** [comment]
This is a known issue with 0.18.  A fix is present in master and will be released soon.

**Comment by medranocalvo** [comment]
@ecraven, 0.18 was released long ago.

Nevertheless, I don't think your code above would work (although it might have worked before).  Please, see https://www.emacswiki.org/emacs/BufferLocalKeys.

The following lets me set local keys for specific `exwm-mode` buffers:

```elisp
(use-local-map (copy-keymap exwm-mode-map))
(local-set-key (kbd "C-p") (lambda () (interactive) (message "OK")))
```
Does that work for you?

**Comment by medranocalvo** [comment]
Closing due to lack of response.  Please, reopen if you still find difficulties.
