### ISSUE TITLE
exwm-floating-toggle-floating should be remowing adjacent windows

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#427]
when you toggle floating by calling `exwm-floating-toggle-floating`, and exwm app window happens to be not the only one, it floats the whole window. It seems to be than first it has to remove adjacent windows and then make it float. As a workaround for now I suppose simple advice would work

    (advice-add #'exwm-floating-toggle-floating :before #'delete-other-windows)

**Comment by ch11ng** [comment]
The intended behaviors are:

1. A floating frame is created with the original buffer displayed there.
1. The original window displays another buffer. 
1. Other windows & buffers remain intact (so they are not removed).

And what's the meaning of 'float the whole window'?

**Comment by agzam** [comment]
Oh, you know what? I think toggling floating acts differently on my config, maybe due to persps.el AKA Spacemacs layouts.
