### ISSUE TITLE
Mode-line and top of minibuffer hidden (most of the time) with ido-vertical-mode

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#428]
Hi,

Thank you for `exwm`!!! I just discovered it and totally love it. I have it mostly working. One thing that sometimes works, but most of the time does not is `ido-vertical-mode` while in non-emacs windows. 

Once in a while, these windows behave as emacs would: the minibuffer covers the bottom of the window, so that I can fully see it. But most of the time, the window remains on top so that most of the minibuffer (and the modeline) are hidden and I can only see the bottom 2 lines which are never covered by the window.

Here are some screenshots to make this more clear:

- with a browser

![image](https://user-images.githubusercontent.com/4634851/40345046-67aac13e-5d4c-11e8-8157-2f628b670c4c.png)

- and the same thing with a terminal emulator

![image](https://user-images.githubusercontent.com/4634851/40345189-11326cfc-5d4d-11e8-9aa2-dee43edaf0c5.png)

- here in comparison is the desired behaviour with an emacs window (which does happen with non-emacs window, every now and then, but rarely)

![image](https://user-images.githubusercontent.com/4634851/40345277-66a32b90-5d4d-11e8-97b3-1f49bb9105c9.png)

Here, one of those rare times, it did work with a non-emacs window

![image](https://user-images.githubusercontent.com/4634851/40345654-fbca9766-5d4e-11e8-8247-1067bb9164b5.png)

I am on Arch Linux and using `exwm` with LXDE.

Thank you!

Note: I use ido for everything (`find-file`, `M-x`, find bookmark, etc.) and I have the same issue in all cases. Ido does work, except that I am totally blind since the top option is hidden. Because I know emacs behaviour and which file/function/buffer will come on top, I can still use it, but only relying on habit, not on what I can see.

Of note also, if a 2nd selection follows the first one, then that 2nd one does work every single time: for instance, if I launch `M-x customize-group`, then I can see the full minibuffer with the groups to select.

![image](https://user-images.githubusercontent.com/4634851/40345666-0ea43f36-5d4f-11e8-95e7-1766b030b498.png)

**Comment by prosoitos** [comment]
Note: I already had `ido` configured in my init file and I did add: `(exwm-config-ido)`

**Comment by ch11ng** [comment]
When the minibuffer is fixed (default behavior) X windows would resize while the minibuffer resizes.  Perhaps there's a conflict with some package.  There won't be such problem with the minibuffer set to auto-hide.

**Comment by prosoitos** [comment]
I have some new info on this and 2 new questions:

I started with LXDE and openbox. Installed exwm and played with it with and without LXDE, but without uninstalling openbox. Eventually, I removed openbox.

Today, I gave it another try at exwm without LXDE (so I replaced `exec startlxde` with `start emacs` in my ~/.xinitrc file. But I didn't like it (see below for this), so I reverted my settings exactly as they were before. But things did not revert to the way they were.

- the problem of this issue got solved (now all windows shrink to leave space for the minibuffer)
- something else changed which I would like to revert (see below)

Since my settings are exactly the same, I imagine that some openbox file or setting somewhere, which was still active due to the chronology of my exwm installation, got replaced when I ran exwm by itself today while openbox was not installed on my machine anymore (I had tried exwm alone before, but that had not happened and that is the only difference I can think of).

So basically, the problem is solved, it had (as expected) nothing to do with exwm and had to do with something somewhere in my settings and I will close this issue.

But I have 2 new questions @ch11ng, if you happen to have the time (and I thank you sincerely for all your time with my numerous issues...):

1/ one of the reasons I didn't like running exwm without LXDE is because the screen resolution is very poor. So something in LXDE must be addressing this that I have to set manually without LXDE. Do you know what that might be? A program to install and set? Which? Any lead would be useful. Thank you! If I can fix this, I really don't have any reason to run LXDE anymore.

2/ with my weird settings until today, a new window would push the previously visible window in the background so that I only had one window visible at a time, unless I explicitly called `split-window-*`. I really liked that and loosing this behaviour for a real tiling window behaviour is one of the reason why I came back to LXDE. But now, this "normal exwm" behaviour is also remaining. (Basically, what I did today fixed something that was wrong in my settings. But in that case, I liked that). Is there any way to set exwm to have this behaviour? I was unable to find anything about this in the settings, the wiki, or with google. (Note: openbox was not installed in my system anymore. Only something left behind by it must have still be running. I did not have floating windows, but a tiling window system, except that new window would not create a split and would only push the current window in the background (as would happen in emacs unless `*-other-window` is called). I would very much like to go back to this behaviour, if possible.

Thank you so much for your time.

**Comment by prosoitos** [comment]
I finally managed to solve 2/ (see previous comment) by setting `pop-up-windows` to `nil`. But this changes the behaviour of some buffers that I was happy to have in the same window (ESS for instance).

If there is a function to customize the behaviour of new windows in exwm, without having to chance emacs window behaviour (so a way to set the behaviour for non-emacs windows) I would love to hear about that. Thank you @ch11ng !

**Comment by ch11ng** [comment]
> 1/ one of the reasons I didn't like running exwm without LXDE is because the screen resolution is very poor.

You can always change the screen resolution with the xrandr utility.  If you do that before launching EXWM then you don't have to enable the exwm-randr module.

> I finally managed to solve 2/ (see previous comment) by setting `pop-up-windows` to `nil`.

`display-buffer-alist` would be an option.  In general it's quite flexible.

**Comment by prosoitos** [comment]
I did try to play with `display-buffer-alist` with no success at all (I failed to have any of the behaviours changed). But I will try some more. I am clearly doing something wrong with this function.

**Comment by prosoitos** [comment]
Actually, I managed to get `display-buffer-alist` to do what I want for some emacs buffers. So this, combined with `pop-up-windows` to `nil` for the exwm windows will get me to what I was hoping for.

But it would be a lot simpler to do it the other way around: reset emacs the way it was and set the exwm windows to always open by themselves in a new window, what would be a good condition to define exwm windows for the `display-buffer-alist` function? Is there a function or a variable that allows to define any exwm window (but only them, so leaving the exwm buffers alone)? If I were not renaming them, I could use the regexp option, but I am renaming them based on the window title.
Thank you!

**Comment by ch11ng** [comment]
You could check buffer's `major-mode`.

**Comment by re5et** [comment]
I am having the same issue, but mine exists when just starting `emacs` from my `.xinitrc`, not running LXDE or anything else.  If I hit `M-x` from Firefox (or whatever gui app), the menu comes in behind.  If I hit `M-x` again, it pops in front as expected.  Is there some trick to this that I am missing?  

I have also found that if I `M-x` and then trigger `(exwm-layout--refresh)` with an interactive keybinding call, it pops up where it should.

**Comment by ch11ng** [comment]
What does <kbd>M-x</kbd> do in your setup? By default it just shows 'M-x ' and waiting for input, which doesn't involve resizing the minibuffer.  If it shows something else, chances are there is some hook you can put `exwm-layout--refresh` in.

**Comment by re5et** [comment]
@ch11ng That makes sense.  I am using https://github.com/nonsequitur/smex which uses `ido` somewhere along the line, which I have configured to be vertical.  I haven't found the right place for it yet, but it gives me something to go on, thanks.  If you have any ideas where that would be awesome, thanks again.

**Comment by re5et** [comment]
It must just be `ido` because I have the same situation when I do `ido-switch-buffer` or `ido-find-file`.

**Comment by prosoitos** [comment]
I also use `ido`, `smex` and `ido-vertical` and I never had the problem again when I ditched LXDE.

**Comment by re5et** [comment]
Hmm, I don't actually use `ido-vertical-mode`, I just change `ido-decorations` so it has newlines.  I dropped the decoration customizations, and I still have the problem sometimes.  It seems to work fine for `M-x` / smex as well as `ido-find-file`, but does not work with `ido-switch-buffer`.  Also tried out `ido-vertical-mode`, same problem as before :man_shrugging:

**Comment by re5et** [comment]
Hmm, I don't actually use `ido-vertical-mode`, I just change `ido-decorations` so it has newlines.  I dropped the decoration customizations, and I still have the problem sometimes.  It seems to work fine for `M-x` / smex as well as `ido-find-file`, but does not work with `ido-switch-buffer`.  Also tried out `ido-vertical-mode`, same problem as before :man_shrugging:

**Comment by ch11ng** [comment]
@re5et 

> I just change `ido-decorations` so it has newlines.

Could you show us the setting?

Please prepare a debug log according to https://github.com/ch11ng/exwm/wiki#how-to-report-a-bug so we can see if there is anything we can do.
