### ISSUE TITLE
google-chrome restore tabs button doesn't work with keyboard

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#43]
This is another strange behavior I observed when using google-chrome.

When google-chrome window is killed uncleanly (due to poweroff, etc.), it offers to restore previous tabs when re-opened. It opens the previous tabs just fine when I press the restore button using the mouse.

But if I press restore button using keyboard (by, typing tab to switch focus to the restore button and typing space key to press it), the restore button stays in pressed state and doesn't get released. So, google-chrome tabs don't open up.

Again, I am not sure if this is exwm issue or not, but we don't get this behavior with other window managers.

**Comment by ch11ng** [comment]
Confirmed. `<return>` should work anyway.

**Comment by ch11ng** [comment]
I believe this issue is fixed in 981293f06af320f2929fd0d209eb97e63b4d8e3e.
