### ISSUE TITLE
Mouse cursor issue with LXDE

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#433]
*Non-urgent as I found a workaround*.

I use exwm with Arch Linux and LXDE.

When the mouse cursor is above any application linked with LXDE (those that do not work if I run exwm without LXDE with my current settings, so this includes the autokey window, pcmanfm, the rofi popups, etc.), it turns into a large cross that works but is really awkward to use. This can be solved simply by opening and closing (without changing anything) `lxappearance`. After each reboot, I have to reopen and close `lxappearnce` to trigger something. After which the mouse cursor remains normal over those applications too.

Of note: `lxappearance` does not keep running processes in the background once I close it. Simply opening it seems to trigger something, but it then becomes unnecessary for the mouse cursor to be fine.

**Comment by ch11ng** [comment]
How do you launch LXDE? It doesn't seem to be a window manager issue.

**Comment by prosoitos** [comment]
I have `exec startlxde` in my ~/.xinitrc file, which is, I think, the standard recommendation according to the Arch Linux wiki.

**Comment by prosoitos** [comment]
I never had this issue with openbox.

Also, of note, if I use exwm without lxde (I don't use exwm without lxde. I only experimented with this out of curiosity), I have the same cursor issue (but not fixable). Again: no big deal: I added lxappearance in my autostart and simply close it after each reboot. And the mouse cursor is fine after doing this.

**Comment by ch11ng** [comment]
Basically you can set the cursor for the root X window with `xsetroot -cursor_name left_ptr` which some X windows would inherit.  And if you happen to have gnome-settings-daemon installed you can start it in the background.

**Comment by ch11ng** [comment]
@prosoitos My previous comment should work.  So I'm closing this issue now.

**Comment by prosoitos** [comment]
It didn't work when I tried it, but I found an easy work around, so I am happy with the closing of the issue.

**Comment by prosoitos** [comment]
I had to rebuild my Arch Linux installation and this time, I decided to get rid of LXDE entirely and use EXWM alone. I still had the issue of the default X shaped cursor showing up above Gtk applications, but with my current setup without LXDE

```
xsetroot -cursor_name left_ptr
```
(which you had suggested) works like a charm :slightly_smiling_face: 

Not very important, but it really made me happy to finally solve this after so long! :smile:
