### ISSUE TITLE
menubar-mode  causes systemtray to be pushed off screen

### ISSUE THREAD

**Issue by mogorman** [ch11ng/exwm#436]
I use menubar-mode on my emacs setup, if i turn it off i can see the systemtray if i enable it disappears.

**Comment by ch11ng** [comment]
This should be fixed in b75c89cae2a1c4c70044f885c44a95fd2f9950dd.

**Comment by ch11ng** [comment]
This issue has been fixed in release 0.19 .  Please reopen this issue if it does not work out.
