### ISSUE TITLE
[XELB ERROR] (args-out-of-range "Telegram" 0 12)

### ISSUE THREAD

**Issue by WorldsEndless** [ch11ng/exwm#438]
Until last week, I had no issues. I'm not sure what change (most likely a Telegram version), but now when I start Telegram app I get the above error, and notice that all exwm key bindings (including `C-x`) are not respected; I have to use C-w to background the Telegram app and then I'm back in usable mode. I assume that the XELB error is related to this keyboard highjacking.

**Comment by zevlg** [comment]
@WorldsEndless why not using native Emacs telegram client? https://github.com/zevlg/telega.el

**Comment by WorldsEndless** [comment]
Ah; solved the problem. It turned out to be because I was re-naming buffers to match their exwm mode name, truncated to 12 chars; Telegram has a name less than 12 chars, so it was erroring. Fixed now.
