### ISSUE TITLE
exwm and remmina

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#440]
Certain apps do act weird in EXWM but to be honest I don't use too many apps. But this one drives me crazy. For whatever reason I can't use Remmina within EXWM session. It's kinda difficult to explain, but it just gets into this weird state where I can't control it. It connects to RDP machine, but won't show anything and everything hangs. Also it takes long for it to start for some reason (GTK+ issue maybe?).This doesn't seem to be X11 issue (I have tested it in other WMs). Anyone else having similar problem?

**Comment by ch11ng** [comment]
Does it work in char-mode? Remote desktop apps often want to grab keyboard.

**Comment by agzam** [comment]
I've tried different things: making its window float, fullscreen, release-keyboard - it just shows a blank screen.

**Comment by djeis97** [comment]
Remmina in particular actually works fine for me without doing anything special for it in particular, but I might have tweaked some more general settings that made it work. I'm running a slightly outdated spacemacs develop and exwm/xelb github master, but I've been using remmina consistently with this setup (throughout updates) for a while now.

**Comment by agzam** [comment]
Oy.. for unknown stupid reason I had this `export GDK_CORE_DEVICE_EVENTS=1`. I think that was causing it. Will keep an eye on thing for a day or two, if it works fine gonna close this.
