### ISSUE TITLE
Black frame when using Gnome Disk

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#441]
I took a USB stick, deleted the partitions and tried to create a new one. At this moment, I got a black frame in the middle of the window with no modeline. I can't do anything with the frame. It just stays there. The only thing I could do is `C-x k` to kill it.

![2018-06-07-095510_829x695_scrot](https://user-images.githubusercontent.com/217543/41086058-1cde1af8-6a39-11e8-9056-801a79c77de6.png)

**Comment by NicolasPetton** [comment]
I have the same issue with the Gnome printer dialog (with EOG for example).

**Comment by NicolasPetton** [comment]
Note: sometimes the printer dialog works though, after seeing a black frame for a few seconds.

**Comment by ch11ng** [comment]
They seem working here.  From the screenshot it appears the X window is there but incorrectly rendered.  Perhaps a result of xwininfo can confirm this? BTW does `exwm-reset` or moving the window make a difference?

**Comment by DamienCassou** [comment]
```
> xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x4600ff9 "Create Partition"

  Absolute upper-left X:  172
  Absolute upper-left Y:  291
  Relative upper-left X:  172
  Relative upper-left Y:  291
  Width: 633
  Height: 437
  Depth: 24
  Visual: 0x130
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x4600006 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +172+291  -1115+291  -1115-352  +172-352
  -geometry 633x437+172+291
```

`exwm-reset` doesn't seem to do anything.
Moving the window makes the content appear! Thank you.

I also noticed that if I place the mouse at some locations, I can get messages:
![2018-06-13-084732_1920x1080_scrot](https://user-images.githubusercontent.com/217543/41335185-38e48c9c-6ee8-11e8-8090-a403382b072b.png)

**Comment by ch11ng** [comment]
The X window is actually there but not properly rendered.  I've found another app (virt-manager) with a similar problem and will check out that instead.

**Comment by ch11ng** [comment]
There was a problem in shrinking Emacs frames.  Please verify if the latest code fixes this issue.

**Comment by DamienCassou** [comment]
> There was a problem in shrinking Emacs frames. Please verify if the latest code fixes this issue.

I can't reproduce anymore. Thank you.
