### ISSUE TITLE
Chrome resets all logins

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#442]
I'm dealing with this very annoying issue that might be completely unrelated to EXWM. Would appreciate any thoughts how to fix this or find workarounds.

Basically from time to time Chrome completely forgets that it was previously logged and prompts me for credentials on websites like Github, Stackoverflow or Twitter. It is especially annoying since I have 2FA enabled.

Could it be because when I quit Emacs, EXWM simply kills the app and Chrome sees that as "unexpectedly terminated session"?

I have even tried starting chrome like this: `google-chrome-stable --password-store=basic`, that didn't seem to make any difference.

**Comment by tumashu** [comment]
when you quit emacs, let emacs tell you manual close chrome

**Comment by ch11ng** [comment]
How do you quit Emacs? You should get a prompt asking you to confirm if there're running apps.

**Comment by medranocalvo** [comment]
@agzam do you still experience this?

**Comment by agzam** [comment]
oh yeah that can be closed
