### ISSUE TITLE
Super key sometimes not detected if held down for multiple presses

### ISSUE THREAD

**Issue by jabranham** [ch11ng/exwm#447]
If I do `s-1`, which does `exwm-workspace-switch-create`, then `s-2` without having released the super key, it inserts a 2 as if I'm not holding down the super key.

This only started appearing after the last commit or two in `exwm` and `xelb`. 

This doesn't happen every time, but does happen pretty frequently

**Comment by ch11ng** [comment]
This has been fixed with the latest code.
