### ISSUE TITLE
EXWM fails to start (unbound-slot: (xcb:xinput:DeviceClass ...)) 

### ISSUE THREAD

**Issue by berkan** [ch11ng/exwm#448]
Hello

I've been trying to get Exwm running, but it's failing to start. The error message as it appears in `*Warnings*` is:

```
Warning (emacs): [EXWM] EXWM fails to start (unbound-slot: (xcb:xinput:DeviceClass #<xcb:xinput:DeviceClass xcb:xinput:DeviceClass-9f4100> xcb:xinput:DeviceClass oref-default))
```

I'm using Xephyr while debugging this. Below is how I start Exwm on Xephyr:

```
$ cat exwm-xephyr

#!/bin/sh
killall Xephyr
Xephyr -screen 1024x768 :1 & sleep 2s; DISPLAY=:1 sh ./xinit
```

My `xinit` file is:

```
exec dbus-launch --exit-with-session emacs-27.0.50 -q --load ./init-min.el "$@";
```

And my `init-min.el` is:

```
(add-to-list 'load-path "~/.emacs.d/elpa/27/xelb-0.14/")
(add-to-list 'load-path "~/.emacs.d/elpa/27/exwm-20180618.1533/")

(require 'exwm)
(require 'exwm-config)

(exwm-enable)

(server-start)
```

I have tried with the following versions of emacs-27 and emacs-25, and got exactly the same behaviour:

```
GNU Emacs 25.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-15
```

```
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)  of 2018-06-19
```

Given how bare-bones the above setup is, at this point I'm guessing the issue may be outside emacs, maybe with my X setup?

Could you please advise where next to look?

Many thanks
Berkan

**Comment by ch11ng** [comment]
This has been fixed with the latest code.
