### ISSUE TITLE
Hook for floating class

### ISSUE THREAD

**Issue by djrmarques** [ch11ng/exwm#452]
I am not sure this is the right place to ask this but how can I set up a hook so that every matplitlib graph window is foating? 

I have been getting a weird behaviour, not on all plots, but on a specific plot of an heatmap using seaborn (40x40 matrix).  I have been browsing the *User Guide* and so far have not been able to figure it out on my own. 

Thanks, and if this is not the right place for this type of questions please redirect me to the correct one.

**Comment by dakra** [comment]
If you know the X class name (which you can get with `xprop`)
you can customize "stuff" with `exwm-manage-configurations`.

E.g. I have keepass windows floating with this:

``` emacs-lisp
(setq exwm-manage-configurations
        '(((equal exwm-class-name "keepassxc")
           floating t
           floating-mode-line nil
           width 0.6
           height 0.8)))
```

**Comment by djrmarques** [comment]
This worked perfectly. I was having a hard time figuring out the functions to use. 

Thanks!
