### ISSUE TITLE
dmenu_run isn't launchable via Super-& (start-process-shell-command)

### ISSUE THREAD

**Issue by a-schaefers** [ch11ng/exwm#454]
Hi,

dmenu_run launches fine when it is spawned by an existing window e.g. from shell, ansi-term, or even when it is called via the suckless surf web browser.

dmenu_run is failing (not visibly appearing on the screen at least) when called via start-process-shell-command or when attempting to launch via Super-&.

Another user in #emacs on freenode has confirmed the same exact behavior.

This is driving me bonkers today and i'm at my wits end. Please help.

**Comment by a-schaefers** [comment]
<Misha_B> has said in irc also,

> whats interesting is that doing `rofi -show run` brings the window
>           up, but doesn't seem to execute any program.

**Comment by a-schaefers** [comment]
I have now found that using (shell-command-to-string "dmenu_run") will pop up the dmenu, but after dmenu launches a program, the program "hangs" (cursor stays spinning) until I hit C-g, which then will, in the case of surf browser, launch a normal surf browser session-- but in the case of qbittorrent, it never opens in a visible window, and emacs stays completely frozen, until you switch to another tty and kill the qbittorrent process. So, things are definitely not right here. I hope these descriptions are helpful.

**Comment by ch11ng** [comment]
'dmenu_run' is a shell script that starts 'dmenu' in background.  I'm not sure why it does this that way but it seems you should call it synchronously, i.e. `(call-process-shell-command "dmenu_run")`.

**Comment by a-schaefers** [comment]
works like a charm! thank you for all you have done here!

**Comment by franburstall** [comment]
For the record, use of `call-process-shell-command` also solves the issue with rofi alluded to [above](https://github.com/ch11ng/exwm/issues/454#issuecomment-404976045).  Very nice!
