### ISSUE TITLE
Can't open android-studio

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#455]
1. download https://developer.android.com/studio/#downloads
2. unzip
3. go to bin/ directory
4. execute `./studio.sh`

you get:

![2018-07-17-163241_961x788_scrot](https://user-images.githubusercontent.com/217543/42824054-4b669f2e-89df-11e8-8e4d-db9373939251.png)

**Comment by sarg** [comment]
Probably you know this, but do you have these lines somewhere in your `Xsession` ?
```
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
```

I am using Intellij IDEA daily without a problem, which android studio is based upon.

**Comment by DamienCassou** [comment]
I didn't know and that fixes my problem. Sorry for not having searched a bit more.

**Comment by DamienCassou** [comment]
Thank you very much @sarg
