### ISSUE TITLE
Signature on the last ELPA version fails validation

### ISSUE THREAD

**Issue by Neku** [ch11ng/exwm#457]

**Comment by ch11ng** [comment]
Tested on Emacs 25/26/master and all seem working.  Which version of Emacs are you using?

**Comment by Neku** [comment]
I'm on the latest version on archlinux with spacemacs.

**Comment by ch11ng** [comment]
GNU ELPA packages are signed by the packaging server automatically.  If security is not an issue, then you may want to disable `package-check-signature` for the moment.

**Comment by medranocalvo** [comment]
@Neku, thank you for reporting.  This was possibly a glitch.  If it persists, please bring it up on emacs-devel.  Feel free to reopen if you think there's something we can do about it.
