### ISSUE TITLE
defun interactive to launch window

### ISSUE THREAD

**Issue by brettgilio** [ch11ng/exwm#459]
Hi, I could not find a related issue on this. It is not a bug, but rather an inquiry as to how to achieve a certain goal.

For regular applications I use, I would like to be able to defun them in my emacs config and be able to initiate them using M-x.

Any ideas how I could achieve this? I came across the realization there is probably an exwm-way to do this, as just using the emacs shell command function causes emacs to freeze when using exwm.

**Comment by imarko** [comment]
The wiki hints at this in the bootstrap section: https://github.com/ch11ng/exwm/wiki#bootstrap

The default config gives you this:
```
  ;; 's-&': Launch application
  (exwm-input-set-key (kbd "s-&")
                      (lambda (command)
                        (interactive (list (read-shell-command "$ ")))
                        (start-process-shell-command command nil command)))
```

programmatically you would use start-process-shell-command like in the above. In my personal config I use some helpers like this:

```
(defun my-quiet-run (command)
  (interactive (list (read-shell-command "$ ")))
  (start-process-shell-command command nil command))

(defun my-run-or-raise (cmd buffer-name)
  (let ((buf (get-buffer buffer-name)))
    (if buf
        (switch-to-buffer buf)
      (my-quiet-run cmd))))

(defun my-chromium ()
  (interactive)
  (my-run-or-raise "chromium" "Chromium"))

(exwm-input-set-key (kbd "s-b") #'my-chromium)
```

**Comment by ch11ng** [comment]
Just as @imarko had demonstrated, you only need to start processes asynchronously.

**Comment by medranocalvo** [comment]
This seems resolved.  @brettgilio, please reopen if you still find difficulties.
