### ISSUE TITLE
Keys are not grabbed when pointer is outside the GUI window

### ISSUE THREAD

**Issue by jvshahid** [ch11ng/exwm#462]
I am running into an issue when I have the frame split vertically where the left side has a GUI application running, for example chrome, and the right side has an Emacs buffer. If chrome has the input focus but the pointer is outside chrome's window and on the Emacs buffer (the parent frame if I understand correctly) then all keyboard events are not captured by EXWM. This means that `s-0,1,2` as well as keyboard simulation don't work. Instead, all key events are sent directly to chrome. My understanding is that this is a result of using passive grabs which require the pointer to be inside the child window. This is slightly annoying if i want my workflow to be entirely keyboard driven without having to move the pointer around.

- Is my understanding correct ?
- Is there a workaround ? 
- Would using active grabs solve this problem ? I am pretty sure there is a reason for not using them but was wondering to hear your thoughts.

**Comment by ch11ng** [comment]
No, that is not by design and has nothing to do with passive/active grabbing.  Probably something is misconfigured.  Please try the latest release with a minimal configuration and report back if this issue persists.

**Comment by jvshahid** [comment]
Yes, you are absolutely right. It looks like git was pulling from https://github.com/emacsmirror/exwm instead of this repo. I fixed the remote url and pulled and this seems to have fixed the issue I described above. It looks like something changed between commimt 0680be104f9394e39dd55b5c4e33b9b7e4e77926 and aebcb0344f18b1aa284a432811175fde2d2feae5 that fixed the issue.
