### ISSUE TITLE
X windows disappear on multiple monitors

### ISSUE THREAD

**Issue by dakra** [ch11ng/exwm#463]
Since the last commit, when you have multiple Monitors
and monitor A shows an X11 app and then you
focus monitor B and change to or create an X app,
the app in monitor A disappears. Modeline still
shows the correct app and just focusing that monitor again
makes the X window reappear.

**Comment by rayslava** [comment]
In my case it also disappears not only on X window create, but on opening helm M-x buffer as well.

**Comment by ch11ng** [comment]
I removed a necessary check in the last commit.  I've added it back in e6527227b387d08146963613ada37022ddf33d80.

**Comment by dakra** [comment]
Last commit fixed it. Thanks.
