### ISSUE TITLE
Closing external programs kills current workspace

### ISSUE THREAD

**Issue by j3kyl** [ch11ng/exwm#464]
Hey,  

As I close a random external program as MPV or Firefox the current workspace is killed, remaining only the residual workspaces.

Eg: I set 3 workspaces, as I finished watching a video on MPV (workspace 0) it closes, as usual,  by itself and the current workspace 0 is killled altogether!

Then now I have only 2 workspaces ( the former workspace 1 and worskpace 2).

Is it an EXWM behavior or did I set something on Emacs that is influencing this weird behavior!

It did not happen back there in my former PC gaming, but it does now on my Lenovo Thinkpad t430.

**EXWM**: https://gitlab.com/j3kyl/dots/blob/master/gnu/.emacs.d/modes/init-exwm.el
**INIT**: https://gitlab.com/j3kyl/dots/blob/master/gnu/.emacs.d/init.el 

Emacs 26.1.50
Debian SID
Lenovo T430

Thanks!

**Comment by j3kyl** [comment]
Wow, my bad...yep...only fullscreen! Lemme try!

**Comment by medranocalvo** [comment]
ELPA only updates with new releases.  Please, test it before the release.

**Comment by j3kyl** [comment]
oh, so Elpa is like  melpa stable. Ok not in a hurry anyway!

**Comment by medranocalvo** [comment]
The new release is out (0.20).  Please, reopen if you still find issues.
