### ISSUE TITLE
exwm-input--fake-key appears to be broken?

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#465]
It seems something has changed in one of the latest updates. The following thing doesn't seem to be working anymore

```
(exwm-input--fake-key ?\C-v)
```

**Comment by ch11ng** [comment]
It's unlikely an XELB issue.  Could it be 6be729847e78576df599cbf70512e3f9e436114b?

**Comment by agzam** [comment]
I'm not sure. I've been trying to get to the bottom of this, but it seems to be too complicated for me. I don't understand how it works within `exwm-input-send-next-key` but it doesn't when called directly.

**Comment by agzam** [comment]
as it looks - it seems to be a timing issue. I have found a workaround for exwm-edit: https://github.com/agzam/exwm-edit/blob/master/exwm-edit.el#L72 I guess we can close this now.

**Comment by ch11ng** [comment]
I forgot to mention `exwm-input--set-focus` is not synchronous (it was in some circumstances before).  You may use `(xcb:aux:sync exwm--connection)` to force that.

**Comment by agzam** [comment]
Thank you for your help @ch11ng  I think this can be closed now
