### ISSUE TITLE
X windows turn white on layout change

### ISSUE THREAD

**Issue by ransomts** [ch11ng/exwm#468]
This is on dual monitors. When I change the layout on one monitor, any X windows on the other turn white. Clicking the blank window or switching from and to the workspace on the other screen will redisplay the window but that is very inconvenient. 

I jumped a couple commits to the latest so I can try to figure out which commit caused it. I experience the issue in #425 as well. I see you recently put up some debug instructions so I'll be trying to gather that as well.

**Comment by medranocalvo** [comment]
I believe #469 might fix this issue. Please test it.

**Comment by ransomts** [comment]
Yes that did fix the issue. Well done :1st_place_medal:

**Comment by medranocalvo** [comment]
My pleasure.
