### ISSUE TITLE
exwm-input-set-key doesn't work with "super" and "shift"

### ISSUE THREAD

**Issue by pmiddend** [ch11ng/exwm#474]
I'm trying to bind the following:

```
(exwm-input-set-key (kbd "s-S-p") (lambda (command)
                      (interactive (list (read-shell-command "$ ")))
                      (start-process-shell-command command nil command)))
```

This doesn't work. `kbd "s-p"` does work. Is this a bug in `exwm-input-set-key` or some emacs constraint?

**Comment by ch11ng** [comment]
It should be <kbd>s-P</kbd> I think.  You may use `(read-key)` to verify that.

**Comment by pmiddend** [comment]
Ah yes, that's it. Thanks!
