### ISSUE TITLE
`exwm-workspace-warp-cursor` set on leaves X windows read-only

### ISSUE THREAD

**Issue by WJCFerguson** [ch11ng/exwm#475]
If I have `exwm-workspace-warp-cursor` set to true, and switch between workspaces in the same monitor to one with an X-window currently selected, then that window is read-only.  To get it back to accepting keystrokes I have to move out of it and back in, or some similar movement to freshly select the window.

**Comment by WJCFerguson** [comment]
I do have multiple monitors, but do not use focus-follows-mouse.

**Comment by medranocalvo** [comment]
Indeed, you mention it in #456.  Are they the same issue?

**Comment by WJCFerguson** [comment]
Ah - apologies, vacation emptied my brain and this is a duplicate issue.

**Comment by medranocalvo** [comment]
Let's close this one, then.
