### ISSUE TITLE
[question] I need to simulate S-spc

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#480]
I need to simulate S-SPC (Win+Space) for example on `C-a`, how do I do this? This is not working:

```
([?\C-a] . [\s-\? ])
([?\C-a] . [\s-\spc])
``` 
I'm also struggling to simulate things like `s-[` or `s-]` or basically anything that involves `super` key

Oh... is it because you can't simulate pressing the keys "outside of exwm app context"? For example if I set `(exwm-input-set-key (kbd "M-x") #'helm-M-x)` I cannot simulate `M-x` via other key? e.g. If I want to be able to do `M-x` from browser but by pressing `C-a`:  `([?\C-a] . [\M-x])` won't work?

**Comment by ch11ng** [comment]
It should be `[?\s-\s]` for <kbd>super-SPC</kbd>.  `[` and `]` should be escaped BTW.  If you find it difficult you may give the Customize interface of `exwm-input-simulation-keys` a try.

**Comment by agzam** [comment]
I guess I should've explained what I am trying to achieve. In a EXWM app buffer I want to simulate a key that would do something that's controlled by Emacs, e.g.: if I have something like: 

    (exwm-input-set-key (kbd "s-b") #'helm-mini)
    (setq exwm-input-simulation-keys([?\C-a] . [\s-b]))

See? I'm trying to make `C-a` in exwm buffer to work as `s-b`. But that doesn't work.

**Comment by medranocalvo** [comment]
Is it crucial that the binding invokes an EXWM-global binding (`exwm-input-set-key`)?

Otherwise, I'm thinking that perhaps https://github.com/ch11ng/exwm/issues/426#issuecomment-420322308 could help.  You could have a buffer-local binding for that app buffer that invokes the emacs command:

```elisp
(with-current-buffer ???
  (use-local-map (copy-keymap exwm-mode-map))
  (local-set-key (kbd "C-a") #'helm-mini))
```

**Comment by ch11ng** [comment]
@medranocalvo's solution is the way to go and you probably want to add it to `exwm-manage-finish-hook`.

**Comment by medranocalvo** [comment]
@agzam, have you had a chance to test my suggestion?

**Comment by agzam** [comment]
> Is it crucial that the binding invokes an EXWM-global binding (exwm-input-set-key)?

@medranocalvo ehmm... otherwise how do I bind it to work from exwm buffer?
Here's what I wanted to do:

- I use Zathura for PDFs and it's awesome with EXWM it feels like you never left Emacs
- I also use Spacemacs. In Spacemacs - `SPC` key have special meaning (when you're not in Insert mode - i.e. not typing). But obviously `SPC` cannot be used in EXWM buffers, I had to add additional binding: `s-SPC`
- So I thought: what if I can make `SPC` to work in Zathura just like in any other (non EXWM buffer), because visually it is almost indistinguishable from any other (non-EXWM) buffer, I even set Zathura's color theme to match with my Emacs colors.
- I cannot bind `SPC` in Zathura to emulate `s-SPC`, so I maybe I can make it via EXWM? Would it be possible to use `exwm-input-set-local-simulation-keys` in such way that pressing `SPC` would emulate `s-SPC`? Unfortunately I was unable...

**Comment by medranocalvo** [comment]
Try playing with the following:

```elisp
(add-hook 'exwm-manage-finish-hook
    (lambda () (use-local-map (copy-keymap (current-local-map)))
                (local-set-key (kbd "s-SPC") (lookup-key global-map (kbd "s-SPC")))))
```

Let me know if something's not clear.

**Comment by medranocalvo** [comment]
@agzam, have you had a chance to test the above snippet?
