### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#481]
Not sure what's updated but things in `master` are broken for me and I see these in `*Warnings*`:

```
Error (use-package): exwm/:catch: Cannot open load file: No such file or directory, xcb-debug
Error (use-package): exwm-edit/:catch: Cannot open load file: No such file or directory, xcb-debug
Error (use-package): helm-exwm/:catch: Cannot open load file: No such file or directory, xcb-debug

```

**Comment by agzam** [comment]
I had to I had to roll-back to 6978c1f45c4d72edab2440faf93fb917afe356ec seems to be working...

**Comment by medranocalvo** [comment]
This issue should be solved by upgrading XELB to the latest unreleased version https://github.com/ch11ng/xelb/commit/b700406b2ece067d6d6f4fdd51a6bd29cc7ef3a9.  EXWM and XELB are often developed in lockstep, so they should both be upgraded at once.  By the way, thanks for testing pre-releases.

**Comment by agzam** [comment]
Thank you. It looks fine now
