### ISSUE TITLE
Crash at boot when default shell is xonsh and login is from SDDM

### ISSUE THREAD

**Issue by Titan-C** [ch11ng/exwm#482]
I'm experimenting with new setups. Thanks for EXWM it looks great. I'm using Archlinux and Emacs 26.1

I followed the install instructions and everything works fine. As long as I keep my default shell to be zsh(I didn't try with bash, I haven't used in a long time). But when I decided to set xonsh as my default shell I could not start EXWM after login from SDDM. What happens is, login on SDDM -> emacs opens -> start loading packages -> emacs freezes with message : 
```
Error in process filter: [XELB] Connection failed: No protocol specified
```
Keyboard and mouse still respond, and I can `ALT+CTRL+F2` to another virtual terminal. There Emacs is running on 100% CPU. After killing it, it logs out.

It is strange to me that login from the text virtual terminal and then `startx` does not give me the issue. Regardless if I do it from a zsh or xonsh. I looked at the issues #33 and and #2. Adding `xhost +` to the `.xinitrc` has no influence. It crashes from the SDDM login too and it plays no role from the terminal launch with `startx`

**Comment by medranocalvo** [comment]
The error message indicates that EXWM cannot connect to the X server; possibly related to the `DISPLAY` environment variable.

Is `.xinitrc` being evaluated by `xonsh`?

Please, add the following to your .xinitrc and run it under each of your shells.  Post the `SHELL` and `DISPLAY` for each of them and analyze the environment for relevant differences.

```bash
date >>/tmp/myenv
echo "SHELL=$SHELL" >>/tmp/myenv
echo "DISPLAY=$DISPLAY" >>/tmp/myenv
env >>/tmp/myenv
```

**Comment by medranocalvo** [comment]
@Titan-C, have you had a chance to try my suggestions?

**Comment by medranocalvo** [comment]
Please reopen once you try the suggestions.
