### ISSUE TITLE
Setting exwm-workspace-minibuffer-position to 'top breaks minibuffer

### ISSUE THREAD

**Issue by pjones** [ch11ng/exwm#489]
I really want to use this neat feature of EXWM but haven't had any luck getting it to work.  In both Emacs 25 and 26 setting `exwm-workspace-minibuffer-position` to `'top` causes an error when the minibuffer needs to grow beyond a single row of text.  I get an error messages something like "can't resize the root window of frame."

I can't recall the exact error message because Emacs becomes unusable without a minibuffer and I have to drop down to the virtual console and reboot.

Any suggestions?

**Comment by medranocalvo** [comment]
Thank you for reporting.

It seems to be working fine here, at least when applying #484.  Which version of EXWM and XELB are you using?  Could you test whether #484?

As for the error message, perhaps taking a photo before rebooting and posting it here could help.

**Comment by pjones** [comment]
@medranocalvo applying #484 did not fix my issue.  I'm using the latest commits of both EXWM and XELB.

The problem is that ivy tries to resize the minibuffer window which isn't allowed because it already occupies the full height of the frame.  I captured a debug trace:

```
Debugger entered--Lisp error: (error "Cannot resize the root window of a frame")
  signal(error ("Cannot resize the root window of a frame"))
  error("Cannot resize the root window of a frame")
  window-resize(#<window 5 on  *Minibuf-1*> 4)
  set-window-text-height(#<window 5 on  *Minibuf-1*> 5)
  ivy--minibuffer-setup()
  #f(compiled-function () #<bytecode 0x1316b9d>)()
  read-from-minibuffer("Find file: " nil (keymap keymap (12 . ivy-backward-delete-char) (3 keymap (19 . ivy-rotate-sort) (1 . ivy-toggle-ignore) (15 . ivy-occur)) (67108903 . ivy-avy) (33554464 . ivy-restrict-to-matches) (15 . hydra-ivy/body) (22 . ivy-scroll-up-command) (prior . ivy-scroll-down-command) (next . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-forward-char) (32 . self-insert-command) (18 . ivy-reverse-i-search) (19 . ivy-next-line-or-history) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-whole-line . ivy-kill-whole-line) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-partial-or-done) (10 . ivy-alt-done) (27 keymap (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . ivy-dispatching-done) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (mouse-3 . ivy-mouse-dispatching-done) (mouse-1 . ivy-mouse-done) (down-mouse-1 . ignore) (13 . ivy-done)) nil file-name-history)
  ivy-read("Find file: " read-file-name-internal :predicate file-exists-p :require-match confirm-after-completion :initial-input "~/" :preselect "~/" :def "~/" :history file-name-history :keymap nil :sort t :dynamic-collection nil :caller read-file-name-internal)
  ivy-completing-read("Find file: " read-file-name-internal file-exists-p confirm-after-completion "~/" file-name-history "~/" nil)
  completing-read("Find file: " read-file-name-internal file-exists-p confirm-after-completion "~/" file-name-history "~/")
  read-file-name-default("Find file: " nil "~/" confirm-after-completion nil nil)
  read-file-name("Find file: " nil "~/" confirm-after-completion)
  find-file-read-args("Find file: " confirm-after-completion)
  byte-code("\300\301\302 \"\207" [find-file-read-args "Find file: " confirm-nonexistent-file-or-buffer] 3)
  call-interactively(find-file)
  eval((call-interactively 'find-file) nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

It seems like I need some way to dynamically resize the frame.  If you have ivy working I'd love to know how.

**Comment by ch11ng** [comment]
> It seems like I need some way to dynamically resize the frame. If you have ivy working I'd love to know how.

In EXWM we have a dedicated function (`exwm-workspace--resize-minibuffer-frame`) to do this, and it's automatically called whenever there is a change in the content of the minibuffer / echo area.  Perhaps we can skip that part in ivy?

**Comment by pjones** [comment]
@ch11ng That's good news.

I'll work with Ivy to see if I can get their code fixed.

Thank you again!

**Comment by medranocalvo** [comment]
@pjones, `ivy` works all right here with `(setq exwm-workspace-minibuffer-position 'top)`.  This is only after light testing.

[... time passes ...]

The issue appears when `(setq ivy-fixed-height-minibuffer t)` and one is using a minibuffer-only frame.  Please report to `ivy`.

**Comment by pjones** [comment]
Yep, and I have `(ivy-fixed-height-minibuffer t)` in my config too.  I'll open an issue with Ivy.

Thanks @medranocalvo.
