### ISSUE TITLE
exwm-manage-configurations can't see Chrome app names

### ISSUE THREAD

**Issue by benley** [ch11ng/exwm#490]
I think this is very similar to https://github.com/xmonad/xmonad/issues/31, wherein browser windows don't have their WM_NAME property set until after the window is created, so the exwm-manage-configurations hook can't see them.

One workaround I've found is to match on the window's `exwm-instance-name`, which is the chrome web store app id (e.g. `crx_gaedmjdfmmahhbjefcbgaolhhanlaolb` for the Authy app), but those IDs sometimes change unexpectedly when chromium extensions get updated.

To reiterate, this doesn't seem like it can work:

```lisp
(setq exwm-manage-configurations
  '(((equal exwm-title "Authy") floating t))))
```

This works, but is awkward and may break with extension updates:
```lisp
(setq exwm-manage-configurations
  '(((equal exwm-instance-name "crx_gaedmjdfmmahhbjefcbgaolhhanlaolb") floating t)))
```

Is there another reasonable way to handle browser-based apps?

**Comment by ch11ng** [comment]
Instead of using ``, you can give `exwm-update-title-hook` a try.  This hook gets called every time there is a change in `_NET_WM_NAME` or `WM_NAME `.

**Comment by benley** [comment]
That does the trick, thanks.  I've actually ended up using exwm-manage-configurations matching on `exwm-instance-name`, even though the extension IDs are a bit annoying to work with, because it makes exwm handle the windows a bit faster.
