### ISSUE TITLE
After window closes, status bar is gone

### ISSUE THREAD

**Issue by WorldsEndless** [ch11ng/exwm#492]
I play a game (Age of Wonders 3) in Wine, which captures a full screen (symptom: even when connected to multiple monitors, once the game is going, my mouse cursor can't move beyond the game window. Not a real problem, though.) Upon closing the game it kills whatever workspace it's in -- and with it goes away my exwm status bar, including my nm-applet icon, vpn icon, telegram icon, etc. Other than restarting exwm I don't know how to get this back. I've tried `(exwm-workspace--update-workareas)` but it doesn't bring my status bar back. Neither does `(exwm-systemtray--refresh)`. Any recommendations other than restarting exwm?

**Comment by ch11ng** [comment]
Hi, I think the fix for this issue is already in release 0.20 .  Please update EXWM and try again.

**Comment by medranocalvo** [comment]
@WorldsEndless, closing this issue.  Please reopen if you still encounter problems.
