### ISSUE TITLE
Every X11 buffer is Read-only

### ISSUE THREAD

**Issue by watkinsr** [ch11ng/exwm#493]
Usual bug. Switch to a given workspace with an X11 buffer. 

Presented with funcall-interactively: Buffer is read-only: #<buffer Firefox>

Using helm-M-x solves the issue and stops it.

Any ideas? I'm using the latest xelb/exwm

**Comment by ch11ng** [comment]
I haven't encountered this problem recently.  Could launch EXWM with `emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ --eval "(require 'exwm)" --eval "(exwm-init)"` and see if this issue persists? If not, please try commenting out some lines of your `~/.emacs` and see if there is any conflicting configuration.

**Comment by watkinsr** [comment]
> I haven't encountered this problem recently. Could launch EXWM with `emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ --eval "(require 'exwm)" --eval "(exwm-init)"` and see if this issue persists? If not, please try commenting out some lines of your `~/.emacs` and see if there is any conflicting configuration.

Sorry but I have moved to stumpwm for the time being so it makes it very difficult to report further.

**Comment by medranocalvo** [comment]
Closing then.  Please reopen if you find this again.
