### ISSUE TITLE
Fix for issue #422 is causing floating windows to be hidden behind other windows

### ISSUE THREAD

**Issue by jvshahid** [ch11ng/exwm#496]
I recently pulled master and I ran into an issue where the following happen:

1. Given a dual monitor setup
2. Start some program in workspace `1` in my case that's the bottom monitor (let's say `paman`)
3. Start another program in workspace `0` in my case that's the top monitor (we can also use `paman`). This window will be called `Paman<2>`
4. Toggle floating of `Paman<2>` to make it floating in workspace `0`
5. Burry `Paman` in workspace `1`
6. Switch to `Paman` to make the window visible again in workspace `1`
7. Try to move `Paman<2>` from workspace `0` to workspace `1` 

Before the changes in https://github.com/ch11ng/exwm/pull/476 the floating `Paman<2>` will continue to be visible after moving it to workspace `1` on top of the fullscreen `Paman`. 

I'm guessing this is happening because the changes in #476 always move the window to the top of the stack on MapNotify, but I'm not 100% sure. Let me know if there are more information I can provide.

**Comment by medranocalvo** [comment]
Thank you for the detailed report.

I can reproduce with a single monitor, just by switching workspaces:

1. Launch XTerm and make it floating.
2. Launch XTerm again.
3. Switch to other workspace.
4. Switch back to the original.

_The floating XTerm is covered by the tiled one._

---

There's another issue: in step 3 the floating window is visible in the other workspace; I think it should be confined to the one in which it was created.

---

One last question: how do you move the floating window to the other monitor?

---

I'll prepare a fix, but will take some time.

**Comment by jvshahid** [comment]
I move the pointer inside the window then hold the super key and left mouse button while moving the pointer.

**Comment by medranocalvo** [comment]
Ouch.  I doubt the code is prepared for such an action (I'm happy it works for you).  In any case, it is tangential to the reported issue.

**Comment by jvshahid** [comment]
To be honest, I don't ever move windows or even use floating windows. The only reason I brought this issue up is that we use [zoom](https://www.zoom.us/) for video conferencing. When I screen share zoom creates a tiny window to do a bunch of things related to the call (e.g. to stop sharing or end the call). 

That little zoom dialog/window is very interesting:

- it doesn't have any borders
- it is not tracked by EXWM in the buffer list!
- you don't even need to hold down the super key. you are able to move it by holding the left mouse button while moving it around

That dialog/window used to stay on top of the window stack the entire time. No matter how many times I switch windows it is always on top and visible.  That is not the case after the fix for #422. With current master switching to another window will hide that little window and it becomes really difficult to get it back.  Remember it is not in the buffer list. That means I cannot end the call or stop sharing without having to kill zoom. 

I am not sure if my explanation makes any difference, I should have explained my use case more carefully in the original bug report.

**Comment by medranocalvo** [comment]
Hello @jvshahid.  Thank you for your follow-up.  I don't have much time at the moment, will read more carefully in the near future and respond to you.

**Comment by jvshahid** [comment]
Sounds good. In the meantime, I reverted commit 6978c1f45c4d72edab2440faf93fb917afe356ec and everything seems to be working as epxected.

**Comment by ch11ng** [comment]
@medranocalvo A quick fix would be to pass `:sibling exwm--guide-window` in addition when configuring tiling X windows so they will stay just above the Emacs frame and won't obscure floating X windows.  I don't have XQuartz so I'm not sure if such fix would break it.

**Comment by medranocalvo** [comment]
@jvshahid, last commit d650159648e88ec4a67c126834cd24fed6e3fc24 (by @ch11ng) should help with this.  Could you test it?

**Comment by jvshahid** [comment]
I just tried master and it is totally broken.  In particular my multi
monitor setup doesn't work.  There is no frame in the laptop monitor
(bottom).  The frame on the external monitor (top) doesn't seem to be
scaled properly. The window splitter created by `C-x 3' is to the far
right instead of being centered.  The only commits that could have done
this are:

d650159 * master origin/master Fix wrong stacking order of tiling X windows
9dcfff5 * Expose `exwm-randr-refresh' public interface
e597ab4 * Add support for RandR 1.5 monitor
fec85bb * Select more sensible buffers after creating new windows

**Comment by ch11ng** [comment]
@jvshahid It sounds like EXWM treated the monitors as horizontally distributed.  Please run the following commands to see the RandR configuration in effect (and the value of `exwm-randr-workspace-output-plist`).

```shell
xrandr
xrandr --listmonitors
```

Also I've made some changes to this module today so make sure to update your local copy.

**Comment by jvshahid** [comment]
I just tried current master (commit: dc3b86d) and I am still seeing the
same result.

Below is the content of `exwm-randr-workspace-output-plist':

    exwm-randr-workspace-output-plist is a variable defined in ‘exwm-randr.el’.
    Its value is (0 "HDMI-1")
      This variable is an alias for ‘exwm-randr-workspace-monitor-plist’.
      This variable is obsolete since 27.1;
      use ‘exwm-randr-workspace-monitor-plist’ instead.

Which is set in my init.el:

    (require 'exwm-randr)
    (setq exwm-randr-workspace-monitor-plist '(0 "HDMI-1"))
    (add-hook 'exwm-randr-screen-change-hook
              (lambda ()
                (start-process-shell-command
                 ;; xrandr --output <something> --same-as <other-thing> for mirroring
                 "xrandr" nil "xrandr --output HDMI-1 --above LVDS-1 --auto")))
    (exwm-randr-enable)

And the output of those commands:

    $ xrandr
    Screen 0: minimum 320 x 200, current 1920 x 1968, maximum 8192 x 8192
    LVDS-1 connected 1366x768+0+1200 (normal left inverted right x axis y axis) 277mm x 156mm
       1366x768      60.02*+
       1360x768      59.80    59.96
       1024x768      60.04    60.00
       960x720       60.00
       928x696       60.05
       896x672       60.01
       960x600       60.00
       960x540       59.99
       800x600       60.00    60.32    56.25
       840x525       60.01    59.88
       800x512       60.17
       700x525       59.98
       640x512       60.02
       720x450       59.89
       640x480       60.00    59.94
       680x384       59.80    59.96
       576x432       60.06
       512x384       60.00
       400x300       60.32    56.34
       320x240       60.05
    VGA-1 disconnected (normal left inverted right x axis y axis)
    HDMI-1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
       1920x1200     59.95*+
       1920x1080     60.00    50.00    59.94    59.93
       1920x1080i    60.00    50.00    59.94
       1600x1200     60.00
       1680x1050     59.88
       1280x1024     75.02    60.02
       1440x900      59.90
       1280x800      59.91
       1280x720      60.00    50.00    59.94
       1024x768      75.03    70.07    60.00
       800x600       72.19    75.00    60.32
       720x576       50.00
       720x480       60.00    59.94
       640x480       75.00    72.81    66.67    60.00    59.94
       720x400       70.08
    DP-1 disconnected (normal left inverted right x axis y axis)
    HDMI-2 disconnected (normal left inverted right x axis y axis)
    HDMI-3 disconnected (normal left inverted right x axis y axis)
    DP-2 disconnected (normal left inverted right x axis y axis)
    DP-3 disconnected (normal left inverted right x axis y axis)
    $ xrandr --listmonitors
    Monitors: 2
     0: +LVDS-1 1366/277x768/156+0+1200  LVDS-1
     1: +HDMI-1 1920/518x1200/324+0+0  HDMI-1

**Comment by jvshahid** [comment]
Quick update.  After sending my previous reply, I noticed that the
output of `xrandr' doesn't have a primary monitor.  Adding the following
to my init.el file does the trick but I don't understand why EXWM
behavior changed:

    (start-process-shell-command
     ;; xrandr --output <something> --same-as <other-thing> for mirroring
     "xrandr" nil "xrandr --output LVDS-1 --primary")

**Comment by jvshahid** [comment]
Forgot to mention that latest master fixes my issue.  Maybe we should address (or not) the primary monitor issue separately.

**Comment by ch11ng** [comment]
Indeed.  I've pushed 786c2b4f7d2e92f77746918b442419fa3b5794e5 to fix this.  Thanks for the report.
