### ISSUE TITLE
Leave full screen with exwm-layout-toggle-fullscreen result in keybinding loss

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#498]
I am using exwm 0.20.
To recreate the bug:
1. open xterm
2. make it fullscreen with exwm-layout-toggle-fullscreen (you need to bind it to a key)
3. run exwm-layout-toggle-fullscreen again
4. now keybindings such as C-x b for switching buffers are not working.

The test .emacs file is:

    (setq debug-on-error t)
    (require 'package)
    (require 'cl) ;remove-if is in cl library
    (require 'cl-lib)
    (setq package-enable-at-startup nil   ; To prevent initialising twice
    package-user-dir "~/.emacs.d/elpa/")
    (package-initialize)
    (require 'exwm)
    (require 'exwm-config)
    (setq exwm-debug-on t)
    (exwm-config-default)
    (exwm-input-set-key (kbd "C-s-<return>") #'exwm-layout-toggle-fullscreen)
    (define-key exwm-mode-map (kbd "s-SPC") #'exwm-floating-toggle-floating)
    (exwm-enable)

**Comment by medranocalvo** [comment]
We are aware of this issue (#494).  Please check whether the fix in #495 works as intended.

Thank you for reporting.
