### ISSUE TITLE
Recalling windows from other workspaces

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#50]
At the moment, windows (such as XTerm) must be explicitly moved (`exwm-workspace-move-window`) _to_ the workspace one wants it to be.  A more natural approach, more in line with the behavior of buffers, would be to be able to _recall_ them to the window one desires them to be.  In this manner, one would be able to <kbd>C-x b</kbd>, select XTerm, and have it appear in current window.

What do you think?

**Comment by pipcet** [comment]
Well, I think the main reason that doesn't work is the space-renaming of EXWM buffers. I've been switching buffers like this for a while on my master branch, I'm pretty sure. (I've disabled space-renaming and think it should be optional).

If you want to keep the space-renaming, it's probably best to write a new wrapper function around `(exwm-workspace-move-window exwm-workspace-current-index id)`?

**Comment by ch11ng** [comment]
Buffers in inactive workspaces are renamed to make their names starting with a space so that they are "hidden" from most commands. This makes each workspace isolated to some extent. The buffers can still be visible if you type a few characters in their names, but the current behavior is to switch to that corresponding workspaces. My suggestion is to either alter this current behavior or invent a new command (and a keybinding) to deal with this feature request.

**Comment by pipcet** [comment]
I don't understand the reasoning behind hiding them: we don't hide buffers that happen to be displayed in a different frame; rather, we put them at the end of the buffer list. Why should we handle client window buffers differently?

I think it would be best not to space-rename buffers on inactive workspaces, just to bury them (easy) or modify the buffer-menu code to show them in a different font, at the end of the buffer list, or not at all (hard).

**Comment by ch11ng** [comment]
> I don't understand the reasoning behind hiding them: we don't hide buffers that happen to be displayed in a different frame; rather, we put them at the end of the buffer list. Why should we handle client window buffers differently?

Because normal buffers are shared among all frames, whereas X windows (so as their corresponding buffers) are not; normal buffers can be thought as desktop widgets in this case. I think such behavior is coincident with most other window managers (and I think EWMH also implies it).

**Comment by pipcet** [comment]
Thanks, that makes it clearer.

I do wonder whether it's really the right thing to reset a "secondary" EXWM buffer to *scratch*, rather than displaying a "this X window is displayed somewhere else, click here to move it to this Emacs window" message. I think there might even be a possibility for a composition manager to make the X window display in two Emacs buffers simultaneously... Clearly this needs more thought, though.

**Comment by ch11ng** [comment]
> I do wonder whether it's really the right thing to reset a "secondary" EXWM buffer to *scratch*, rather than displaying a "this X window is displayed somewhere else, click here to move it to this Emacs window" message.

I think it'd be too intrusive, and if this buffer happens to be in the same workspace with that EXWM buffer, it is just unnecessary. It'd be better to use something like `(other-buffer)`, I think.

> I think there might even be a possibility for a composition manager to make the X window display in two Emacs buffers simultaneously... Clearly this needs more thought, though.

I don't know if it's technically possible here. It's also a challenge if two windows displaying one EXWM buffer are of different sizes.

Anyway, this issue is relatively easy to solve. It's just a matter of which scheme we should adopt.

**Comment by zevlg** [comment]
JFYI: In SXEmacsen xwem there are two commands:

H-x b  - switch to X window client (by name). It pops up frame where client lives and activates frame's window where client is attached to, so client become selected (aka focused)

H-x a - attach X window client (by name) to current frame's window.  It takes X window client and makes it belong to currently selected frame/window.  You call it recalling

The problem is that there is no easy way to clone X clients using X protocol

**Comment by ch11ng** [comment]
Thanks for the information, @zevlg. I also think we should make two commands to do these two different works. The current behavior of <kbd>C-x b</kbd> in EXWM is just like <kbd>H-x b</kbd> in xwem. Since <kbd>C-x b</kbd> is so commonly used, we will evaluate how it should behave and assign another keybinding for the other.

**Comment by ch11ng** [comment]
I've add a command `exwm-workspace-switch-to-window` for this purpose. You might bind a key sequence to try it. I don't make it the default behavior since it's a bit expensive.

**Comment by uu1101** [comment]
Hello,

Thank you very much!

I have played a little bit with the code.  The following version relies on Emacs 25 (due to `read-buffer`'s `PREDICATE` parameter), but seems much clearer.  It should be possible to hack something compatible with 24 relying on `completing-read`.

I think it could be improved by also allowing switching to any other buffer, and to any window in the same workspace.  In that case, it would be a complete replacement for `switch-to-buffer` (even though we may or may not want to have this switching behaviour by default).  What do you think?

By the way, thank you very much for sharing this great package, and for your continued efforts.

Best regards,
uu1101

~~~{.elisp}
(defun exwm-workspace-switch-to-window ()
  "Make the current Emacs window display another X window."
  (interactive)
  (let ((buffer (read-buffer "Switch to window: " nil t
                             (lambda (bufname)
                               (exwm--buffer->id
                                (cond
                                 ((listp bufname) (cdr bufname))
                                 (t (get-buffer bufname))))))))

    (when buffer
      (with-current-buffer buffer
        (when (and (eq major-mode 'exwm-mode)
                   (not (eq exwm--frame exwm-workspace--current)))
          (exwm-workspace-move-window exwm-workspace--current-index
                                      exwm--id))))))
~~~

**Comment by uu1101** [comment]
How about the following?

~~~{.elisp}
(defun exwm-workspace-switch-to-window ()
  "Make the current Emacs window display another X window."
  (interactive)
  (let ((buffer (read-buffer "Switch to window: " nil t
                             (lambda (candidate)
                               ;; True for visible buffer or a window
                               (let ((bufname (if (listp candidate)
                                                  (car candidate)
                                                candidate)))
                                 (or (/= ?\s (aref bufname 0))
                                     (exwm--buffer->id (if (listp candidate)
                                                           (cdr candidate)
                                                         (get-buffer candidate)))))))))
    (when buffer
      (with-current-buffer buffer
        (if (or (not (eq major-mode 'exwm-mode))
                (eq exwm--frame exwm-workspace--current))
            (switch-to-buffer buffer)
          (exwm-workspace-move-window exwm-workspace--current-index
                                      exwm--id))))))
~~~

**Comment by uu1101** [comment]
I'm not sure anymore the one above works.  In any case, the one below should work on 24, and allows `switch-to-` buffers, windows currently in other namespaces, or windows in current.

It has only been lightly tested.

~~~{.elisp}
(defun exwm-workspace-switch-to-window ()
  "Make the current Emacs window display another X window."
  (interactive)
  (let* ((collection (mapcar (lambda (buf) (cons (buffer-name buf) buf)) (buffer-list)))
         (buffer (completing-read "Switch to window: " collection
                                  (lambda (candidate)
                                    ;; True for visible buffer or a window
                                    (let ((bufname (if (listp candidate)
                                                       (car candidate)
                                                     candidate)))
                                      (or (/= ?\s (aref bufname 0))
                                          (exwm--buffer->id (if (listp candidate)
                                                                (cdr candidate)
                                                              (get-buffer candidate))))))
                 t nil)))
    (when buffer
      (with-current-buffer buffer
        (if (or (not (eq major-mode 'exwm-mode))
                (eq exwm--frame exwm-workspace--current))
            (switch-to-buffer buffer)
          (exwm-workspace-move-window exwm-workspace--current-index
                                      exwm--id))))))
~~~

**Comment by ch11ng** [comment]
I agree with you that we should make this feature more complete (perhaps some users will want to alter the behavior of <kbd>C-x b</kbd>). But I'm afraid we have to stick to `read-buffer` to provide more consistent behavior with e.g. `ido-mode`. Besides, the last argument to `read-buffer` is not regarded by `ido-mode` so I think we should avoid it. I'll fix it later.

**Comment by uu1101** [comment]
I see your point, and definitely agree.  With the change you introduced it is already a very nice replacement for `switch-to-buffer`, thank you!

In my view, the ideal arrangement is as follows:

- There is a defvar `exwm-hide-windows-other-workspaces` (probably not a good name), that controls whether windows in other workspaces are hidden in the workspace list.
- `exwm-layout--refresh` is improved to support getting the windows from other workspaces.  This means that:
  - now both `exwm-workspace-move-window` and `exwm-workspace-switch-to-window` can be implemented on top of the default `switch-to-window` functionality.
  - `exwm-workspace-switch-to-window` stops being so necessary, as regular `switch-to-buffer` can switch to other buffers (no matter the value of the above variable, as inputting a space as the first character of `switch-to-buffer` allows selecting invisible ones).

What do you think?

Best regards,
uu1101.

**Comment by ch11ng** [comment]
As for hiding `exwm-mode` buffers in other workspaces, my idea is that if we provide no isolation for workspaces, then there would be no difference to use just one single workspace. And I don't know whether my assumption is correct but I suppose users would rarely move X windows to other workspaces (or at least not as frequently as switching buffers). 

And your other proposal is large based on the inconsistent behavior of `switch-to-buffer` for `exwm-mode` and ordinary buffers, right? I really have no idea which scheme is better; indeed I never thought about it since I think users would never switch buffer this way. Perhaps we should introduce the workspace concept to those buffers, too, so that everything would be consistent. If you have good reason to prefer the other scheme, please show me that.

I should clarify that any implementation of moving an X window to other workspace can never be lightweight since it would consist of more works like reparenting. A merely call to `exwm-layout--refresh` is not enough.

Besides, I think I should discourage the use of `exwm-workspace-switch-to-window` as a replacement of `switch-to-buffer` (or whatever bound to <kbd>C-x b</kbd>) since it introduces many overheads; it should only be used when really needed.

Feel free to defend your ideas.

**Comment by uu1101** [comment]
Hello,

Thank you for your thoughtful response and thank you for inviting me to share my opinion.  Note that English is not my native language... please, take what follows with a grain of salt :-).

I like how windows are managed in Emacs.  I don't know whether it's just familiarity, but by now I find it natural.  Frames can be split into windows, each window can be occupied with a buffer.  To manage all of this there are some basic commands such as `switch-to-buffer`, `split-window-vertically`, `select-frame-by-name`, ...; on top of them more complex/featureful commands such as `window-configuration-to-register`, `winner-undo`, etc. and even third-party packages such as `ace-window`, Helm, what-have-you.  I would like EXWM to leverage all that.

When I first tried EXWM, my thought went like: "Oh! It's just like Emacs on a terminal, but with X windows as well.  Genius!".  Of course, common WM thingies are needed as well: floating windows, move to workspace, the pager, etc.  The point is whether to build a regular WM using Emacs, or to have an WM that behaves like Emacs —that _is_ Emacs— and can leverage the ecosystem around it.

> As for hiding exwm-mode buffers in other workspaces, my idea is that if we provide no isolation for workspaces, then there would be no difference to use just one single workspace. And I don't know whether my assumption is correct but I suppose users would rarely move X windows to other workspaces (or at least not as frequently as switching buffers).

Hmm... one is certainly not often switching those, but what about the initial configuration?  I would like to lay my X windows as easily as I lay my buffers.  With regards to the single workspace, note that terminal emacs works exactly like that: one single frame is shown at any time, one usually names its frames with `set-frame-name` and switches frames with `select-frame-by-name` (this is my workflow, at least). I configure each frame to show a couple of related buffers/shells/whatever.  I would love this kind of workflow with EXWM.

> And your other proposal is large based on the inconsistent behavior of switch-to-buffer for exwm-mode and ordinary buffers, right? I really have no idea which scheme is better; indeed I never thought about it since I think users would never switch buffer this way. Perhaps we should introduce the workspace concept to those buffers, too, so that everything would be consistent. If you have good reason to prefer the other scheme, please show me that.

I'm attaching a demo patch at the end that demonstrates what I referring to.

> I should clarify that any implementation of moving an X window to other workspace can never be lightweight since it would consist of more works like reparenting. A merely call to exwm-layout--refresh is not enough.

Yes, it is not lightweight, but switching buffers should not be such a common operation anyway, as discussed earlier.

> Besides, I think I should discourage the use of exwm-workspace-switch-to-window as a replacement of switch-to-buffer (or whatever bound to C-x b) since it introduces many overheads; it should only be used when really needed.

I'm guess you refer to the overhead of renaming.  I agree it's not nice.  The patch below makes `switch-to-buffer` able to switch `exwm-mode` buffers as well (along with their associated X windows).  Note that the default behaviour of switch-to-buffer when called interactively is to show a list of visible buffers (those not starting with space, as you know), but invisible buffers can be selected as well if one types an space first.  This allows best of both worlds, would I say: you get not to see `exwm-mode` buffers from other workspaces, and I get the chance to `switch-to-` them if I need to.  Please, try it out if you find the time.  Note that regular `switch-to-buffer` needs to be used, it seems that `ido` does not allow selecting the invisible ones (with Helm, pressing <kbd>C-c a</kbd> is needed to see them).

Note that I'm not proposing the patch _as-is_ and that it has been only lightly tested.

~~~{.patch}
diff --git i/exwm-layout.el w/exwm-layout.el
index 27533a5..d7e0301 100644
--- i/exwm-layout.el
+++ w/exwm-layout.el
@@ -227,13 +227,25 @@
       (dolist (pair exwm--id-buffer-alist)
         (with-current-buffer (cdr pair)
           ;; Exclude windows on other workspaces and floating frames
-          (when (and (eq frame exwm--frame) (not exwm--floating-frame))
+          (when (not exwm--floating-frame)
             (setq windows (get-buffer-window-list (current-buffer) 0))
+            ;; Loop through windows in selected workspace:
+            ;; - If exwm-mode buffer not shown in this workspace -> hide window.
+            ;; - If exwm-mode buffer shown in this workspace -> reparent window
+            ;;   here if needed, show window and hide exwm-buffer in all others.
             (if (not windows)
-                (exwm-layout--hide exwm--id)
-              (exwm-layout--show exwm--id (car windows))
-              (dolist (i (cdr windows))
-                (set-window-buffer i placeholder))))))
+                (when (eq frame exwm--frame)
+                  (exwm-layout--hide exwm--id))
+              (let ((window (car windows)))
+                ;; Reparent to this workspace if needed.
+                (when (not (eq frame exwm--frame))
+                  (exwm-workspace-move-window (cl-position frame exwm-workspace--list)
+                                              exwm--id))
+                (exwm-layout--show exwm--id window)
+                ;; Hide it everywhere else.
+                (dolist (i (get-buffer-window-list (current-buffer) 0 t))
+                  (when (not (eq i window))
+                    (set-window-buffer i placeholder))))))))
       ;; Make sure windows floating / on other workspaces are excluded
       (dolist (window (window-list frame 0))
         (with-current-buffer (window-buffer window)
~~~

**Comment by ch11ng** [comment]
Since it's really hard to decide which is the appropriate  response after users select ignored (i.e. invisible) buffers, I think I should implement both and let users to choose between them: one is to attach the X window to current workspace, and the other is to switch to the workspace the X window is in. `exwm-workspace-switch-to-window`, though should be deprecated, would still be required since it's not easy to switch to an ignored buffer in most cases (e.g. one need to type an extra space after invoking `switch-to-buffer` or press <kbd>C-a</kbd> after `ido-switch-buffer`, let alone other commands may not come with such toggle), and more importantly most users are perhaps not aware of it.

BTW, do you still prefer to showing buffers in other workspaces? It'd be another story then.

**Comment by uu1101** [comment]
Hello,

Hmm, I see your point.  Personally, I think the behaviour of `switch-to-buffer` should be preserved.  What you describe is more akin to the following:

~~~{.elisp}
(defun exwm-select-buffer-window (buffer-or-name)
  (interactive
   (list (read-buffer-to-switch "buffer: ")))
  (let* ((w (get-buffer-window buffer-or-name t))
         (f (window-frame w)))
    (select-frame-set-input-focus f)
    (select-window w)))
~~~

There seems to be no command like that in regular emacs (somewhat surprisingly), but it definitely makes sense for EXWM.

With regards to `exwm-workspace-switch-to-window`, yes, I think it should be provided as a separate command as well.  Speaking of that, we should really really establish some nomenclature to differentiate between Emacs windows and X windows, both when talking and in command names, or it will get confusing pretty soon.  I propose _window_ vs. _x-window_, or _window_ vs. _x-client_.

> BTW, do you still prefer to showing buffers in other workspaces? It'd be another story then.

Given the ability to reach them by pressing space (or <kbd>C-a</kbd>) it's not that important to me.  If it were configurable I would personally set it to show everything in any workspace.

**Comment by ch11ng** [comment]
Well, apparently these two behaviors have puzzled some of you. I'll leave the freedom to users to decide whether buffers on other workspaces should be hidden and how to handle `switch-to-buffer`.

**Comment by ch11ng** [comment]
I've just added two new variables to customize these two behaviors: one is `exwm-workspace-show-all-buffers` to allow showing buffers on all workspaces, and the other is `exwm-layout-show-all-buffers` to allow moving an X window by switching to its buffer. I have not documented them yet. Please report if there're something missing.

**Comment by uu1101** [comment]
Wonderful!  It works like a charm!

It took me a little bit by surprise the presence of two variables.  I think that when `exwm-workspace-show-all-buffers` is `t`, it only makes sense for `exwm-layout-show-all-buffers` to be true as well. But even when the former is `nil`, why prevent users from `switch-to-` X windows if they desire so? (e.g. by using ido's <kbd>C-a</kbd>, or whatever).  In that case the function `exwm-workspace-switch-to-buffer` could be simplified to just using `switch-to-buffer`...

In any case, I am very thankful for this, and really appreciate the care and effort you put into this.

Have a nice day,
uu1101.

**Comment by ch11ng** [comment]
When `ido-mode` is enabled, switching to a buffer displayed in another frame (i.e. workspace) would raise that frame. So when `exwm-workspace-show-all-buffers` is `t` and `exwm-layout-show-all-buffers` is `nil`, a workspace would be automatically activated in this case. OTOH, I believe when `exwm-workspace-show-all-buffers` is `nil` and `exwm-layout-show-all-buffers` is `t`, users can also switch to X windows with either `switch-to-buffer` or `ido-switch-buffer`. Did you have `(exwm-enable-ido-workaround)` in your `.emacs`?

**Comment by uu1101** [comment]
Ah!  Indeed, I do not use `ido`, so was not seeing the behaviour. It would not be a bad idea to provide an `exwm-select-workspace-by-buffer` (akin to `select-frame-by-name`), that presents a list of visible buffers (including X windows' `exwm-mode` buffers) in various workspaces, and switches to _some_ workspace where the selected buffer is being displayed.

By the way, I see that the efforts to get this into ELPA progresses.  Thank you very much!
