### ISSUE TITLE
exwm-manage-configuration failing for libreoffice

### ISSUE THREAD

**Issue by kinleyd** [ch11ng/exwm#501]
I have been trying but failing to get this to work for libreoffice applications:
 ((equal exwm-class-name "libreoffice-writer")
                                    workspace 4)

My exwm-manage-configurating settings work for all other apps I have included, except libreoffice. Would be grateful for any advice.

**Comment by kinleyd** [comment]
I should add that using: 
M-: exwm-class-name
on the buffer containing the libreoffice application does return libreoffice-writer, libreoffice-calc, etc. It just doesn't trigger the drop into the target workspace.

**Comment by medranocalvo** [comment]
I'm unable to test that, but you could try something similar to https://github.com/ch11ng/exwm/issues/490#issuecomment-431662587, add a function to `exwm-update-class-hook` that prints the X window class.  That way you could check whether Libreoffice uses some other class upon startup or, in any case, apply some configuration whenever it changes to `libreoffice-calc`.
Ask for help if you need any.

**Comment by kinleyd** [comment]
@medranocalvo, thanks for the quick response. That was helpful: it seems the exwm-class-name values for libreoffice applications switche between Soffice and libreoffice-calc/writer, etc. Testing the name against equality to Soffice did the trick.
