### ISSUE TITLE
set a new frame active before deactivating the old one causes some problem with the initial frame

### ISSUE THREAD

**Issue by ysmiraak** [ch11ng/exwm#502]
hi, first of all, thanks for the awesome package.  i've been using it on my arch linux.

after a recent update from melpa, exwm initializes to a black screen.
it works fine when `exwm-workspace-number` is greater than 1,
but i use the `ace-window` package which does not work well with more workspaces.

i managed to track down the problem to commit `24287f2`
where `(exwm-workspace--set-active old-frame nil)`
is moved after `(exwm-workspace--set-active frame t)`

i understand this change was to `Reduce flicker when switching workspaces`,
but maybe you a special case can be added for the initial frame,
or is there an easier way around it?

**Comment by ysmiraak** [comment]
oh i forgot to mention that it's in the definition of `exwm-workspace-switch` in case you don't remember.
the problem starts from line 554 in the current commit.

**Comment by medranocalvo** [comment]
Thank you for reporting this issue.  I'm at fault.  Luckily, it has already been reported (#494) and the fix is in the master branch (see #495).  Please give the master branch a try, and report any issues to #494.
