### ISSUE TITLE
move a workspace to a monitor and move focus to a monitor

### ISSUE THREAD

**Issue by rdiaz02** [ch11ng/exwm#504]
(I've googled around, searched in reddit, etc, and I cannot find the answers, so I am wondering if I am getting something basic about EXWM wrong. I have two issues/questions that I think are closely related).

**Move a workspace to a monitor**
I have a multi-monitor setup. Sometimes I want to have a particular workspace displayed in a particular monitor, and I cannot find a straightforward way to do it; the idea is something like "bring this workspace to this monitor" (something that I am used to doing in Xmonad). As you explain in https://github.com/ch11ng/exwm/issues/150#issuecomment-205293065 , when one switches between workspaces, one ends up in the monitor of that workspace (kind of the opposite of what I want).

I know about `C-c C-m` but that moves X-windows (and that command is issued from the X-window you want to move). What I want is to move the whole workspace with all its buffers/X-windows, etc, and preferably by issuing the command from the monitor of choice.

Interestingly, from what I can find, other packages that work with EXWM also use the model you point to: : when selecting a workspace/frame you are moved to the monitor where that workspace resides (e.g., https://github.com/akirak/frame-workflow  or https://github.com/pjones/exwm-nw) [1]. 

**Move focus to a monitor**
A related question is moving focus (using the keyboard) to another monitor. The way to do it seems to be to move to the workspace that is active in another monitor.   What I would like to do is to just move focus (the cursor) to another monitor directly (i.e., specifying something like "jump to the monitor";  of course what would now be in focus would be the workspace that is active in that monitor).

[1] Note that akira's  `frame-workflow-exwm-swap-workspaces` swaps visible workspaces, but does not bring an invisible workspace to a monitor.

**Comment by ch11ng** [comment]
EXWM has no conception about monitors.  It only treat them as rectangle areas for displaying workspaces.  That said, it's still possible to achieve what you want by wrapping what we already have.  Below are only rough ideas.

> **Move a workspace to a monitor**

You can modify `exwm-randr-workspace-output-plist` to make a workspace _belong_ to a monitor and then manually call `exwm-randr--refresh` to take it into effect.

> **Move focus to a monitor**

There is an `exwm-active` frame parameter set on each active workspace (frame) so together with `exwm-randr-workspace-output-plist` it's possible to programmatically select the destination workspace (and switch to it).

**Comment by WJCFerguson** [comment]
FWIW, for the second issue, `framemove.el` (sadly not melpa packaged), allows you to move frames by geometric direction, which might help.  Personally I use windmove quite a bit (on `s-hjkl`) to move between windows, and hook `framemove` in so that my movement carries on between monitors.   `(framemove-default-keybindings) (setq framemove-hook-into-windmove t)`.

Another package to consider is `avy`, with `avy-all-windows` set, to quickly select any window regardless of which monitor/frame it's in.

**Comment by rdiaz02** [comment]
@ch11ng and @WJCFerguson : thanks a lot to both for the suggestions.

I understand then that what I want should be achievable with some elisp code; and for the second issue there are actually two ways of dealing with it (I played with `ace-window` but I missed that it was a simple way of moving focus). Since the second is not an issue, then, and the first is doable, and part of my question seemed to originate from a misunderstanding of the model, I am closing this. (I'll try to see if I can implement something, though I know basically no elisp).

I am wondering, though, if making it explicit the idea de EXWM has no conception about monitors in the documentation would be worth it.

**Comment by medranocalvo** [comment]
Hola @rdiaz02.  It seems to me that `framemove.el` should help with your second request.  Please, try it out and add some text in the Wiki about that, so that other users can benefit from it.

With regards to your first request, it's been asked before (https://github.com/ch11ng/exwm/issues/202), and it's something I wish were supported.  I'm happy to help if you'd like to take a stab at working on it, it should not be too difficult (tm).  Otherwise it will have to wait, mostly because I don't use multiple monitors.

**Comment by lsp-ableton** [comment]
@rdiaz02 
I wrote some elisp code dealing with multiple monitors. Take a look, maybe it will help if you're still interested in this: https://github.com/ch11ng/exwm/issues/202#issuecomment-559222831

**Comment by rdiaz02** [comment]
Thanks a lot for the suggestion and sorry for the late reply. I suspended my explorations of EXWM for a while (and returned to xmonad) because I was making frequent changes in my emacs config and that was leading to problems.

**Comment by medranocalvo** [comment]
@rdiaz02, thanks for getting back.  That's understandable.  You are welcome back when you feel like it.

**Comment by moritzschaefer** [comment]
Here is how to switch to the frame active on the 'other' monitor:

`(exwm-workspace-switch (car (delete exwm-workspace--current (seq-filter #'exwm-workspace--active-p exwm-workspace--list))))`
