### ISSUE TITLE
exwm-input-toggle-keyboard doesn't work right on FreeBSD X server

### ISSUE THREAD

**Issue by a-schaefers** [ch11ng/exwm#505]
Hello, I have never had this issue in Linux, but using my normal exwm config as usual-- only on freebsd-- exwm-input-toggle-keyboard will visibly toggle between char / line mode on the modeline, but never actually sends the keys. I am __always__ stuck in simulation keys.

I work around it on freebsd by binding exwm-input-send-next-key and using that instead.

I'm sorry that I do not know how to debug it very well, but feel free to ask for any information that may be needed. Thanks.

edit: I'm going to just leave this here "X input: devd, dbus, hald, evdev... ???" as I suspect the differences between freebsd's devd and linux udev and other underlying stuff might be connected to my problem:

 https://lists.freebsd.org/pipermail/freebsd-x11/2017-March/018978.html 

Maybe it will be better when freebsd gets libinput.

**Comment by medranocalvo** [comment]
Thank you for reporting.  If I understand you correctly, `line-mode` works fine, but `char-mode` does not?  That would be weird, as `line-mode` –so-to-say– delegates to `char-mode` for non-intercepted keys.  In principle I don't see how devd, etc. could be related, but I'm not an expert either.  If @ch11ng or other user can't before, I'll be able to help you debug next or the following week.

**Comment by a-schaefers** [comment]
Hi @medranocalvo , I forget which is which, "line" vs "char", but I am definitely stuck using one of them, regardless which one it says in the modeline, the behaviour is exactly the same. And the behaviour I experience is that I am always using emacs simulation keys in xorg applications. E.g. In firefox, C-s is search, (not C-f) regardless of line or char on the modeline. I hope that makes it clear.

Regarding debugging, I actually have no intention to stay on freebsd and the machine is being moved to Linux today. I made this post just to put the info out there, and perhaps other freebsd users may find it helpful in the future. Feel free to close the issue if you feel it's necessary.

Thank you.

**Comment by medranocalvo** [comment]
Hello @a-schaefers,

in that case, thank you for taking the time to let us know of these issues.  I'm closing the ticket as there's nothing we can do about it right now.  Please reopen it (you or any other user facing the same issues) when you are able to help with the debugging.

Best regards,
Adrián.
