### ISSUE TITLE
How to bind key sequence with exwm-input-set-key

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#506]
I have tried this:

    (exwm-input-set-key (kbd "C-x C-b") #'ibuffer)
    (exwm-input-set-key (kbd "C-x b") #'ivy-switch-buffer)

It doesn't work, eg. in libreoffice, C-x b is type bold b.

**Comment by QiangF** [comment]
"C-x" is not a simulation key and it's in exwm line mode, how could the key is grabbed by libreoffice and not sent to emacs?

**Comment by medranocalvo** [comment]
That is indeed surprising.  Please check your `exwm-prefix-keys`, there should be `?\C-x` (24?) in there.  If that's the case, please follow the debugging instructions in the Wiki and place a `(exwm--log "...")` in `exwm-input--on-KeyPress` or the functions it calls, check `*XELB-DEBUG*` buffer and report your findings here.

**Comment by QiangF** [comment]
Ahh! I rebooted the computer today and it seems find today.
I should reboot more often. Sorry. :-(
