### ISSUE TITLE
Help with making a smooth monitor hotplug behavior

### ISSUE THREAD

**Issue by WJCFerguson** [ch11ng/exwm#507]
Hi, I'm wondering if you can help me better handle monitor plug/unplug events.

I hooked a defun into exwm-randr-screen-change-hook, but it gets called 5 times if it doesn't change the layout, 7 if it does (via xrandr).

I made my defun do nothing unless the connected displays actually changed since last time (by parsing xrandr output - is there another way? is that data available natively?).   However, it's still pretty slow and the 7 flashes take multiple seconds.  When my defun acts (once per physical change), all it does is configure the display geometry with xrandr and sets up exwm-randr-workspace-output-plist.

I'm wondering how I could do it better?  Really I want a hook to connect to for when there's a change in the physical monitors _connected_, rather than when the screen layout changes and whatever else is triggering some of the hook calls.

This obviously isn't crippling, but every time I return to my desk, multiple times per day, I plug in two monitors and get ~14 flashes over many seconds.  I may well just remove my defun from the hook and just call it manually from a hotkey, but I'm wondering if there's a 'right' way to do it I'm missing?  

(if fairly simple exwm code changes might help, then pointed in the right direction I could attempt to come up with patches.  I'd be happy to help, though my Elisp coding skills are middling at best)

**Comment by medranocalvo** [comment]
That's great news.  I suggest to have a look at how `xrandr` does it: https://gitlab.freedesktop.org/xorg/app/xrandr/blob/master/xrandr.c.

**Comment by ch11ng** [comment]
@WJCFerguson I'm not sure which is a monitor serial number in xrandr output but it sounds like a 'output property'.  Please refer to the RandR spec where all those are defined.

RandR 1.5 monitor in last week's commit is only a logical region and has nothing to do a physical monitor.

**Comment by WJCFerguson** [comment]
Two unrelated directions:

1.  The above patch I mentioned seems to work nicely.  I hope my copyright assignment is progressing, but I've heard nothing.

2.  As a separate issue I've been investigating providing some utility support for choosing a monitor layout based on which specific monitor is attached - hence looking for monitor serial number, but I'm running out of motivation.  For one thing, I question whether this is good use of time and even a feature exwm should have.  I'm running under gnome-flashback precisely so I shouldn't have to deal with already-solved-problems like this (though unfortunately, gnome-flashback *doesn't* reliably/properly restore my layouts).

I've poked around for a bit at getting the serial number from output properties, but I'm still pretty baffled.  I get a list of atoms from ListOutputProperties, but I have failed so far to work out how to turn the atoms into something useful useful - but I don't know that I have the time or motivation to actually address it properly.

**Comment by dakra** [comment]
Maybe have a look how [autorandr](https://github.com/phillipberndt/autorandr) does it.
I use it and works very reliably.

**Comment by benley** [comment]
https://github.com/jceb/screenconfig handles things pretty well too.  It is normally combined with https://github.com/jceb/srandrd to achieve something similar to what autorandr does, but it might actually make sense to use it as part of an exwm randr hook to react to hotplug events.

**Comment by ch11ng** [comment]
Hi all, I've made a change (882a628daad04e27fe19c03ceeb287ac9e6a8323) to the RandR module to better integrate with external tools like xrandr or autorandr.  EXWM will detect those changes made by external tools and automatically refresh workspaces.  The only thing you need to do is to either a) run the external tool manually, b) make the external tool configure RandR automatically (if it's able to detect screen changes itself) or c) register the external tool in `exwm-randr-screen-change-hook` so it'd get run by EXWM when necessary.

It'd still be interesting if someone is going to come up with a configuration interface so we can e.g. modify the screen resolution just from Emacs.  Theoretically this is not the role a WM should play but it can be included in EXWM as a utility.  I think this is what @WJCFerguson is contriving to achieve in this issue.  Of course, depending on your needs a third-party tool may already be enough.

@WJCFerguson Please make a PR for your solution to filter out redundant events.  Note I've added listeners for three other events so please also take them into account.

**Comment by WJCFerguson** [comment]
https://github.com/ch11ng/exwm/pull/521 covers the most basic fix - de-duplicating the events on monitor hotplug.

**Comment by ch11ng** [comment]
@WJCFerguson Thanks! The patch looks good to me.
