### ISSUE TITLE
Enhancement: More sensible buffer shown when splitting an X window

### ISSUE THREAD

**Issue by Vifon** [ch11ng/exwm#509]
When I split (<kbd>C-x 3</kbd>) an X window, EXWM switches the second Emacs window to some other buffer. It seems to be handled [here](https://github.com/ch11ng/exwm/blob/dbccda22a6b6e32a9e547954ec660ad8e80b7416/exwm-layout.el#L349).

Currently this mechanism seems to favor the least used buffers, similarly to the behavior of `unbury-buffer`. I think the more sensible buffer to choose would be the most recently used one (so the exact opposite behavior).

Replacing `switch-to-prev-buffer` with `switch-to-next-buffer` seems to do the trick but I don't know the codebase well enough to open a PR.

Some more places that might need this change: [exwm-layout--refresh-other](https://github.com/ch11ng/exwm/blob/dbccda22a6b6e32a9e547954ec660ad8e80b7416/exwm-layout.el#L299), [another place in exwm-layout--refresh-workspace](https://github.com/ch11ng/exwm/blob/dbccda22a6b6e32a9e547954ec660ad8e80b7416/exwm-layout.el#L356).

**Comment by ch11ng** [comment]
Hi, thanks for the tip.  The problem is with newly created windows which have no window history.  We should keep calling `switch-to-prev-buffer` for existing windows.  I'll push a fix for this issue.

**Comment by ch11ng** [comment]
Please checkout fec85bb72a2d93fb86949f3409327b0f88ae60bc.

**Comment by Vifon** [comment]
Seems to be working great, thank you!
