### ISSUE TITLE
exwm-layout-set-fullscreen doesn't get into char-mode

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#511]
I noticed that there is no function to get into char mode after 0.20.
I think char-mode have to be fullscreen. Maybe we should get exwm-toggle-line-char-mode back.

**Comment by ch11ng** [comment]
Hi, the behavior is not changed I think.  `exwm-input-release-keyboard` can still be used to switch to char-mode while `exwm-input-grab-keyboard` (or simply `exwm-reset`) does the opposite.  And setting full screen mode would automatically enable char-mode.  I don't think we've ever provided `exwm-toggle-line-char-mode`.
