### ISSUE TITLE
go to full screen of vmware freezes emacs

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#514]
This happens when exec exwm-layout-toggle-fullscreen twice on vmware. I am using
emacs 25 on debian stretch with the git code with use-packge setting:

    :load-path "~/.emacs.d/exwm"

After a long freeze, I tried to pkill vmware, the system is back to life.The
debug buffer is
https://gist.github.com/QiangF/feeb262f66b6a4a6617c3fc66b7c9b4f
I am not sure if this is related to the old issues:
https://github.com/ch11ng/exwm/issues/483
https://github.com/ch11ng/exwm/issues/386

**Comment by QiangF** [comment]
OK switching to the virtual machine even in line mode is really slow. And I
can't type in chrome now. (this is pasted)
https://gist.github.com/QiangF/f8203fb2575bdeb13211bc2ad34e1b98

**Comment by QiangF** [comment]
Only some keys work in chrome. C-w C-l all not working.

**Comment by ch11ng** [comment]
The problem is `exwm-input--update-global-prefix-keys` was being called too frequently.  Perhaps vmware changed the keyboard mapping? I think it'd make more sense to put such apps always in char-mode as they also grab the keyboard and would conflict with line-mode.  Could you try the following snippet (you probably need to correct the class name) and see if the issue persists without line-mode?

```elisp
(setq exwm-manage-configurations
      '(((equal exwm-class-name "vmware")
         char-mode t)))
```

**Comment by QiangF** [comment]
This issue does persist without line mode, it is a little bit better that Emacs
doesn't freeze completly, but the global-keys are messed up sometimes. Perhaps
it's because exwm-input-global-keys. Is it possible to create a blacklist that
EXWM won't coerce the application if it constantly asking for freedon (the
keyboard control?) and in fullscreen mode. Often these app has a shortcut to get
out of fullscreen themselves. Maybe put that in a less cpu (time) consuming
checking loop.

The debug output without line mode is:
https://gist.github.com/QiangF/bae4b14c1eb7bd23884eb08fabb64926

**Comment by QiangF** [comment]
When I set exwm-input-global-keys to a minimum of 4 bindings. I
got a small increase in response speed.

    (setq exwm-input-global-keys
          '(([C-s-return] . exwm-layout-toggle-fullscreen)
            ([?\s-1] . buffer-flip-by-time)
            ([?\s-2] . buffer-flip-by-mode)
            ([?\s-7] . switch-to-scratch-and-back)))

The debug out put is :
https://gist.github.com/QiangF/a40c7645ff36fb8f258d915afff0943b

**Comment by QiangF** [comment]
vmware virtual machine (in char mode) mess with keymaps for chrome.
The debug output is recorded during the following operation :
1. when chrome accept keys, type 1234 in the address bar
2. switch to vmware virtual machine, type 1234 in the virtual machine
3. switch back to chrome (click the chrome icon on tint2 bar), now type 1234 again, no response.
4. toggle fullscreen on chrome twice, now I can type 1234 again.
So go out char mode from the virtual machine messed up the key binding.
The debug output is
https://gist.github.com/QiangF/f6774cdb4f22006db32de53cb7d732e3

**Comment by ch11ng** [comment]
I've just noticed the event handling in char-mode is suboptimal and pushed 38e343ff076e1a00826986b302e389e3f2873cbd to fix this.  Please check if that works for you.

**Comment by QiangF** [comment]
I do noticed some improvement of responsiveness. But still switch from a char mode buffer (vmware buffer) to a line mode buffer (chrome or libreoffice), I can't make text input, seems only exwm-input-global-keys work. I need to make the line mode buffer fullscreen once to get the control of keyboard back.
The debug output is
https://gist.github.com/QiangF/3611abbe44e9ac8348c2fcf141ba2d64

**Comment by QiangF** [comment]
I am closing this issue since it is quite fast to work with vmware buffer.

**Comment by ch11ng** [comment]
We make passive grabs on each X window so theoretically there is no conflict with other X clients like vmware.  This is still not clear to me and I'll make further investigation.

> I am closing this issue since it is quite fast to work with vmware buffer.

I don't quite get it.

**Comment by ch11ng** [comment]
If you make a global binding with a key sequence then it'll still make Emacs freeze.  But I believe users seldom do this.

**Comment by QiangF** [comment]
>  According to the log it seems after switching from vmware to libreoffice you pressed 1, 1, 2, 3, 3
No, I only pressed 123 at normal typing speed, maybe emacs is so slow at that moment so a short press is like a long one. 

>  I've noticed when you pressed keys the shift and mod5 keys are almost always held. 
I didn't held these keys, perhaps I pressed Ctl-Alt-Return to toggle fullscreen in the virtual machine.
I have made the following operations this time:
1. open vmware and libreoffice
2. type 123 in libreoffice
3. start a virtual machine in vmware, press the fullscreen button so it grabs the keyboard
4. in the virtual machine type 123
5. switch to libreoffice with tint2, it takes some time (it is fast if the virtual machine hasn't grabbed the keyboard.
6. type 123, libreoffice receives nothing, 123 is not sent
The new debug log and my xmodmap output  are here:
https://gist.github.com/QiangF/273cadcd8078b416b2ad6495a5a86ab0

**Comment by ch11ng** [comment]
According to the debug log it seems EXWM received the key events in Step 6 and decided to forward them to libreoffice with `AllowEvents`.  I'm not sure if it was because the `AllowEvents` request failed or libreoffice ignored the events for some reason.

While in Step 6, please monitor libreoffice with `xev -id XID | grep KeyPress` (you can get XID with `xwininfo | grep 'Window id'`) and type some keys to see if there are KeyPress event received by libreoffice.

**Comment by QiangF** [comment]
@ch11ng I can't find "keyPress" in the output of xev. I have attached the outputs.

Output bad is after switch from vmware, I typed abc with libreoffice in focus, but the document I am
editing didn't change.
The bad output:
https://gist.github.com/QiangF/79c6dcf6a8d8fc99ee6670866ffc92a0

Output good is before entering vmware or when I run exwm-reset, and typed abc, and they
are shown in the document. 
The good output:
https://gist.github.com/QiangF/89750f59bb3bc2d104c275cc8777a0c7

The lines with "keys" are the same in both output:

    KeymapNotify event, serial 18, synthetic NO, window 0x0,
        keys:  0   0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  4294967281 0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  2   0   0   0   64  0   0   0   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  1   0   0   0   0   0   64  0   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  1   0   0   0   0   0   0   0   4   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

    KeymapNotify event, serial 19, synthetic NO, window 0x0,
        keys:  1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
            0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

But there are many other differences.

**Comment by ch11ng** [comment]
Perhaps you got the wrong window ID? I've verified xev is able to intercept KeyPress events forwarded to libreoffice-writer.  You can also get the window ID with <kbd>C-h v exwm--id RET</kbd> when the window is selected.

**Comment by QiangF** [comment]
I can confirm that the two id are just different representations of the same number.

exwm--id
Its value is 52429184
Local in buffer libreoffice-writer::Untitled 1 - LibreOffice Writer; global value is nil

xwininfo | grep 'Window id'
xwininfo: Window id: 0x3200180 "Untitled 1 - LibreOffice Writer"

**Comment by ch11ng** [comment]
What if you run xev with no option and type keys in the auto created window? And what if you switch between line-mode and char-mode?

**Comment by QiangF** [comment]
The auto created window did receive "keyPress" event, but libreoffice doesn't even in char mode, the only keyboard event are like:

    KeymapNotify event, serial 17, synthetic NO, window 0x0,

**Comment by QiangF** [comment]
I will report back if it is the same with the minimum configurations.

**Comment by ch11ng** [comment]
IIRC you have an unconventional keyboard and key events in log files have a special modifier.  Xev cannot handle some keys correctly.  What if you try with a more ordinary keyboard?
