### ISSUE TITLE
[Question]: is there a way to get out of cyclic simulation keys?

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#515]
This is a small sample of my global simulation keys:

```
(setq exwm-input-simulation-keys
      '(([?\C-y]. [C-v])
	([?\C-\;] . [C-y])))
```
What I want is:

`C-y` to paste (as in Emacs)
`C-;` to redo.

But it doesn't work because after I have set `C-y` to paste, then `C-;` does not become redo (the `C-y` in the app), but paste (the `C-y` which now means `C-v`).

Is there a way to break this cyclicity and to bind redo (`C-y` in many apps) to anything once I have set
`([?\C-y]. [C-v])`?

Thank you!!

**Comment by medranocalvo** [comment]
Hm.  This seems to be working fine in my setup.  Please, try the following and report your results:
1. Start XTerm.
2. Open the menu with Control+Right-click and activate "Allow SendEvents".
3. Execute command `cat -A`.
4. Press twice <kbd>C-;</kbd> and twice <kbd>C-y</kbd> .

The following appears here:
```
bash-4.4$ cat -A
^Y^Y^V  
```

**Comment by prosoitos** [comment]
Thank you for trying to help me.

Do you know how to activate "Allow SendEvents" in urxvt? I don't use XTerm...

**Comment by prosoitos** [comment]
Arg. Totally my bad. I found the issue.

EXWM allows for keybindings swapping and the error was on my side (EXWM settings conflicting with other settings set elsewhere).

Apologies for the noise... and thank you @medranocalvo. Closing this.

**Comment by prosoitos** [comment]
Actually, I still have the problem in some applications... (e.g. slack-desktop)

`C-;` paste instead of doing a "redo"

**Comment by ch11ng** [comment]
@prosoitos It'd be good if you can name some open source apps so we'll be able to check their source to find out why this does not work.

**Comment by prosoitos** [comment]
Thank you!

slack-desktop is one: https://aur.archlinux.org/packages/slack-desktop/

**Comment by ch11ng** [comment]
@prosoitos I'm afraid both slack and skype are closed source though linked against GTK.  We are not able to inspect binary builds.

**Comment by prosoitos** [comment]
OK. Thank you @ch11ng. All the other apps I am using are handling EXWM keybindings pretty well.
