### ISSUE TITLE
[Question]: Is it possible to assign Emacs buffers to EXWM workspaces?

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#516]
I am trying to assign all buffers matching the regexp `^\*help\[R:.*$` (R help files in ESS) to a certain workspace.

While I know how to assign apps to EXWM workspaces with `exwm-manage-configurations`, I don't know whether it is possible to assign Emacs buffers in some similar fashion. Do they have a `WM_CLASS`? If not, what would be an option to go about this?

I asked the question [here](https://emacs.stackexchange.com/questions/45956/how-to-assign-an-emacs-buffer-to-an-exwm-workspace-based-on-a-regexp) with no success so far and I would be very grateful for any suggestion.

Thank you!!!

**Comment by medranocalvo** [comment]
I suggest you have a look at the docstring of `display-buffer-alist`, and from them that of `display-buffer`, in particular the `display-buffer-use-some-frame` option.  Ask if you need help with that.

As an aside, and valuing how useful `exwm-manage-configurations` is to many, I wish EXWM relied/built on the existing Emacs mechanisms in this area, or that those mechanisms were improved.

**Comment by prosoitos** [comment]
Thank you very much for the hints! I will give this a try and ask for help when I get stuck.

**Comment by prosoitos** [comment]
Hi @medranocalvo,

I finally found some time to look at your answer. As I mentioned in my Emacs Stack Exchange post (see link above), I have used `display-buffer-alist` before. Here is my current setting:
```
(setq display-buffer-alist
   '(("magit-diff.*"
      (display-buffer-reuse-window display-buffer-pop-up-window))
     ("\\*magit-.*-popup\\*" display-buffer-below-selected)
     ("\\*helm.*\\*"
      (display-buffer-reuse-window display-buffer-pop-up-window))))

```
However, I have no idea how to integrate exwm workspaces within the alist... I tried various things, but unsuccessfully and I would appreciate some additional help.

Thank you very much.

**Comment by ch11ng** [comment]
Here is an example of how to always display the `*Help*` buffer on workspace 2:

```elisp
(push '((lambda (buffer-name action)
          (and (string= buffer-name "*Help*")
               (> (exwm-workspace--count) 2)))
        (lambda (buffer alist)
          (with-selected-frame (elt exwm-workspace--list 2)
            (display-buffer-same-window buffer alist))))
      display-buffer-alist)
```

**Comment by prosoitos** [comment]
Thank you so much @ch11ng for your help. How could I use this with a regular expression? This has nothing to do with exwm anymore and I should be able to find that out, but despite a lot of reading and googling, I have been unable to find a way to use a regexp to identify a buffer in a function...

I am trying to apply your code to the regexp `^\*help\[R:.*$` (which, I think, should be written `^\\*help\\[R:.*$` in an elisp function).

Thank you very much for your time.

**Comment by ch11ng** [comment]
Just replace `string=` with `string-match-p`.  You can find it in the Elisp refrence manual `(info "(elisp)")`.

**Comment by prosoitos** [comment]
That's what I had tried, but it doesn't work (the R help file still opens in the current buffer, as it does without having this code in my init file, even after reboot). So I thought that I had gotten the code wrong.

Maybe there is something in the ESS package that imposes conditions on the R help file and this prevents the code to work?

I guess I will have to keep digging.

But thank you very much for the help @ch11ng. I appreciate a lot.

**Comment by prosoitos** [comment]
The only thing that I can see which might maybe interfere is `ess-help-own-frame`:

> ess-help-own-frame is a variable defined in ‘ess-custom.el’.
Its value is nil
>
> Documentation:
Controls whether ESS help buffers should start in a different frame.
>
> Possible values are:
   nil: Display help in current frame.
  ’one: All help buffers are shown in one dedicated frame.
     t: Each help buffer gets its own frame.
>
> Note if you set this to t you should also set
‘ess-help-reuse-window’ to nil to ensure that help buffers are
displayed in a new frame.
>
> The parameters of the own frame are stored in ‘ess-help-frame-alist’.
See also ‘inferior-ess-own-frame’.

If I set the variable to `t`, emacs gets stuck, probably because, with EXWM, there is no such thing as several emacs frames (???). So I leave it to `nil`. I have no idea if this may be the reason why the code you gave me has no effect on the ESS help buffers.

Thank you for any advice you may have. I have been trying to solve this for a long time as I use ESS all the time and the help files always mess up my windows organization and it would be so amazing to be able to have them all open in one workspace, making it easy to jump back and forth to them without messing up my current workspace.

Thank you

**Comment by prosoitos** [comment]
I managed to set ESS so that my current workspace isn't getting messed up by the opening of ESS help files anymore. The only problem that remains is that I don't know how to choose the workspace in which those help files will open. They seem to open one new workspace (workspace 10 since I have set 9 workspaces as the default).

Is there a way to set workspace 3 in the `ess-help-frame-alist`?

**Comment by ch11ng** [comment]
In EXWM each workspace is an Emacs frame and can be retrieved with `(elt exwm-workspace--list N)`.  I'm not sure why ESS is so obsessed with picking a window for its help buffer but it's definitely a bad idea to allow some other package to get involved in managing Emacs frames when using EXWM.  Please disable its frame management functionality if possible.  Also I noticed there is an option called `ess-help-reuse-window` so perhaps you can enable it and create a help buffer for ESS in some workspace in advance so ESS would reuse that.

**Comment by prosoitos** [comment]
This is my last question... I tried the whole day to configure EXWM so that the "R_x11" windows would appear in workspace 2 **and that the workspace 2 would be split vertically into 2 windows**. I got the first part to work easily, but I cannot get the workspace 2 to split in 2...

I tried:
```
(setq exwm-manage-configurations
   (quote
      ((string= exwm-class-name "R_x11")
      workspace 2 other split-window-right))))
```
and
```
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "R_x11"))
              (exwm-config-misc window-split-right))))
```
and
```
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "R_x11"))
              (window-split-right))))

and I tried to also play with the `display-buffer-alist`, but nothing does it...

**Comment by prosoitos** [comment]
I am really struggling to automate the setting up of my ESS windows and buffers...

`Bookmark+` works great to save a desktop with a bunch of Emacs buffers and basically, I need an equivalent which would work with EXWM windows and desktops...

**Comment by prosoitos** [comment]
While your code:
```
(push '((lambda (buffer-name action)
          (and (string= buffer-name "*Help*")
               (> (exwm-workspace--count) 2)))
        (lambda (buffer alist)
          (with-selected-frame (elt exwm-workspace--list 2)
            (display-buffer-same-window buffer alist))))
      display-buffer-alist)
```
works beautifully, I cannot get it to work for buffers associated with files (for instance, this has no effect):
```
(push '((lambda (buffer-name action)
          (and (string= buffer-name "r_test.R")
               (> (exwm-workspace--count) 2)))
        (lambda (buffer alist)
          (with-selected-frame (elt exwm-workspace--list 2)
            (display-buffer-same-window buffer alist))))
      display-buffer-alist)
```
If you have the time/patience, I would love to understand why the above does not work. In the meantime, I am following #216 and I set some macros to launch my various EXWM windows and Emacs buffers in their respective workspaces. Very inelegant, but after days of trying, I gave up on setting it in a nicer way.

**Comment by ch11ng** [comment]
> I cannot get the workspace 2 to split in 2...

It'd be easier if workspace 2 is split into 2 windows in advance (on startup for example) so no extra work is required when displaying a buffer, or you'll have to check if the workspace is in correct configuration and make possible fixes.

> I cannot get it to work for buffers associated with files

IMO there is no difference when it comes to buffer names.  You may check if the buffer is really named that: with the buffer selected, type <kbd>M-:</kbd>, `(buffer-name)`, and <kbd>RET</kbd>.

**Comment by prosoitos** [comment]
Thank you again sincerely @ch11ng for your time on this thread. It took me a while, but thanks to the information you gave here (a long time ago now), I finally got the behaviours I want for all buffers and workspaces.

**Comment by xvrdm** [comment]
Hi @prosoitos, I am not sure if you are still using this considering the age of the issue but would it be possible to see what your final ESS+EXWM config for buffer placement looks like please?

**Comment by prosoitos** [comment]
Indeed, it has been a while. I actually switched to i3wm quite a while ago. Sorry... :neutral_face:
