### ISSUE TITLE
Switching resolution with xrandr --mode does not work well

### ISSUE THREAD

**Issue by jabranham** [ch11ng/exwm#519]
If I execute something like:

```
xrandr --output HDMI-0 --mode "1920x1200"
```

where 1920x1200 is a smaller resolution than what I'm currently using, it doesn't work as expected. Instead of resizing the monitor to show the desktop, the desktop seems to "run off" the monitor. In other words, I can't see the bottom part of the current Emacs frame.

**Comment by QiangF** [comment]
I think your issue is not exwm related, instead of a smaller resolution, why not making the font size bigger?

**Comment by ch11ng** [comment]
Hi @jabranham, which version are you using? I believe this is automatically fixed in master by e597ab4f785982d44f56f61ba113b54c501256ac.

**Comment by jabranham** [comment]
@ch11ng current git master (38e343ff076e1a00826986b302e389e3f2873cbd)

**Comment by ch11ng** [comment]
Is the `exwm-randr` module enabled?

**Comment by jabranham** [comment]
I did `(require 'exwm-randr)` and `(exwm-randr-enable)`. That should be enough, right?

... oh, I just looked at `exwm-randr-enable`. It just attaches to `exwm-init-hook`, which had already run. Manually running `exwm-randr--init` does fix this problem, thanks.

**Comment by jabranham** [comment]
@ch11ng Perhaps exwm-randr-enable should add to the hook if exwm hasn't started yet, but if it has it should run exwm-randr--init?

**Comment by ch11ng** [comment]
Not all module can be loaded after EXWM finishes starting so this one just follows the same way.
