### ISSUE TITLE
emacs key binding does not work in exwm line mode

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#520]
From the wiki:

    In line-mode, EXWM intercepts all key events and sends applications only
    keys not explicitly assigned.

But this is not enforced, for example I have bind C-y to my-yank, with bind-key*

    (defun my-yank ()
    (interactive)
        (let ((inhibit-read-only t))
            (if (derived-mode-p 'exwm-mode)
                (exwm-input--fake-key (aref (kbd paste-key) 0))
                (if (eq last-command 'yank) (yank-pop) (yank)))))

    (bind-key* "C-y" #'my-yank)

It's supposed to work in emacs anywhere, but in chrome C-y doesn't do yank, run
my-yank with M-x works. That make me to set C-y in exwm-input-global-keys for it
to work in chrome, which is over done.

I guess exwm line mode need some trick to make it behave as the wiki described
to mimimise the use of exwm-input-global-keys, as it makes using another
Emacs under EXWM a pain.

**Comment by QiangF** [comment]
Set the binding in exwm-mode-map solves this issue. Though it would be nice to make bind-key* do the work.

**Comment by ch11ng** [comment]
`bind-key*` is not a standard Emacs function and I don't know what it is.  But it's actually possible to make a key binding specifically for `exwm-mode` without using `exwm-input-global-keys`.  Please refer to https://github.com/ch11ng/exwm/wiki#local-key-bindings.  Note that Emacs global key bindings are not automatically accessible in `exwm-mode` unless they are added to the white list (`exwm-input-prefix-keys`).
