### ISSUE TITLE
Question: is it possible to toggle simulation keys live

### ISSUE THREAD

**Issue by kmerfeld** [ch11ng/exwm#522]
Is there any way to toggle simulation keys system wide?
I would like to write a function to enable disable them without having to restart my programs

**Comment by ch11ng** [comment]
Do you mean modifying global simulation keys at runtime? You could achieve it by customizing `exwm-input-simulation-keys`.  It does not require a restart to take effect.

**Comment by kmerfeld** [comment]
I'm looking to create a function that will toggle simulation keys while in a x11 app.
during my testing it seems like x11 apps (or at least qutebrowser) keep whatever simulation keys
existsed when the app was started

**Comment by ch11ng** [comment]
Perhaps `custom-set-variables` is what you are looking for.

```elisp
(custom-set-variables
 '(exwm-input-simulation-keys
   '(([?\C-b] . [left])
     ([?\C-f] . [right]))))
```
