### ISSUE TITLE
exwm does not play with wmctrl -a

### ISSUE THREAD

**Issue by franburstall** [ch11ng/exwm#524]
In a shell, I do `wmctrl -ax google-chrome`.

What I expect: the desktop switches to the one on which google-chrome is running.

What happens: nothing.

Any ideas? 

Emacs: 26.1
Exwm: 0.20

PS Many, many thanks for exwm: a truly wonderful software!

**Comment by franburstall** [comment]
On Sun, 9 Dec 2018 at 12:29, Chris Feng <notifications@github.com> wrote:

> It seems wmctrl has some problem in identifying a window's name/class.
> With wmctrl -s <DESK> it correctly orders EXWM to switch to a specified
> workspace but not wmctrl -a with -i or -x. You can add a -v option to see
> which window it picks. It seems to me the result is always wrong.
>
Agreed that wmctrl -s is working: this is the work-around I am using.
wmctrl -ax has worked for me with other window managers, such as whatever
cinnamon uses (mutter?).

> BTW please upgrade to release 0.21.
>
Will do!

**Comment by ch11ng** [comment]
I've figured it out: instead of `wmctrl -ax <WIN>` you should use `wmctrl -xa <WIN>` since it's the option `-a` that accepts an argument.
