### ISSUE TITLE
Unable to rebind "C-t" using simulation keys

### ISSUE THREAD

**Issue by lafrenierejm** [ch11ng/exwm#525]
I am attempting to rebind some chords in Firefox using the following code.

``` emacs-lisp
(add-hook
 'exwm-manage-finish-hook
 (defun init-exwm/set-firefox-simulation-keys ()
   (when (and exwm-class-name (string= exwm-class-name "Firefox"))
     (exwm-input-set-local-simulation-keys
      '(([?\C-s] . [?\C-f])
        ([?\C-q] . [?\C-w])
        ([?\C-t] . [?\C-n]))))))
```

"C-s" and "C-q" are correctly rebound.
However, "C-t" is becoming `pop-tag-mark`.
I have not manually rebound "C-t" anywhere in my config.

The output of `emacs-version` is `GNU Emacs 26.1 (build 1, x86_64-unknown-linux-gnu, GTK+ Version 3.22.30) of 2018-07-25`.
I am using EXWM 0.20.

**Comment by ch11ng** [comment]
<kbd>C-t</kbd> normally runs `transpose-chars` and I believe EXWM does not have it rebound by default.  Perhaps this is modified by some minor-mode.  You can check the list of enabled minor-modes with <kbd>C-h v minor-mode-list RET</kbd>, and you may have to disable suspicious ones to find out who does it.

BTW please upgrade to 0.21 which has some bugs fixed.

**Comment by lafrenierejm** [comment]
Forgot to close this. It was an issue caused by my Evil config. Thanks for having taken a look at it!
