### ISSUE TITLE
Failing to reset screen resolution since 0.21

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#529]
I have a laptop (1920x1080) which I connect to a separate screen (1920x1200).  My setup is so that when I plug in the HDMI cable, it switches to the external screen and turns off the laptop screen; when I unplug the cable, the laptop screen is turned back on.

Here follows my configuration hook:

```elisp
;; Function to automatically toggle between internal/external screens.
(defun ambrevar/exwm-change-screen-hook ()
  (let ((xrandr-output-regexp "\n\\([^ ]+\\) connected ")
        default-output)
    (with-temp-buffer
      (call-process "xrandr" nil t nil)
      (goto-char (point-min))
      (re-search-forward xrandr-output-regexp nil 'noerror)
      (setq default-output (match-string 1))
      (forward-line)
      (if (not (re-search-forward xrandr-output-regexp nil 'noerror))
          (call-process "xrandr" nil nil nil "--output" default-output "--auto")
        (call-process
         "xrandr" nil nil nil
         "--output" (match-string 1) "--primary" "--auto"
         "--output" default-output "--off")
        (setq exwm-randr-workspace-output-plist (list 0 (match-string 1)))))))

(require 'exwm-randr)
(add-hook 'exwm-randr-screen-change-hook 'ambrevar/exwm-change-screen-hook)
(exwm-randr-enable)
```

This used to work fine on 0.20.  Since 0.21 (I also tested on master), when I unplug the screen, EXWM still displays on a 1920x1200 area on my laptopscreen (which is 1920x1080), thus the bottom is not visible :(

I've noticed numerous randr-related changes in the commit log, so I assume something has changed.

Any idea?

**Comment by ch11ng** [comment]
EXWM now uses interfaces from a more updated version of the RnndR protocol by default.  What's the result of `xrandr --listactivemonitors` before and after you plugging/unplugging the external monitor?

**Comment by Ambrevar** [comment]
With my current config and the external monitor plugged in:

```sh
> xrandr --listactivemonitors
Monitors: 1
 0: +*HDMI-2 1920/518x1200/324+0+0  HDMI-2

# After unplugging:
> xrandr --listactivemonitors
Monitors: 2
 0: +*HDMI-2 1920/508x1200/317+0+0  HDMI-2
 1: +eDP-1 1920/294x1080/165+0+0  eDP-1
```

**Comment by ch11ng** [comment]
It seems the HDMI-2 is still active and set as primary after it's unplugged.  Could you check with `xrandr`?

**Comment by Ambrevar** [comment]
It is, but if I run

    xrandr --output eDP-1 --primary --auto

afterwards EXWM does not update its display area.

**Comment by ch11ng** [comment]
What's the content of `exwm-workspace--workareas` after each step? It should always be synchronized with the output of `xrandr --listactivemonitors`.

BTW I suspect your function won't work if it's called by even times which might happen sometimes.

**Comment by dakra** [comment]
I'm not sure if that's your problem but in newer exwm versions `exwm-randr-workspace-output-plist` is now called `exwm-randr-workspace-monitor-plist`

**Comment by Ambrevar** [comment]
> What's the content of exwm-workspace--workareas after each step? It should always be
> synchronized with the output of xrandr --listactivemonitors.

It's always `([0 21 1920 1179])`, which matches the resolution of my external
monitor.

> BTW I suspect your function won't work if it's called by even times which might happen sometimes.

Hmmm, I don't know, because my function is stateless.  What it does is very
simple: 
- if there is only one monitor, turn it on.
- if there are two monitors, turn the first one off and turn the second one on.

> I'm not sure if that's your problem but in newer exwm versions exwm-randr-workspace-output-plist
> is now called exwm-randr-workspace-monitor-plist

No because the former is now an alias to the other.

**Comment by ch11ng** [comment]
What if you run `xrandr --output HDMI-2 --auto` then? Perhaps it's enabled even if it's disconnected.

The `*` before eDP-1 indicates this is the primary monitor.  Not sure why it's not used.

**Comment by Ambrevar** [comment]
> What's the content of exwm-workspace--workareas after each step? It should always be
> synchronized with the output of xrandr --listactivemonitors.

It's always `([0 21 1920 1179])`, which matches the resolution of my external
monitor.

> BTW I suspect your function won't work if it's called by even times which might happen sometimes.

Hmmm, I don't know, because my function is stateless.  What it does is very
simple: 
- if there is only one monitor, turn it on.
- if there are two monitors, turn the first one off and turn the second one on.

> I'm not sure if that's your problem but in newer exwm versions exwm-randr-workspace-output-plist
> is now called exwm-randr-workspace-monitor-plist

No because the former is now an alias to the other.

**Comment by ch11ng** [comment]
Perhaps https://github.com/ch11ng/exwm/issues/507#issuecomment-439144015 or https://github.com/ch11ng/exwm/issues/507#issuecomment-439194888 ?

**Comment by Ambrevar** [comment]
Thanks for the pointers, I'll look into it!

**Comment by Ambrevar** [comment]
I think this can now be closed since my above code snippet works.
