### ISSUE TITLE
Changing number of workspaces breaks the wm

### ISSUE THREAD

**Issue by TLATER** [ch11ng/exwm#53]
After scratching my head over what made stuff go wrong I found commenting

```elisp
(setq exwm-workspace-number 9)
```

fixed all issues... Since essentially all functionality broke down I am not sure what the problem is.

The relevant code is extremely simple and essentially what's in the wiki, except for setting the number of workspaces:

```elisp
;; EXWM settings
(require 'exwm)
(add-hook 'exwm-update-class-hook
          (lambda () (rename-buffer exwm-class-name t)))
;; Set the number of workspaces to 9
;; (setq exwm-workspace-number 9)
(exwm-enable)
```

Where should the workspace number be set, if this is not a bug? I'd assume require overrides the custom value, and enable makes any change irrelevant.

**Comment by ch11ng** [comment]
It's a bug introduced by #42, we'll fix it ASAP. BTW, it's okay to set `exwm-workspace-number` anywhere in your `.emacs`.
