### ISSUE TITLE
GraphicsMagick "gm" screenshots of text buffers are black.

### ISSUE THREAD

**Issue by IQubic** [ch11ng/exwm#536]
So I'm trying to come up with a good way to take screenshots on EXWM. I'm currently trying to use GraphicsMagick to take screenshots, but that's not working very well. I'm running the following command from eshell, and it does take a screenshot, but there are still issues.

`gm import -window root \"/home/iqubic/screenshots/test.png\"`

This is the result of that: https://i.imgur.com/TGV00Y7.png
The black part of the image is supposed to be the eshell instance where I ran that function from.

**Comment by Sbozzolo** [comment]
I use ImageMagick:
``` emacs-lisp
(exwm-input-set-key (kbd "<print>")
                    '(lambda () (interactive)
                       (progn
                         (shell-command "import -window root ~/screenshots/$(date +%Y-%m-%d:%H:%M:%S).png")
                         (alert "Screenshot taken! Saved in ~/screenshots" :title "Screenshot")
                         )
                       )
                    )
```

**Comment by IQubic** [comment]
I can confirm that ImageMagick works for me. Closing this now.
