### ISSUE TITLE
Applications on workspace 0 don't take full width.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#538]
My display resolution is 1600x900, but apps on workspace 0 are only 1592x882.
Other workspaces aren't affected. I have tried to disable system tray but it didn't help.
```
xwininfo: Window id: 277 (the root window) "LG3D"

  Root window id: 277 (the root window) "LG3D"
  Parent window id: 0 (none)
     18 children:
     23068673 "EXWM: exwm-systemtray--selection-owner-window": ()  1x1+0+0  +0+0
     20971564 "EXWM: exwm-input--timestamp-window": ()  1x1+-1+-1  +-1+-1
     25165829 "~": ("xterm" "xterm")  1592x882+0+0  +0+0
        1 child:
        8388761 (has no name): ()  1x1+515+421  +515+421
     20971522 "EXWM: exwm--guide-window": ()  1x1+-1+-1  +-1+-1
     20971559 "EXWM workspace 0 frame container": ()  1600x900+0+0  +0+0
        1 child:
        18874687 "xterm – Doom Emacs": ("emacs" "Emacs")  1600x900+0+0  +0+0
           2 children:
           18874691 (has no name): ()  1600x900+0+0  +0+0
              1 child:
              23068674 "EXWM: exwm-systemtray--embedder-window": ()  2x17+1598+883  +1598+883
           18874688 (has no name): ()  1x1+-1+-1  +-1+-1
     20971560 "EXWM workspace 1 frame container": ()  1x1+0+0  +0+0
        1 child:
        18875044 "*doom* – Doom Emacs": ("emacs" "Emacs")  1600x900+0+0  +0+0
           2 children:
           18875048 (has no name): ()  1600x900+0+0  +0+0
           18875045 (has no name): ()  1x1+-1+-1  +-1+-1
     20971562 "EXWM workspace 3 frame container": ()  1x1+0+0  +0+0
        1 child:
        18875705 "*doom* – Doom Emacs": ("emacs" "Emacs")  1600x900+0+0  +0+0
           2 children:
           18875709 (has no name): ()  1600x900+0+0  +0+0
           18875706 (has no name): ()  1x1+-1+-1  +-1+-1
     20971561 "EXWM workspace 2 frame container": ()  1x1+0+0  +0+0
        1 child:
        18875375 "*doom* – Doom Emacs": ("emacs" "Emacs")  1600x900+0+0  +0+0
           2 children:
           18875379 (has no name): ()  1600x900+0+0  +0+0
           18875376 (has no name): ()  1x1+-1+-1  +-1+-1
     20971563 "EXWM workspace 4 frame container": ()  1x1+0+0  +0+0
        1 child:
        18876035 "*doom* – Doom Emacs": ("emacs" "Emacs")  1600x900+0+0  +0+0
           2 children:
           18876039 (has no name): ()  1600x900+0+0  +0+0
           18876036 (has no name): ()  1x1+-1+-1  +-1+-1
     20971521 "EXWM: exwm--wmsn-window": ()  1x1+-1+-1  +-1+-1
     18874727 (has no name): ("emacs" "Emacs")  28x45+0+0  +0+0
        1 child:
        18874728 (has no name): ()  1x1+-1+-1  +-1+-1
     18874700 (has no name): ()  1x1+-1+-1  +-1+-1
     18874369 "emacs": ("emacs" "Emacs")  10x10+10+10  +10+10
     12582913 (has no name): ()  10x10+-20+-20  +-20+-20
     14680067 (has no name): ()  1x1+-1+-1  +-1+-1
     14680065 "Dunst": ("Dunst" "Dunst")  1600x1+0+0  +0+0
     2097153 "xsettingsd": ()  1x1+-1+-1  +-1+-1
     8388612 (has no name): ()  1x1+0+0  +0+0

```

**Comment by ch11ng** [comment]
Did you mean the 8 pixel loss in width? From the output of xwininfo I can see nothing abnormal.  In `exwm-mode` margins, fringes and scroll bar are automatically disabled so perhaps there is something else left in the first workspace.  Please check with `M-: (window-inside-pixel-edges) RET` with the first workspace selected.

**Comment by sarg** [comment]
Yeah, 8 pixels.
Output for `window-inside-pixel-edges` is `(0 0 1592 852)`.

And here is right bottom corner of my screen. You can see, that system tray is located correctly and app window have 8 pixel gray area at its right side.
![image](https://user-images.githubusercontent.com/193264/52129141-d7689680-2647-11e9-92e1-23df65b16ee2.png)

**Comment by sarg** [comment]
Can't reproduce the bug in clean emacs with latest exwm. Maybe the problem is causes by another package.

**Comment by sarg** [comment]
Removed this from early-init.el, provided by doom-emacs.
```
;; Prevent the glimpse of un-styled Emacs by setting these early.
(add-to-list 'default-frame-alist '(menu-bar-lines . 0))
```
After that the problem dissapeared.
But the root cause isn't this line, because adding it to clean emacs doesn't lead to reproducing the bug.

**Comment by ch11ng** [comment]
It looks like the frame has a non-zero sized internal border.  Please check with `(frame-parameter nil 'border-width)` with the first workspace selected.

**Comment by sarg** [comment]
```((parent-id . 20971559) (explicit-name) (display . ":0") (icon-name) (outer-window-id . "18874687") (window-id . "18874691") (top + -1) (left + -1) (buried-buffer-list) (buffer-list #<buffer *doom*> #<buffer  *Minibuf-1*> #<buffer *helpful function: frame-parameters*> #<buffer  *Minibuf-2*> #<buffer qutebrowser> #<buffer *scratch*>) (unsplittable) (modeline . t) (width . 199) (height . 52) (name . " *Minibuf-1* – Doom Emacs") (exwm-urgency) (exwm-selected-window) (exwm-active . t) (exwm-geometry . #s(#s(eieio--class xcb:RECTANGLE nil (#s(eieio--class xcb:-struct "Struct type." (#s(eieio--class xcb:--struct nil nil [] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data ()) (xcb:keysyms:-device xcb:ewmh:-_NET_WM_FULLSCREEN_MONITORS xcb:ewmh:-_NET_WM_SYNC_REQUEST_COUNTER xcb:ewmh:-_NET_FRAME_EXTENTS xcb:ewmh:-_NET_WM_ICON_GEOMETRY xcb:ewmh:-_NET_WM_STRUT_PARTIAL xcb:ewmh:-_NET_WM_STRUT xcb:ewmh:-_NET_DESKTOP_LAYOUT xcb:ewmh:-_NET_DESKTOP_GEOMETRY xcb:icccm:-WM_ICON_SIZE xcb:icccm:-WM_STATE xcb:icccm:-WM_HINTS xcb:icccm:-WM_SIZE_HINTS xcb:icccm:--ClientMessage xcb:auth-info xcb:connection xcb:-struct) nil [] [] #s(#7) (:custom-groups nil))) [#s(cl-slot-descriptor ~lsb (symbol-value 'xcb:lsb) xcb:-ignore nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (~lsb 0)) (xcb:randr:LeaseNotify xcb:randr:MonitorInfo xcb:randr:ResourceChange xcb:randr:ProviderProperty xcb:randr:ProviderChange xcb:randr:OutputProperty xcb:randr:OutputChange xcb:randr:CrtcChange xcb:randr:ModeInfo xcb:randr:RefreshRates xcb:randr:ScreenSize xcb:cursor:-file-chunk-image xcb:cursor:-file-chunk-header xcb:cursor:-file-toc xcb:cursor:-file-header-toc xcb:cursor:-file-header xcb:render:TRAP xcb:render:SPANFIX xcb:render:ANIMCURSORELT xcb:render:TRANSFORM xcb:render:GLYPHINFO xcb:render:TRAPEZOID xcb:render:TRIANGLE xcb:render:LINEFIX xcb:render:POINTFIX xcb:render:COLOR xcb:render:INDEXVALUE xcb:render:PICTSCREEN xcb:render:PICTDEPTH xcb:render:PICTVISUAL xcb:render:PICTFORMINFO xcb:render:DIRECTFORMAT xcb:xkb:SymInterpret xcb:xkb:SIAction xcb:xkb:SADeviceValuator xcb:xkb:SALockDeviceBtn xcb:xkb:SADeviceBtn xcb:xkb:SARedirectKey xcb:xkb:SAActionMessage xcb:xkb:SASetControls xcb:xkb:SASwitchScreen xcb:xkb:SATerminate xcb:xkb:SAIsoLock xcb:xkb:SASetPtrDflt xcb:xkb:SALockPtrBtn xcb:xkb:SAPtrBtn xcb:xkb:SAMovePtr xcb:xkb:SASetGroup xcb:xkb:SASetMods xcb:xkb:SANoAction xcb:xkb:DeviceLedInfo xcb:xkb:Listing xcb:xkb:Row xcb:xkb:Overlay xcb:xkb:OverlayRow xcb:xkb:OverlayKey xcb:xkb:Key xcb:xkb:Shape xcb:xkb:Outline xcb:xkb:SetKeyType xcb:xkb:KTSetMapEntry xcb:xkb:KeyVModMap xcb:xkb:KeyModMap xcb:xkb:SetExplicit xcb:xkb:SetBehavior xcb:xkb:OverlayBehavior xcb:xkb:RadioGroupBehavior xcb:xkb:DefaultBehavior xcb:xkb:CommonBehavior xcb:xkb:KeySymMap xcb:xkb:KeyType xcb:xkb:KTMapEntry xcb:xkb:CountedString16 xcb:xkb:KeyAlias xcb:xkb:KeyName xcb:xkb:ModDef xcb:xkb:IndicatorMap xcb:HOST xcb:RGB xcb:COLORITEM xcb:SEGMENT xcb:STR xcb:CHARINFO xcb:FONTPROP xcb:TIMECOORD xcb:Setup xcb:SetupAuthenticate xcb:SetupFailed xcb:SetupRequest xcb:SCREEN xcb:DEPTH xcb:VISUALTYPE xcb:FORMAT xcb:ARC xcb:RECTANGLE xcb:POINT xcb:CHAR2B xcb:-union xcb:-error xcb:-event xcb:-reply xcb:-request) ((:~lsb . ~lsb)) [] [] #s(#5 t) (:custom-groups nil :documentation "Struct type."))) [#s(cl-slot-descriptor ~lsb (symbol-value 'xcb:lsb) xcb:-ignore nil) #s(cl-slot-descriptor x unbound xcb:INT16 nil) #s(cl-slot-descriptor y unbound xcb:INT16 nil) #s(cl-slot-descriptor width unbound xcb:CARD16 nil) #s(cl-slot-descriptor height unbound xcb:CARD16 nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (~lsb 0 x 1 y 2 width 3 height 4)) nil ((:~lsb . ~lsb) (:x . x) (:y . y) (:width . width) (:height . height)) [] [] #s(#3 t unbound unbound unbound unbound) (:custom-groups nil)) t 0 0 1600 900)) (exwm-randr-monitor . "LVDS1") (client) (exwm-container . 20971559) (exwm-id . 18874691) (exwm-outer-id . 18874687) (last-focus-update . t) (environment) (cursor-color . "#000010") (background-mode . light) (display-type . color) (window-system . x) (z-group) (skip-taskbar) (visibility . t) (fullscreen . fullboth) (no-accept-focus) (no-focus-on-map) (alpha) (scroll-bar-height . 0) (scroll-bar-width . 0) (cursor-type . box) (auto-lower) (auto-raise) (icon-type . t) (inhibit-double-buffering) (tool-bar-position . top) (wait-for-wm . t) (title) (buffer-predicate . exwm-layout--other-buffer-predicate) (tool-bar-lines . 0) (menu-bar-lines . 0) (scroll-bar-background) (scroll-bar-foreground) (no-special-glyphs) (right-fringe . 0) (left-fringe . 0) (line-spacing) (screen-gamma) (border-color . "black") (mouse-color . "black") (background-color . "#c0c0c0") (foreground-color . "#232333") (horizontal-scroll-bars) (vertical-scroll-bars) (bottom-divider-width . 1) (right-divider-width . 1) (internal-border-width . 0) (border-width . 0) (font-parameter . "-*-Hack-*-*-*-*-14-*-*-*-*-*-*-*") (font . "-SRC-Hack-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1") (font-backend xft x) (override-redirect) (undecorated) (parent-frame) (minibuffer . t))```

**Comment by ch11ng** [comment]
There are two diagrams in `(info "(elisp)Window Sizes")` and `(info "(elisp)Frame Layout")` illustrating various UI components of an Emacs window/frame.  Basically fringes, margins and scroll bars (all are Emacs window components) are automatically removed by EXWM, while the rest are left to users and you may want to check them.

There is something suspicious in the frame parameters: the frame is positioned at (-1, -1).  It should be (0, 0) normally.  Is the result the same with a minimal configuration?

**Comment by sarg** [comment]
I have found that `emacs --fullscreen` in my Xsession doesn't take full screen space even when exwm is disabled. I have removed that parameter and the problem is gone. I suppose it isn't exwm issue at all, feel free to close it because workaround exist.

**Comment by ch11ng** [comment]
You don't have to specify that option since EXWM will do that for you (and it does not rely on Emacs's builtin fullscreen support).

**Comment by paulalesius** [comment]
I'm also experiencing this after logging in and the first EXWM workspace is displayed.

When switching to workspace 1, and back to workspace 0, the issue disappears and the window is aligned to the screen dimensions.

It looks to me like it's caused by emacs being created in a systemd daemon. Once Xorg is started, an emacsclient connects to the daemon socket, the geometrics of the initial frame is a bit off.
![2022-01-25-135254_1920x1080_scrot](https://user-images.githubusercontent.com/6217472/150980784-4433d14b-1256-4960-8cf5-652c7bfd63e6.png)

**Comment by paulalesius** [comment]
It's a problem with the initial frame parameters.

When botting up exwm and you see the initial workspace, if you type:
`(x-frame-geometry)`

You will see that it has "external-border-size" set, in my case:
`(external-border-size 7 . 8)`

According to the emacs documentation, it describes "[External border](https://www.gnu.org/software/emacs/manual/html_node/elisp/Frame-Layout.html#index-external-border)" as:

>  Its width is determined by the window manager and cannot be changed by Emacs’ functions. ...  For graphical frames, their display can be suppressed by setting the override-redirect or undecorated frame parameter

So you'd want to create the initial emacs frame as "undecorated" (by any window manager). These external borders are for window-resize and such functionality but we don't resize the initial emacs frame.

In my Doom config.el I set and synced the config:
`(modify-frame-parameters (selected-frame '(undecorated . t)))`

This solves the issue. However, the idiomatic way is to set it earlier through the "default-frame-alist" or "initial-frame-alist" variable. Does anybody know how one would do this with doom emacs to ensure that the initial emacs frame is "undecorated"?

Thank you for a great desktop! I'm still surprised that everything works! 

![2022-01-26-121326_1920x1080_scrot](https://user-images.githubusercontent.com/6217472/151153466-1cd5b61b-da1f-49d9-a524-dda57738dbfd.png)
