### ISSUE TITLE
Resizing float windows crashes exwm

### ISSUE THREAD

**Issue by mgudemann** [ch11ng/exwm#54]
Hi,

when resizing (at least certain) floating windows, i.e., MPlayer or Skype, exwm crashes predictibly for me on emacs 25.0.50.3. To reproduce: open mplayer, toggle floating, hold (s-) and resize with mouse for several seconds.

Matthias

**Comment by ch11ng** [comment]
I installed MPlayer and can't seem to reproduce it here, though I did find another bug which I believe is not relevant to this issue. I tried starting MPlayer in both CLI or GUI mode and the window playing video can be resized (not perfect however). So could you describe this issue in more detail, like how EXWM crashes? Some logs will be better (with `exwm-debug-on` on for example).

**Comment by mgudemann** [comment]
I start mplayer in CLI mode, toggle floating with C-c m and then hold down "s" and Mouse-right and resize a while with the mouse. With `exwm-debug-on t' I get many of these messages:

```
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
[EXWM] Refresh floating window #x1200001
[EXWM] Show #x1200001 in #<window 14 on MPlayer>
...
```

and then emacs dies (and X with it). My .xsession-errors is empty and I do not get any other debug messages. Maybe you have an idea of how to get more information from emacs/X.

**Comment by ch11ng** [comment]
Does this happen to other programs? Or only video applications?

**Comment by pipcet** [comment]
Wait, Emacs dies? That's not supposed to happen, no matter what we do to it. Can you run emacs using "gdb --args emacs <your usual args>", then entering "run<enter>" at the gdb prompt and report what it says?

My guess is Emacs segfaults due to an Emacs bug, and then X auto-terminates because it doesn't have any clients left. You can prevent the latter by launching xclock (from a shell that doesn't die along with emacs) or any other application before starting Emacs.

**Comment by mgudemann** [comment]
Ok, I started an xterm in .xinitrc and then emacs from there with gdb.

I got roughly the following:

```
Fatal error 6 Aborted
Backtrace
/usr/local/bin/emacs25[@506b8b]
/usr/local/bin/emacs25[@4ed63b]
/usr/local/bin/emacs25[@506be3]
/usr/local/bin/emacs25[@562ce4]

...
Program received signal SIGABRT, Aborted
0x... in raise (sig=sig@entry=6)
at ../nptl/sysdeps/unix/sys/linux/pt-raise.c:37
```

So you're probably right, it is an emacs bug. Sorry for not providing the whole backtrace, but I had no way to copy-past it somewhere and wrote only a small number down.

**Comment by ch11ng** [comment]
You might create a gist to hold the backtrace.

**Comment by pipcet** [comment]
If you start gdb with "gdb --args emacs <your usual args> | tee gdblog.txt", that will create a gdblog.txt file. If it's an Emacs bug, it would be great if you would report it—exwm is really good at triggering those, unfortunately.

**Comment by mgudemann** [comment]
@pipcet thanks for the idea using tee, I redirected stderr and stdout to a file and here's the complete trace:

```
GNU gdb (Debian 7.9.1-1) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from emacs25...done.
(gdb) run
Starting program: /usr/local/bin/emacs25 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdf653700 (LWP 27820)]
Fatal error 6: Aborted
Backtrace:
/usr/local/bin/emacs25[0x506b8b]
/usr/local/bin/emacs25[0x4ed63b]
/usr/local/bin/emacs25[0x506be3]
/usr/local/bin/emacs25[0x562ce4]
/usr/local/bin/emacs25[0x562d09]
/usr/local/bin/emacs25[0x56352a]
/usr/local/bin/emacs25[0x54c286]
/usr/local/bin/emacs25[0x54e0e7]
/usr/local/bin/emacs25[0x59891b]
/usr/local/bin/emacs25[0x5633b8]
/usr/local/bin/emacs25[0x5616e2]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x56208c]
/usr/local/bin/emacs25[0x5622f3]
/usr/local/bin/emacs25[0x563078]
/usr/local/bin/emacs25[0x561ab1]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x56208c]
/usr/local/bin/emacs25[0x5622f3]
/usr/local/bin/emacs25[0x563078]
/usr/local/bin/emacs25[0x5623c1]
/usr/local/bin/emacs25[0x597b23]
/usr/local/bin/emacs25[0x5633b8]
/usr/local/bin/emacs25[0x5616e2]
/usr/local/bin/emacs25[0x563382]
/usr/local/bin/emacs25[0x5616e2]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x56208c]
/usr/local/bin/emacs25[0x5633b8]
/usr/local/bin/emacs25[0x5616e2]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x555a95]
/usr/local/bin/emacs25[0x561949]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x56495d]
/usr/local/bin/emacs25[0x561949]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x561949]
/usr/local/bin/emacs25[0x561949]
/usr/local/bin/emacs25[0x561d05]
/usr/local/bin/emacs25[0x561949]
...
[New Thread 0x7fffdee52700 (LWP 27822)]
[New Thread 0x7fffe6b3b700 (LWP 27802)]

Program received signal SIGABRT, Aborted.
0x00007ffff099579b in raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
37	../nptl/sysdeps/unix/sysv/linux/pt-raise.c: No such file or directory.
(gdb) Error detected on fd 0
error detected on stdin
```
Does this look like an emacs problem?

**Comment by pipcet** [comment]
Yes. There are instructions for how to report Emacs bugs here: http://www.gnu.org/software/emacs/manual/html_node/emacs/Bugs.html

The important thing is to get a symbolic backtrace by entering "bt" at the gdb prompt after it crashed; if you built Emacs yourself, try cd'ing to /path/to/emacs/src before running gdb so this backtrace also includes Lisp information. The hex numbers in the raw backtrace are only useful for people who have access to the precise same Emacs binary that you built, unfortunately. If you have a spare gigabyte or so of disk space, it's also a good idea to enter "generate-core-file" at the prompt you get after the "bt". You should not share the generated core file (it's very large and contains everything that Emacs had in memory, possibly including passwords), but it allows you to go back and debug things without having to reproduce the crash each time.

Hope any of this helps, and feel free to ask for more information if you need it.

**Comment by mgudemann** [comment]
I filed an emacs bug https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21430 for this, the problem is already solved after https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21380 so it is not reproducible on a current git checkout

**Comment by pipcet** [comment]
Sorry about that, I had no idea it was the same bug we'd already fixed. We still need a workaround for older Emacs versions, though, I'm afraid.

**Comment by ch11ng** [comment]
The commit caused that bug seems not included in Emacs 24, so I guess we are quite safe now.
