### ISSUE TITLE
exwm-title doesn't seem to work for Term names

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#540]
Goal: I use qalc with `urxvt -e qalc` and I want to have it floating.

The window in which qalc is running this way is called "qalc" and evaluating `exwm-title` on it gives "qalc". 

However:

```elisp
(setq exwm-manage-configurations
      '(((equal exwm-title "qalc") floating t)))
```
has no effect.

This:

```elisp
(setq exwm-manage-configurations
      '(((equal exwm-class-name "URxvt") floating t)))
```
does work, but I only want qalc to be floating. Not all my urxvt windows.

Thank you!

**Comment by ch11ng** [comment]
It was not possible to achieve this.  I've pushed 65d371d55f22109a6ab886df4c7dfcdb4b893e6c to fix it.

**Comment by prosoitos** [comment]
Great! Thank you!!
