### ISSUE TITLE
*Async Shell Command(chrome)* <-- like this...

### ISSUE THREAD

**Issue by PlumpMath** [ch11ng/exwm#543]
I want you to show us what you've done with the Async Shell Command buffer. 
*Async Shell Command(chrome)* <-- like this...
Or 
is there a how to setup that can show me?
thanks :)

**Comment by ch11ng** [comment]
@PlumpMath I can't quite recall if we have ever provided such example before.  Anyway, does @WJCFerguson's solution work for you?

**Comment by ch11ng** [comment]
Since this issue is not directly related to EXWM I'm closing it now.
