### ISSUE TITLE
Focus follows mouse not working (again?)

### ISSUE THREAD

**Issue by setzer22** [ch11ng/exwm#544]
I seem to be experimenting an issue related to #340. However, I'm currently on 0.22, and the fix for that issuse was pushed by then.

I have set the following variables in my config:
```
(setq mouse-autoselect-window t
      focus-follows-mouse t)
```
At first, I did so *after* requiring exwm, and the behavior was just as described in #340. Focus-follows-mouse worked for regular emacs buffers, but didn't work at all for EXWM buffers. 

However, after reading the issue, I realised I had to set their value *before* loading exwm. However, after doing so focus-follows-mouse doesn't work on any kind of buffer. I tried two different methods of setting the variables before exwm loads: 

- Through emacs' configuration interface
- Inside a use-package directive, in the :init section.

Please let me know if there's any way I can help debug this!

**Comment by ch11ng** [comment]
Perhaps it's a little bit tricky but you should put `(setq mouse-autoselect-window t)` before `(require 'exwm)`, as described in [here](https://github.com/ch11ng/exwm/wiki#how-to-make-focus-follow-mouse).

**Comment by setzer22** [comment]
@ch11ng You are right, none of the methods I tried actually set the variables before exwm loaded. For other people with the same issue, the problem with the `use-package` macro was that I was setting the variables in the `:config` section, not the `:init` section (which is executed after the `require`). 

Closing this, since it wasn't an issue at all!
