### ISSUE TITLE
Failed to add space, "a" and "u" to exwm-input-prefix-keys

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#547]
I am not sure maybe it's not the same variable but I would like to use space as emacs prefix key which is possible and default setting in xah-fly-keys.

I also would like to hide a and u from the X buffers because a is mapped to M-x (in command mode) and u is mapped to xah-fly-insert-mode-activate.

In the end I would like to remove and add this keys to the exwm buffers depending on the modal mode of xah-fly-keys. but I could probably do that with hooks if it would be possible to define them as exwm-input-prefix-keys in general or if you think this variable is the wrong a variable with exwm-hidden-keys or something like that with the same effect would be ok, too.

Hope the question is clear but the first step would be to make that working:

`(push 'space exwm-input-prefix-keys)`

**Comment by ch11ng** [comment]
Space is represented as `?\s` or `32`.  You can always use `(read-key)` to retrieve the representation (numerical value if possible, symbol otherwise).  Please refer to `(info "(elisp)Basic Char Syntax")` for more info.

**Comment by spiderbit** [comment]
Wrote a small howto how to make exwm work good with xah-fly-keys based on that maybe it's interesting to somebody:
xahlee/xah-fly-keys#63

**Comment by ch11ng** [comment]
So your problem seemed solved and I'm closing it now.
