### ISSUE TITLE
 poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

### ISSUE THREAD

**Issue by PlumpMath** [ch11ng/exwm#548]
I'm execute 
FreeCAD-0.17.13541.9948ee4.glibc2.17-x86_64.AppImage

**Comment by ch11ng** [comment]
Could you elaborate on how to reproduce this issue? I've downloaded exactly the same binary and at least it runs (I've no CAD file to open though).  Perhaps your download is corrupted?

**Comment by PlumpMath** [comment]
@ch11ng I think so.
I made a mistake when it was first turned on.
dot dir, It's all cleared, so it. sorry; and Thanks~*

**Comment by ch11ng** [comment]
So I'm closing it now.
