### ISSUE TITLE
Add option to control what EXWM will do if another WM is detected

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [ch11ng/exwm#551]
As it stands EXWM prompts the user to replace the existing window manager and if the user says no it signals an error.

Often I debug my emacs by spawning a new emacs instance in EXWM. When I do this, its disorienting to always have to say "No" and then additionally to get the distracting error message come up.

Could you provide an option that allows the user to configure how EXWM will react in the case of there being an existing window manager?

As a side note: 
It seems to me that signaling an error in this situation is a bit overkill. This is because the user already said "No" to replacing the window manager. I know that as a user I was surprised I got an error when EXWM did what I told it to do (not replace) successfully. In contrast, if I had said "Yes" and for internal some reason EXWM could not replace it, I would expect an error.

**Comment by WJCFerguson** [comment]
My config is different in that I don't automatically load `exwm`, and instead, when I want it, run `emacs --eval "(exwm-enable)"`.  This seems like a neater solution to me, rather than loading and running `exwm` whether you want it or not.

**Comment by Luis-Henriquez-Perez** [comment]
Actually, I also do not load `exwm` whether I want it to or not.

My Init.el has:

`(with-os! linux
  (use-package exwm
    :if (display-graphic-p)
    :demand t))`

I only load exwm if I'm running a graphical emacs display and I'm on linux.  This is when I want it to be loaded.  @WJCFerguson your way is fine of course, we just have different preferences as when we want the loading to happen.

My main point is this:
I additionally don't want it to be loaded when `EXWM` already running.  And, fortunately, `EXWM` actually already checks for this in `exwm--wmsn-acquire`. But it does not do what I want it to in this situation. I just want an option to specify what it does in this situation. 

Of course I can override this function and change what it does, but nevertheless I think there should be an option. I'm willing to contribute a change myself if necessary (I don't think it would be considered a significant change?).

My other point is that:
I don't think that it should raise an error when the user says "No". Because nothing is actually going wrong in that case and because it seems confusing. As a user, my first thought was that EXWM had an error in not replacing the window manager (in other words that the window manager was actually replaced).

**Comment by ch11ng** [comment]
Please checkout b12c67de2ed10e2528b1c494aa08d51b43e563dd.  I've added `exwm-replace` to customize this behavior.

**Comment by Luis-Henriquez-Perez** [comment]
Thanks for this!
I have tested it and it works great! 
I'm ready to close issue.
