### ISSUE TITLE
Plasma shell window closes right after opening

### ISSUE THREAD

**Issue by setzer22** [ch11ng/exwm#555]
I am using exwm inside Plasma 5 (KDE) and so far it has been a very pleasant experience. I get all the session management (WiFi, bluetooth, startup apps, volume control...) as well as all the good stuff from EXWM. However, the latest Plasma upgrade seems to have broken some things. I know this is probably not supported, but I'd like to kindly ask for help to see if I can debug this.

First of all, let me briefly describe the situation. Here, we can see my regular desktop, with the Plasma 5 panel on top, and the emacs modeline and minibuffer at the bottom. 
![image](https://user-images.githubusercontent.com/7241990/54748956-6bc89180-4bd3-11e9-9bf8-12aadc001f41.png)

When clicking on plasma shell widgets, instead of launching on a floating window, I get the menu as a tiled window occupying the full screen. However, this behavior is fine to me, and is what I'd like to happen in all cases. See for example how clicking on the volume widget looks like (couldn't figure out how to screenshot this as the screenshot app would close the popup window!):
![image](https://user-images.githubusercontent.com/7241990/54749128-eee9e780-4bd3-11e9-89cb-d1b78d100ebd.png)

The issue comes when I click on the application launcher, which used to work the same as the volume widget. Now, I can only briefly see it as a popup window (where it would usually launch on other WMs), and then it closes almost instantly (again, not easily snapshotted): 
![problem](https://user-images.githubusercontent.com/7241990/54749396-b0086180-4bd4-11e9-927d-2f14c2fb36ea.gif)

I'm assuming there was a change in how this window is created by plasma, which causes EXWM to not manage it correclty. I recorded a log file where I perform a single click on the application launcher and the issue is reproduced, you can find this here: https://pastebin.com/FVYVwbHJ

Any idea on why is the window being closed instantly? Is there a way I could fix this? Please let me know if there's any more relevant info I could capture!

**Comment by setzer22** [comment]
After debugging the exwm-manage--manage-window I've found out that when the window is created, it's being set to floating. This is the piece of code responsible, in `exwm-manage.el:316`:
```
(if (plist-member exwm--configurations 'floating)
          ;; User has specified whether it should be floating.
          (if (plist-get exwm--configurations 'floating)
              (exwm-floating--set-floating id)
            (with-selected-window (frame-selected-window exwm--frame)
              (exwm-floating--unset-floating id)))
        ;; Try to determine if it should be floating.
        (if (and (not exwm-manage-force-tiling)
                 (or exwm-transient-for exwm--fixed-size
                     (memq xcb:Atom:_NET_WM_WINDOW_TYPE_UTILITY
                           exwm-window-type)
                     (memq xcb:Atom:_NET_WM_WINDOW_TYPE_DIALOG
                           exwm-window-type)))
            (exwm-floating--set-floating id)
          (with-selected-window (frame-selected-window exwm--frame)
            (exwm-floating--unset-floating id))))
```
As a quick check I've edited the code to just force all X windows to be tiled, and it seems to do the trick: The old behaviour is restored. The issue still remains that plasma shell windows are instantly closed when launched in floating mode. However that is fine by me.

Now the question is: Is there a way to configure exwm to force *some* windows to be tiled? I can only see the exwm-manage-force-tiling option, which is obviously too coarse-grained. If there is no such feature, would a pull request with it be welcome?

**Comment by ch11ng** [comment]
I suppose the correct behavior would be to make the application launcher menu pop up and stay there as an unmanaged X window.  But according to your report it's actually managed.  Perhaps this is by design (in KDE).  In case the current behavior is not what you actually want you can still use `exwm-manage-configurations` to prevent it from being managed.
