### ISSUE TITLE
Please add workspace number to mode line

### ISSUE THREAD

**Issue by luhux** [ch11ng/exwm#556]
The panel that relies on dbus is big and slow on my machine.
Please provide a switchable workspace indicator on the modeline

**Comment by ch11ng** [comment]
Hi, you can customize `mode-line-format` and include `exwm-workspace-current-index` (which stores the index of the current workspace) somewhere in there.  I'm reluctant to provide a default indicator as it's quite objective to decide where and how to display such info.
