### ISSUE TITLE
Clean redundant wiki pages

### ISSUE THREAD

**Issue by ch11ng** [ch11ng/exwm#56]
Hi @pipcet and @tumashu,

You once created some wiki pages which should get some cleanups now.

* [Applications ignoring simulated keys](https://github.com/ch11ng/exwm/wiki/Applications-ignoring-simulated-keys) only holds for simulation keys. I think some contents can be extracted to the User Guide.
* [Too many window resizes](https://github.com/ch11ng/exwm/wiki/Too-many-window-resizes) refers to an yet unimplemented feature.
* [https://github.com/ch11ng/exwm/wiki/Other-resources](https://github.com/ch11ng/exwm/wiki/Other-resources) contains some links that are not very helpful.

If you have no objection, I will remove these pages in a couple of days.

**Comment by tumashu** [comment]
ok

**Comment by pipcet** [comment]
No objections from me.
