### ISSUE TITLE
Error in exwm-randr--refresh

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#561]
EXWM 0.22.1 on Debian 9 with emacs 26.

Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  slot-value(nil timestamp)
  exwm-randr--get-monitors()
  exwm-randr--refresh()

**Comment by ch11ng** [comment]
Is there any monitor in the output of `xrandr --listactivemonitors` and `xrandr --listmonitors`? An RandR 1.5 compatible X server is required to use the exwm-randr module.

**Comment by QiangF** [comment]
The output is :

    q@debian$ xrandr --listactivemonitors
    Monitors: 1
    0: +*VGA-0 1360/360x768/203+0+0  VGA-0

**Comment by QiangF** [comment]
q@debian$  xrandr --version
    xrandr program version       1.5.0
    Server reports RandR version 1.5

**Comment by ch11ng** [comment]
It looks OK.  What's the result of the following form?

```elisp
(xcb:+request+reply exwm--connection
    (make-instance 'xcb:randr:GetMonitors
                   :window exwm--root
                   :get-active 1))
```

**Comment by QiangF** [comment]
https://gist.github.com/QiangF/864ce24ac7fb63ff7a535af80ce7f9df

**Comment by ch11ng** [comment]
And what's the values of the followings:

```elisp
(xcb:marshal (make-instance 'xcb:randr:GetMonitors
                            :window exwm--root
                            :get-active 1))

(slot-value exwm--connection 'extension-opcode-plist)
```

**Comment by ch11ng** [comment]
The server just complained it received an `xcb:SetInputFocus` request with an incorrect length, which should be an `xcb:randr:GetMonitors`.  So there seems to be some problem when encoding the request into wire format.  What's the version of XELB and the platform on which Emacs runs?

**Comment by QiangF** [comment]
I am using xelb 0.17. The output of 

    (xcb:marshal (make-instance 'xcb:randr:GetMonitors
                                :window exwm--root
                                :get-active 1))
    (slot-value exwm--connection 'extension-opcode-plist)
                   
is:

    [42 146 2 0 0 1](xcb:render 139 xcb:xkb 135)

**Comment by ch11ng** [comment]
The problem is with the `xcb:randr` module not being correctly initialized.  Since your server does support RandR, there should some problem in the client side.  Do you have `(exwm-randr-enable)` in your config file (in case you call `exwm-randr-refresh` manually)? If so, does `(slot-value (xcb:get-extension-data exwm--connection 'xcb:randr) 'major-opcode)` fail to report a number?

**Comment by QiangF** [comment]
Ahh! I forgot to run (exwm-randr-enable). Sorry.
