### ISSUE TITLE
How can I use `s-i` as keybinding?

### ISSUE THREAD

**Issue by RidaAyed** [ch11ng/exwm#564]
How can I use `s-i` as keybinding?

    (setq exwm-input-global-keys
          `(
    ;; Works
            ([s-f2] . (lambda ()
                        (interactive)
                        (start-process "" nil "/usr/bin/firefox")))
    ;; Fails 's-i is undefined'
            ([s-i] . (lambda ()
                       (interactive)
                       (start-process "" nil "/usr/bin/firefox")))
            ))

Using spacemacs<sup><a id="fnr.1" class="footref" href="#fn.1">1</a></sup>

### Footnotes

<sup><a id="fn.1" href="#fnr.1">1</a></sup> <https://github.com/timor/spacemacsOS#key-bindings>

**Comment by ch11ng** [comment]
Key events like <kbd>s-i</kbd> are represented as integers in Emacs so you'll have to use `[?\s-i]` there.  Also

```elisp
(kbd "s-i")
     ⇒ [8388713]
```
