### ISSUE TITLE
[Question] Is it possible to display different parts of same buffer at different  windows in 1 workspace?

### ISSUE THREAD

**Issue by BooAA** [ch11ng/exwm#568]
As title, in normal emacs window/buffer, we can split a window and show different parts of the same buffer at different windows, is it possible to do that in EXWM? (in just 1 workspace)

I noticed that whenever I split the window, the new window after split will switch to other buffer rather than the original exwm buffer. It seems that exwm buffer has some different behavior to normal emacs buffer.

**Comment by ch11ng** [comment]
This is not possible without compositing.  We've experimented with compositing before and it turns out Elisp is not efficient enough for dealing with graphics.  Now we only support third-party compositor which will unlikely implement anything like this.  Would you mind clarifying the use case of such feature?

**Comment by BooAA** [comment]
>  Would you mind clarifying the use case of such feature?

I asked this question mainly out of curiosity. For most of daily works, like browsing, playing music ... etc, this feature might not be so useful. One situation I can think of that this feature might be useful : when reading pdf, user may hope to have different parts of the document showing at the same time without opening the file twice. 

I wish to have this feature since it can make the way of managing applications more like that of managing emacs buffers. If this limitation is because of elisp rather than EXWM itself,  I think we can close this issue. You have answered my question clearly, thanks.

**Comment by ch11ng** [comment]
> If this limitation is because of elisp rather than EXWM itself, I think we can close this issue. 

Fine.  At the moment we can do little about it.
