### ISSUE TITLE
Input method can't use minibuffer for a floating frame

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#572]
The pyim input method needs the minibuffer to display matches (using message I guess), but it can't access the minibuffer or maybe the echo area for a floating frame (I can't see the matches, selecting word still works https://github.com/tumashu/pyim/issues/267). But press M-x brings up a minibuffer (let label this minibuffer A) behind the floating frame in focus, can we redirect the echo area of the floating frame to the echo area corresponding to minibuffer A? 

Another issue is if the floating frame is big enough, minibuffer A will be partly blocked, maybe we should let the floating frame move up a distance of the height of minibuffer A? or why not hide the floating frame temporarily?

**Comment by ch11ng** [comment]
I believe you were referring to the `exwm-xim` module working with an Emacs input method, so please make sure the module is correctly configured.  By default the echo area is used for displaying candidates when necessary so only the 'root window' input method style (see [XIM](https://www.x.org/releases/X11R7.7/doc/libX11/XIM/xim.html)) is supported which means no fancy popup.  And I don't see the possibility of implementing other input method styles for X windows.

> Another issue is if the floating frame is big enough, minibuffer A will be partly blocked, maybe we should let the floating frame move up a distance of the height of minibuffer A? or why not hide the floating frame temporarily?

I'd recommend detaching the minibuffer / echo area in this case so the minibuffer window (which is reused by echo area) would be automatically raised above the floating frame & X window.

**Comment by QiangF** [comment]
Detaching minibuffer works! One small issue : the minibuffer can
't adjust its height, when there is only one line, the selection
echoed by the input method (pyim) can 't be viewed. For example :

      (read-from-minibuffer "Try type with an input method (eg. chinese):"))

My setting is :

    (setq exwm-workspace-minibuffer-position 'bottom
          minibuffer-auto-raise nil
          exwm-workspace-display-echo-area-timeout 2)

**Comment by QiangF** [comment]
We need to make the minibuffer auto adjust its height within a maximum number of rows to show all messages.

**Comment by QiangF** [comment]
pyim uses the following function to display selection candidates :

    (defun pyim-minibuffer-message (string)
    "当在 minibuffer 中使用 pyim 输入中文时，需要将
    minibuffer 原来显示的信息和 pyim 选词框整合在一起显示
    这个函数就是作这个工作。"
    (message nil)
    (let ((inhibit-quit t)
            point-1)
        (save-excursion
        (insert string)
        (setq point-1 (point)))
        (sit-for 1000000)
        (delete-region (point) point-1)
        (when quit-flag
        (setq quit-flag nil
                unread-command-events '(7)))))

**Comment by QiangF** [comment]
seems like current-message can 't be used to determine minibuffer height in exwm-workspace--update-minibuffer-height

**Comment by QiangF** [comment]
Detaching minibuffer works! There are two more issue.

1. the minibuffer can 't adjust its height, when there is more than one line, the selection echoed
by the input method (pyim) can 't be viewed, because the minibuffer still only one line and the
selections are on another line. It looks like current-message can 't be used to determine minibuffer
height in exwm-workspace--update-minibuffer-height . This bug can be replayed with :

  (read-from-minibuffer "Try type with an input method (eg. chinese):"))

My setting is :

    (setq exwm-workspace-minibuffer-position 'bottom
        minibuffer-auto-raise nil
        exwm-workspace-display-echo-area-timeout 2)

pyim uses the following function to display selection candidates :

    (defun pyim-minibuffer-message (string)
    "当在 minibuffer 中使用 pyim 输入中文时，需要将
    minibuffer 原来显示的信息和 pyim 选词框整合在一起显示
    这个函数就是作这个工作。"
    (message nil)
    (let ((inhibit-quit t)
            point-1)
        (save-excursion
        (insert string)
        (setq point-1 (point)))
        (sit-for 1000000)
        (delete-region (point) point-1)
        (when quit-flag
        (setq quit-flag nil
                unread-command-events '(7)))))

2. there is flickering when the selection lists of the input method is updated, the echo area is on and off during typing.

**Comment by QiangF** [comment]
I can get around the swiper issue by using C-M-n. https://github.com/abo-abo/swiper/issues/116

**Comment by ch11ng** [comment]
> It looks like current-message can 't be used to determine minibuffer height in exwm-workspace--update-minibuffer-height .

That function is a bit tricky.  I think the `exwm-xim` module can pick up the desired height if the message is displayed with `(message "%s" string)`.

> This bug can be replayed with...

In order to make `read-from-minibuffer` honor the choice of input method, the following command would be required:

```elisp
(read-from-minibuffer "Try type with an input method (eg. chinese):" nil nil nil nil nil t)
```

**Comment by QiangF** [comment]
You can't just use message to update the candidates list, that's why the author of pyim made the function pyim-minibuffer-message.
When the content of the minibuffer is altered by pyim-minibuffer-message, how to let the minibuffer auto adjust its's height?

**Comment by QiangF** [comment]
Try to evaluate the following, it will show that you can only see some, can not see the "message":

    (defun pyim-minibuffer-message (string)
    "当在 minibuffer 中使用 pyim 输入中文时，需要将
    minibuffer 原来显示的信息和 pyim 选词框整合在一起显示
    这个函数就是作这个工作。"
    (message nil)
    (let ((inhibit-quit t)
            point-1)
        (save-excursion
        (insert string)
        (setq point-1 (point)))
        (sit-for 1000000)
        (delete-region (point) point-1)
        (when quit-flag
        (setq quit-flag nil
                unread-command-events '(7)))))
    (run-with-timer 2 nil
            (lambda ()
            (pyim-minibuffer-message "Some \n message")))
    (read-from-minibuffer "Try get the focus to the minibuffer with one line:" nil nil nil nil nil t)

**Comment by QiangF** [comment]
I got an ugly workaround:

    (defun my-set-minibuffer-height (orig-func &rest args)
        (let ((set-height (and exwm-workspace--minibuffer (= 1 (frame-height exwm-workspace--minibuffer)))))
            (when set-height
                (set-frame-height exwm-workspace--minibuffer 2))
            (apply orig-func args)
            (when set-height
                (set-frame-height exwm-workspace--minibuffer 1))))

    (advice-add 'pyim-minibuffer-message :around #'my-set-minibuffer-height)

**Comment by ch11ng** [comment]
Perhaps you only need to call `exwm-workspace--update-minibuffer-height`? It works for both minibuffer and echo area.

**Comment by QiangF** [comment]
Thank you!
