### ISSUE TITLE
Window of slack 3.4.0 isn't managed correctly

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#574]
Hi there. I have updated slack-desktop to 3.4.0 and now it's window behaves strangely. It's not managed by exwm and is on top of all windows in every workspace. This issue is reproducible in clean emacs with fresh exwm. Slack-desktop 3.3.8 isn't affected.

Here is `xprop` for 3.4.0:
```
_NET_WM_USER_TIME(CARDINAL) = 0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 400, 150
		program specified minimum size: 300 by 325
WM_NAME(UTF8_STRING) = "Slack"
_NET_WM_NAME(UTF8_STRING) = "Slack"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "slack", "Slack"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_MAIN
_NET_WM_PID(CARDINAL) = 16302
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "thinkpad"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

And here is `xprop` for 3.3.8:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE
_NET_WM_USER_TIME(CARDINAL) = 115866910
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 400, 150
		program specified minimum size: 300 by 325
WM_NAME(UTF8_STRING) = "Slack"
_NET_WM_NAME(UTF8_STRING) = "Slack"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "slack", "Slack"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 16042
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "thinkpad"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by sarg** [comment]
Oh, I've got it. `_NET_WM_WINDOW_TYPE_MAIN` windows aren't managed. Solved by adding to `exwm-manage-configurations` this rule: `((equal exwm-class-name "Slack") managed t)`

According to freedesktop specification there is not such type. Seems that this is a slack-desktop's bug.

**Comment by sarg** [comment]
According to "Extended Window Manager Hints" specification: 
```
_NET_WM_WINDOW_TYPE_NORMAL indicates that this is a normal, top-level window, either managed or override-redirect. Managed windows with neither _NET_WM_WINDOW_TYPE nor WM_TRANSIENT_FOR set MUST be taken as this type. Override-redirect windows without _NET_WM_WINDOW_TYPE, must be taken as this type, whether or not they have WM_TRANSIENT_FOR set.
```

Maybe EXWM should should treat unknown (non-basic) window types as _NET_WM_WINDOW_TYPE_NORMAL?

**Comment by DamienCassou** [comment]
Thanks to @sarg suggestion, I've added that to my configuration:

```emacs
(add-to-list 'exwm-manage-configurations
                 '((equal exwm-class-name "Slack") managed t))
```

**Comment by ch11ng** [comment]
> Maybe EXWM should should treat unknown (non-basic) window types as _NET_WM_WINDOW_TYPE_NORMAL?

From my understanding the spec actually means X windows without the `_NET_WM_WINDOW_TYPE` property (key) at all, not with the property but with an unknown value.

It appears to be a bug in slack since other users are also affected: https://forum.manjaro.org/t/slack-not-showing-when-tabbing-between-apps/86759/2 .

**Comment by sarg** [comment]
Yeah, that's a slack bug for sure. I just thought that it maybe a sane default if all windows are normal by default and additional behaviour is hinted by `_NET_WM_WINDOW_TYPE` property. That's my reading of specification.

**Comment by ch11ng** [comment]
Some applications would create X windows without `_NET_WM_WINDOW_TYPE` set for internal use and it'd break them if they are treated as `_NET_WM_WINDOW_TYPE_NORMAL` (of course it'd be better if they can set `override-redirect` but some just fail to do it IIRC).

BTW is this bug fixed in slack?

**Comment by DamienCassou** [comment]
Chris Feng <notifications@github.com> writes:
> BTW is this bug fixed in slack?

I haven't seen any update for Slack yet.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
The bug is still present in Slack 3.4.2.

**Comment by sarg** [comment]
Fixed in Slack 4.0.1

**Comment by DamienCassou** [comment]
I confirm. The issue can be closed.

**Comment by relrod** [comment]
FWIW Slack 4.39 still has this issue often for me with pop-out windows of any kind, like control-clicking a channel.

The [suggestion above](https://github.com/ch11ng/exwm/issues/574#issuecomment-490814569) fixed that for me.

**Comment by Stebalien** [comment]
@relrod can you open an issue in https://github.com/emacs-exwm/exwm/?
