### ISSUE TITLE
EXWM freezes in high latency situations

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#577]
My colleague & I have been having a problem where our emacs hangs about once or twice a week. It was happening a lot when connecting remotely over X2go, but has happened a lot locally as well.

We run the latest stable emacs 26.2 compiled with debugging features on Debian 8 (X.Org X Server 1.16.4) using the latest master branch of EXWM (but also this issue happened on 0.20 which is what we were using before). I've been keeping track of this problem since January this year.

When the issue happens each buffer will go black except for frames with GUI's in them like a browser. I cannot use the browser though when this has happened.

I ran emacs without the EXWM package for 25 days without a crash. Today I put the EXWM package back in and it crashed when I had high latency on my network.  I tried to replicate the problem by setting a delay on my network card like so:

`sudo tc qdisc add dev enx8cae4ce92c47 root netem delay 1000ms`

This made it crash once but I couldn't reliably crash it everytime.

I originally thought it was emacs so I started a stackoverflow question about it here;
https://emacs.stackexchange.com/questions/48748/emacs-is-frozen

After my tests I'm convinced it's EXWM.

I have tried using (toggle-debug-on-error) but when it freezes it doesn't hit this error. When it's frozen I've also tried killing it with the following but I still cannot get access to emacs after it's in this state.
`killall -USR2 emacs`
`pkill -SUSR2 emacs`
`kill -SIGUSR2 <pid of emacs>`

Crashed again and I tried going to the Virtual Terminal and connecting through 'emacsclient -nw' but this command just enters a frozen emacs in the terminal which I cannot do anything with.

What else can I do to help fix this issue? Can I somehow keep a log of emacs method calls? I've compiled emacs for debugging so is there something in the debugger I could do when next in error state?

**Comment by ch11ng** [comment]
> I tried to replicate the problem by setting a delay on my network card like so:
> 
> `sudo tc qdisc add dev enx8cae4ce92c47 root netem delay 1000ms`
> 
> This made it crash once but I couldn't reliably crash it everytime.

The default timeout in XELB is 3 seconds and you may want to decrease `xcb:connection-timeout` a little bit.

It'd be difficult to debug this problem if `USR2` signal can't revive Emacs.  The `*kill*` command accepts `-12`/`-USR2`/`-SIGUSR2` as argument and you can test them against a working Emacs to see if the command is correct.

Debugging Emacs with gdb would be the last resort.  Personally I only do this when Emacs crashes. 
 `etc/DEBUG` in Emacs's source tree gives an intensive guide on how to do this.  For EXWM it'd be required to launch the debug session from a Linux console with the `DISPLAY` environment variable properly set (you can reuse an existing X session and make EXWM replace the window manager).

**Comment by map7** [comment]
I decreased xcb:connection-timeout to 2 and 1 and both still crashed with black background on emacs buffers and GUI applications frozen but still visible. I tried to kill emacs with the -USR2/-SIGUSR2 and emacs didn't get out of the frozen state. In the end I had to kill -9 emacs not even a kill emacs worked.

**Comment by map7** [comment]
Could this problem be caused by older libraries? We use Debian 8 still, could this be an issue?

**Comment by ch11ng** [comment]
> I decreased xcb:connection-timeout to 2 and 1 [...]

I meant decreasing `xcb:connection-timeout` would help reproducing this issue.  If you are seeking for alleviating the problem then increasing it may help.

> I tried to kill emacs with the -USR2/-SIGUSR2 and emacs didn't get out of the frozen state.
> Also if I go to the command line and try "emacsclient -nw" this doesn't start and I end up having to hit control+c to get out of that command.

This is strange.  Perhaps the command loop stopped working and I'm afraid it's only viable to debug such problem with gdb.

> Could this problem be caused by older libraries?

Unlikely I believe.  X11 doesn't change significantly in recent years.

**Comment by map7** [comment]
I've been running my config in i3 the last few days and it's also frozen. It doesn't look like it's EXWM's fault. Closing this now thanks for help.
