### ISSUE TITLE
exwm-xim not working for Hangul input.

### ISSUE THREAD

**Issue by demokritos** [ch11ng/exwm#579]
I tried exwm-xim for Hangul (Korean character system).
Nothing is inputted. I think it is because input-method-function does not return.
`<return>` or `<space>` stops this infinite loop, but the result is nil.
input-method-function for Hangul uses quail overlay and does not echo to the echo area.
I think that exwm-xim should read temp-buffer and overlay, and send it to the client.
For test, I tried this code. I could input some Korean letters, but could not continue to 
proceed, probably because input state was messed up.

```elisp
--- exwm-xim.el.orig 	2019-05-16 22:56:39.162696768 +0900
+++ exwm-xim.el	        2019-05-20 21:04:04.682585040 +0900
@@ -532,13 +532,15 @@
                  (when (eq exwm--selected-input-mode 'char-mode)
                    ;; Grab keyboard temporarily for char-mode.
                    (exwm-input--grab-keyboard))
-                 (unwind-protect
-                     (with-temp-buffer
+                 (with-temp-buffer
+                   (unwind-protect
                        ;; Always show key strokes.
                        (let ((input-method-use-echo-area t))
-                         (setq result (funcall im-func event))))
-                   (when (eq exwm--selected-input-mode 'char-mode)
-                     (exwm-input--release-keyboard)))
+                         (setq result (funcall im-func event)))
+                     (setq result (or result
+                                      (buffer-string)))
+                     (when (eq exwm--selected-input-mode 'char-mode)
+                       (exwm-input--release-keyboard))))
                  ;; This also works for portable character encoding.
                  (setq result
                        (encode-coding-string (concat result)
```
Is it possible that you start a thread for input-method-function and read the temp buffer 
and overlay whenever the buffer state is changed, and send it to the client?

This is not only for Hangul input. I also tried esperanto-postfix, but couldn't input properly.
It would also be nice if I could see intermediate steps in X client, not the echo area.

**Comment by ch11ng** [comment]
The XIM protocol defines [four input method styles](https://www.x.org/releases/X11R7.7/doc/libX11/XIM/xim.html#Input_Method_Styles) and here we only support the 'root-window' style, that is, displaying pre-editing info somewhere dedicated to the input method (echo area).  Perhaps we can also get 'on-the-spot' style working to some extent.

The problem with `korean-hangul` (I'm not sure if i get it right; there seems to be other names) input method is it does not support `input-method-use-echo-area` nor does it return input events when called.  From the doc for `input-method-function`:

> [...]
> The function *should* return a list of zero or more events to be used as input.
> [...]
> The input method function *should* refer to the variables `input-method-use-echo-area` and `input-method-exit-on-first-char` for guidance on what to do.

Of course it's just *should* instead of *must* there so it's fine for input methods to ignore these tips.  But this makes it more difficult to get them working with `exwm-xim`.

I fully understand the frustration of being unable to type CJK characters in EXWM.  But fortunately it's quite simple to create a new input method for Emacs.  I don't know about Korean but `hangul.el` only consists of around 400 LOC.

> Is it possible that you start a thread for input-method-function and read the temp buffer
and overlay whenever the buffer state is changed, and send it to the client?

Users can force `input-method-use-echo-area` (and it might not work) so things get more complicated.

> I also tried esperanto-postfix, but couldn't input properly.

It seems working here.  After typing for example <kbd>e</kbd> it'd prompt in echo are that <kbd>^</kbd> or <kbd>x</kbd> can be followed.

> It would also be nice if I could see intermediate steps in X client, not the echo area.

This might be possible but it requires support from clients.  I'm not sure if this is specific to GTK or Qt IM module.

**Comment by demokritos** [comment]
@ch11ng, Thank you for your kind explanation.
I have a question:
When you inputted with esperanto-postfix, didn't you experience letter-skipping?
In my case, after inputting `c`, `g`, `h`, `s`, `j` or `u`, and then `x` or `^`, a following letter is skipped.
Also after inputting `c`, `g`, `h`, `s`, `j` or `u`, an input other than `x` or `^` is skipped.

I don't know I can do it, but I have to implement a hangul input method in Emacs, since I just changed my hangul input method to what is not implemented in Emacs. I will consider following the doc for `input-method-function`.

**Comment by ch11ng** [comment]
> When you inputted with esperanto-postfix, didn't you experience letter-skipping?

Just noticed this.  I'll look into it.

**Comment by ch11ng** [comment]
> > When you inputted with esperanto-postfix, didn't you experience letter-skipping?
>
> Just noticed this. I'll look into it.

I've pushed fe2336a11e26a488f9fc428efce095a6c10981df to fix this.  Please check it out.

**Comment by demokritos** [comment]
I tried that commit, but if I press `<return>`, an error occurs and any key cannot be delivered to all X clients afterwards. It just keep saying 'read-only buffer'.
```
error in process filter: byte-compile--function-signature: Wrong type argument: characterp, return
error in process filter: Wrong type argument: characterp, return
```

**Comment by ch11ng** [comment]
Thanks for trying out.  I've made another fix: 672a5e2a23e1d41609136170bfa851e25244e4c4 .

**Comment by demokritos** [comment]
Now, it works for esperanto-postfix. Good job.

I implemented an input method that returns a hangul syllable every time when it completes a hangul syllable. A hangul syllable is composed of 1 to 6 key inputs, and the current syllable is determined to complete by a key input belonging to the next syllable. So, if a key input is coming in and a syllable is completed, then the input method function cons the key to `unread-input-method-events` and returns the completed syllable. With this method, exwm-xim does not work. After the first syllable, two key inputs per a syllable are missing. For example, if I input `한글을`, `한ㄹㄹ` is only delivered.

**Comment by demokritos** [comment]
The issue with my hangul input method is fixed. Maybe I coded it incorrectly.
I still hope exwm-xim will get on-the-spot style.
Thank you.

**Comment by demokritos** [comment]
If I input `<return>` after `c`, `g`, `h`, `s`, `j` or `u` in esperanto-postfix,
a character is delivered, but `<return>` is not delivered.
In contrast, if I input `<space>` after those keys, a character and `<space>` both are delivered.
There is the same issue with my hangul input method.

**Comment by ch11ng** [comment]
Thanks for the finding.  Please try 75833e0c53fa92d9b7c7f6ab78e206df6e07f9b9 and see if there is any other problem.

**Comment by demokritos** [comment]
Thank you. It works well with terminal app. But with my hangul input method and firefox, it does not work.
It seems that `<return>` key generates `\r`(carriage return). Should my hangul input method convert `\r` to `'return`?

**Comment by ch11ng** [comment]
> Should my hangul input method convert `\r` to `'return`?

I'm not sure where the conversion is done in your IM but usually it's `'return` (try evaluating `(read-event)` and press `RET`).  Perhaps `\n` (`C-j`, while `\r` is `C-m`) also works.
