### ISSUE TITLE
Right alt is being ignored

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#58]
Right alt is being ignored, previously in other WMs (stumpwm, awesome) worked well without any configuration or tooling. I think I might be able to fix this with some keymap hacks, but there must be some cause of this.

Emacs 24.5.1, Archlinux

**Comment by ch11ng** [comment]
Does it work in Linux console? If so, does it get recognized by `evtest` (in X) and Emacs (e.g. evaluate `(read-key)` and press <kbd>M-\<f1\></kbd>)? And do these X window managers share the same init file?

**Comment by fm4d** [comment]
It works in linux console, is recognized by evtest but not by Emacs (by (read-key). Previously my x init file was usually limited to exec *wm* and application startup (pre-systemd).

**Comment by ch11ng** [comment]
Did you run `evtest` under X? You mentioned it was not recognized by Emacs then what it got recognized instead? And what if you just put `exec emacs` in your X init file?

**Comment by fm4d** [comment]
Sorry, false alarm. Apparently Xkb option grp:alts_toggle was behind this problem.
