### ISSUE TITLE
suggestion: record the setting of attach or detach minibuffer in a variable

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#589]
The package pyim need minibuffer in a seperated frame to work for floating windows.  With that setting, the package awesome-tray (https://github.com/manateelazycat/awesome-tray) show the modeline in the minibuffer, it requires the minibuffer attached. And awesome-tray doesn't refresh the minibuffer in exwm mode buffers. I found it was caused by exwm-workspace--hide-minibuffer.  Turns out exwm-workspace--hide-minibuffer will be executed in hooks no matter the minibuffer is attached or auto-hide. Obviously there is no need to hide minibuffer if the minibuffer is set to be attached.
my suggestion is:

    (defvar exwm-workspace-attach-minibuffer nil)

    (defun exwm-workspace--hide-minibuffer ()
    "Hide the minibuffer frame."
    (exwm--log)
    ;; Hide the minibuffer frame.
    (if exwm-workspace-attach-minibuffer
        ;; required to update the minibuffer height for awesome-tray, without it the echo area is too high
        (exwm-workspace--update-minibuffer-height t)
        (if (exwm-workspace--minibuffer-attached-p)
            (xcb:+request exwm--connection
                (make-instance 'xcb:ConfigureWindow
                                :window (frame-parameter exwm-workspace--minibuffer
                                                        'exwm-container)
                                :value-mask (logior (if exwm-manage--desktop
                                                        xcb:ConfigWindow:Sibling
                                                    0)
                                                    xcb:ConfigWindow:StackMode)
                                :sibling exwm-manage--desktop
                                :stack-mode (if exwm-manage--desktop
                                                xcb:StackMode:Above
                                            xcb:StackMode:Below)))
            (exwm--set-geometry (frame-parameter exwm-workspace--minibuffer
                                                'exwm-container)
                                nil nil 1 1))
        (xcb:flush exwm--connection)))

and in the attach and detach function toggle exwm-workspace-attach-minibuffer:

    (defun exwm-workspace-attach-minibuffer ()
    "Attach the minibuffer so that it always shows."
    (interactive)
    (exwm--log)
    (setq exwm-workspace-attach-minibuffer t)
    .....

    (defun exwm-workspace-detach-minibuffer ()
    "Detach the minibuffer so that it automatically hides."
    (interactive)
    (exwm--log)
    (setq exwm-workspace-attach-minibuffer nil)
    ......

**Comment by ch11ng** [comment]
Actually `(exwm-workspace--minibuffer-attached-p)` there already does the job.  Basically `exwm-workspace--hide-minibuffer` hides the minibuffer completely when it's detached, or lowers it when attached.  This behavior should be transparent to other packages.

**Comment by QiangF** [comment]
But awesome-tray need to be seen always in my case. Normally you don't have the need to use a separate minibuffer frame. But I have to use pyim for floating windows, that only works with a separate minibuffer frame.

**Comment by ch11ng** [comment]
I don't quite get it.  If you want a separate minibuffer but want it always to be visible, you can just attach it again with `exwm-workspace-attach-minibuffer` and the minibuffer is actually still separated.

**Comment by QiangF** [comment]
The issue is  exwm-workspace--hide-minibuffer  mess up with awesome-tray.

**Comment by QiangF** [comment]
For some reason  exwm-workspace--hide-minibuffer will clear the text inserted by awesome-tray.

**Comment by ch11ng** [comment]
The only way I know so far to clear the echo area is to call `(message nil)` and there is no such code in EXWM.  Actually we seldom call `message`.

**Comment by QiangF** [comment]
Sorry, exwm-workspace--hide-minibuffer actually did something else, it hide the minibuffer frame for exwm mode buffers, so I can't view the awesome-tray.

**Comment by ch11ng** [comment]
The function is less than 20 LOC.  I really don't see what else it can do.  Do you have it adviced?

**Comment by QiangF** [comment]
It is exactly what the function does, hide the minibuffer when it should not.
I just redefines it as:

    (defun exwm-workspace--hide-minibuffer ()
        (exwm-workspace--update-minibuffer-height t))
