### ISSUE TITLE
Very fast key capture (scrolling..)

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#59]
Not sure if this is a bug or inteded behavior (but I doubt so), but it seems like EXWM is capturing keys at 3-4x rate as normal, causing scrolling with Ctrl-n/p or arrows very difficult, or browsing shell history and so on.

Emacs 24.5.1, Archlinux

**Comment by ch11ng** [comment]
So I guess you have `xset r rate 200 60` in your X init file. You may want to set the repeat rate to a larger value.

**Comment by fm4d** [comment]
Oh, I totally didnt notice this line in default config, sorry.
