### ISSUE TITLE
Binding "suspend" puts the system to sleep twice in a row

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#590]
I tried using the following snippet:

```elisp
(defun ambrevar/suspend-to-sleep ()
  (interactive)
  (start-process "loginctl" nil "loginctl" "suspend"))
(exwm-input-set-key (kbd "s-Z") #'ambrevar/suspend-to-sleep)
```

When I press `s-Z`, the computer goes to sleep.  When I press any key, it wakes up, then immediately goes to sleep again.  Pressing a key another time finally brings it back from sleep for good.

Note that if I run `loginctl suspen` in Eshell, it works as expected.

I run Guix System.

**Comment by QiangF** [comment]
I use dbus-send and doesn't have that issue.
    (defun suspend ()
      (interactive)
      (let ((suspend-command
             (concat "/usr/bin/dbus-send --system --print-reply --dest=org.freedesktop.login1 "
                     "/org/freedesktop/login1 'org.freedesktop.login1.Manager.Suspend' boolean:true")))
        (bookmark-save)
        (recentf-save-list)
        (call-process-shell-command suspend-command nil 0)))

**Comment by Ambrevar** [comment]
This seems to work indeed?

@QiangF: Can you try with my function see if you can reproduce the same issue?

**Comment by QiangF** [comment]
No, I don't have the issue with your function.

**Comment by Ambrevar** [comment]
With your function I have the same problem only once in a while.  (First
time I call it?  Weird.)  It works most of the time though.

Maybe an issue with Guix then.

**Comment by ch11ng** [comment]
Was the command `loginctl suspend` called twice? You may wrap it in a script if it doesn't yield any log.

**Comment by Ambrevar** [comment]
Hmm, not sure to understand which script to write.

**Comment by ch11ng** [comment]
I mean make a script containing `loginctl suspend` with some log messages and make EXWM calls it on <kbd>s-Z</kbd>.

**Comment by QiangF** [comment]
Something like:

    (defun ambrevar/suspend-to-sleep ()
    (interactive)
    (call-process-shell-command "suspend.sh&" nil 0))

    (exwm-input-set-key (kbd "s-Z") #'ambrevar/suspend-to-sleep)

**Comment by Ambrevar** [comment]
I tried your suggestion with the following script:
```sh
#!/bin/sh
echo "BEFORE SUSPEND" >> ~/exwm.log
date --rfc-3339=ns >> ~/exwm.log
loginctl suspend
echo "AFTER SUSPEND" >> ~/exwm.log
date --rfc-3339=ns >> ~/exwm.log
```

And here is the resulting log:
```
BEFORE SUSPEND
2019-06-24 10:00:43.554967748+02:00
AFTER SUSPEND
2019-06-24 10:00:43.560714413+02:00
BEFORE SUSPEND
2019-06-24 10:00:50.515328054+02:00
AFTER SUSPEND
2019-06-24 10:00:50.520524638+02:00
```
So indeed the script gets called twice, which I believe proves that EXWM is calling it twice.

**Comment by ch11ng** [comment]
You could use the `$PPID` variable to verify if it was EXWM that called it.  What if you enable `exwm-debug` mode? If it's EXWM then the debug log would at least record two key presses.

**Comment by Ambrevar** [comment]
I tried printing out the PPID: It is the emacs process indeed.

I tried enabling exwm-debug, here is the output, although I'm not sure
which key exactly was recorded.

--8<---------------cut here---------------start------------->8---
exwm-input--on-KeyPress:	major-mode=fundamental-mode buffer=*XELB-DEBUG*
exwm-input--on-KeyPress-char-mode:	(90 . 131)
exwm-input--mimic-read-event:	
exwm-input--on-KeyPress:	major-mode=fundamental-mode buffer=*XELB-DEBUG*
exwm-input--on-KeyPress-char-mode:	(104 . 131)
exwm-input--mimic-read-event:	
--8<---------------cut here---------------end--------------->8---

**Comment by ch11ng** [comment]
@Ambrevar Is this the full debug log? If so you had `(90 . 131)` and `(104 . 131)` pressed and both involved the <kbd>mod5</kbd> key of which the meaning really depends on your setting.  However you can interpret them with the following snippet.

```elisp
(key-description (vector (xcb:keysyms:keysym->event exwm--connection 90 131)))
(key-description (vector (xcb:keysyms:keysym->event exwm--connection 104 131)))
```

**Comment by QiangF** [comment]
The evaluation output on my machine is "S-Z""h"

**Comment by Ambrevar** [comment]
Yeah, I got "S-Z""h" too, but on retry I get `90 131` ("S-Z") twice.
Not sure what happened.

If I bind it to anything lowercase, it works (e.g. `s-q`) as expected, only called a single time.

Note that since my binding is `s-Z`, I actually press `super`+`shift`+`z`.  Maybe EXWM is confused by the shift?

**Comment by ch11ng** [comment]
@Ambrevar Perhaps it was because you released the <kbd>super</kbd> key first.  Do you have a global key binding for <kbd>Z</kbd> (or <kbd>S-z</kbd>/<kbd>S-Z</kbd> as they are basically the same thing)? You may check it with <kbd>C-h k Z</kbd>.  If not EXWM will unlikely receive this event in the first place.

Or even worse the <kbd>super</kbd> may not get properly configured/recognized on your system.  You may verify it by checking if the value of `xcb:keysyms:super-mask` is `0`.

**Comment by Ambrevar** [comment]
Nope, `Z` is not bound to anything, but it's a prefix key in Evil.
In particular, `Z Z` is bound to `evil-save-modified-and-close`.

`xcb:keysyms:super-mask` is 64 on both my desktop and my laptop.
My OS is Guix.

**Comment by ch11ng** [comment]
So did you actually typed <kbd>S-Z</kbd> and <kbd>h</kbd>? I think it's unlikely because there were three modifiers involved: <kbd>shift</kbd>, <kbd>lock</kbd> and <kbd>mod5</kbd>.  Perhaps the log just missed the <kbd>s-Z</kbd> part? You can check what is expected with

```elisp
(xcb:keysyms:event->keysym exwm--connection 's-Z)
```

and it's probably `(90 . 67)`.

**Comment by Ambrevar** [comment]
There might have been some confusion.  To clarify:

- I've bound `s-Z` to `loginctl suspend`.

- I type super + shift + "z".

I've never typed "h", I think it was a log error, or maybe a
mis-manipulation on my end.

> (xcb:keysyms:event->keysym exwm--connection 's-Z)

(90 . 195)

**Comment by ch11ng** [comment]
What's the result of `xmodmap -pm`? I just wonder why there's always a <kbd>mod5</kbd>.

**Comment by Ambrevar** [comment]
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Shift_L (0x32)
control     Control_L (0x25),  Control_L (0x42),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

**Comment by ch11ng** [comment]
It seems you have remapped <kbd>caps-lock</kbd> to <kbd>control</kbd>.  Could you share your config? I tried the same thing but the result wasn't quite the same.

Also, does the problem persist if you avoid the left <kbd>shift</kbd> and only use the right one? (You may have to do the test in a new session.)

**Comment by Ambrevar** [comment]
Indeed, if I login with a "us intl" layout it works.
My config:

--8<---------------cut here---------------start------------->8---
setxkbmap -layout us -variant ""
xkbcomp -I"$HOME/.xkb" "$HOME/.xkb/usim.xkb" $DISPLAY 2>/dev/null
xcape -e 'Control_L=Escape'
numlockx on
xbindkeys
--8<---------------cut here---------------end--------------->8---

`usim.xkb` is a custom layout.  In particular, it sets Caps Lock to act
as Left Control and
sets Left-Shift+Right-Shift to act as Caps Lock.

Full definition here: 
https://gitlab.com/ambrevar/dotfiles/blob/master/.xkb/symbols/usim

**Comment by Ambrevar** [comment]
Oh, and using the right shift does not fix the issue with my custom layout.

**Comment by ch11ng** [comment]
I tried your xkb config and there seemed to be no duplicate key events.  Is it possible that something else also invoked the script, especially xbindkeys in your config?

**Comment by Ambrevar** [comment]
I don't see what else.

Anyways, I've switched to "us intl", there is little chance anyone else
will ever hit this issue, so I guess it can be closed for now.
Thanks for your time investigating this!
