### ISSUE TITLE
Focus issues with Emacs child frames

### ISSUE THREAD

**Issue by dakra** [ch11ng/exwm#591]
I have focus follows mouse active and I have problems getting focus for Emacs child frames.

E.g. if I install [child-frame-read-string](https://github.com/Alexander-Miller/cfrs) and execute the example:

``` emacs-lisp
(let ((input (cfrs-read "Text: " "Initial Input")))
  (message "Hello %s!" input))
```

The child frame doesn't focus and I first have to hover with the
mouse over it.

I have similar issues with company-childframe and other child frame
libs (that's why I don't use them).

(I run Emacs 27 from the master branch with latest exwm and xelb)

**Comment by QiangF** [comment]
Maybe you can try posframe, it works well for non exwm mode buffers.

**Comment by dakra** [comment]
> Maybe you can try posframe, it works well for non exwm mode buffers.

`cfrs` what I linked above uses posframe.

The issue is not the creation or the display of child frames but the input focus.
I can use posframe (or have lsp-ui display docs in a posframe) but
something that focuses the child frame ofter like
`company-childrame` or `cfrs` have problems (at least when
focus-follows-mouse is set).
I guess this
[here](https://github.com/Alexander-Miller/cfrs/blob/master/cfrs.el#L44)
doesn't work.

**Comment by ch11ng** [comment]
In EXWM, moving X input focus from an Emacs frame to another directly won't work correctly without calling frame-related commands.  @dakra Perhaps you are correct about your finding, and `redirect-frame-focus` may help there.

**Comment by dakra** [comment]
Adding `(redirect-frame-focus (window-frame) posfr)` didn't work,
but when I add `(select-frame posfr)` after `x-focus-frame` it
works.

But adding this in the library where all other window managers
work fine with the code doesn't feel right.

Any way we can add a kludge to exwm to make things like
`company-childframe` work without changing them?

**Comment by ch11ng** [comment]
I feel it more reasonable for Emacs to forward key events to child frames automatically without ever to manipulate X input focus.  This feature is cross-platform after all.

> Any way we can add a kludge to exwm to make things like `company-childframe` work without changing them?

Is there any interface that tells which child frame should receive input? I've just checked the document and found no one yet.

**Comment by dakra** [comment]
> I feel it more reasonable for Emacs to forward key events to child
> frames automatically without ever to manipulate X input
> focus. This feature is cross-platform after all.

What do you mean with "automatically".
If it is "every time" a child-frame appears, then this would be
wrong. Often you just want to display help text in a child-frame
e.g. `lsp-mode` uses child frames to display docstrings.

> Is there any interface that tells which child frame should receive
> input? I've just checked the document and found no one yet.

Sorry, I'm not really familiar with child frames myself and
I'm not even sure if such an interface exists as I thought
a child frame is basically just a normal Emacs frame (isn't it?).

**Comment by ch11ng** [comment]
> > I feel it more reasonable for Emacs to forward key events to child
> > frames automatically without ever to manipulate X input
> > focus. This feature is cross-platform after all.
> 
> What do you mean with "automatically".
> If it is "every time" a child-frame appears, then this would be
> wrong. Often you just want to display help text in a child-frame
> e.g. `lsp-mode` uses child frames to display docstrings.

So when should it accept input then? If this is done programmatically, why not just receive input the traditional way and make child frames solely for displaying text?

> a child frame is basically just a normal Emacs frame (isn't it?)

Yes it is, but reparented to another frame in X11.  We can only detect if a frame is selected (not necessarily focused).

**Comment by dakra** [comment]
> So when should it accept input then? If this is done
> programmatically, why not just receive input the
> traditional way and make child frames solely for displaying text?

The idea behind
[child-frame-read-string](https://github.com/Alexander-Miller/cfrs)
is that the user doesn't have to "look down" to the minibuffer and
can simply input text where his cursor and focus is.

`company-childframe` needs input to change autocomplete selections.


(Maybe I didn't understand your question right and you
mean something else)

**Comment by ch11ng** [comment]
I mean we don't really need to make child frame accept input directly.  Instead input can come from its parent frame / minibuffer and the text is also displayed in the child.  Perhaps this implementation is not applicable in some scenarios.

**Comment by dakra** [comment]
@ch11ng I'm not sure if I'm supposed to do something and you're waiting for me.

Should I suggest/make changes to the child frame libraries (`cfrs` and `company-childframe`)?
I could certainly make a PR to those projects if you say e.g. the correct way to focus frames
would be to call `(select-frame posfr)` after `(x-focus-frame)`.

But as I understand you suggest that the implementation how those libs read input should be different and they shouldn't switch focus of frames at all?!

**Comment by ch11ng** [comment]
@dakra It were merely suggestions to hopefully make those packages compatible with EXWM.  The problem is EXWM refreshes input focus constantly so it need to know which child frame should get the input focus. 
But since `x-focus-frame` is quite low-level and there is no such record, there is nothing much can be done on our side.

BTW I'm not sure if those packages are intended for other platforms.  If so, the use of `x-focus-frame` is a little bit nasty.

**Comment by dakra** [comment]
OK, thanks for the explanation. I'll close this issue for now and try to fix packages upstream if possible.

Many thanks for exwm and your support. Really love it :)
