### ISSUE TITLE
Question : how to advice switch-to-buffer to work for floating windows

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#593]
When a floating window is hidden, normal switch-to-buffer doesn't work, we have to use exwm-workspace-switch-to-buffer. Since ivy-switch-buffers uses switch-to-buffer, I think it would be nice to advice that function. The following is borrowed from exwm-workspace-switch-to-buffer, but it doesn't work. But if I save exwm--floating-frame in a variable and I can use select-frame-set-input-focus to switch to it.

    (advice-add 'switch-to-buffer :around 'my-exwm-workspace-switch-to-buffer)

    (defun my-exwm-workspace-switch-to-buffer (orig-func buffer-or-name &rest args)
    (when buffer-or-name
        (with-current-buffer buffer-or-name
        (if (derived-mode-p 'exwm-mode)
            ;; EXWM buffer.
            (if (eq exwm--frame exwm-workspace--current)
                ;; On the current workspace.
                (if (not exwm--floating-frame)
                    (switch-to-buffer buffer-or-name)
                    ;; Select the floating frame.
                    (message "select floating")
                    (select-frame-set-input-focus exwm--floating-frame)
                    (select-window (frame-root-window exwm--floating-frame)))
                ;; On another workspace.
                (if exwm-layout-show-all-buffers
                    (exwm-workspace-move-window exwm-workspace--current
                                                exwm--id)
                (let ((window (get-buffer-window buffer-or-name exwm--frame)))
                    (if window
                        (set-frame-parameter exwm--frame
                                            'exwm-selected-window window)
                    (set-window-buffer (frame-selected-window exwm--frame)
                                        buffer-or-name)))
                (exwm-workspace-switch exwm--frame)))
            ;; Ordinary buffer.
            (apply orig-func buffer-or-name args)))))

**Comment by ch11ng** [comment]
> When a floating window is hidden

Do you mean it's hidden with `exwm-floating-hide` or it's simply on an inactive workspace? I tested your snippet in both cases and found it working.  Actually you can simply call `exwm-workspace-switch-to-buffer` after ensuring it's an `exwm-mode` buffer.

**Comment by QiangF** [comment]
I mean exwm-floating-hide. It's would be better to be integrated in one command, and I use ivy-switch-buffer which has auto completion.

**Comment by ch11ng** [comment]
I mean you don't need to copy the content of `exwm-workspace-switch-to-buffer`; just call it in your function.

**Comment by QiangF** [comment]
No, replace this :

              (select-frame-set-input-focus exwm--floating-frame)
              (select-window (frame-root-window exwm--floating-frame)))
with 

              (exwm-workspace-switch-to-buffer buffer-or-name))

don't work too.
Can you please attached the working code in your test?

**Comment by ch11ng** [comment]
> Can you please attached the working code in your test?

I used your original snippet without any modification.

**Comment by QiangF** [comment]
Could it because I have the minibuffer detached

       (setq exwm-workspace-minibuffer-position 'bottom)

**Comment by ch11ng** [comment]
I had tested it with minibuffer detached.

**Comment by QiangF** [comment]
Finally, I got it to work with ivy.

    (defun my-exwm-workspace-switch-to-buffer (orig-func buffer-or-name &rest args)
    (when buffer-or-name
    (if (or exwm--floating-frame
            (with-current-buffer buffer-or-name exwm--floating-frame))
        (exwm-workspace-switch-to-buffer buffer-or-name)
        (apply orig-func buffer-or-name args))))
            (derived-mode-p 'exwm-mode)

    (advice-add 'switch-to-buffer :around 'my-exwm-workspace-switch-to-buffer)
    (advice-add 'ivy--switch-buffer-action :around 'my-exwm-workspace-switch-to-buffer)
