### ISSUE TITLE
exwm--fullscreen void

### ISSUE THREAD

**Issue by adouzzy** [ch11ng/exwm#6]
I used the config settings on the wiki
(exwm-reset) give symbol's value is void : exwm--fullscreen
when I M-x exwm-floating-toggle-floating gives exwm--floating-frame void.

My git head is 3fb90b. My emacs is built from git.

Any ideas?

**Comment by ch11ng** [comment]
What's the error message if you put `(setq debug-on-error t)` in your `~/.emacs`?

**Comment by adouzzy** [comment]
﻿Error Message:
Symbol's value as variable is void: exwm--fullscreen

(if exwm--fullscreen (progn (exwm-layout-unset-fullscreen)))
  (save-current-buffer (set-buffer (window-buffer (selected-window))) (if
exwm--fullscreen (progn (exwm-layout-unset-fullscreen)))
(exwm-input-grab-keyboard))
  exwm-reset()
  funcall-interactively(exwm-reset)
  call-interactively(exwm-reset nil nil)
  command-execute(exwm-reset)


On Thu, Aug 6, 2015 at 4:00 PM, Chris Feng <notifications@github.com> wrote:

> What's the error message if you put (setq debug-on-error t) in your
> ~/.emacs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ch11ng/exwm/issues/6#issuecomment-128257145>.
>



-- 
Zeyu Zhou,
Department of Mathematics and Statistics,
University of Melbourne
Victoria 3010
AUSTRALIA

**Comment by ch11ng** [comment]
All right, I see an error in the code. But why do you call `exwm-reset` then? It's intended for switching from `char-mode` to `line-mode` and exiting fullscreen.

**Comment by adouzzy** [comment]
You are right. exwm was not functioning correctly when I first installed it. So I keep pressing keys... It was just wired. 
After I did nothing, It's working fine now.
