### ISSUE TITLE
[Question] how to use exwm as second session

### ISSUE THREAD

**Issue by poulpoulsen** [ch11ng/exwm#601]
hello,
currently i'm using Linux Mint 19.1 with xfce.
I want to test exwm and therefore use it as second session. So i could choose session exwm and session xfce on the login screen.
Is this possible?
Because i'm not a programmer, is there any complete script for this purpose?

Best wishes
Poul

**Comment by ch11ng** [comment]
You mean a session configuration file? Basically you have to put a `exwm.desktop` file under `/usr/share/xsessions` and ensure the `Exec` entry points to your Emacs binary, or some script that starts EXWM.

**Comment by poulpoulsen** [comment]
Chris Feng <notifications@github.com> writes:

> You mean a session configuration file? Basically you have to put a
> exwm.desktop file under /usr/share/xsessions and ensure the Exec
> entry points to your Emacs binary, or some script that starts EXWM.
hello,
yes this is what i want to do.
i will try that.

Regards
Poul

**Comment by medranocalvo** [comment]
Closing.  Please reopen if you still find difficulties.
