### ISSUE TITLE
Neo keyboard layout - certain key sequences don't work globally

### ISSUE THREAD

**Issue by WhatDothLife** [ch11ng/exwm#603]
I am using the neo ergonomic keyboard layout and encountered the problem, that certain key sequences, that are bound globally, don't work in char-mode.
This concerns the key sequences starting with a modifier-key, followed by a symbol of the third (e.g. "C-=", "s-*" ) or fourth layer ("s-kp-1", "M-¿"). Yet, the sequences are recognized in line-mode and work fine there (except for "s-kp-1"!).
I used the helpful-key function to find out what key event is actually happening instead, but it seems like there is no valid key event at all (function doesn't respond).
Telling from this, pressing modifier-keys in char-mode blocks the use of the neo-modifier-keys of third and fourth layer.

Since those bindings work in line-mode, this should be a rather quick fix. If I forgot to mention any important details, or you need more information regarding the neo  layout, I'll be happy to provide them. Thank you for your work on EXWM!

**Comment by ch11ng** [comment]
Thanks for the report! I've identified a bug in converting Emacs events to their X11 counterparts.  I've pushed fixes to XELB and EXWM.  Please update both repos and see whether the problem persists.

**Comment by WhatDothLife** [comment]
It all works fine now, thanks a lot!
