### ISSUE TITLE
`exwm-mode-map` hard codes keybindings (cf. ["Toggle mode-line" exwm-layout-toggle-mode-line :keys "C-c C-t C-m"])

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#605]
Based on  [EXWM User Guide: Local Key Bindings](https://github.com/ch11ng/exwm/wiki#local-key-bindings), I had disabled the `C-c` prefix keys with 

> (define-key exwm-mode-map (kbd "C-c") nil)

Even then, the `EXWM` menu entry was indicating that mode line could be toggled with`C-c C-t C-m`.  I was confused, because I had /explicitly/ disallowed `C-c` prefix bindings.  

On further investigation, I noticed that `exwm-mode-map` (cf. [exwm-core.el#L254](https://github.com/ch11ng/exwm/blob/c5794765362460b5c18fdedb3f77617fb34ee804/exwm-core.el#L254),  hard-codes the kebinding like so

> ["Toggle mode-line" exwm-layout-toggle-mode-line :keys "C-c C-t C-m"]

Why is the need for hard-coding of keys, when Emacs itself takes care of inserting a suitable suggestion based on user's active configuration.

**Comment by ch11ng** [comment]
Perhaps it was to make <kbd>C-m</kbd> rendered as <kbd>C-m</kbd> rather than <kbd>RET</kbd> (though they are the same).  It turns out to be a bad idea.  I'll remove them.

**Comment by ch11ng** [comment]
Done.
