### ISSUE TITLE
Mismatch Between Emacs Buffer List and GNOME Panel's Window List

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#607]
### Mismatch Between Emacs Buffer List and GNOME Panel's Window List

0. Setup a `EXWM GNOME Flashback` session with `GNOME Panel ` enabled.    See https://github.com/ch11ng/exwm/issues/606 for details on how to accomplish this step.
1. Make sure that the GNOME Panel displays the windows
2.  Open firefox via the panel menu.  I have used firefox this bug report.  It doesn't really matter if the app that is lauched is firefox or something else.
1. Do `C-x C-b`.
2. In the `*Buffer List*` window, kill firefox  with `k`.
3.  Refresh the `*Buffer List*` with `g`. Ensure that the firefox window is indeed gone from the `*Buffer List*`.
4. Note that the firefox window is still shown.
4. Now look at the window list on the `GNOME Panel`.  Yep.  The window is still there.
5.  Now `C-x b` to the firefox window and `C-x k` it.
6. Note that the firefox window disappears, and is removed from GNOME Panel's window list.

See the screenshot below for details.  The screenshot shows that the `k` on a `*Buffer List* window, doesn't actually kill that window.

![`k` on `C-x C-b` buffer doesn't kill the corresponding EXWM window](https://user-images.githubusercontent.com/42199775/62514074-a4dc6800-b83b-11e9-9d2a-b64755cb6aca.png)

**Comment by emacksnotes** [comment]
Closing this issue. (I got the title of the issue wrong)

**Comment by medranocalvo** [comment]
No problem.  (It was probably possible to edit the title clicking the `Edit` button at the top left, near the title.)

**Comment by emacksnotes** [comment]
> No problem. (It was probably possible to edit the title clicking the `Edit` button at the top left, near the title.)

How could I have missed the `Edit` button.  It is far to the right, really too far away from the title  ... ugh.
