### ISSUE TITLE
 `k` on `C-x C-b` buffer doesn't kill the corresponding EXWM window [GNOME Flashback + GNOME Panel]

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#608]
### `k` on `C-x C-b` buffer doesn't kill the corresponding EXWM window

(My /gut feeling/ is that the session details--GNOME Flashback Session + GNOME Panel--has no bearing on the issue at hand.  I am including the details for the sake of completion.)

0. Setup a `EXWM GNOME Flashback` session with `GNOME Panel ` enabled.    See https://github.com/ch11ng/exwm/issues/606 for details on how to accomplish this step.
1. Make sure that the GNOME Panel displays the windows
2.  Open firefox via the panel menu.  I have used firefox this bug report.  It doesn't really matter if the app that is lauched is firefox or something else.
1. Do `C-x C-b`.
2. In the `*Buffer List*` window, kill firefox  with `k`.
3.  Refresh the `*Buffer List*` with `g`. Ensure that the firefox window is indeed gone from the `*Buffer List*`.
4. Note that the firefox window is still shown.
4. Now look at the window list on the `GNOME Panel`.  Yep.  The window is still there.
5.  Now `C-x b` to the firefox window and `C-x k` it.
6. Note that the firefox window disappears, and is removed from GNOME Panel's window list.

See the screenshot below for details.  The screenshot shows that the `k` on a `*Buffer List* window, doesn't actually kill that window.

![`k` on `C-x C-b` buffer doesn't kill the corresponding EXWM window](https://user-images.githubusercontent.com/42199775/62514074-a4dc6800-b83b-11e9-9d2a-b64755cb6aca.png)

**Comment by emacksnotes** [comment]
This is not an `exwm` issue.  But an issue with `tablist-minor-mode` package.  I am taking this ball to their court. 

Closing the issue.

**Comment by medranocalvo** [comment]
I think you are misunderstanding `ibuffer` (<kbd>C-x C-b</kbd>).

The docstring of the <kbd>k</kbd> keybinding (you can find it with <kbd>C-h k k</kbd>):

```
k runs the command ibuffer-do-kill-lines (found in ibuffer-mode-map), which is
an autoloaded interactive compiled Lisp function in ‘ibuf-ext.el’.

It is bound to k.

(ibuffer-do-kill-lines)

Hide all of the currently marked lines.

[back]
```

Says that it *hides* marked lines, not that it kills the corresponding buffers.

Instead you probably want to hit <kbd>D</kbd> or <kbd>d</kbd> (<kbd>C-h k D</kbd>):

```
D runs the command ibuffer-do-delete (found in ibuffer-mode-map), which is an
interactive compiled Lisp function in ‘ibuffer.el’.

It is bound to D, <menu-bar> <operate> <do-delete>.

(ibuffer-do-delete)

Kill marked buffers as with ‘kill-this-buffer’.

[back]
```

**Comment by emacksnotes** [comment]
> I think you are misunderstanding `ibuffer` (C-x C-b).

`C-x C-b` runs 

```
C-x C-b runs the command list-buffers (found in global-map), which is
an interactive compiled Lisp function in ‘buff-menu.el’.

It is bound to C-x C-b, <menu-bar> <buffer> <list-all-buffers>.

(list-buffers &optional ARG)

Display a list of existing buffers.
The list is displayed in a buffer named "*Buffer List*".
See ‘buffer-menu’ for a description of the Buffer Menu.

By default, all buffers are listed except those whose names start
with a space (which are for internal use).  With prefix argument
ARG, show only buffers that are visiting files.

[back]
```

To add to my close-ing comment

> [This is not an exwm issue. But an issue with tablist-minor-mode package. I am taking this ball to their court. Closing the issue.](https://github.com/ch11ng/exwm/issues/608#issuecomment-518517587)

what really happening was this.

`Buffer-menu-mode` derives from `tabulated-list-mode`

> (define-derived-mode Buffer-menu-mode tabulated-list-mode "Buffer Menu"

and I have hooked `tablist-minor-mode` with `tabulated-list-mode` (See [How I shortlist add-ons for my Emacs: Introducing `tablist`](https://emacsnotes.wordpress.com/2019/04/16/how-i-shortlist-add-ons-for-my-emacs-introducing-tablist/))as below

> [(add-hook 'tabulated-list-mode-hook 'tablist-minor-mode)](https://github.com/emacksnotes/emacsnotes.wordpress.com/blob/a382a312e2472937e95624a33f06bb4a9cacb7b6/my-tablist-minor-mode-menu.el#L3)

and `tablist-minor-mode` was overriding the `Buffer-menu-mode`'s `k` with it's own

```
k runs the command tablist-do-kill-lines (found in
tablist-minor-mode-map), which is an interactive compiled Lisp
function in ‘tablist.el’.

It is bound to k, <menu-bar> <Tablist Misc> <Do Kill Lines>.

(tablist-do-kill-lines &optional ARG INTERACTIVE)

Remove ARG lines from the display.

[back]
```

This was creating some confusion.

I have worked around this issue by re-working my `.emacs`.
