### ISSUE TITLE
exwm starts emacs in a small window

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#61]
I am happy that I got exwm running at all, but its a bit strange I thought emacs is supposed to be fullscreen and in buffers u have the x apps.

But I only see a small Emacs window the rest is black and when I start a programm with s-& I can move it outside of emacs.

Any idea what I do wrong?

**Comment by spiderbit** [comment]
the xhost + line fixed that problem.

So emacs is fullscreen now.

next problem is when I try to start something with s-& I get the error:

error in process filter: if: Wrong number of arguments: ((t) (newname) "Rename a bufferv" (let ((hidden...

I search for old issues if I find that prob.

**Comment by ch11ng** [comment]
It's due to two typos in the configuration example, and @fm4d has already fixed it. You may search `exwm-workspace-rename-buffer` and correct those typos accordingly.
