### ISSUE TITLE
Impossible to answer y-or-n-p prompt in EXWM if X window is focussed

### ISSUE THREAD

**Issue by moritzschaefer** [ch11ng/exwm#611]
After getting the suggestion to report this issue as a bug on [Stackoverflow](https://emacs.stackexchange.com/questions/52029/impossible-to-answer-y-or-n-p-prompt-in-exwm-if-x-window-is-focussed):
When a y-or-n-p question (e.g. The file you want to open is very large. Really want to open it?) pops up in the minibuffer while an EXWM buffer is focussed, I have no option to answer the question (using y or n).

In that situation, ALL inputs are forwarded to the buffer's X window, including key bindings I use for EXWM (for example s-q to close the current window/buffer or s-w to change the active window).

In order to rescue the situation, I have to close the active window (if it's got a menu to do so, as I can't use my exwm hotkeys), which allows me to answer the question (in case the subsequently focussed window is an Emacs (text) buffer).

I have no clue how/why inputs are handled in a different way during this (y-or-n-p) question (probably because it's blocking the Emacs event queue which is required for handling X commands?).

How can I debug/fix this issue?

**Comment by medranocalvo** [comment]
I think this was discussed in #255, and @demokritos even implemented a patch (https://github.com/demokritos/exwm/tree/fix-y-or-n), but it never made it back.

@moritzschaefer: Could you try that patch and report back?

@demokritos: would you be willing to submit the patch?  For such a small change no copyright assignment should be needed.

**Comment by moritzschaefer** [comment]
@medranocalvo Indeed I experience the same issue when an appliation is frozen and killed! That patch however is specific to the application-freezing problem. Is there a way to "patch"/overwrite the `y-or-n` function such that it always calls `exwm-input-grab-keyboard` before calling `y-or-n`?

**Comment by Stebalien** [comment]
I've worked around this by setting line-mode passthrough when a transient map is set:

```elisp
      (define-advice set-transient-map (:around (fun map &optional keep-pred on-exit) exwm-passthrough)
        (setq exwm-input-line-mode-passthrough t)
        (let ((on-exit (lexical-let ((on-exit on-exit))
                         (lambda ()
                           (setq exwm-input-line-mode-passthrough nil)
                           (when on-exit (funcall on-exit))))))
          (funcall fun map keep-pred on-exit)))
```

I do the same for hydras:

```elisp
      (define-advice hydra-set-transient-map (:around (fun keymap on-exit &optional foreign-keys) exwm-passthrough)
        (setq exwm-input-line-mode-passthrough t)
        (let ((on-exit (lexical-let ((on-exit on-exit))
                         (lambda ()
                           (setq exwm-input-line-mode-passthrough nil)
                           (when on-exit (funcall on-exit))))))
          (funcall fun keymap on-exit foreign-keys)))
```

**Comment by demokritos** [comment]
@medranocalvo I have already made it as PR #578.

**Comment by ch11ng** [comment]
@demokritos Sorry I didn't notice there was an update.  Perhaps you should call `exwm-input-grab-keyboard` instead of `exwm-input--grab-keyboard` to update the mode-line in case user answers 'n'.

@moritzschaefer I think this is a different issue.  I tried to open a large file and was able to make the answer.  Did you put the X window in char-mode? If so how did you manage to open a file with the X window focused?

**Comment by moritzschaefer** [comment]
@ch11ng My browser opens files, after a download finished, with emacsclient, that's why it happens I guess.

**Comment by moritzschaefer** [comment]
I use char-mode all the time (I'm using spacemacs so that fits me better ATM). 

Thanks for the point in the right direction @Stebalien. This is what works for me:

```
(defun exwm-y-or-n-p-wrapper (orig-fun &rest args)
  (let ((is-exwm-mode (derived-mode-p 'exwm-mode))
        (is-fullscreen (exwm-layout--fullscreen-p)))
    (when is-exwm-mode
      (when is-fullscreen
        (exwm-layout-unset-fullscreen))
      (call-interactively #'exwm-input-grab-keyboard))
    (let ((res (apply orig-fun args)))
      (when is-exwm-mode
        (call-interactively #'exwm-input-release-keyboard)
        (when is-fullscreen
          (exwm-layout-set-fullscreen))
        )
      res)))
```

@ch11ng if you think this might help others, I'd be happy to open a PR.

**Comment by ch11ng** [comment]
@Stebalien @moritzschaefer Thanks for the idea! I've worked out a more generic solution.  Please checkout 5b9f4b0851d27e8132a930dfbfec0b94099a4c9f.

**Comment by moritzschaefer** [comment]
Smart, thank you. I really appreciate the work!

**Comment by divansantana** [comment]
@moritzschaefer @Stebalien I've tried your suggestions on the work around. I don't yet know lisp, so don't quite understand it.

I've evaluated and tried both code but the issue still occurs. If you could ellaborate on how to apply the work around, would be greatly appreciated.
