### ISSUE TITLE
Provide an informationla message, when EXWM creates new workspace to honor a new frame

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#613]
### Provide an informationla message, when EXWM creates new workspace to honor a new frame

This is a add-on bug to https://github.com/ch11ng/exwm/issues/606.  

New [Emacs frames => New workspace](https://github.com/ch11ng/exwm/issues/560#issuecomment-478331677) is so dramatic a change, that it left me baffled and confused.  It would help if EXWM pities users like me, and /prepares/ me for the transition.

For example, a simple message like "Created a new frame.  Switched to workspace x." will immensely help.

As noted in the bug, when the Ediff Conrol Panel was created in a new frame, I was a bit confused because all-of-a-sudden my source-code window disappeared and a mal-filled Ediff Panel appeared.  After a lot of digging around, I realized that I was in a new workspace and my source-code files were in a different workspace.  (Yep. My edits weren't lost because of a crash. Knowing this was a big relief) .  The workspace list in the GNOME Flashback panel merely confirmed what I found out in this wiki.

This could be a one-line change.  But in terms of user-experience it is a big improvement.

**Comment by ch11ng** [comment]
Thanks! Added in dd6f5c36edf62f8c9d3c98a77b0d22b141663f6c.

**Comment by emacksnotes** [comment]
> Provide an informationla message, when EXWM creates new workspace to honor a new frame
>> Thanks! Added in dd6f5c3.

>> `(message "Added %s as workspace %d" frame exwm-workspace-current-index)`

As I was doing other things. I was wondering 

1. which workspace I moved out from.  I wanted to switch back to it.
2. `Added` => `Created` + `Switched`.  The two operations are orthogonal.   A user may want to know which of those two happened, particularly when EXWM does some background magic, without any user intervention.

**Comment by ch11ng** [comment]
Okay I'll add that.
