### ISSUE TITLE
Systemtray gets pushed off the screen

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#615]
When starting a window mapped as a STRUT (e.g., lemonbar), the exwm systemtray disappears. Running `(exwm-systemtray--exit)` followed by `(exwm-systemtray--init)` fixes the issue.

I'm guessing that EXWM needs to recalculate the position of the systemtray when the available screen space changes.

**Comment by ch11ng** [comment]
This is a regression.  I've pushed a fix (1f2bd54c117b3eeb88b6af1e8627030f00e37898).  Thanks for the report!
