### ISSUE TITLE
Suggestion for improving the prompt strings in `exwm-input-set-simulation-key`.

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#616]
### Suggestion for improving the prompt strings in `exwm-input-set-simulation-key`.

When the above command prompted me for `"Original keys"`,  I was baffled.  I was baffled because the term is `relative`.    Is `Emacs` original?  Is the `X Client` original? What is `Original` or `Fake` depends on which side of the shore you are, and in what direction  you look.  

So, when I invoked the above command for first time, I froze completely.  I couldn't respond immediately without also answering the /meta/ questions that you see above.

Fortunately, I got help from the docstring.

```
(defcustom exwm-input-simulation-keys nil
  "Simulation keys.

It is an alist of the form (original-key . simulated-key), where both
original-key and simulated-key are key sequences.  Original-key is what you
type to an X window in line-mode which then gets translated to simulated-key
by EXWM and forwarded to the X window.
```

Based on the above docstring ....

### I suggest re-writing of prompts as below:

1. "Original keys"  =>  "What you type (in Emacs)"  / "Translate from"
2. ""Simulate %s as" =>  "What the X Client (or the Application) Sees"  / "What EXWM sends to  App"  / "Translate to". 

Prompt in (1) above is probably confusing as the one I request you to replace.  

BUT I do /not/ have the same hesitation in regard to (2).  

------

### Suggestion for modifying the menu entry for simulation keys

I am used to thinking in terms of "What I Input" and "What is Output".  This is probably so for most people. 

The Emacs command for simulation keys takes you from `input-to-output`.  But the menu entry for simulation keys is `output-to-input`.  Consider the screenshot below.  

![Menu for Simulation Keys](https://user-images.githubusercontent.com/42199775/62817526-065f4800-bb56-11e9-8828-e05109a9d2c5.png)

Do you now see why my confusion in regard to setting up simulation keys was magnified manifold?  Not only was I forced to ask and answer some /meta/ questions, I was also asked to /adopt drastically opposing perspectives/ at the same time. The cognitive load I was asked to bear was too heavy for me.

#### My suggestion in regard to menu entries are 

(1) Transpose the two columns in the menu
(2) Add a dummy entry to the menu which labels the columns.

I would prefer (1) and (2).  At the minimum, I would like you to adopt (2).

_**To appreciate this report, EXWM experts need to put themselves in someone new to EXWM, who understands nothing whatsoever about EXWM and relies solely on intuition.**_

**Comment by ch11ng** [comment]
> My suggestion in regard to menu entries are
> (1) Transpose the two columns in the menu
> (2) Add a dummy entry to the menu which labels the columns.

The display order of entry name and keys is enforced by Emacs so (1) is not feasible.

Please check if the following patch works for you.

```
diff --git a/exwm-core.el b/exwm-core.el
index 287fc6f71..0c42d5443 100644
--- a/exwm-core.el
+++ b/exwm-core.el
@@ -265,7 +265,8 @@ One of `line-mode' or `char-mode'.")
     ;; This is merely a reference.
     ("Send simulation key" :filter
      (lambda (&rest _args)
-       (let (result)
+       (let ((result '(["Translate from *RIGHT* to *LEFT*" #'ignore nil]
+                       "---")))
          (maphash
           (lambda (key value)
             (when (sequencep key)
diff --git a/exwm-input.el b/exwm-input.el
index ababbb6e7..e9017ec98 100644
--- a/exwm-input.el
+++ b/exwm-input.el
@@ -975,10 +975,11 @@ ends unless it's specifically saved in the Customize interface for
 `exwm-input-simulation-keys'."
   (interactive
    (let (original simulated)
-     (setq original (exwm-input--read-keys "Original keys" ?\C-g))
+     (setq original (exwm-input--read-keys "Translate from" ?\C-g))
      (when original
        (setq simulated (exwm-input--read-keys
-                        (format "Simulate %s as" (key-description original))
+                        (format "Translate from %s to"
+                                (key-description original))
                         ?\C-g)))
      (list original simulated)))
   (exwm--log "original: %s, simulated: %s" original-key simulated-key)
```

**Comment by emacksnotes** [comment]
> Please check if the following patch works for you.
> 
> ```
> diff --git a/exwm-core.el b/exwm-core.el
> index 287fc6f71..0c42d5443 100644
> --- a/exwm-core.el
> +++ b/exwm-core.el
> @@ -265,7 +265,8 @@ One of `line-mode' or `char-mode'.")
>      ;; This is merely a reference.
>      ("Send simulation key" :filter
>       (lambda (&rest _args)
> -       (let (result)
> +       (let ((result '(["Translate from *RIGHT* to *LEFT*" #'ignore nil]
> +                       "---")))
>           (maphash
>            (lambda (key value)
>              (when (sequencep key)
> ```


> The display order of entry name and keys is enforced by Emacs so (1) is not feasible.

Don't use `:keys`.  

That is ...

### Instead of generating this

```elisp
(["Translate from *RIGHT* to *LEFT*" #'ignore nil]
 "---"
 ["C-v"
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(22))
      (exwm-input--fake-key i)))
  :keys "C-y"]
 ["C-x"
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(24))
      (exwm-input--fake-key i)))
  :keys "C-w"]
 ["C-c"
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(3))
      (exwm-input--fake-key i)))
  :keys "M-w"]
 ["C-c"
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(3))
      (exwm-input--fake-key i)))
  :keys "<escape> w"])
```

### you may want to generate some variation of this

```elisp
("From                     To                       " "---"
 ["C-y                      C-v                      "
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(22))
      (exwm-input--fake-key i)))]
 ["C-w                      C-x                      "
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(24))
      (exwm-input--fake-key i)))]
 ["M-w                      C-c                      "
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(3))
      (exwm-input--fake-key i)))]
 ["<escape> w               C-c                      "
  (lambda nil
    (interactive)
    (dolist
	(i
	 '(3))
      (exwm-input--fake-key i)))])
```

**Comment by medranocalvo** [comment]
I understand the confusion.  Nevertheless, I think the following let us keep the convention of showing the keys at the right, while being clear on what gets sent:

```
Send C-v      C-y
Send C-x      C-w
Send C-c      M-w
```

**Comment by emacksnotes** [comment]
I have another thought.  It could be perceived (rightfully) as a needless bloat.  Nevertheless,  I will register it, FWIW.

The confusion is not about how the key sequences are rendered on the menu.  The confusion is because one is looking at two key sequences: one applies to the X Client, the other applies to Emacs (for want of a better term).  

When inputting simulated keys, if one were to input a purpose, in addtion to From and To key sequences, it would not only serve as a 'literate' documentation on what /function/--cut, copy, paste, undo etc--the key sequence achieves, but also serve as the text portion of menu item.  As a programmer, I understand that adding such a 'purpose'/'function' field will 'disrupt' the plist data type, and adds needless complexity with the questionable merit.

**Comment by emacksnotes** [comment]
> I understand the confusion. Nevertheless, I think the following let us keep the convention of showing the keys at the right, while being clear on what gets sent:
> 
> ```
> Send C-v      C-y
> Send C-x      C-w
> Send C-c      M-w
> ```

I like this suggestion too.

**Comment by ch11ng** [comment]
> FWIW, in the screenshot that I shared, I used **`(format "%-20s%-20s" ...)`** to sneak in sufficient amount of whitespace in the menu entry's text.

The text is not aligned though.  Or perhaps still use `:keys` but improve the description?

```
Send 'C-v'      C-y
Send 'C-x'      C-w
Send 'C-c'      M-w
```

**Comment by emacksnotes** [comment]
> > FWIW, in the screenshot that I shared, I used **`(format "%-20s%-20s" ...)`** to sneak in sufficient amount of whitespace in the menu entry's text.
> 
> The text is not aligned though. 

It is just a matter of adjusting the field specifiers, right?

> Or perhaps still use `:keys` but improve the description?
> 
> ```
> Send 'C-v'      C-y
> Send 'C-x'      C-w
> Send 'C-c'      M-w
> ```

Sounds good to me.  Could you please commit the above change?

**Comment by ch11ng** [comment]
> It is just a matter of adjusting the field specifiers, right?

The field width should be calculated dynamically though.

> The above change sounds good to me. Could you please commit the above change?

Done.

**Comment by emacksnotes** [comment]
> diff --git a/exwm-input.el b/exwm-input.el
> index ababbb6e7..e9017ec98 100644
> --- a/exwm-input.el
> +++ b/exwm-input.el
> @@ -975,10 +975,11 @@ ends unless it's specifically saved in the Customize interface for
>  `exwm-input-simulation-keys'."
>    (interactive
>     (let (original simulated)
> -     (setq original (exwm-input--read-keys "Original keys" ?\C-g))
> +     (setq original (exwm-input--read-keys "Translate from" ?\C-g))
>       (when original
>         (setq simulated (exwm-input--read-keys
> -                        (format "Simulate %s as" (key-description original))
> +                        (format "Translate from %s to"
> +                                (key-description original))
>                          ?\C-g)))
>       (list original simulated)))
>    (exwm--log "original: %s, simulated: %s" original-key simulated-key)

You have left this part of the patch.  Could you please fix the prompt strings as above?

**Comment by ch11ng** [comment]
Indeed.  I'll do that.
