### ISSUE TITLE
When using apps like browsers, how would one enter passthrough mode until a defined key is pressed?

### ISSUE THREAD

**Issue by skallinen** [ch11ng/exwm#621]

**Comment by ch11ng** [comment]
Did you mean char-mode when saying 'passthrough mode'? If so then make a global key binding that binds that specific key to `exwm-input-grab-keyboard` is enough.  `exwm-reset` (<kbd>s-r</kbd>) can also be used.

**Comment by skallinen** [comment]
Meant something that sends all keystrokes to the app, regardless if they are emacs related keys such as C-* and so forth or not. Emacs does not do anything with the stroke until the exit keybinding is sent. Something like passthrough mode in the qutebrowser. Basically as far as I can understand the same as exwm-input-send-next-key, but something that instead of a counter keeps sending keys until the exit keybinding is detected.

**Comment by skallinen** [comment]
Ah, this indeed is the char-mode. Thought I tried it without luck for my use case, but it does now work. Thank you.

**Comment by skallinen** [comment]
I am a bit confused about char mode. Get the feeling it sometimes passes through all key strokes, but usually not. C-c ... is usually the problem. May be that there is a user error here. Need to use emacs keybindings in qutebrowser. Any ponters?

**Comment by skallinen** [comment]
Have a hack working like this:
`(cl-defun my-exwm-input-send-next-key (times &optional end-key)
  "Send next key to client window.
EXWM will prompt for the key to send.  This command can be prefixed to send
multiple keys.  If END-KEY is non-nil, stop sending keys if it's pressed."
  (interactive "p")
  (exwm--log)
  (let (key keys)
    (dotimes (i 200)
      ;; Skip events not from keyboard
      (let ((exwm-input-line-mode-passthrough t))
        (catch 'break
          (while t
            (setq key (read-key (format "Send key: %s (%d/%d) %s"
                                        (key-description keys)
                                        (1+ i) 100
                                        (if end-key
                                            (concat "To exit, press: "
                                                    (key-description
                                                     (list end-key)))
                                          ""))))
            (unless (listp key) (throw 'break nil)))))
      (setq keys (vconcat keys (vector key)))
      (message (key-description (list key)))
      (when (eq key 134217755) (cl-return-from my-exwm-input-send-next-key))
      (exwm-input--fake-key key))))

      (define-key exwm-mode-map [?\C-q] #'my-exwm-input-send-next-key)
`
Did not get the vanilla exwm-input-send-next-key to receive the end-key. How should one do to get that to work?

**Comment by skallinen** [comment]
having tested it a bit more the send-next-key function does not seem to send some keystrokes correctly. have problems at least with RET and DEL. basically would need char mode with one specified end-key.

**Comment by ch11ng** [comment]
> Get the feeling it sometimes passes through all key strokes, but usually not. C-c ... is usually the problem.

In char-mode global keys are still accessible.  However you can customize `exwm-input-global-keys` to only include the keys you want (`exwm-reset` of course).

Since you want to 'passthrough' keys to X windows most of the time, it'd be less efficient to use `exwm-input-send-next-key` than to work in char-mode and switch to line-mode occasionally.

**Comment by skallinen** [comment]
ok cool, sounds like a sensible approach for these situations to temporarily disable all global keys but the one to that returns from char mode. can / should I also temporarily disable all the prefix keys I don't want to be captured by emacs when in char mode?

**Comment by skallinen** [comment]
Thanks! Sounds like a good approach for these situations to temporarily disable all global keys but the one used to return to line with restored global keys. Doing some experiments so a few further questions:
Even though I disable all global keys, run `exwm-reset` emacs still capture C-c prefix when in an X app. For some reason, C- seems to be the only prefix captured though. M- nor S- for instance, are not captured. How would I change that? Was experimenting with the `exwm-input-prefix` but that did not seem to have any effect. 

My preference would be to write a function that saves the normal keybindings, disables all, but say `s-t`, toggles from line to char and resets. When `s-t` called from char the opposite would happen. It seems that currently, the only keys that I can capture are those beginning with C- but I would prefer to send all those to the app.

**Comment by skallinen** [comment]
Thanks! Sounds like a good approach for these situations when in `char` to temporarily disable all global keys but the one used to return to `line` with restored global keys. Doing some experiments so a few further questions:
Even though I disable all global keys, run `exwm-reset` emacs still captures `C-c` prefix when in an X app. For some reason, `C-` seems to be the only prefix captured though. `M-` nor `S-` for instance, are not. How would I change that? Was experimenting with the `exwm-input-prefix` but that did not seem to have any effect.

My preference would be to write a function that saves the normal keybindings, disables all, but say s-t, toggles from `line` to `char` and resets. When `s-t` called from `char` the opposite would happen. It seems that currently, the only keys that can be captured in `char` are those beginning with `C-` but I would prefer to send all those to the X app.

**Comment by skallinen** [comment]
Ok, think I've figured it out:
```      (exwm-input-set-key (kbd "C-c C-t C-t") #'exwm-input-toggle-keyboard)
      (exwm-input-set-key (kbd "C-c s-d") #'dmenu)
      (exwm-input-set-key (kbd "s-t") #'my-exwm-input-passthrough)

      (defun my-exwm-input-passthrough (&optional id)
        "Toggle between 'line-mode' and 'char-mode' with passthrough (only 's-t' captured all else passed to X app)."
        (interactive (list (when (derived-mode-p 'exwm-mode)
                             (exwm--buffer->id (window-buffer)))))
        (when id
          (exwm--log "id=#x%x" id)
          (with-current-buffer (exwm--id->buffer id)
            (cl-case exwm--input-mode
              (line-mode
               (progn
                 (message "passthrough enabled")
                 (setq exwm-input--global-prefix-keys '(s-t))
                 (exwm-input-release-keyboard id)))
              (char-mode
               (progn
                 (message "passthrough disabled")
                 (exwm-input--update-global-prefix-keys)
                 (exwm-reset)))))))
```
Thank you for your help and thank you for your hard work and this absolutely awesome project!!
