### ISSUE TITLE
IntelliJ blank window

### ISSUE THREAD

**Issue by fxkrait** [ch11ng/exwm#623]
OS: Arch Linux
local/intellij-idea-community-edition 2:2019.2-1

IntelliJ main window is blank (under tiling & floating), and unusable. 
However, the startup pop-ups work. 
I'm not too versed in debugging and/or emacs/elisp, but I can try and help.
This is the only application that shows this behavior.
I'm using the stock example config copy and pasted with some keybinding changes.

Video:
https://streamable.com/q5rfe

**Comment by fxkrait** [comment]
This might be related to #455, I'll see if I can figure out how to add that to my xsession.

**Comment by fxkrait** [comment]
Put the given fix in a .xsession file in home directory, restarted, and blank screen still occurs.
Am I supposed to edit /usr/share/xsessions/exwm.desktop that lightdm uses? If so how?

**Comment by fxkrait** [comment]
From #377, this appears to be an issue strictly with java. I'm still trying to get the fix working for me.

**Comment by fxkrait** [comment]
OK, using example xinitrc, adding wmname LG3D, issue is fixed.
I guess I should have done more  thorough research on this, and not just assume it was something strictly with intelliJ

**Comment by fxkrait** [comment]
Also, for future reference to anyone: You **do not** need to modify any lightdm/dm specific xsession (/usr/share/xessions/exwm.desktop)
the local .xinitrc xsession changes will get picked up by lightdm and for any xsession it has.
So just modify the .xinitrc, lightdm should pick up the changes.
 You do not have to use startx to use the .xinitrc, lightdm will use the .xinitrc additions automatically.

**Comment by fxkrait** [comment]
Actually, this lightdm is not reading my .xintirc, and is just evaluating the /usr/share/xsession/exwm.desktop file. 
You are going to have to Ctrl-Alt-2 + startx to run the .xinitrc from a console.

**Comment by medranocalvo** [comment]
There‘s some info on the FAQ wrt Java: https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#java-applications-not-drawing-properly. Please try whether that solves the issues and add the wmname trick if that‘s not the case. You could also mention Intellij explicitely, so that it‘s easier to find.
Thanks in advance.

**Comment by fxkrait** [comment]
@medranocalvo Note: This **issue is solved**. Intellij is affected like all java programs, there is nothing special about intellij per se in this case. Using the given java fixes which are found in the exwm example .xinitrc **solves** the issue (https://github.com/ch11ng/exwm/blob/master/xinitrc).
The only issue is now that I have to use startx to load this said custom .xinitrc and cannot use lightdm, but I can make a new issue for that later if I can't figure it out.
