### ISSUE TITLE
[elisp help] Need some help binding Super+Shift in exwm-input-global-keys

### ISSUE THREAD

**Issue by fxkrait** [ch11ng/exwm#624]
I'm trying to bind `Super + Shift + h` in exwm-input-global-keys
I have a partially working solution:
`([(super shift h)] . buf-move-left)` , however it does not work in X-buffers that are in **line** mode
The following keybinding works in all cases, however it is not the keybinding that I want:
`([?\s-g] . buf-move-left)`

I've tried the following, but they give me` Invalid read syntax: "?"`
(I'm new to elisp, these are just some other attempts I tried, probably incorrect syntax)
```
([?\s-S-h] . buf-move-left)
([?\s-?\S-h] . buf-move-left)
```

Is there a way to get the `Super + Shift + h` binding working globally?

**Comment by fxkrait** [comment]
There is a regression that occurs when adding `([(super shift h)] . buf-move-left)`:
 - char mode: urxvt terminal (X-based) becomes read only
 - line mode: urxvt terminal (X-based) you can not do Control + C 
   - [It just waits for future input ( C-c- ) ]

I don't know if that's a bug, or just a side effect of bad lisp being entered.

For now `([?\s-g] . buf-move-left)` works great.
 I might just have to pick different bindings if I can not bind `Shift + Super`.

**Comment by emacksnotes** [comment]
`M-: (kbd s-H)` => `[8388680]`

In `exwm-input-global-keys`, you can add an entry like the one below

```elisp
 ([8388680]
      . ignore)'
```

**Comment by ch11ng** [comment]
@fxkrait Please check if @emacksnotes 's solution works for you.  BTW you are encouraged to customize `exwm-input-global-keys` instead so you won't have to deal with the key syntax.

**Comment by fxkrait** [comment]
OK. I've got it working by adding `([?\s-H] . buf-move-left)` to `exwm-input-global-keys`
I see I can combine shift and a letter, and just use the capital letter itself.
Thanks for the help!
