### ISSUE TITLE
exwm-xim in char-mode prints "nil" to echo area

### ISSUE THREAD

**Issue by TatriX** [ch11ng/exwm#626]
When I `(toggle-input-method)` to non-default one (Cyrillic in my case) and type in a buffer with a running app in the `char-mode`, after every letter  "nil" is printed in the echo area.

**Comment by ch11ng** [comment]
It appears `input-method-use-echo-area` (enforced by EXWM) makes the `cyrillic-jcuken` input method (not sure if you meant this one) print ' nil' on every key stroke.  Please checkout ddc22f2feddd99ff488f5f1c03b4f059e353056a for the fix.

**Comment by TatriX** [comment]
Yes, it works as intendant, thanks!
