### ISSUE TITLE
exwm-workspace-move-window fails for non X windows.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#627]
Trying to move regular emacs window results in error.

**Comment by ch11ng** [comment]
Fixed in d63dc6a82a44c1e918b93c4f50e5d4274ad6d21a.  Thanks for the report!

**Comment by fxkrait** [comment]
How are we supposed to move "non-exwm" (Non-X) windows between exwm-workspaces if exwm-workspace-move-window does not allow this? Is this not possible?

**Comment by ch11ng** [comment]
Indeed, there's no point in 'moving' a non-exwm-mode buffer with `exwm-workspace-move-window`.  Nevertheless we should handle the error when user have it bound to some global key and accidentally press that key.
