### ISSUE TITLE
Exwm/emacs crash frequently

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#63]
I experience frequent crashes, at least 2 every day. I can see the crash in coredumpctl:
```Thu 2015-09-17 15:22:05 CEST   2758  1000  1000  11 * /usr/bin/emacs-25.0.50 ```
but I am unable to find any actual error or reason behind them.

I run startx with  ```exec startx >> ~/.xsession-errors```, but there is nothing emacs related, only error is ```Fatal server error:
(EE) xf86OpenConsole: VT_ACTIVATE failed: Operation not permitted```.

in ~/.local/share/xorg/Xorg.0.log.old I found
```
(EE) BUG: triggered 'if (priv->num_active_touches == 0)'
(EE) BUG: synaptics.c:2963 in UpdateTouchState() 
(EE) Backtrace:
(EE) 0: /usr/lib/xorg/modules/input/synaptics_drv.so (_init+0x2e64) [0x7f6346d224b4]
(EE) 1: /usr/lib/xorg/modules/input/synaptics_drv.so (_init+0x4dc2) [0x7f6346d270d2]
(EE) 2: /usr/lib/xorg-server/Xorg (DPMSSupported+0xe8) [0x4778f8]
(EE) 3: /usr/lib/xorg-server/Xorg (xf86SerialModemClearBits+0x2b2) [0x4a1222]
(EE) 4: /usr/lib/libc.so.6 (__restore_rt+0x0) [0x7f634efc367f]
(EE) 5: /usr/lib/libc.so.6 (__select_nocancel+0x2a) [0x7f634f071e1a]
(EE) 6: /usr/lib/xorg-server/Xorg (WaitForSomething+0x1d7) [0x58f537]
(EE) 7: /usr/lib/xorg-server/Xorg (SendErrorToClient+0x111) [0x438c61]
(EE) 8: /usr/lib/xorg-server/Xorg (remove_fs_handlers+0x41b) [0x43cf4b]
(EE) 9: /usr/lib/libc.so.6 (__libc_start_main+0xf0) [0x7f634efb0610]
(EE) 10: /usr/lib/xorg-server/Xorg (_start+0x29) [0x427319]
(EE) 11: ? (?+0x29) [0x29]
```
but I dont think this error is non-emacs/exwm related, because this never happend to me with different window managers. Thanks for any help with debugging those.

**Comment by ch11ng** [comment]
Is there any way to reproduce it? The log file indicates that the crash is related to touchpad (but may be triggered by EXWM),

**Comment by fm4d** [comment]
So, after many crashes and empty logs, I am quite sure now that the problem is not related to the things I previously posted. Only traces are the fact that I witnessed the crash and the entry in coredumpctl. Ill leave this issue open for now and try to find a way how to find out whats going on. Maybe debugging the coredump in gdb could be the way.

**Comment by ch11ng** [comment]
How did you record the logs? They shouldn't be empty I think. Perhaps you forgot to redirect stderr (2>&1)?

**Comment by fm4d** [comment]
You are right, my redirect was wrong. Thanks, Ill update with errors after I experience another crash.

**Comment by fm4d** [comment]
I believe this can be closed now, everything seems very stable for last ~2 weeks.
