### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by divansantana** [ch11ng/exwm#630]
Hi,

Seems like a lot of good has happened since the previous release.

Specifically this bug #611 is fixed.

It would be great if a new stable release could be tagged :smile:

**Comment by emacksnotes** [comment]
> It would be great if a new stable release could be tagged smile

I was more or less making the same request.   

Just in case, if any one is interested in trying `exwm` even if it isn't tagged, they can follow the instructions here at https://github.com/ch11ng/exwm/issues/619#issuecomment-524634054

**Comment by ch11ng** [comment]
Sure.  Perhaps next weekend if no major fix is scheduled.

**Comment by divansantana** [comment]
@ch11ng hopefuly no major fixes are needed. New stable would be most welcome.

**Comment by ch11ng** [comment]
Please wait a few more days.  There are some fixes I suppose are necessary to be included in the next release.

**Comment by setzer22** [comment]
With 0.23 just released, I think this can be closed now. Right?

**Comment by ch11ng** [comment]
Sure.

**Comment by divansantana** [comment]
@ch11ng thanks! :smile:
