### ISSUE TITLE
Detecting memory leaks

### ISSUE THREAD

**Issue by TatriX** [ch11ng/exwm#633]
My Emacs with EXWM slowly leaks memory.
```
while (true) { ps -h -p `pidof emacs` -O rss | awk '{print $2;}' | tee emacs.log; sleep 1 }
```
![2019-08-27-135925_1447x1021_scrot](https://user-images.githubusercontent.com/703150/63769351-e27c6000-c8d2-11e9-8560-9ace8264680c.png)

Any advices on how can I find what is leaking memory?
```
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-23
EXWM commit d63dc6a
```

**Comment by TatriX** [comment]
If I run the same Emacs configuration under `awesome` WM, it doesn't leak.
It seems that every time I switch workspace ~1Mb of memory is leaked.

**Comment by ch11ng** [comment]
I do notice increasing memory usage here, but not after switching workspace.  The cause is not clear to me.  Now that you can reproduce this issue reliably, please take a took at various variables/functions described in `(info "Garbage Collection")` which show some internal statistics.

**Comment by TatriX** [comment]
Will do, thanks!

**Comment by TatriX** [comment]
BTW, running `(garbage-collect)` freezes my EXWM session.

**Comment by TatriX** [comment]
It seems that the reason why it's eating so much memory in my case is this:
```
;; Disable GC for startup. It will be restored in after-init-hook.
(setq gc-cons-threshold most-positive-fixnum)
(add-hook 'after-init-hook
          (lambda ()
              (setq gc-cons-threshold 800000))
```

**Comment by ch11ng** [comment]
But isn't `gc-cons-threshold` restored eventually?

**Comment by TatriX** [comment]
It is in `after-init-hook`. But for some reason collections do not happen afterwards. After I've removed that piece of code from my init file it became much better. Still sometimes Emacs's memory usage slowly grows to a bigger numbers. I will investigate it a bit more and if I find anything, I'll reopen this issue.

**Comment by TatriX** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37006
