### ISSUE TITLE
font sizes to small

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#64]
the size of the fonts in apps I start is horrible small.

If I start any application in exwm (gedit, conkeror, xterm, icecat) the fonts are very small. In Stumpwm this did somehow work.

I use a high dpi 4k Monitor so of course any standart sizes from the xserver will not work. Any idea what stumpwm could do differentlly and how I get it with exwm?

or maybe it was gdm that fixed it somehow. Still the question is how :) or do I have to change try to change the font size for every app seperatly.

**Comment by TLATER** [comment]
Stumpwm (haven't used it) probably either sets a custom GTK theme with a larger font or uses x settings to scale the DPI.

Set ```Xft.dpi``` in the .Xresources to whatever you like to adjust that, and change the font size in all application themes you use. It should be simple enough to figure out, otherwise the arch wiki has a great article on hidpi.

**Comment by ch11ng** [comment]
Font size is not managed by X window manager. Perhaps there is a setting hidden somewhere in X/GDM/StumpWM init files?

**Comment by spiderbit** [comment]
;; Set font for input box
(set-font "-*-terminus-*-*-*-*-30-*-*-*-*-*-*-*")

found that in config of stumpwm. Either I can set that somewhere or it has something to do with the PPI detection, seems like X detects here a wrong number.

A yes just saw it. Just thought first post here bugs that I cant find, I guess other people will have similar problems. In stumpwm there is this (set-font...) mechanism. 

So it was not clear to me how to do that. I dont would it call simple lets call it doable for people with much time :)

using mechanism from shurly 1980 when Xserver will be gone for good in 3 years or so, is nothing u should depend on.

and I should post that comment faster so I dont have to add more stuff to it when you answer :)

**Comment by spiderbit** [comment]
k Xft.dpi did the trick (thanks for the tipp, even I found it by my self in the archlinux doku).

So I guess Dell has buggy EDID infos.

**Comment by spiderbit** [comment]
I think I close this now, but good to have that documented, maybe it helps somebody

**Comment by ch11ng** [comment]
Thank you, @spiderbit. I'll do that.
