### ISSUE TITLE
`exwm-config` default is  too  opinionated when it recommends `ido`.  I don't use `ido`.

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#642]
### `exwm-config` default is  too  opinionated when it recommends `ido`.  No, I don't use `ido`.  

I don't have anything against `ido` or people using `ido`.  It is also possible that there are many users of `ido`--and any of the modern completion packages like `helm` or `ivy`.  Sorry, I got carried away--than there are other non users.

My problem is when the user guide recommends doing `exwm-config-default`, and I trust the recommendation as a good baseline config, only to find that `exwm-config` has surreptitiously loaded `ido` behind my back and messes with the workflow that I am habituated to.

Please move all `ido` related config elsewhere away from `exwm-config` (to say a `contrib` directory, in a file of it's own say `exwm-ido` or `exwm-workarounds` or `exwm-whatever`).

Let me reiterate,  EXWM is a popular package, and is getting increasingly mainstream.  So, it should be conservative when making recommendations.  

Stuff like this 

```elisp
  ;; Configure Ido
  (exwm-config-ido)
  ;; Other configurations
  (exwm-config-misc)
```
 
is better added as an `:options` in a `defcustom` for a relevant `hook` (either existent or a new one).

```elisp
 (defun exwm-config-misc ()
  "Other configurations."
  ;; Make more room
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (fringe-mode 1))
```

I really need menu for my Emacs.  I  cannot live without it, particularly those packages which I am exploring newly.

**Comment by ch11ng** [comment]
`ido` was chosen for 1) the default way to switch buffers between frames (a tiling and a floating frames in EXWM) requires <kbd>C-x 5</kbd>-prefixed keys which is awkward, and 2) `ido` is builtin.  This was solely to make a working example.

Again, codes in `exwm-config` are just examples.  Use of `ido` is not mandatory.

**Comment by shukryzablah** [comment]
I setup exwm today and I stumbled upon this problem too. I ended up copying the parts of the configuration that dealt with keybindings but not the part with ido nor how emacs looks. Did I have to do this or was there a simpler way?

**Comment by ch11ng** [comment]
@shukryzablah That's totally fine.  The `exwm-config` module is provided only as a working example, and users are free to configure EXWM in their own way.

**Comment by medranocalvo** [comment]
I think the solution here is to emphasize in the documentation that `exwm-config` is provided only for quick testing, and that it is inteded that users copy it to their configuration and adapt it to their needs.

**Comment by ch11ng** [comment]
Yes.  The user guide contains the following statement:

> **Note**: Do not use `(exwm-config-default)` in your `.emacs` when you have a customized configuration.

Perhaps it's not noticeable enough.

**Comment by medranocalvo** [comment]
> I think the solution here is to emphasize in the documentation ...
>> Yes. The user guide contains the following statement: ...

I retract my previous comment.

The actual solution is to rename `exwm-config.el` to `exwm-config-example.el`; especially renaming the function `exwm-config-default` to `exwm-config-example`.

This should take care of this confusion once and for all (incl. #644 and others).

**Comment by ch11ng** [comment]
@medranocalvo Sounds great! I've made the change: 624a30212cca1af99fda1417fd81c31eeba4cca8.  Note the wiki will remain unchanged until the next release.

**Comment by medranocalvo** [comment]
Thank you.  I hope it'll work.  Maybe renaming the file from `exwm-config.el` to `exwm-config-example.el`?

**Comment by ch11ng** [comment]
There are some functions there like `exwm-config-ido` and `exwm-config-misc` which might be useful.  So I didn't renamed the module altogether.

**Comment by medranocalvo** [comment]
That makes sense, thanks.

**Comment by ch11ng** [comment]
I'm closing this issue now.
