### ISSUE TITLE
any dropdown menu causes program crash

### ISSUE THREAD

**Issue by WorldsEndless** [ch11ng/exwm#647]
Running Tumbleweed OpenSUSE Linux, version from 2019.09.02 onward (it's a rolling release), any program attempting to open a dropdown menu (including the file menu) crashes and pops up the bug reporter, which also crashes as soon as you try to select what kind of bug you're reporting. When I leave exwm back to the KDE environment, I have no problems.

**Comment by ch11ng** [comment]
Haven't tried your exact setup but did you mean *any* dropdown menu? This is unlikely to happen unless you made some change to for example `exwm-manage-configurations` (could you confirm this?).  BTW do the dropdown menus of Emacs's own crash Emacs?

**Comment by WorldsEndless** [comment]
I haven't touched exwm-manage-configurations, to the best of my knowledge. Now I notice, for instance, that it doesn't appear to happen with Firefox dropdowns (e.g. file menu), nor does it happen with emacs filebar menus. 

Attempting a screenshot using Spectacle, trying use any of the dropdown options: 
![sserror2](https://user-images.githubusercontent.com/5042778/64490047-74129880-d216-11e9-920e-bf05605a50c7.png)

Then, KDE pops up the "submit bug report" and I attempt to select from the dropdown:
![sserror3](https://user-images.githubusercontent.com/5042778/64490061-9c9a9280-d216-11e9-8de7-0c851750bd47.png)

**Comment by ch11ng** [comment]
I installed Spectacle 18.04.0 and found no such problem (tried the 'Area', 'Tools', 'Export' and 'Save As' popups).  Can you reproduce this with a minimal configuration?

**Comment by WorldsEndless** [comment]
Re-installing spectacle didn't help me; perhaps it was a distribution upgrade. I've switched my screen shot program to Flameshot and installed dunst, so I'm taken careof now.
