### ISSUE TITLE
[Question] What's the recommended way to take screenshots while using EXWM?

### ISSUE THREAD

**Issue by WhatDothLife** [ch11ng/exwm#649]

**Comment by ch11ng** [comment]
I wonder if there is any screenshot application not working here as they are mostly 'general purpose' (all right there is one issue we are still investigating: #628).

**Comment by emacksnotes** [comment]
> What's the recommended way to take screenshots while using EXWM?

I have seen people using `scrot`.  For example,  you can see `scrot` mentioned in https://github.com/DamienCassou/desktop-environment.  

> all right there is one issue we are still investigating: https://github.com/ch11ng/exwm/issues/628

`gnome-screenshot` works too.  Only that there are some issues with window geometry.

**Comment by dakra** [comment]
I use `scrot` as well and wrote a simple package [here](https://github.com/dakra/scrot.el) that automatically
suggests the current buffer's project with date suffix as name (and you can
cycle through a few different name suggestions with `M-n`),
uploads it to imbb and copies to URL in the kill-ring for easy sharing.
You can call it with `C-u` prefix and it will automatically insert
the image as org-link in your current buffer.

**Comment by WhatDothLife** [comment]
`scrot` looks promising, I'll give it a try. Thank you all!

**Comment by maavelar5** [comment]
`gscreenshot` works, if you have `desktop-environment` emacs package installed you can also use
`desktop-environment-screenshot` or `desktop-environment-screenshot-part`

**Comment by WorldsEndless** [comment]
Spectacle used to work great for me, but one of the recent versions fails; I switched to Flameshot and have been very pleased (you'll need a notification system, such as Dunst, to get it to work smoothly, but that's true of many apps in exwm)

**Comment by BlueFlo0d** [comment]
Ah, just to share in case it may help,
you don't really need any of those to capture screen, here's from my `init.el`
```
;; Print screen
(global-set-key (kbd "<print>")
  (lambda ()
    (interactive)
    (let ((path (concat "~/Documents/Screenshot-" (format-time-string "%Y-%m-%d,%H:%M:%S") ".png")))
      (start-process-shell-command
       "import" nil (concat "import -window root " path))
    (message (concat "Screenshot saved to " path)))
    ))
```
So basically just use the `import` command from `X`. Simple, and works great for me.

**Comment by ch11ng** [comment]
@BlueFlo0d Thanks for sharing that.

**Comment by orencio** [comment]
> `gscreenshot` works, if you have `desktop-environment` emacs package installed you can also use
> `desktop-environment-screenshot` or `desktop-environment-screenshot-part`
> 
> Edit: Just noticed `desktop-environment` uses `scrot`

It can be modified:

```lisp
  (setq desktop-environment-screenshot-command "/sbin/gnome-screenshot -i")
  (setq desktop-environment-screenshot-partial-command "/sbin/gnome-screenshot -i")
  (setq desktop-environment-screenshot-directory "~/Descargas")
```

Regards.

**Comment by ChenSun-Phys** [comment]
The recommended way 

    (setq desktop-environment-screenshot-partial-command "/sbin/gnome-screenshot -i")
leads to what was expected. That said, I was experimenting with `gnome-screenshot -a` and got the following error showing up in my shell window.

    Error in X event loop: XCB_WINDOW (3)`

Any idea about what could be causing it?
