### ISSUE TITLE
Wishlist: hide the echo area during inactivity

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#65]
Hi everyone,
The echo area is most blank during normal use, this is a big issue for a window manager. There is some discussions here:
http://stackoverflow.com/questions/5079466/hide-emacs-echo-area-during-inactivity
Also someone has suggested the mode line can be displayed in the echo area.
http://emacs.stackexchange.com/questions/7563/make-use-of-an-empty-echo-area-to-display-information
Phils gives us some directions on how to achieve this
http://stackoverflow.com/questions/10063410/is-it-possible-to-separate-minibuffer-and-echo-area-in-emacs?lq=1
I wish someone can make this happen.
Thank you!

**Comment by zevlg** [comment]
With EXWM hiding echo area can be done by resizing emacs frame vertically, such as echo area moves off the screen.

**Comment by ch11ng** [comment]
But the echo area can grow to display long messages.  Besides, on a multi-monitor setting, the echo area might be visible on another screen.

**Comment by ch11ng** [comment]
Implemented in 0e4055d3392537cd4138181b9c615fa03053add8.  You can try this feature with

```
(setq exwm-workspace-minibuffer-position 'bottom)
```

in your `.emacs`.

**Comment by QiangF** [comment]
Will this work for an emacs window too? I will try it when I get the time.
Happy Chinese new year!

**Comment by ch11ng** [comment]
> Will this work for an emacs window too?

If you mean an Emacs frame not running under EXWM, then no.  But I think it's still possible and some code here can be reused.
