### ISSUE TITLE
Regular total freezes needing force reboot if I let Emacs run for more than a few hours

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#651]
I have been experiencing total freezes (needing force reboot as `C-M-<f2>`, etc., to get to other ttys are also unresponsive: no key seems to have any action) for several months.

This systematically happens if I keep an Emacs session running for a whole day or longer. So I really cannot let my laptop hibernate overnight and go back to the same session the next day or this is sure to happen. Rebooting my machine every day helps a lot. Nevertheless, I still experience these freezes regularly, particularly when several programs are running and I ask a lot of Emacs such as, for instance, editing a file with code blocks. But they seem to happen in the middle of totally unrelated tasks, so I can't pinpoint the trigger.

I have no clue what is causing it and I don't see anything which seems related in the log obtained by `journalctl -b`. So I have no idea how to get started looking for a solution for this.

I love EXWM but this ongoing issue is really disruptive. I would appreciate any advice on how to try to identify the root of the problem. Thanks!

---
- Operating system and version: 5.2.14-arch2-1-ARCH
- Locale: LC_COLLATE=C
- Emacs: 26.3-1
- EXWM: 0.22.1

**Comment by prosoitos** [comment]
Note that, on occasions, particularly if I make a mistake, I make Emacs freeze and `C-M-<f2>` allow me to kill it and reboot cleanly or relaunch it or sometimes, to clean whatever other program went wrong and go back to the Emacs session.

But the freezes I am talking about in this issue seem to be total freezes of the entire machine. They aren't caused by a mistake on my part (such as a wrong request to a program) and happen while I am doing totally mundane, normal tasks.

**Comment by QiangF** [comment]
I  sometimes too got freezes. Often caused  incompatible apps like vmwre woksation, ug nx etc. In my case, login in another tty and

    pkill -SIGUSR2 emacs

often bring emacs back from dying.

**Comment by prosoitos** [comment]
My problem is that in those "full freezes" (as I called them), I cannot log in to another tty. I simply cannot do anything at all (except a force reboot). No key or key combo is responsive. When I can get to another tty (in the "normal" freezes which I am not worried about), all is good.

**Comment by ch11ng** [comment]
Sounds like a systemic problem, or at least Xorg hangs.  Have you checked system logs and Xorg.log?

I'd suggest you deploy monitoring tools or simply run some scripts in the background to capture and save the status of your system.  Problems like out of memory can cause such issue.

Also if you run SSH server on it chances are you can login to it and carry out some diagnoses.

**Comment by prosoitos** [comment]
I installed i3wm to test things out and I had the same problem (while Emacs was not even running!). So, contrary to what I thought, this has nothing to do with either Emacs or EXWM. And it makes sense that it would be something higher up since I could not reach another tty.

Thank you @ch11ng for your quick reply (as always) and your suggestion (I had not thought of looking at the Xorg log). I don't see anything suspicious in it though. I will have to dig into my Arch Linux settings and post in the forum there. At least, now I know that it is not a WM problem while I always thought it was...

Sorry for the noise: I will close this issue.
