### ISSUE TITLE
exwm and spacemacs ？

### ISSUE THREAD

**Issue by brioglade** [ch11ng/exwm#652]
Hi,Is it possible to install EXWM and Spacemacs in the same computer at the same time？
Thanks.

**Comment by setzer22** [comment]
It sure is! I have been using my current setup for months and it mostly has been a pain-free experience. Something that still has some issues for me is the synchronization between evil modes and exwm's char/line modes, but it works most of the time.

Take a look at this layer: https://github.com/timor/spacemacsOS

**Comment by brioglade** [comment]
@setzer22  Thank you!

**Comment by ch11ng** [comment]
Many users do have such setup.  There are some compatibility issues raised from time to time but most can be fixed.  Please open new issues if you encountered such problems.
