### ISSUE TITLE
exwm-xim doesn't work with R lang editor

### ISSUE THREAD

**Issue by TatriX** [ch11ng/exwm#654]
Running this `R` code will hang the process instead of showing editor window
```
fix(rivers)
```
Disabling exwm-xim helps:
```
$ XMODIFIERS= R
> fix(rivers)
```

In my `.xprofile` I have
```
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim
```
EXWM version `988f983 2019-09-15 `

**Comment by emacksnotes** [comment]
> Running this `R` code will hang the process instead of showing editor window

What is your editor?  Are you running in RStudio, or are you using Emacs + ESS?

> ```
> fix(rivers)
> ```

`rivers` looks like a dataset.  It seems you are trying to run a vignette from a package. Unofrtunately, I am not able to identify what the package could be.

You can consult this link https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#how-to-report-a-bug, if you need some help with reporting bugs.

**Comment by TatriX** [comment]
Sorry, I think I've made a bad example.
`rivers` is a built in dataset in R.
As you can see from first post I'm running R from a command line (the same also happens from ESS).

Let me try in a different way

I'm running zsh in alacritty 
```sh
# Download dataset from http://faculty.marshall.usc.edu/gareth-james/ISL/data.html
wget http://faculty.marshall.usc.edu/gareth-james/ISL/Auto.csv
# run R
EDITOR=vi R
```
Then in R repl:
```R
x <- read.csv("./Auto.csv")
fix(x)
```
The last command will open a GUI editor for the dataset. In the scenario above it will hang R process and the only way to handle this is to `killall -9 R`.

Then if I run R like this:
```sh
EDITOR=vi XMODIFIERS= R
```
everything works as expected:
![r](https://user-images.githubusercontent.com/703150/65135202-cec1a680-da05-11e9-8652-53a183ea5c86.png)

**Comment by ch11ng** [comment]
I tried debugging R and it failed [here](https://github.com/wch/r-source/blob/R-3-6-branch/src/modules/X11/dataentry.c#L2130-L2136).  It correctly recognized the input method style (`ioim_style`) `exwm-xim` declared but failed to create an input context.  Perhaps some arguments to `XCreateIC` are incorrect/redundant when input method style is set to `XIMPreeditNothing | XIMStatusNothing`.  This is basically an interaction between R and X server so I'm afraid nothing can be done here.

**Comment by TatriX** [comment]
Thanks! I'll just make an alias to disable xim.

**Comment by emacksnotes** [comment]
>  exwm-xim doesn't work with R lang editor

>> I tried debugging R and it failed here. It correctly recognized the input method style (ioim_style) exwm-xim declared but failed to create an input context. Perhaps some arguments to XCreateIC are incorrect/redundant when input method style is set to XIMPreeditNothing | XIMStatusNothing. This is basically an interaction between R and X server so I'm afraid nothing can be done here.

>>> Thanks! I'll just make an alias to disable xim.

@TatriX when you have some time  you may want to file a bug report against R https://www.r-project.org/bugs.html.
