### ISSUE TITLE
`Unminimize`-ing a hidden floating window doesn't work.  Or it works but requires a workspace switch out and switch in

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#657]
#### Screenrecording.

https://drive.google.com/file/d/1FgKkzbNkQMBbpvEaNkdo8oD3w2XhyK0H/view?usp=sharing

#### Debug Log

[exwm-unhide.txt](https://github.com/ch11ng/exwm/files/3630684/exwm-unhide.txt)

### Note the following in the video

Steps 1-3 are triggered using GNOME Panel's bottom bar.

1. Left clicking on the  `teminal` window raises the Emacs window
2.  Once I `Unminimize`, nothing seems to happen
3. I temporarily switch to Workspace 1 and then back to Workspace 0.  (See what happens on the   The Unminimized window is displayed.
4.  Enlarge / Shrink window horizontally does NOT work.
5.  Enlarge / Shrink window vertically works.  The window resizes by a pixel.  So, pay close attention to the the bottom border of the window.

`Toggle Floating`on `Gnome Terminal` creates a window of reasonable size.  This is in contrast to what happened in https://github.com/ch11ng/exwm/issues/653.

**Comment by ch11ng** [comment]
Thanks for the report! This is fixed in 2005fa5c5dcfdcc49e1ce0b631a1793e9c25604f.
