### ISSUE TITLE
EXWM started with `exwm-init` when exited, freezes the keyboard, and I cannot continue the running session

### ISSUE THREAD

**Issue by emacksnotes** [ch11ng/exwm#658]
## EXWM started with `exwm-init` when exited, freezes the keyboard, and I cannot continue the running session

_(I cannot think of a better description.  But the attached video should make the things clear)_

### Setup

1. Install [`exwm-gnome-flashback`](https://github.com/WJCFerguson/exwm-gnome-flashback) after applying following patch.  

[exwm-gnome-flashback-with-gnome-panel.diff.txt](https://github.com/ch11ng/exwm/files/3638530/exwm-gnome-flashback-with-gnome-panel.diff.txt)

With the above patch, when Emacs / EXWM is exited, the session stays put so that I can continue working without any window manager.

2. Use `lightdm` and login to above `exwm-gnome-flashback` session. _Lately, `gdm` on Debian unstable is giving me lots of problem.  So, I switched to `lightdm`._

### Video

https://drive.google.com/file/d/16okmtjAuPe_-J9rmrUSxdkEn9i2BY8nt/view?usp=sharing

#### What happens in the video

_(Annotations below uses the clock time that you see on my desktop)_

#####  Step 1: Initial state
1. Start a `exwm-gnome-flashback` session.  So that both Emacs and EXWM are running.

#### Step 2: From 2:39:48 to  2:40:14

2. Exit Emacs.  You can confirm this by what happens in the minibuffer / echo area.
3. `wmctrl -m` report "Bad Window".  This is expected, because we just exited Emacs / EXWM

####  Step 3: From 2:40:14 to 2:40:55
1. Start Emacs.
2. Start EXWM with `exwm-init`
3. `wmctrl -m` reports EXWM as window manager.  Good.

#### Step 4: From 2:40:55 to 2:41:19
1. Exit Emacs / EXWM
2. _(Then I open terminal.  I want to run `wmctrl -m`, and hope to see that there is now window manager.  /But/ The keystrokes on the `Gnome Terminal` never goes through.  i.e., keyboard is  frozen.  But The mouse still works)_

#### Step 5: From 2:41:19 to 2:41:46
1.  Start Emacs.
2. Start EXWM through `exwm-init`.
3.  Switch to Gnome Terminal and start typing something.  The keyboard works.

#### So, where is the bug

At the end of `Step 2`, there is no window manager.  (Still) I was able to type `wmctrl -m` and get  a response.  i.e, the keyboard works

At the end of `Step 4`, again there is no window manager.  But I am not able to type anything in the terminal. i.e., keyboard is frozen.  

### Where could be the problem  -- My Theory

The only difference between the `Step 2` and `Step 4` is the manner in which EXWM is started. 

In  `Step 2` case, exwm is started by the session manager via `exwm-enable`.   Whereas, in `Step 4` case, it is started by hand with `exwm-init`.  There is some difference in these two init paths, which prevents some cleanup handlers (???keboard grabbing) from being installed or executed.

**Comment by ch11ng** [comment]
9bea3c9bcd02dc2647881feaaacbf71f6c25ff64 forces setting input focus to where the cursor hovers so the problem should be resolved.

**Comment by medranocalvo** [comment]
@emacksnotes, could you confirm whether @ch11ng's change fixes the issue?

**Comment by medranocalvo** [comment]
Closing. @emacksnotes, please reopen if needed.

**Comment by emacksnotes** [comment]
Lately, I am catching up with other things.

Will revert on this (and other) issues whenever I find some time.

**Comment by medranocalvo** [comment]
Thanks for getting back.  Please check when you have time.
