### ISSUE TITLE
[QUESTION] Detect the buffer created by an application in elisp

### ISSUE THREAD

**Issue by setzer22** [ch11ng/exwm#659]
One thing that I tend to do a lot in my workflow is launching some application, and right after renaming its buffer to some easy to remember name.

In order to automate this process, I would like to create an interactive command that launches an X application and, after exwm has opened a buffer for it, rename that buffer. The problem lies in the fact that after executing a command, the elisp code continues executing, but the buffer is not created and focused immediately, so calling `rename-buffer` at that point would rename the currently focused buffer. Is there an easy way to be notified when a buffer is created for a specific application?

**Comment by ch11ng** [comment]
It depends on what you want to rename it to.  The default configuration contains this:

```elisp
(add-hook 'exwm-update-class-hook
          (lambda ()
            (exwm-workspace-rename-buffer exwm-class-name)))
```

You may find other hooks in the [wiki](https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#list-of-user-options).  If you want to rename it interactively, perhaps you should give `exwm-manage-finish-hook` a try.

**Comment by setzer22** [comment]
Sorry, I think I created a bit of confusion with my original question. What I usually do is rename the window interactively, binding the rename to a hotkey. What I'm trying to achieve now, is an interactive function that will launch a program, but give a specific name to the newly created window.

It makes sense to use `exwm-manage-finish-hook` for that, and in fact, I was planning to. However, my question was more oriented towards how do I distinguish the buffer that I want when running the hook. 

I think it's better with an example: Let's say I launch `qterminal -e htop`, and want to rename that buffer automatically to `*htop*`. How do I know in `exwm-manage-finish-hook` that the current buffer being managed is the one created by the spawned process? I could check the window class, but ideally, this should also work in the case I launch two `qterminal` processes in very quick succession, but are supposed to get different names (let's say, one for htop and the other for something else).

**Comment by ch11ng** [comment]
This is actually quite difficult to achieve as (a) an application does not necessarily create one single X window and (b) for applications consecutively launched there's no easy way to tell them apart.  Creating processes and X windows are two decoupled procedures, and little info can be found on an X window about the process creating it; I can only think of class/instance names and PID.

**Comment by setzer22** [comment]
I see, I suspected as much.

Even if this cannot be done 100% reliably, having the PID would be good enough for what I'm envisioning. Is there a way with the current exwm codebase to get the PID of the process that created an X window?

Thanks!

**Comment by ch11ng** [comment]
It's briefly used in `exwm-manage--kill-client` and not every application support this atom.  For completeness just try the following snippet in the context of an `exwm-mode` buffer.

```elisp
(slot-value (xcb:+request-unchecked+reply exwm--connection
                (make-instance 'xcb:ewmh:get-_NET_WM_PID
                               :window exwm--id))
            'value)
```

**Comment by setzer22** [comment]
Thank you, I'll try this! 

I'm closing the issue because the question is solved :+1:
