### ISSUE TITLE
How to find a window across desktops?

### ISSUE THREAD

**Issue by cyc115** [ch11ng/exwm#665]
Is there a way to search and switch to a particular program for all desktops and not just the current one?

**Comment by sarg** [comment]
It's not EXWM related, but rather how do you manage your buffers. You must be using some package that filters buffer list.

**Comment by ch11ng** [comment]
You'll need to toggle `exwm-layout-show-all-buffers` and `exwm-workspace-show-all-buffers` to list / work with X windows on other workspaces.  By default EXWM only shows X windows on the current workspace.

**Comment by cyc115** [comment]
> You'll need to toggle `exwm-layout-show-all-buffers` and `exwm-workspace-show-all-buffers` to list / work with X windows on other workspaces. By default EXWM only shows X windows on the current workspace.

Thanks @ch11ng! This helps a lot!

**Comment by ch11ng** [comment]
So I'm closing it now.
