### ISSUE TITLE
Querying the WM_WINDOW_ROLE of a window

### ISSUE THREAD

**Issue by daviwil** [ch11ng/exwm#666]
Is there a way to query/access the `WM_WINDOW_ROLE` of a window?  I'm trying to distinguish between two Pidgin windows with the same `WM_CLASS` and it seems the role is an effective way to do that.

```
λ xprop
... snip ...
WM_WINDOW_ROLE(STRING) = "conversation"
WM_CLASS(STRING) = "Pidgin", "Pidgin"
... snip ...
```

**Comment by daviwil** [comment]
Perhaps I should send a PR to add another get/set class pair like [the one for `WM_CLASS`](https://github.com/ch11ng/xelb/blob/801ab287616c252e00bb8e06ca12a607a2c08bc6/xcb-icccm.el#L436)?

**Comment by ch11ng** [comment]
This property is included in the session manager section that's not covered by XELB.  Nevertheless it's of STRING type and can be retrieved like this:

```elisp
(let ((atom (exwm--intern-atom "WM_WINDOW_ROLE")))
  (slot-value (xcb:+request-unchecked+reply exwm--connection
                  (make-instance 'xcb:icccm:-GetProperty-text
                                 :window exwm--id
                                 :property atom))
              'value))
```

**Comment by daviwil** [comment]
Thanks a lot, that worked perfectly!  In case someone else looks for this in the future, I made a utility function for this based on @ch11ng's snippet:

```emacs-lisp
  (defun exwm/get-window-role (buffer-or-name)
    (with-current-buffer buffer-or-name
      (if (derived-mode-p 'exwm-mode)
        (let ((atom (exwm--intern-atom "WM_WINDOW_ROLE")))
            (slot-value (xcb:+request-unchecked+reply exwm--connection
                            (make-instance 'xcb:icccm:-GetProperty-text
                                        :window exwm--id
                                        :property atom))
                        'value)))))
```
