### ISSUE TITLE
[Question]: Hide frame until Emacs has finished loading

### ISSUE THREAD

**Issue by WhatDothLife** [ch11ng/exwm#667]
Is there a way to prevent Emacs from showing a blank white frame at the top left corner of the screen, while it is loading the configs?

**Comment by emacksnotes** [comment]
> Is there a way to prevent Emacs from showing a blank white frame at the top left corner of the screen, while it is loading the configs?

Add `-mm`  to the command line args.  This is how I start `emacs/exwm`.

`emacs -mm --eval "(exwm-enable)"`

**Comment by WhatDothLife** [comment]
That worked. Thank you Sir.
