### ISSUE TITLE
EXWM fails to start on emacs27

### ISSUE THREAD

**Issue by ValentinPearce** [ch11ng/exwm#673]
If I try to start exwm with emacs27 I get the following warning :

    Warning (emacs): [EXWM] EXWM fails to start (wrong-type-argument: (number-or-marker-p 2020568943.0))

My test config is split into two files.

* init.el :
```lisp
     (require 'package)
     (add-to-list 'package-archives
    	     '("org" . "http://orgmode.org/elpa/")
    	     )
    (add-to-list 'package-archives
    	     '("melpa" . "https://melpa.org/packages/")
    	     )
    (package-initialize)
    (org-babel-load-file "~/.emacs.d/exwm.org")
```
* exwm.org :

```org
* EXWM
** Nice basic settings
#+BEGIN_SRC emacs-lisp
  (use-package exwm)
  (require 'exwm)
  (require 'exwm-config)
  (exwm-config-default)
  (exwm-enable)
#+END_SRC
** Multi Monitor Support ?
#+BEGIN_SRC emacs-lisp
  (require 'exwm-randr)
  (setq exwm-randr-workspace-output-plist '(0 "VGA1" 1 "LVDS-1"))
  (add-hook 'exwm-randr-screen-change-hook
            (lambda () (start-process-shell-command
                        "xrandr" nil "xrandr --output VGA1 --left-of LVDS --auto")))
  (exwm-randr-enable)

#+END_SRC


```

This simple configuration works fine with emacs 26.2

I'm running arch32 on an i686 system.

**Comment by emacksnotes** [comment]
> (setq exwm-randr-workspace-output-plist '(0 "VGA1" 1 "LVDS-1"))

Take a look at the source code, and you may get a clue on how to fix the problem (atleast temporarily).

At https://github.com/ch11ng/exwm/blob/3c8b39505825eff7e2b61e09833374d904926724/exwm-randr.el#L92, I see that on Emacs 27 `exwm-randr-workspace-monitor-plist' supercedes `exwm-randr-workspace-output-plist`.

```elisp
(with-no-warnings
  (define-obsolete-variable-alias 'exwm-randr-workspace-output-plist
    'exwm-randr-workspace-monitor-plist "27.1"))
```

At https://github.com/ch11ng/exwm/blob/3c8b39505825eff7e2b61e09833374d904926724/exwm-randr.el#L68, I see the following documentation for `exwm-randr-workspace-monitor-plist`

```elisp
(defcustom exwm-randr-workspace-monitor-plist nil
  "Plist mapping workspaces to monitors.

In RandR 1.5 a monitor is a rectangle region decoupled from the physical
size of screens, and can be identified with `xrandr --listmonitors' (name of
the primary monitor is prefixed with an `*').  When no monitor is created it
automatically fallback to RandR 1.2 output which represents the physical
screen size.  RandR 1.5 monitors can be created with `xrandr --setmonitor'.
For example, to split an output (`LVDS-1') of size 1280x800 into two
side-by-side monitors one could invoke (the digits after `/' are size in mm)

    xrandr --setmonitor *LVDS-1-L 640/135x800/163+0+0 LVDS-1
    xrandr --setmonitor LVDS-1-R 640/135x800/163+640+0 none

If a monitor is not active, the workspaces mapped to it are displayed on the
primary monitor until it becomes active (if ever).  Unspecified workspaces
are all mapped to the primary monitor.  For example, with the following
setting workspace other than 1 and 3 would always be displayed on the
primary monitor where workspace 1 and 3 would be displayed on their
corresponding monitors whenever the monitors are active.

  \\='(1 \"HDMI-1\" 3 \"DP-1\")"
  :type '(plist :key-type integer :value-type string))

```

The leading `Commentary` at https://github.com/ch11ng/exwm/blob/3c8b39505825eff7e2b61e09833374d904926724/exwm-randr.el#L24, talks a little bit more about how the `exwm-randr` library is to be used.

**Comment by emacksnotes** [comment]
> EXWM fails to start on emacs27

I was a bit surprised with this title, because I use `Emacs` from  git repo, and I never had any issues.  Had you mentioned `randr` or `multi monitor` in the title, I believe, I wouldn't be confused.

You may want to press the `Edit` button next to this issue's title, and specifically mention that this issue pertains to `randr` / `multi monitor` setup.   This would help people (like me) who regularly keep track of title of issues, to see whether an issue interests them.

**Comment by ValentinPearce** [comment]
I tried without my randr config and the error was the same. I decided to clean emacs config directory and it worked without changing anything.

I'm not sure what the problem was but I guess it's not an issue anymore.

I'll have a closer look at my randr settings and follow your advice.

**Comment by ch11ng** [comment]
This is due to you were using a 32-bit build of Emacs without 'wide-int' support.  Not sure where that number from though.
