### ISSUE TITLE
Read only mode in Chromium (sometime Firefox too)

### ISSUE THREAD

**Issue by 11111000000** [ch11ng/exwm#676]
Sometime chromium window become read-only (I can't input anything), how to fix that or how to disable RO-mode? That's very annoying - only full restart helps... ((

**Comment by dakra** [comment]
Looks like a duplicate of https://github.com/ch11ng/exwm/issues/585

**Comment by ch11ng** [comment]
As @dakra have mentioned it's likely the same with #585 .  TBH I'm quite confused with the problem.  But I highly suspect Emacs runs into some error or it should be recoverable.  @11111000000 did you notice anything wrong in e.g. `*Messages*`? You may try <kbd>M-x exwm-restart RET</kbd> next time to avoid a full restart.

**Comment by 11111000000** [comment]
exwm-restart don't  help there. Also, ro-mode is here after chromium restart.

**Comment by 11111000000** [comment]
close with #585
