### ISSUE TITLE
Focus detaches from current workspace when window changes

### ISSUE THREAD

**Issue by juligreen** [ch11ng/exwm#679]
I'm using emacs 26.3-1 on Arch Linux with EXWM 0.23.
My config files can be found [here](https://github.com/juligreen/Configfiles).

I'm using multiple displays with a workspace on each.

So the scenario is the following:
I have my mouse hovering on workspace [0] (focus is also on [0]), I press super+1 to switch focus to workspace [1] which contains my browser, Vivaldi. In Vivaldi I navigate by keyboard to another page (using vimium mostly). When the displayed page changes or refreshes any typed keys go to workspace [0] (where my mouse still hovers).

The focus is still on [1], as when I try to use super+1 to change focus to [1] it does not work. I have to use super+0 to go to [0] first and can afterward go to workspace [1] and type in Vivaldi again.

I set the variable focus-follows-mouse to nil already.

Is this a bug or am I missing some configuration?

**Comment by ch11ng** [comment]
It appears you have `mouse-autoselect-window` set to `t`.  That would cause the problem.

**Comment by juligreen** [comment]
After testing this for a while, it seems to be doing the trick.

Thank you!
