### ISSUE TITLE
EXWM keyboard layout changes in different buffers 

### ISSUE THREAD

**Issue by utraz** [ch11ng/exwm#681]
When I start a program f.e; firefox my keybindings are to QWERTY while i have a AZERTY layout. Even when running "setxkbmap fr" the keybindings stay in QWERTY layout. Everything else is in AZERTY though and the keybindings work correctly when used from a emacs buffer.

**Comment by ch11ng** [comment]
Which version of XELB have you installed? I suppose this has been fixed before.  And what if you put `setxkbmap fr` in `.xinitrc` (or whatever script Emacs is run) before launching EXWM?

**Comment by utraz** [comment]
Putting it in the .xinitrc worked...

Thank you!
