### ISSUE TITLE
Can't bind Control-TAB to "other-window" function in managed X window 

### ISSUE THREAD

**Issue by dto** [ch11ng/exwm#687]
Hi. I'm using the current ELPA version. I attempted to add a global EXWM keybinding for Control-TAB to "other-window", but it only works in Emacs buffers. This keybinding already exists and works in my .emacs, but it doesn't seem to work once I get to a non-emacs window. So to cycle through all the windows on a given workspace, I have to press the default keybinding for other-window "C-x o" to get back to the other windows into the Emacs windows. I tried giving the keybinding as (kbd "C-TAB") and as [(control tab)] but neither of them work, either when set in .emacs and restarting, or using the Customize interface. What am I doing wrong? I would greatly appreciate any help you can offer. My .emacs snippet is below.

```
(setq exwm-input-global-keys
      `(
        ([?\s-s] . exwm-reset)
        ([?\s-w] . exwm-workspace-switch)
        ,@(mapcar (lambda (i)
                    `(,(kbd (format "s-%d" i)) .
                      (lambda ()
                        (interactive)
                        (exwm-workspace-switch-create ,i))))
                  (number-sequence 0 9))
        ([?\s-&] . (lambda (command)
		     (interactive (list (read-shell-command "$ ")))
		     (start-process-shell-command command nil command)))
        ([(control tab)] . other-window)))

```

**Comment by dto** [comment]
Just discovered that the menu item EXWM/Define global binding does the trick, but it still won't work from my .emacs init file.

**Comment by emacksnotes** [comment]
> setq exwm-input-global-keys

`exwm-input-global-keys` has a setter. So,  I recommend that you use `custom-set-variables` instead of `setq`.  

> ([(control tab)] . other-window)

I use the customize interface, and with focus on the `Key Sequence` field, I use `C-q` to input the keys I want.  In this specific case, Ctrl-Tab.  This is what the Emacs generates for me,

```elisp
(custom-set-variables
 '(exwm-input-global-keys
   '(([C-tab] . other-window))))
```

The above snippet works for me.

**Comment by ch11ng** [comment]
@dto Please follow @emacksnotes 's instructions on the Customize interface.

**Comment by dto** [comment]
The following indeed works when evaluated in a running EXWM. But it does not work when in .emacs startup ; I get "C-tab is undefined" until I go into .emacs and evaluate the custom-set-variables again. See below.

At one point I saw an error "do not use [C-TAB] to bind control tab, use [?\C-\t] ". But I can't seem to reproduce that error message. Also, the binding it suggests did not work, and it just kept giving that message even after I had removed the offending keybinding from the call.


```
(custom-set-variables
 `(exwm-input-global-keys
   '(([C-tab] . other-window)
     ([?\s-s] . exwm-reset)
     ([?\s-w] . exwm-workspace-switch)
     ,@(mapcar (lambda (i)
                 `(,(kbd (format "s-%d" i)) .
                   (lambda ()
                     (interactive)
                     (exwm-workspace-switch-create ,i))))
               (number-sequence 0 9))
        ;; Bind "s-&" to launch applications ('M-&' also works if the output
        ;; buffer does not bother you).
     ([?\s-&] . (lambda (command)
                  (interactive (list (read-shell-command "$ ")))
                  (start-process-shell-command command nil command))))))
```

**Comment by dto** [comment]
Perhaps my call to custom-set-variables should go after EXWM-ENABLE?

**Comment by ch11ng** [comment]
`'C-TAB` and `?\C-\t` both represent <kbd>control tab</kbd> in Emacs.  In EXWM we actually always match against `'C-TAB`,  but it's okay to register both keys if you are unsure.

> Perhaps my call to custom-set-variables should go after EXWM-ENABLE?

This probably has nothing to do with `exwm-enable`.  Perhaps you called some function in `exwm-config` that may have override it?

**Comment by medranocalvo** [comment]
@dto, have you managed to get it to work?

**Comment by medranocalvo** [comment]
Closing this.  @dto, please reopen if needed.
