### ISSUE TITLE
simulation key not working for kitty

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#690]
The paste from clipboard hotkey for kitty (https://github.com/kovidgoyal/kitty) is "C-S-v".
But the following doesn't seem to work.

    (exwm-input--fake-key (aref (kbd "C-S-v") 0))

**Comment by elnawe** [comment]
If `C-S-v` is supposed to mean `Control+Shift+v` here, the correct `kbd` is `C-V` (mayus V means `Shift+v` in Emacs)

```elisp
(exwm-input--fake-key (aref (kbd "C-V") 0))
```

**Comment by ch11ng** [comment]
Actually it is <kbd>C-S-v</kbd>:

```
(event-modifiers ?\C-\S-v)
  => (shift control)
(event-basic-type ?\C-\S-v)
  => 118
(event-modifiers ?\C-V)
  => (control)
(event-basic-type ?\C-V)
  => 118
```

Note that `118` is `?v`.

The problem might be that you didn't have that X window selected when running the code.  Please enable `exwm-debug` and there'll be a log starting with `exwm-input--fake-key` showing which X window the event is targeted.  Also I'm not sure if this specific application allows `SendEvent`; if not this won't work anyway.

**Comment by QiangF** [comment]
I don't know why, but accidentally I managed to get paste work in one kitty buffer (with home in the prompt) but not the other one (with tmp in term prompt), here is the debug output.

https://gist.github.com/QiangF/b7efa1daab3ed8f9cd64fae4ee4009c0

**Comment by QiangF** [comment]
I guess in the following two functions (I bind it to C-y), my-yank-2 sometimes doesn 't work is because of the focus drift.
How can I avoid that?

    (defun my-yank-1 ()
    (interactive)
    (let ((inhibit-read-only t)
            (yank-pop-change-selection t))
        (exwmx-sendstring--send (current-kill 0))))

    (defun my-yank-2 ()
    (interactive)
    (let ((inhibit-read-only t)
            (yank-pop-change-selection t))
        (exwmx-sendstring--send (call-interactively #'counsel-yank-pop))))


    (defun exwmx-send-paste-key ()
    (interactive)
    (let* ((paste-key "C-S-v"))
            (sleep-for 0.01)
            (exwm-input--fake-key (aref (kbd paste-key) 0))))

    (defun exwmx-sendstring--send (string)
    "Send `string' to clipboard and then send paste key to
    application to trigger paste operation, `string' will be
    inserted into the application. If string is nil, send paste key."
    (when string
        (cond ((derived-mode-p 'exwm-mode)
            (progn
                (kill-new string)
                (exwmx-send-paste-key)))
        (t (insert string)))))

**Comment by ch11ng** [comment]
More delay in this case perhaps? I guess transferring input focus to minibuffer is inevitable in order to invoke counsel.

**Comment by QiangF** [comment]
More delay is no problem. To avoid possible misbehave, is it possible to add an optional parameter (the targeted window) to exwm-input--fake-key?

**Comment by ch11ng** [comment]
It's possible but applications may drop events received when they don't have input focus after all.  That's why it doesn't have such argument.
