### ISSUE TITLE
Question: how to get the exwm buffer created by a shell command

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#692]
I need to save that into an variable, so I can access it later :

    (call-process "gtk-launch" nil 0 nil "stterm")

**Comment by QiangF** [comment]
This seems to work :

    (defvar last-created-exwm-buffer nil)
    (defun my-exwm-manage-finish-hook ()
      (setq last-created-exwm-buffer (current-buffer)))
    (add-hook 'exwm-manage-finish-hook #'my-exwm-manage-finish-hook)

Is there a better way?

**Comment by ch11ng** [comment]
An `exwm-mode` buffer is created by EXWM on X window creation, and its name really depends on the rules defined.  But for most modern applications you can utilize the `_NET_WM_PID` property set on each X window to determine which process it is related to.  Please refer to the source of `exwm-manage--kill-client` for how to get that property.

**Comment by QiangF** [comment]
But call-process does not return the process id. The setting in the hook works great so far.

**Comment by ch11ng** [comment]
`start-process` returns a process object that contains the PID (get with `process-id`).  `call-process` doesn't.

**Comment by QiangF** [comment]
Here is my solution:

    (defun my-get-buffer-from-pid (pid)
    (catch 'loop
        (dolist (item exwm--id-buffer-alist)
        (let* ((id (car item))
                (response (xcb:+request-unchecked+reply exwm--connection
                            (make-instance 'xcb:ewmh:get-_NET_WM_PID :window id))))
            (when (equal pid (and response (slot-value response 'value)))
            (throw 'loop (cdr item)))))))

Note there is a delay between the process start and being managed by exwm, about 1 second on my machine.
