### ISSUE TITLE
When EXWM is enabled, and restarting X11, Emacs takes more and more memory untill system freezes on Manjaro XFCE.

### ISSUE THREAD

**Issue by nhmacuk** [ch11ng/exwm#696]
Everytime I have logged out/switched users or issue xmodmap (maybe it's restarting X11 what causes the problem?), EXWM (started using exwm-init) either crashes (when "exec exwm" not added to .xinitrc), or freezes (when "exec exwm" is added to .xinitrc, and when "exec exwm" is all that is in the .xinitrc (so commented out the Manjaro config)). 
Moreover, when using exwm-exit or exiting emacs the keyboard becomes unresponsive (similar behavior to an earlier resolved issue [#658](https://github.com/ch11ng/exwm/issues/658)).

The used operating system is Manjaro XFCE. The .xinitrc file is chmod'ded 774, after copied to the home directory of the .xinitrc from /etc/X11/xinit/.xinitrc. The file has the line "exec exwm" added (below the config added by Manjaro (see below)). EXWM does not seem to start without the exwm-init command. The exwm configuration within Emacs is the [spacemacs layer](https://github.com/timor/spacemacsOS), and is used unchanged. 

EXWM doesn't seem to crash or slow down, or cause any issues during use, aside from when logging in, or when calling exwm-exit.

When hanging:
![emacs hanging](https://user-images.githubusercontent.com/44981227/71667740-a5cfe200-2d66-11ea-859d-d2e6973e5b0d.jpeg)

After crash:
![image](https://user-images.githubusercontent.com/44981227/71667612-26421300-2d66-11ea-8a1e-ba2139446f5c.png)

The .xinitrc:
```
#!/bin/sh

#### start config added automatically by Manjaro 
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

 ## xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
 ## xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

 ## xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
 ## xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 ## for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
     ## [ -x "$f" ] && . "$f"
 ## done
 ## unset f
fi

twm &
xclock -geometry 50x50-1+1 &
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
exec xterm -geometry 80x66+0+0 -name login
### end config added by Manjaro 
exec emacs
```

**Comment by ch11ng** [comment]
I noticed there is a line `twm &` in your config file which would probably start another window manager.  Maybe this is the cause of all the problems?

**Comment by nhmacuk** [comment]
Thank you for your time, I'll try it out as soon asap and post results here.

**Comment by ch11ng** [comment]
I'm so confused by how you started EXWM:
* You are not required to call `exwm-init`; you just put `(exwm-enable)` in your Emacs init file and EXWM will start when appropriate.
* The line `xterm -geometry 80x66+0+0 -name login` in your `.xinitrc` which effectively blocks Emacs from staring is clearly wrong.
* There was a process called `xfce4-session` according to your screenshot but I think it doesn't make use of your `.xinitrc`.
* There were far more processes than what were declared in your `.xinitrc` so again you X session was started from somewhere else.

Please consult the wiki for the correct ways of lanunching EXWM.  I'd suggest you start without XFCE.

**Comment by nhmacuk** [comment]
Many of my issues seem to have been solved by starting EXWM as a session and indeed not start XFCE at all (I was hoping to avoid issues that would come with it). I think this issue could be closed even though I haven't been able to solve my opening issue. Thank you for your patience and help!

To a fellow Manjaro user, I cannot find where I saved my .desktop file for now, but I am pretty sure I made one before in an earlier attempt at EXWM that was similar to the one provided with the repo in the link below. If I find it I will post it here.
- create a .desktop file as described by https://github.com/timor/spacemacsOS#note-about-display-managers
- log out and click on the bottom-right XS button to change the xsession to Emacs.
This will start EXWM and emacs (if configured correctly) upon login.

**Comment by ch11ng** [comment]
To try out EXWM in other sessions, you may simply start Emacs in such a normal session and Emacs (when properly configured) would prompt you to replace the current window manager.  EXWM would finally take over the control after you confirmation.

The method of making EXWM the default window manager of other sessions seems to vary depending on the session you use.  So there's no general guide for that.

**Comment by medranocalvo** [comment]
@nhmacuk, do you still suffer the memory issues?

**Comment by nhmacuk** [comment]
Oh I had given up trying to run EXWM under XFCE, but I will try it out ASAP today/tomorrow and let you know

**Comment by ch11ng** [comment]
> EXWM did crash however,

At which point?

> and emacs seemed to took a lot more resources than in the desktop session.

How much is the difference?

**Comment by nhmacuk** [comment]
It crashed after a few minutes (while I went afk for a bit), it used to hang after a few seconds I
logged in. When it was running before that it seemed the memory wasn't
completely swamped from the memory usage indicator application built in
my task bar. The difference was pretty big, as in my computer was
fanning itself audibly much more than when using the desktop session.

**Comment by ch11ng** [comment]
Is it possible to get a crash log? It just happened at a unlikely time.  You talked about CPU usage.  What about memory (the original problem)?

**Comment by nhmacuk** [comment]
Ah I checked it and it hasn't changed with the original described problem: CPU goes up, then my swap memory (8GB) is filled untill my system freezes. If I don't reboot, after an extensive amount of time emacs crashes but the X-windows are kept open and I can use my system again. Could you advice me a program to use to get a crash log (Maybe I am using the term "crash" incorrectly here, I meant that emacs closes)?

**Comment by ch11ng** [comment]
When Emacs crashes it prints errors and backtrace so it's usually adequate to redirect stdout & stderr to some file by appending `> /path/to/some/file 2>&1` to the command running Emacs.

As for the resource usage issues, please put the following lines at the beginning of your Emacs config file and check the usages with `profiler-report` at times.  Also compare Emacs's report with that of some other utilities like `top`.

```elisp
(require 'profiler)
(profiler-start 'cpu+mem)
```

**Comment by nhmacuk** [comment]
I will try your suggestion and let you know the results.

**Comment by medranocalvo** [comment]
@nhmacuk, do you stil suffer this issue?  Have you been able to test @ch11ng's proposal?

**Comment by nhmacuk** [comment]
Oh, I haven't yet! Sorry for not communicating

**Comment by ch11ng** [comment]
Yes, please reopen it whenever necessary.
