### ISSUE TITLE
Some java apps behave strange

### ISSUE THREAD

**Issue by djiamnot** [ch11ng/exwm#697]
The one in particular is wekinator: http://www.wekinator.org/downloads/
I tried it in exwm (0.23 from melpa) and for comparison in i3 and the default Ubuntu (18.04) Unity desktop. My issue is particularly with the menus:
- exwm: the app tries to use GTK look and feel. The styling works but I can't control the menu items (i.e. clicking the menu opens it but its items are no longer clickable)
- i3: does not style the menu and they work fine
- Unity: the menus are styles and they work alright.
The widgets in the window work fine.

I have a feeling that I should raise the issue with Wekinator developers but since I have no idea about Java nor how Java applications are handled under X, my naive interpretation of the above tests leads me to believe that the WM has something to do with handling of UI drawn by Java. I would appreciate any pointers to possible workarounds or explanations.

**Comment by ch11ng** [comment]
I tried the application and it seemed get stuck shortly after launch each time and could only be terminated with `SIGKILL`.  The last message it printed was `INFO: Creating neural network builder with string i`.  No interaction with X11 was observed during that time BTW.  Do you have exactly the same problem?

**Comment by djiamnot** [comment]
No, this is not the problem I am experiencing. I'm assuming that you arrived at this window: 
![image](https://user-images.githubusercontent.com/777400/71559548-65522a80-2a2d-11ea-870b-b392f3a9e544.png)
I get the same info about neural network builder printed in the terminal but I can interact with the controls on that window and I can click the **Next >** button, which  opens another window. I can also interact with the controls in the new window except for the menus in the top part of the window.
If you're actually getting stuck and the application becomes unresponsive at that stage, then it's a different problem.

**Comment by djiamnot** [comment]
Ok, so I discovered that with this particular application, when run in exwm, I have to click the menu item and, while holding the left mouse button engaged, mouse around the top-left corner of the screen in order to interact with the menu items, irrespective of the app's window position. Placing the frame in the upper-left corner of the screen helps. It's a workaround that I can live with (better than changing WM only for this app). 
I noticed a similar issue with Processing (processing.org) but there, the menu opens in the middle of the screen, where the interaction with the menu is possible. Also, in both of these applications, resizing the frame (floating or not) does not resize the content (whereas in other WMs the content gets resized). These are the only two java applications I'm using (since recently) but there is clearly something strange happening in their interaction with exwm (although not exactly consistent between applications).
@ch11ng, I let you decide whether to close this issue or not ;)

**Comment by ch11ng** [comment]
It seems the cause of my problem was XIM.  After unsetting environment variables like `XMODIFIERS` the program works.

However I've not reproduced your problems.  The menu bar works regardless of its position, and the X windows also resize well (except the first X window doesn't support resizing vertically which is likely enforced by the program itself).  I've also tried EXWM 0.23 and the result is the same.  Perhaps you could try with a minimal configuration and see if the problems persist.

**Comment by djiamnot** [comment]
oh my... I was missing `export _JAVA_AWT_WM_NONREPARENTING=1`. I guess I ignored this bit because when I first installed exwm, my system was a _Java Free Zone_. Thanks for taking the time to investigate, though.
