### ISSUE TITLE
Best way to use the same buffer switch keybinding everywhere

### ISSUE THREAD

**Issue by codygman** [ch11ng/exwm#699]
It seems like most use `s-b` to switch buffers from X applications back to emacs buffers and maybe something else from emacs buffers? Maybe others switch to using `s-b` everywhere? My usual bind for switching buffers is `SPC b b` and I couldn't get that working in both X buffers (ex. firefox) and emacs buffers.

I figured out how to get `s-b` to work, but now have to figure out how to bind `s-b` with general if I want to go the route of re-learning a new binding for switching buffers. `s-b` is slightly better than `SPC b b` anyway so I might go this route.

I think it would be valuable to have a guide on how to get the same buffer switching behavior regardless of whether you are in a normal emacs buffer or exwm buffer.

**Comment by QiangF** [comment]
I think we need to integrate exwm-workspace-switch-to-buffer to switch-to-buffer, then you can just use the normal emacs buffer switching.

    (defun my-exwm-workspace-switch-to-buffer (orig-func buffer-or-name &rest args)
      (when buffer-or-name
        (if (get-buffer buffer-or-name)
            (progn
              ;; hide buffers on other workspaces
              (unless exwm-workspace-show-all-buffers
                (dolist (pair exwm--id-buffer-alist)
                  (with-current-buffer (cdr pair)
                    (unless (or (eq exwm--frame exwm-workspace--current)
                                (= ?\s (aref (buffer-name) 0)))
                      (let ((buffer-list-update-hook
                              (remq #'exwm-input--on-buffer-list-update
                                    buffer-list-update-hook)))
                        (rename-buffer (concat " " (buffer-name))))))))

              ;; floating frame
              (if (or exwm--floating-frame
                      (with-current-buffer buffer-or-name exwm--floating-frame))
                  (exwm-workspace-switch-to-buffer buffer-or-name)
                  (apply orig-func buffer-or-name args)))
            (apply orig-func buffer-or-name args))))

    (advice-add 'switch-to-buffer :around 'my-exwm-workspace-switch-to-buffer)

**Comment by codygman** [comment]
I'm not quite sure if that addresses what I'd like to do. It doesn't help me achieve  use =SPC b b= to switch buffers in emacs, in firefox in char mode, and in firefox line mode.

**Comment by codygman** [comment]
I'm not quite sure if that addresses what I'd like to do. It doesn't help me achieve  use =SPC b b= to switch buffers in emacs, in firefox in char mode, and in firefox line mode.

I'm surprised it seems others don't also use the same binding to switch buffers regardless of context.

**Comment by ch11ng** [comment]
To use <kbd>SPC b b</kbd> globally you'll have to make <kbd>SPC</kbd> a prefix key, which means pressing & releasing <kbd>SPC</kbd> alone won't have any effect normally.  This is probably not what you want as this key is so frequently used.  I don't know if there is any trick out there to work around this.

**Comment by codygman** [comment]
I think I've figured out that many probably use the default `C-x b` binding which works in all contexts. The least effort way for me might just be to do that as well.

Closing since that's a solution for me for now.
