### ISSUE TITLE
xcb:SetupFailed [...] No protocol specified

### ISSUE THREAD

**Issue by jdhuntington** [ch11ng/exwm#7]
Just tried to get this running with `master` commits of exwm, xelb, and xelb-util (on a 32 bit install) and the init given in the example.

Ran into these errors on startup. Any suggestions? Thanks! 

    error in process filter: let: [XELB] [object xcb:SetupFailed xcb:SetupFailed t 0 22 11 0 6 No protocol specified
    (name reason type xcb:char size (xcb:-fieldref (quote reason-len)))]
    error in process filter: [XELB] [object xcb:SetupFailed xcb:SetupFailed t 0 22 11 0 6 No protocol specified
    (name reason type xcb:char size (xcb:-fieldref (quote reason-len)))]
    error in process filter: let: [XELB] [object xcb:SetupFailed xcb:SetupFailed t 0 22 11 0 6 No protocol specified
    (name reason type xcb:char size (xcb:-fieldref (quote reason-len)))]
    error in process filter: [XELB] [object xcb:SetupFailed xcb:SetupFailed t 0 22 11 0 6 No protocol specified
    (name reason type xcb:char size (xcb:-fieldref (quote reason-len)))]

**Comment by ch11ng** [comment]
Same as #4

**Comment by jdhuntington** [comment]
Thank you! Sorry I missed #4.
