### ISSUE TITLE
[wishlist] Could we have an option not to use C-c in the exwm-input-prefix-keys ?

### ISSUE THREAD

**Issue by CestDiego** [ch11ng/exwm#70]
It makes it really hard to use C-c or C-v to copy and paste which is kinda like a surprise for newcommers. I know it's the default for user-defined keybindings, but if one could opt-out of having C-c in the prefix keys it would be a great options... Mainly because it's *not even* in such variable but it's hardcoded in https://github.com/syl20bnr/spacemacs/blob/perspectives-fix/elpa/exwm-20150919.2151/exwm-input.el#L262

**Comment by ch11ng** [comment]
It's possible. I'll think about it.

**Comment by uu1101** [comment]
I tend to agree with regards to making it configurable... it would help alleviate the XTerm issue #71.

**Comment by ch11ng** [comment]
Fixed in 22ee3e6c5ffdc73f231e7125f48827dc1d44237f.

**Comment by uu1101** [comment]
Thank you!
