### ISSUE TITLE
Switch keyboard languages / toggle-input-method in non Emacs buffers

### ISSUE THREAD

**Issue by tenpast** [ch11ng/exwm#702]
Thank you for a fantastic package. 

I have been unable to find a way to change keyboard layout on applications such as Firefox, Rambox, etc. In Emacs buffers I do so using toggle-input-method. Is this possible to do?

**Comment by ch11ng** [comment]
If there's already an Emacs input method meets your need, you may give the `exwm-xim` module a try (please refer to the user guide for instructions).

**Comment by tenpast** [comment]
Hi, thanks for your response. I have spent quite some time trying to get this to work, to no avail. I looked through the user guide, but the only place I found instructions was in the exwm-xim.el file. I followed those exactly as written. I then change the input language on a buffer with an X application and can see that the input method does change on the mode line, but X Applications do not use the new input method. Am I missing something? Thank you!

These are the instructions I followed:

;; To use this module, first load and enable it as follows:
;;
;;    (require 'exwm-xim)
;;    (exwm-xim-enable)
;;
;; A keybinding for `toggle-input-method' is probably required to turn on &
;; off an input method (default to `default-input-method').  It's bound to
;; 'C-\' by default and can be made reachable when working with X windows:
;;
;;    (push ?\C-\\ exwm-input-prefix-keys)
;;
;; It's also required (and error-prone) to setup environment variables to
;; make applications actually use this input method.  Typically the
;; following lines should be inserted into '~/.xinitrc'.
;;
;;    export XMODIFIERS=@im=exwm-xim
;;    export GTK_IM_MODULE=xim
;;    export QT_IM_MODULE=xim
;;    export CLUTTER_IM_MODULE=xim

**Comment by QiangF** [comment]
If you are the only one that uses that input method, maybe you can put it somewhere for others to see. The problem could be in your input method.

**Comment by ch11ng** [comment]
Please examine the environment variables with e.g. `echo $XMODIFIERS` and make sure the application supports XIM.  If you are not sure, try xterm first.

**Comment by medranocalvo** [comment]
@tenpast, is your issue solved?

**Comment by tenpast** [comment]
I have solved this issue successfully. Thanks a lot for the assistance!
