### ISSUE TITLE
C-c is not sent to the application in char-mode

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#708]
It used to work properly a few months ago.  I haven't touched my EXWM config much, beside installing exwm-edit.

Any clue?

**Comment by medranocalvo** [comment]
Is this XTerm? If so, you must "Allow SendEvents" (C-mouse1 menu).

**Comment by Ambrevar** [comment]
No, all EXWM windows :p

**Comment by ch11ng** [comment]
So you must have make a global binding for it.  What does the configuration look like? Does other global key bindings work as intended?

**Comment by Ambrevar** [comment]
Making progress: I have `(require 'exwm-edit nil 'noerror)` in my config.
EXWM-edit has this in its code:

```elisp
(exwm-input-set-key (kbd "C-c '") #'exwm-edit--compose)
(exwm-input-set-key (kbd "C-c C-'") #'exwm-edit--compose)
```

and 

```elisp
(defvar exwm-edit-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c '") 'exwm-edit--finish)
    (define-key map (kbd "C-c C-'") 'exwm-edit--finish)
    (define-key map (kbd "C-c C-c") 'exwm-edit--finish)
    (define-key map (kbd "C-c C-k") 'exwm-edit--cancel)
    map)
  "Keymap for minor mode `exwm-edit-mode'.")
```

If I comment out the `require`, then "C-c" works even if I load exwm-edit after logging in.

**Comment by ch11ng** [comment]
The calls to `exwm-input-set-key` are problematic.  They won't take effect unless called interactively or put into config file, and they disable C-c when in effect.

**Comment by Ambrevar** [comment]
So what do you suggest then?

**Comment by ch11ng** [comment]
There shouldn't be any side effect by just loading a package.  That is, the two forms should be removed from there.

**Comment by medranocalvo** [comment]
I suggest either binding <kbd>C-c C-c</kbd> to send <kbd>C-c</kbd> or (better) lobbying exwm-edit to use a different or a configurable prefix.

The best solution would be to get rid of `exwm-input-set-key` and use regular keymaps instead, though I doubt it's easy.  I think https://github.com/ch11ng/exwm/commit/3420cd24d107bf9a0396089bb00396e6ab35447e is a step in that direction, though I haven't been able to investigate.

**Comment by medranocalvo** [comment]
@Ambrevar, can this ticket be closed?

**Comment by Ambrevar** [comment]
Sorry, forgot about it.

**Comment by medranocalvo** [comment]
No problem.
