### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by bijang** [ch11ng/exwm#710]
is there progress on wayland support?

**Comment by ch11ng** [comment]
No.  Neither in the Emacs community I'm afraid.  What's the status of Wayland as of 2020? It seems a couple of distros have made it the default display server.

**Comment by bijang** [comment]
Slow but steady, GNOME has it's version being spuured by redhat, KDE is close to getting Kwin ported to the point of being the default, running off wlroots project, a side effect of the sway community porting i3, notably has wlroots for non C language binding like Cl-wlroots and cl-wayland (for common lisp).

**Comment by ch11ng** [comment]
It seems cl-wlroots is an FFI binding for the library and the Elisp counterpart is dynamic modules.
We already had some discussions about this topic in #559 so I'm closing this one in favor of that.
