### ISSUE TITLE
exwm wants to "Replace existing window manager" under Xephyr on Emacs 27

### ISSUE THREAD

**Issue by vonHabsi** [ch11ng/exwm#711]
Prior to upgrading to Emacs 27  I have been able to run multiple sessions of Xephyr, but after upgrading to Emacs 27, new instances come up with the `Replace existing window manager? (yes or no)` prompt.

When I answer `yes`, it takes over the underlying KDE 5 desktop on which the Xephyr session is run. It as though it is not even aware that is is running under Xephyr.

**Comment by ch11ng** [comment]
It likely has nothing to do with the upgrade.  You have to set up the `$DISPLAY` environment variable correctly for Emacs, which defaults to `:0` on which your desktop runs.  I believe you must have specified which display to use when launching Xephyr, so it'd be as simple as prepending that to the command launching Emacs/EXWM.

**Comment by vonHabsi** [comment]
I always start exwm/Xephyr with the command 
`startx ~/exwm_xinitrc -- /usr/bin/Xephyr :4 -screen 1366x768`

I alway include the `$DISPLAY`. After upgrading to the emacs 27, the first instance above works.

When I follow it up with `startx ~/exwm_xinitrc_chemacs -- /usr/bin/Xephyr :5 -screen 1366x768` it seems that somewhere along the line exwm gets ignorant that it is supposed to be running under Xephyr, let alone under `$DISPLAY :5`

**Comment by vonHabsi** [comment]
Sorry I think I was invoking the follow up command from the history without the preceding `startx`, ie just `~/exwm_xinitrc_chemacs -- /usr/bin/Xephyr :5 -screen 1366x768`

My bad
