### ISSUE TITLE
Binding C-[ to escape in setq exwm-input-simulation-keys

### ISSUE THREAD

**Issue by nhmacuk** [ch11ng/exwm#712]
I tried so far:
```           
;; ([ESC] . [escape])
;; ([?\e ] . [escape]) ;;crashes exwm
;;((kbd "C-[") . [escape])
;;(,(kbd "C-[") .   ,(kbd "escape"))
;;([escape] . [escape])
```
```(key-description (vector (read-key)))``` followd by C-[ returns ESC.

**Comment by ch11ng** [comment]
Please try the Customize interface for `exwm-input-set-simulation-key`.
 There you can use the `INS` button to add a new binding, and fill in the `Original` and `Choice/User-defined` fields by typing <kbd>C-q</kbd> followed by the key in choice (answer `n` when prompted whether to use <kbd>ESC</kbd> for <kbd>escape</kbd>).

However the use of <kbd>ESC</kbd> here is discouraged as it'd effectively disable the use of <kbd>M-*</kbd> (`*` stands for any character here), as for example <kbd>ESC x</kbd> is actually equivalent to <kbd>M-x</kbd>.

**Comment by nhmacuk** [comment]
Ah thanks, I won't use <kbd> ESC </kbd> then. I'll try to use the easy customize interface for the other keys.
