### ISSUE TITLE
How to send non printable characters to an exwm-mode buffer via the input method

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#715]
For example, the following input method translate all key to delete, but it doesn't work in exwm-mode buffer

    (defun test-input-method (key)
        (list 127))

    (defun test-activate ()
        (setq input-method-function 'test-input-method))

    (register-input-method "test" "euc-cn" 'test-activate "test input method")

I am working on a chinese input method, which sometimes need to send non-printable characters like delete, deletechar to modify already typed text.
https://github.com/QiangF/liberime/

I also tried 

    (push key unread-command-events)

But exwm-xim doesn't accept these non-printable chars as valid input.

**Comment by ch11ng** [comment]
Character 127 would be rejected even if sent.  Not sure if it's reliable and desirable to send backspace to applications as it seems the XIM protocol provides no info about the surrounding text.

Aside from that, it's possible to use `XIM_FORWARD_EVENT` to send <kbd>backspace</kbd>.
But such use would violate the protocol, as from the spec (here IM server is the XIM module in EXWM):

> XIM_FORWARD_EVENT message is used for forwarding the events from the IM library to the IM Server in order for IM to be able to filter the event. **On the other hand, this message is also used for forwarding the events from the IM Server to the IM library *if the event forwarded from the IM library is not filtered*.**

Also, it's only feasible when such user-typed keys are intended to be 'translated' to <kbd>backspace</kbd> only.
That is, one key cannot generate both a <kbd>backspace</kbd> and some text at the same time.

It's also possible to fake a <kbd>backspace</kbd> event which is trickier and can cause timing issues.

**Comment by QiangF** [comment]
Thank you for the explanation.
