### ISSUE TITLE
Java application freeze

### ISSUE THREAD

**Issue by ram535** [ch11ng/exwm#717]
I was trying this java application called jdownloader2. It completely freeze when open. It just appear a gray screen which you can't interact.
 
Putting `export _JAVA_AWT_WM_NONREPARENTING=1` in `.xinitrc` did no work.

I am using:
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

**Comment by ch11ng** [comment]
Aside from ensuring `_JAVA_AWT_WM_NONREPARENTING` is set, did you have XIM enabled like I just discovered in https://github.com/ch11ng/exwm/issues/697#issuecomment-570888607 ?

**Comment by ram535** [comment]
I added this:

```
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim
```

But the buffer still only show a gray screen.

**Comment by ram535** [comment]
I added `export _JAVA_AWT_WM_NONREPARE` to `.profile` and it worked.
