### ISSUE TITLE
Support _NET_WM_STATE_HIDDEN

### ISSUE THREAD

**Issue by djeis97** [ch11ng/exwm#719]
I've discovered an application that doesn't properly handle the case of setting `WM_STATE` to Iconic without also setting `_NET_WM_STATE` to hidden.

I think I fixed the problem by adding
```
      (xcb:+request exwm--connection
          (make-instance 'xcb:ewmh:set-_NET_WM_STATE
                         :window exwm--id
                         :data (vector)))
      (setq exwm--ewmh-state
            (delq xcb:Atom:_NET_WM_STATE_HIDDEN exwm--ewmh-state))

```
and
```
      (xcb:+request exwm--connection
          (make-instance 'xcb:ewmh:set-_NET_WM_STATE
                         :window exwm--id
                         :data (vector xcb:Atom:_NET_WM_STATE_HIDDEN)))
      (cl-pushnew xcb:Atom:_NET_WM_STATE_HIDDEN exwm--ewmh-state)
```
to `exwm-layout--show` and `exwm-layout--hide` respectively (based on similar code in the handling of fullscreen), but I'm not sure if that's the "right" solution or not.

**Comment by ch11ng** [comment]
The spec declares this property to be optional, but I think it's fine to include it here.  Could you name the application so we can verify our implementation?

**Comment by djeis97** [comment]
The application is Discord’s desktop client (https://discordapp.com), and the issue specifically has to do with it conditionally sending notifications over dbus. The client only lets you view one channel at a time. No matter what state it is in, discord will send notifications from any of the other channels that aren’t visible. However, it mutes notifications from the channel you do have visible- presumably the idea is those notifications would be redundant because you can see the channel. However, it continues muting those notifications even when the window is iconified. Setting the state to hidden allows those notifications to come through again.

**Comment by ch11ng** [comment]
Please check out 3dbf1b1bed96d9ac3ee2718134ded619f46951bb the fix.

**Comment by medranocalvo** [comment]
@djeis97 ping.

**Comment by medranocalvo** [comment]
Closing for lack of response. @djeis97, please reopen if needed.
