### ISSUE TITLE
Click on X window does not switch focus anymore

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#72]
With external monitor setup, click on any window on one monitor would switch focus to the workspace on this monitor if the focus was previously on the second one. This is no longer the case, only Emacs buffer window will change the focus now. 

It can be seen in *Messages* log:

After click on Emacs buffer window on second monitor: 
```
[EXWM] Focus on workspace 2
[EXWM] Focus on #<window 22 on *Messages*>
[EXWM] Focus on workspace 0
[EXWM] Workspace was switched unexpectedly
```

After click on X window on second monitor:
```
[EXWM] Set focus on #x12000a2
[EXWM] Focus on #x12000a2 with SetInputFocus
```

Workspace 2 is the active workspace, workspace 0 the workspace with Emacs buffer I click, and 'Messages' name of the buffer.

**Comment by ch11ng** [comment]
Fixed in f685de12d464b334ba7efdfe67e989dd63a96fa0.
