### ISSUE TITLE
Menu navigation in wiki seems broken

### ISSUE THREAD

**Issue by arael** [ch11ng/exwm#720]
The menu navigation in the wiki seems broken.

This is the correct URL https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide.

But the links in the side menu lack the page name "EXWM-User-Guide".

For example, clicking on Prerequisites points to this:

https://github.com/ch11ng/exwm/wiki#prerequisites

**Comment by minikN** [comment]
Click on `Pages` above the navigation menu and select from there. I think they are currently remaking the wiki.

**Comment by medranocalvo** [comment]
I think it's an oversight.

The "Home" page was renamed to "EXWM User Guide" in a4f7719ff0776986c04a76b02e8775d8f44133c7; probably by mistake.  Did the wiki "work" up to a week ago?

Then @AdrianoSROSA created a new "Home" fdd9f11099df24be69f978d9d58d73a32b1713fc. I'm not sure it's an improvement.

A possible fix would be to rename the "EXWM User Guide" page back to "Home".

Another option is to place a brief description of EXWM on the Home page with a screenshot or GIF, and links to the guide, etc.  The sidebar links would need to be adapted then.

@ch11ng?

**Comment by medranocalvo** [comment]
I reverted both changes meanwhile.

**Comment by ch11ng** [comment]
No idea why that change was made.  However it's better to keep the links persistent to avoid breaking other sites.  Thanks for fixing that!
