### ISSUE TITLE
How to remove C-c o keybinding in ansi-term 

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#721]
Hi,

The default exwm keybinding to switch workspace `C-c o [n]` seem to conflict with ansi-term's default `C-c o` keybinding. When I type `C-c o` when in ansi-term window, I sometimes get the switch-to-other-window behavior instead of exwm presenting me with the workspace list.

Does anyone else face this issue? If yes, how can I remove this one specific keybinding from ansi-term keymap?

Thanks,
Chaitanya

**Comment by medranocalvo** [comment]
<kbd>C-c o</kbd> is not defined by EXWM.

You can find the keymap the key sequence belongs to by pressing <kbd>C-h k C-c o</kbd>.

You can disable the key sequence in that keymap as follows:

```elisp
(define-key whatever-map (kbd "C-c o") nil)
```
