### ISSUE TITLE
exwm doesnt fill the screen / has wrong geometry

### ISSUE THREAD

**Issue by n8m4** [ch11ng/exwm#724]
~ 1-2 pixels on the bottom and ~5 on the right. It aligns correctly if i add new workspace and switch to it. But if i try to kill any of the workspaces, i get error saying "Attempt to delete a surrogate minibuffer frame"

**Comment by medranocalvo** [comment]
This is unusual.

Could you provide more details?  Please, follow the instructions at https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#how-to-report-a-bug.

**Comment by n8m4** [comment]
Seems like problem fixed when i added -fs cli option to emacs. 
