### ISSUE TITLE
Changing keybinding for `exwm-reset` breaks `char-mode`

### ISSUE THREAD

**Issue by minikN** [ch11ng/exwm#725]
Hello. I have this snippet in my config for global key bindings:

```
(setq exwm-input-global-keys
      `(
        ;; Bind "s-r" to exit char-mode and fullscreen mode.
        ([?\s-1] . (lambda () (interactive) (exwm-workspace-switch 0)))
        ([?\s-2] . (lambda () (interactive) (exwm-workspace-switch 1)))
        ([?\s-3] . (lambda () (interactive) (exwm-workspace-switch 2)))
        ([?\s-4] . (lambda () (interactive) (exwm-workspace-switch 3)))
        ([?\s-5] . (lambda () (interactive) (exwm-workspace-switch 4)))
        ([?\s-6] . (lambda () (interactive) (exwm-workspace-switch 5)))
        ([?\s-7] . (lambda () (interactive) (exwm-workspace-switch 6)))
        ([?\s-8] . (lambda () (interactive) (exwm-workspace-switch 7)))
        ([?\s-9] . (lambda () (interactive) (exwm-workspace-switch 8)))
        ([?\s-0] . (lambda () (interactive) (exwm-workspace-switch 9)))
        ([?\s-r] . exwm-reset)
        ([?\s-w] . exwm-workspace-switch)
        ([?\s-&] . (lambda (command)
                     (interactive (list (read-shell-command "$ ")))
                     (start-process-shell-command command nil command)))
        ))
```

However, I want to change `s-r` to something else, let's say `s-ESC`, when I do so

```
([(super escape)] . (lambda () (interactive) (exwm-workspace-switch 9)))
```
It breaks `char-mode`. I can't input anything anymore in char-mode, it all gets redirected to emacs instead of the x application.

The root of my problem is that I'm using `doom-emacs` which has the `SPC` key as a leader key. I'm having a hard time switching focus from an x application to emacs in both `char` and `line-mode`. `SPC` will always get redirected to the x application. `SpacemacsOS` hacked together [https://github.com/timor/spacemacsOS/blob/50a5d572b564a0d840384caab3b3199048696d11/funcs.el#L44](exwm/escape), which works, however I'm not a big fan of it. So I guess I have two questions:

1. How can I rebind `exwm-reset` to lets say `s-ESC` or `s-backspace`?
2. Is anyone using `doom-emacs` and if so, how do you redirect `SPC` to emacs when needed? -> I guess one option would be to send **all** input to emacs when in `line-mode` ...?

**Comment by medranocalvo** [comment]
1.  The binding works for me:
```elisp
(exwm-input-set-key [(super escape)]
                    (lambda () (interactive) (message "Works %s" (format-time-string "%H%M%S"))))
(exwm-input--update-global-prefix-keys)
```
   Binding to `exwm-reset` works as well.  Note that `exwm-reset` switches from `char-mode` to `line-mode`.

 2. Please, see if https://github.com/ch11ng/exwm/wiki/Notes-to-Spacemacs-users helps you.  If it does, or you find another solution, please add it to the Wiki (e.g., create a new page Notes to Doom users).

**Comment by minikN** [comment]
> 1. The binding works for me:
> 
> ```emacs-lisp
> (exwm-input-set-key [(super escape)]
>                     (lambda () (interactive) (message "Works %s" (format-time-string "%H%M%S"))))
> (exwm-input--update-global-prefix-keys)
> ```
> 
> Binding to `exwm-reset` works as well. Note that `exwm-reset` switches from `char-mode` to `line-mode`.
> 

Thank you. I tried this:

```
(setq exwm-input-global-keys
      `(
        ;; Bind "s-r" to exit char-mode and fullscreen mode.
        ([?\s-1] . (lambda () (interactive) (exwm-workspace-switch 0)))
        ([?\s-2] . (lambda () (interactive) (exwm-workspace-switch 1)))
        ([?\s-3] . (lambda () (interactive) (exwm-workspace-switch 2)))
        ([?\s-4] . (lambda () (interactive) (exwm-workspace-switch 3)))
        ([?\s-5] . (lambda () (interactive) (exwm-workspace-switch 4)))
        ([?\s-6] . (lambda () (interactive) (exwm-workspace-switch 5)))
        ([?\s-7] . (lambda () (interactive) (exwm-workspace-switch 6)))
        ([?\s-8] . (lambda () (interactive) (exwm-workspace-switch 7)))
        ([?\s-9] . (lambda () (interactive) (exwm-workspace-switch 8)))
        ([?\s-0] . (lambda () (interactive) (exwm-workspace-switch 9)))
        ([(super escape)] . (lambda () (interactive) (exwm-reset)))
        ;([?\s-r] . exwm-reset)
        ([?\s-w] . exwm-workspace-switch)
        ([?\s-&] . (lambda (command)
                     (interactive (list (read-shell-command "$ ")))
                     (start-process-shell-command command nil command)))
        ))

```
Which doesn't work. Can't type anything in `char-mode` after I did that. I will try out your suggestion.

> 1. Please, see if https://github.com/ch11ng/exwm/wiki/Notes-to-Spacemacs-users helps you.  If it does, or you find another solution, please add it to the Wiki (e.g., create a new page Notes to Doom users).

I actually just discovered that page 10 minutes ago. I don't really like the idea of rebinding `SPC` to `m-SPC` to be honest. I'll see what I can come up with.

**Comment by minikN** [comment]
> 1. The binding works for me:
> 
> ```emacs-lisp
> (exwm-input-set-key [(super escape)]
>                     (lambda () (interactive) (message "Works %s" (format-time-string "%H%M%S"))))
> (exwm-input--update-global-prefix-keys)
> ```
> 
> Binding to `exwm-reset` works as well. Note that `exwm-reset` switches from `char-mode` to `line-mode`.

This actually doesn't work for me. No idea what I'm doing wrong. If I add it and let it execute `exwm-reset` I'm not able to type in `char-mode` any more. (I have `(setq exwm-manage-configurations '((t char-mode t)))` set). 

It tells me `Buffer ... is read-only` in the minibuffer.

**Comment by medranocalvo** [comment]
For some reason the X window loses focus.  Probably you are not doing nothing wrong.  It sounds similar to #585.

* Does the same happen if you run `exwm-reset` from other keybinding (e.g. <kbd>s-r</kbd>)?
* Does it get fixed when you click on the X window?  (Try clicking around and back.)
* Does it get fixed when you switch workspaces?
* Does it get fixed when you switch to `line-mode`?  And back to `char-mode`?

**Comment by minikN** [comment]
> For some reason the X window loses focus. Probably you are not doing nothing wrong. It sounds similar to #585.
> 
> * Does the same happen if you run `exwm-reset` from other keybinding (e.g. s-r)?
It works with `s-r`.
> * Does it get fixed when you click on the X window?  (Try clicking around and back.)
No.
> * Does it get fixed when you switch workspaces?
No.
> * Does it get fixed when you switch to `line-mode`?  And back to `char-mode`?
No.

**Comment by minikN** [comment]
> For some reason the X window loses focus. Probably you are not doing nothing wrong. It sounds similar to #585.

Maybe, I don't know. What actually happens is that the input is not redirected to the x application in char-mode any more. Whatever key I type, I see in the minibuffer, looks to me emacs is interpreting the key presses instead of sending them to the application.

**Comment by medranocalvo** [comment]
Hmm.

What does <kbd>C-h c s-ESC</kbd> say?  Here it's:
> \<s-escape> runs the command exwm-reset

Otherwise, please paste the log (see https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#how-to-report-a-bug).

I'd recommend you to disable other modes (incl. Doom), and try to find out when does it break.

I can't help you anymore right now.

**Comment by minikN** [comment]
With
```
([(super escape)] . (lambda () (interactive) (exwm-reset)))
```
`C-h c s-ESC` reports `<s-escape> runs the command (lambda nil (interactive) (exwm-reset))`.
Pressing `s-ESC` in char-mode works.

With
```
([(super escape)] . exwm-reset)
```
`C-h c s-ESC` reports `<s-escape> runs the command exwm-reset`.
Pressing `s-ESC` in char-mode works.

However as I said, char-mode is broken in both.

**Comment by minikN** [comment]
@medranocalvo Thanks for you help so far. I gave up on `s-ESC`. I can settle with a different command as well. I now have

```
(setq exwm-input-global-keys
      `(
        ;; Bind "s-0 -> s-9" to workspaces.
        ([?\s-1] . (lambda () (interactive) (exwm-workspace-switch 0)))
        ([?\s-2] . (lambda () (interactive) (exwm-workspace-switch 1)))
        ([?\s-3] . (lambda () (interactive) (exwm-workspace-switch 2)))
        ([?\s-4] . (lambda () (interactive) (exwm-workspace-switch 3)))
        ([?\s-5] . (lambda () (interactive) (exwm-workspace-switch 4)))
        ([?\s-6] . (lambda () (interactive) (exwm-workspace-switch 5)))
        ([?\s-7] . (lambda () (interactive) (exwm-workspace-switch 6)))
        ([?\s-8] . (lambda () (interactive) (exwm-workspace-switch 7)))
        ([?\s-9] . (lambda () (interactive) (exwm-workspace-switch 8)))
        ([?\s-0] . (lambda () (interactive) (exwm-workspace-switch 9)))

        ;; Enter line mode and redirect input to emacs
        ([?\s-n] . (lambda () (interactive)
                     (exwm-reset)
                     (setq exwm-input-line-mode-passthrough t)))

        ;; Only enter line mode
        ([?\s-N] . (lambda () (interactive)
                     (exwm-reset)
                     (setq exwm-input-line-mode-passthrough nil)))

        ;; enter char-mode again
        ([?\s-i] . exwm-input-release-keyboard)
        ([?\s-w] . exwm-workspace-switch)
        ([?\s-&] . (lambda (command)
                     (interactive (list (read-shell-command "$ ")))
                     (start-process-shell-command command nil command)))
        ))

(define-key exwm-mode-map (kbd "C-c") nil)
```

This means:
`s-n`: Switch to line-mode and redirect all key presses to emacs (I can press SPC finally)
`s-N`: Normal line-mode if I ever need that.
`s-i`: Go back to char mode.

That's good for me.

**Comment by medranocalvo** [comment]
I don't understand why you need `exwm-input-line-mode-passthrough`: can't you use `exwm-input-release-keyboard` and bind <kbd>SPC</kbd> in `exwm-mode-map` (or the local version)?

```elisp
(defun my-set-SPC ()
  (use-local-map (copy-keymap (current-local-map)))
  (local-set-key (kbd "SPC") (lookup-key global-map (kbd "SPC"))))
(add-hook 'exwm-manage-finish-hook 'my-set-SPC)
```

This assumes <kbd>SPC</kbd> is bound in global map, adapt for Doom's leader key map.

**Comment by ScottFreeCode** [comment]
Is it any key chord/soquence besides s-r that's a problem, or only s-escape? I have found that Emacs generally doesn't like using escape as if it were a key in its own right, due to the special handling as an alternative meta (alt).

**Comment by ch11ng** [comment]
@ScottFreeCode <kbd>ESC</kbd>, only when pressed and released alone, is a prefix key.  Otherwise it's represented as `'espace` as in <kbd>C-escape</kbd>.  Eval `(read-key)` whenever you're unsure about such representation.
