### ISSUE TITLE
Unable to open any x application from within EXWM

### ISSUE THREAD

**Issue by minikN** [ch11ng/exwm#726]
Hello, I've recently adapted the XDG specification and moved some config files.

I added the following environment variables in `/etc/profile.d/xdg.sh`:

```
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"

 if test -z "${XDG_RUNTIME_DIR}"; then
     export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
     if ! test -d "${XDG_RUNTIME_DIR}"; then
         mkdir "${XDG_RUNTIME_DIR}"
         chmod 0700 "${XDG_RUNTIME_DIR}"
     fi
 fi
```

My `.xinitrc` in `$XDG_CONFIG_HOME/X11/xinitrc`:

```
xhost +SI:localuser:$USER
xsetroot -cursor_name left_ptr
xset r rate 200 60

export VISUAL=emacsclient
export EDITOR="$VISUAL"

exec picom & emacs
```

I launch it via `startx $XDG_CONFIG_HOME/X11/xinitrc`.

I've also changed `$XAUTHORITY`:

```
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority
```
So, `echo $XAUTHORITY`: `/tmp/1000-runtime-dir/Xauthority`.

Emacs itself starts fine, however I can't launch any X application, they all report: `No protocol specified: Unable to open X display`.

`echo $DISPLAY`: `:0`.

I think the problem is the `Xauthority` file. But I'm not able to fix this on my own sadly.

If I comment out `xhost +SI:localuser:$USER` in my `xinitrc` I get this error after starting Emacs:
```
error in process filter: [XELB] Connection failed: No protocol specified
```

**Comment by medranocalvo** [comment]
No clue.  Perhaps a permission issue?

I'd try running `xauth list`, etc.

Try using a different window manager (e.g. twm).  Does it work in that case?

Please, report back when you get it working, might be useful to others.

Perhaps others can help.

---

Aside, you probably mean:
```sh
picom &
exec emacs
```

**Comment by minikN** [comment]
> No clue. Perhaps a permission issue?
> 
> I'd try running `xauth list`, etc.
> 
> Try using a different window manager (e.g. twm). Does it work in that case?
> 
> Please, report back when you get it working, might be useful to others.
> 
> Perhaps others can help.
> 
> Aside, you probably mean:
> 
> ```shell
> picom &
> exec emacs
> ```

Okay, one step further. If I start the Xsession once so the `Xauthority` file gets created and then close it again and do `chmod 0700 $XDG_RUNTIME_DIR/Xauthority` and start the Xsession again it works. So yeah, it's an permission issue. But how to solve it permanently?

**Comment by minikN** [comment]
Alright. I just restarted my machine, and now it works. Really no idea why though.

**Comment by medranocalvo** [comment]
Good.

A guide on how to set it up on the Wiki would still be welcome.

**Comment by minikN** [comment]
> Good.
> 
> A guide on how to set it up on the Wiki would still be welcome.

Sure, you mean how to set up the XDG folder structure?

**Comment by minikN** [comment]
Btw, this is completely off-topic, but I've had issues with screen tearing ever since I use EXWM. I was finally able to fix it adding `ForceFullCompositionPipeline` to my xorg config. I've not seen this in the wiki or amongst the issue. Maybe it's worth adding it to the wiki as well.

**Comment by medranocalvo** [comment]
> Sure, you mean how to set up the XDG folder structure?

Yes.  I think there's interest in that, since Emacs 27 will support it.  I thought you might be able to help other users now that you have it fresh on your mind, especially any hints or things to watch out for.  If you think the whole thing is straightforward there's no need.

I suggest you create a new page "XDG" or something like that.

> Btw, this is completely off-topic, but I've had issues with screen tearing ever since I use EXWM. I was finally able to fix it adding ForceFullCompositionPipeline to my xorg config. I've not seen this in the wiki or amongst the issue. Maybe it's worth adding it to the wiki as well.

Well, it's not off-topic.  This will definitely help other NVidia users suffering the same issues.  Please do write it on the Wiki.  I suggest a subsection in [Known Issues](https://github.com/ch11ng/exwm/wiki#known-issues).

**Comment by minikN** [comment]
> Well, it's not off-topic. This will definitely help other NVidia users suffering the same issues. Please do write it on the Wiki. I suggest a subsection in [Known Issues](https://github.com/ch11ng/exwm/wiki#known-issues).

https://github.com/ch11ng/exwm/wiki#known-issues scroll down a bit.

**Comment by minikN** [comment]
> Yes. I think there's interest in that, since Emacs 27 will support it. I thought you might be able to help other users now that you have it fresh on your mind, especially any hints or things to watch out for. If you think the whole thing is straightforward there's no need.
> 
> I suggest you create a new page "XDG" or something like that.

There you go: [XDG specification](https://github.com/ch11ng/exwm/wiki/XDG-Specification).

**Comment by medranocalvo** [comment]
@minikN, thank you for the detailed instructions, it's very kind of you.  I'm sure it'll help others.

Regards,
Adrián.

**Comment by minikN** [comment]
@medranocalvo No problem. Always happy to help. Is there a discord server for EXWM? I know there is an IRC channel, but it holds about 10 people. I've a couple more questions about EXWM, however, I don't feel like spamming the issue tracker.

**Comment by medranocalvo** [comment]
> Is there a discord server for EXWM?

I don't think so.  At least not an "official" one (i.e., run by @ch11ng).

There was interest some time ago: https://github.com/ch11ng/exwm/issues/453.  I'm not sure whether anything resulted from it.  Possibly #exwm.  You could try reviving that ticket?

> I've a couple more questions about EXWM, however, I don't feel like spamming the issue tracker.

I think it's alright to post your questions here.  Worst case no-one can help, (e.g., they are very configuration-specific).  Best case your issue is solved and others can benefit from it (esp. if distilled to the Wiki).
