### ISSUE TITLE
Bind application to specific workspace / window?

### ISSUE THREAD

**Issue by minikN** [ch11ng/exwm#727]
Hello, I'd like to know if it's possible to bind certain applications to specific workspaces or windows inside workspaces.

I use `persp-mode` to save my workspace layouts to a file and reload them after every start. So let's say my workspace "CHAT" always has two windows split horizontally. The upper one for IRC the bottom one for discord.

Could it be possible to bind discord to the lower window of that particular workspace? So that everytime I open discord it will open in that window, or even better once I switch to the chat workspace for the first time automatically open discord in its designated window?

Thanks.

**Comment by medranocalvo** [comment]
The standard way to tell Emacs where certain buffers should be displayed is `display-buffer-alist`.  Hold on: this's been asked before! Have a look at https://github.com/ch11ng/exwm/issues/516, does it help?

> or even better once I switch to the chat workspace for the first time automatically open discord in its designated window?

I suggest you try launching it on `exwm-workspace-switch-hook`.

**Comment by medranocalvo** [comment]
Also: https://github.com/ch11ng/exwm/issues/341.

**Comment by minikN** [comment]
Will close for now and look at it thoroughly. Thanks.
