### ISSUE TITLE
Intercept key-chord.el chords in line-mode

### ISSUE THREAD

**Issue by mindlike** [ch11ng/exwm#730]
Hi! Thanks for EXWM. I've been thoroughly enjoying the consistency it brings to my computing workflows.

I use [key-chord.el](https://github.com/Russell91/emacs/blob/master/key-chord.el) heavily for many common commands. Is there an existing way to ensure Emacs receives these commands in line-mode? Currently, they are passed through to each X application, so I have to toggle `exwm-input-line-mode-passthrough` (using [this code](https://emacs.stackexchange.com/questions/33326/how-do-i-cut-and-paste-effectively-between-applications-while-using-exwm)).

If there isn't an existing way to capture key-chords, does anyone have a sense of how difficult this
would be to add?

**Comment by ch11ng** [comment]
Your link seems dead.  Did you mean [this](https://www.emacswiki.org/emacs/KeyChord)? I checked the code briefly and it seems to rely on Emacs's builtin input method feature to work.  You may get it work by configuring the `exwm-xim` module (there's a howto in the wiki) but I doubt if this is an overkill.

**Comment by mindlike** [comment]
I won't have time to dig into this further for a while. I also doubt many others would run into this, though I do think having key-chords working would be nice. I don't mind closing this as "not worth it for now".

FYI, XIM causes issues with Next browser: https://github.com/atlas-engineer/next/issues/645
