### ISSUE TITLE
Some application GUIs freeze after some time

### ISSUE THREAD

**Issue by moritzschaefer** [ch11ng/exwm#731]
On my 4K screen (Dell XPS 15 9560), some X applications freeze after a random amount of time after startup (in a matter of minutes). This happens regardless of whether they are the active window or not. Not all applications are affected. I have so far experienced problems exclusively with "code" (VisualStudio Code), qutebrowser and Zoom. Of note, once the freeze happens, these applications still seem to run (e.g. in Zoom I am still able to continue the conversation), but fail to update their UI and to respond to UI events (mouse clicks, alt+F4 etc.). There is no way to rescue these windows and I have to kill them.

Interestingly, this only happens on my 4K laptop-screen, even though it's configured in 1920x1080 resolution. When working on an HDMI-connected monitor (fullHD) those applications do not start to freeze.
I am using emacs 27.1 (spacemacs) with exwm-0.24.

Does anyone experience similar issues?
Do you see any "overlap" between the named applications (e.g. I think both Zoom and qutebrowser are based on the Qt framework)?
Which kinds of logs/debug messages might hint me to the right track?

Any help is welcome. 

EDIT: found out that 1920x1080 is also affected. So it seems that 4K is not the driving issue here

**Comment by ch11ng** [comment]
Perhaps it's possible to start by turning on and saving the debug logs of these applications.  Usually they are streamed to stdout & stderr and dropped silently.  Also it may be helpful to compare the of (working vs not working) results of `xwininfo` and `xprop`, in case EXWM makes some wrong changes to them.

**Comment by moritzschaefer** [comment]
qutebrowser did not output any error messages when freezing. The only difference (between working and frozen qutebrowser) I observed was the Height field in xwinfo which was 5px larger in the frozen window compared to the working one.

    # Working:
    Height: 2046

    # Frozen:
    Height: 2051

**Comment by ch11ng** [comment]
Five pixels are perhaps not quite noticeable on 4K screens.  Can you figure out what operation caused the difference? Besides are there any X windows created/destroyed then?

**Comment by moritzschaefer** [comment]
The freeze seems to happen randomly, independent whether qutebrowser is in focus or not.
When I have  split my frame into 2 windows, and show qutebrowser in one of them, it won't freeze (presumably, because the resolution for that window is "small enough"). 
I will try a few things to provoke the  freeze (like fast window focus switching etc).

**Comment by medranocalvo** [comment]
@moritzschaefer, any news?

**Comment by moritzschaefer** [comment]
I did not yet find a real cause or a way to reliably reproduce the error. Fast switching from/to windows also does not lead to the freezing behavior. 
Since qutebrowser is a python application, I thought I might enter a debugger somewhere in the main loop and try to find out something via that.

**Comment by moritzschaefer** [comment]
Further findings: 
- The issue persists if I use my laptop screen in 1920x1080 resolution instead of 4K
- It's somehow connected to graphics drivers. I have recently updated my system to disable the Nvidia graphics card and only intel and now almost all GUI applications freeze on my notebook screen (before, Firefox for example did not freeze, now it does).

**Comment by moritzschaefer** [comment]
I found that other window managers as for example Xfce is also affected by this bug, so I close this here. I think this issue is related to Intel graphics drivers
