### ISSUE TITLE
Extra workspace switch when minibuffer active

### ISSUE THREAD

**Issue by mindlike** [ch11ng/exwm#733]
Something like this was already noticed in the comments of #580.

If I have an active minibuffer (I tried ivy, helm, and just `eval-expression`), then switch workspaces, EXWM bounces me back to the original workspace. It also closes the minibuffer, so subsequent calls to `exwm-workspace-switch` work fine.

It's mildly annoying, but since I finally correlated it with the minibuffer being active, I thought I'd report it here.

To be clear, this is what I see.

In workspace 1: Run `eval-expression` and leave the minibuffer active. Then trigger `exwm-workspace-switch` with a key binding to switch to workspace 2.

EXWM then takes me from 1 -> 2, then immediately back 2 -> 1. The minibuffer is no longer active, and I can switch 1 -> 2 fine.

**Comment by medranocalvo** [comment]
Thank you for the report.  I think I fixed it with #736.  As you can see in the PR description, the first commit fixes the issue and the second commit does away with exiting other minibuffers upon workspace switch.

Please, try both commits separately and report any issues.

**Comment by mindlike** [comment]
FYI I've been using commit cddb342 for a few days without any issues.
Thanks!

**Comment by medranocalvo** [comment]
That's great, thanks.
Could you try https://github.com/ch11ng/exwm/pull/736/commits/373eda99bd01e5bf53abc46c8a3c096bceeff72c?  I've been using it without issues as well, but your usage might vary.

**Comment by mindlike** [comment]
Seems fine.

**Comment by medranocalvo** [comment]
Thank you.  Let's see what @ch11ng thinks.

**Comment by ch11ng** [comment]
@medranocalvo Thanks.
I agree with your proposal.
My original fix simply introduced more trouble.
