### ISSUE TITLE
Change color of mode-line when jumping between line- or char-mode

### ISSUE THREAD

**Issue by acakojic** [ch11ng/exwm#734]
How to add hook when changing` from one mode to another. I need change color of mode-line depending what mode I'm using.. I got this code:

`(add-hook 'exwm-mode-hook` 
`  (lambda () `
`    (if exwm-window-type `
`      (if (string= exwm--input-mode "mode-line") `
`          (face-remap-add-relative ' mode-line '((:foreground "red" :background "Green") mode-line))`
`       (face-remap-add-relative ' mode-line '((:foreground "ivory" :background "DarkOrange2") mode-line)) ))))`

This is only working when I enter first time in some applications..

**Comment by medranocalvo** [comment]
Hello @acakojic,

`exwm-mode-hook` is not the right hook for this: it only runs once when the X window is first handled by EXWM.

At the moment there's no hook triggered when switching between `line-mode` and `char-mode`.  I think it's a useful thing to have.

I'll try to provide one in the following days, as I find time.

**Comment by acakojic** [comment]
> Hello @acakojic,
> 
> `exwm-mode-hook` is not the right hook for this: it only runs once when the X window is first handled by EXWM.
> 
> At the moment there's no hook triggered when switching between `line-mode` and `char-mode`. I think it's a useful thing to have.
> 
> I'll try to provide one in the following days, as I find time.

**Comment by acakojic** [comment]
> > Hello @acakojic,
> > `exwm-mode-hook` is not the right hook for this: it only runs once when the X window is first handled by EXWM.
> > At the moment there's no hook triggered when switching between `line-mode` and `char-mode`. I think it's a useful thing to have.
> > I'll try to provide one in the following days, as I find time.

**Comment by acakojic** [comment]
Thank you @medranocalvo, that is great  to have :+1:

**Comment by acakojic** [comment]
@medranocalvo found the way, dunno if it good, but it works :-)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;Jumping to **line-mode**;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
`(defun change-color-line-mode ()`
`  (interactive)`
`  (call-interactively #'exwm-reset)`
`  ;; (message "change-color-line-mode")`
`  (face-remap-add-relative`
`		   'mode-line '((:background "#99ff99") mode-line))`
`  )`
implementation **line-mode**:
`(setq exwm-input-global-keys`
     \``([?\s-l] . change-color-line-mode))`
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;Jumping to **char-mode**;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
`(defun change-color-char-mode ()`
`  (interactive)`
`  (call-interactively #'exwm-input-release-keyboard)`
`  ;; (message "change-color-char-mode")`
`  (face-remap-add-relative`
`		   'mode-line '((:background "#8080ff") mode-line)))`
implementation **char-mode**:
`(define-key exwm-mode-map [?\s-c] #'change-color-char-mode)`

**Comment by medranocalvo** [comment]
@acakojic, of course it's good.  That's the spirit!

I did implement the hook, nevertheless.  Please test #738 and report whether it works for you.  You can find sample code in the pull request page.

Note I don't use `face-remap-add-relative`, as it keeps adding remappings without end.

**Comment by acakojic** [comment]
@medranocalvo  thank you in your time and effort :-)

Now I dont have minnor-mode line- or char-mode, only (EXWM)

When turn first application:
`error in process filter: custom-initialize-reset: Symbol’s function definition is void: case`
`error in process filter: Symbol’s function definition is void: case`

When turn second application:
`error in process filter: let: Symbol’s function definition is void: case`
`error in process filter: Symbol’s function definition is void: case`

**Comment by acakojic** [comment]
This is working for Firefox but not for Xterm:
`(add-hook 'exwm-input--input-mode-change-hook`
`	  (lambda ()`
`	    (if exwm-window-type`
`		(if (string= exwm--input-mode "line-mode")`
`		     (set-face-background 'mode-line "red")`
`		 (set-face-background 'mode-line "ivory")))))`

**Comment by medranocalvo** [comment]
@acakojic, I updated the sample code to use `cl-case` instead of `case`.  Please, try it again.

There are two issues with your code:
1. `(string= exwm--input-mode "line-mode")` should be `(eq exwm--input-mode 'line-mode)`
2. I think `set-face-background changes the face globally.

**Comment by chrisboeg** [comment]
When will the next release of EXWM land in ELPA?

**Comment by ch11ng** [comment]
Sorry for the long wait.  I think now it's time.
