### ISSUE TITLE
how to bind global shortcuts

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#74]
I use different shortcuts than the standard ones, so I can press C-x b to change the buffer form a X-window manager.

But I cant use my Menu + c + g shorcut that I bount also to ido-switch-buffer(that also . can I make X windows pass that Menu key shortcuts to exwm/emacs?

"""
\<menu\> c g runs the command ido-switch-buffer
"""

**Comment by spiderbit** [comment]
(exwm-input-set-key (kbd "<menu> u")
		    (lambda () (interactive) (start-process "" nil "conkeror")))

k I just added that and outside of a X window it works, but when a X window buffer is selected it eats the keys.

**Comment by ch11ng** [comment]
> I use different shortcuts than the standard ones, so I can press C-x b to change the buffer form a X-window manager.

Isn't that the default behavior?

> ``` elisp
(exwm-input-set-key (kbd "<menu> u")
            (lambda () (interactive) (start-process "" nil "conkeror")))
```
k I just added that and outside of a X window it works, but when a X window buffer is selected it eats the keys.

<kbd>\<menu\></kbd> cannot be used as a prefix key by default. You should remove it from the global keymap first, e.g.

```elisp
(global-unset-key (kbd "<menu>"))
```

But I guess you have already done this since you claimed the key worked for ordinary buffers. So maybe you have some special settings?

**Comment by spiderbit** [comment]
yes sorry I use xah-fly-keys what seems to make it possible. how exactly I don't know.

But I am not 100% shure which of the 2 packages I have to adress here.

I mean outside of a xwindow xah-fly-keys are active/availible and all from exwm, in a exwm-xwindow only the one from exwm are availible.

I mean how is C-x b managed, its no special exwm shortcut but still its not overwritten/shadowed. why is menu key shadowed or is there a way to make menu-starting shortcuts not hand through to the application.

if exwm would be a major mode (it seems it is) I guess there is a mechanism in xah-fly-keys to setup modespecific shortcuts.

I think I will try that and report back, when I testet it.

**Comment by ch11ng** [comment]
Then you may try

```elisp
(push 'menu exwm-input-prefix-keys)
````

**Comment by spiderbit** [comment]
k mode specific shortcuts like that did not work I try your push command now

```elisp
(progn
  (defun spiderbit-exwm-mode-setup ()
    "for `exwm-mode'."
    (local-set-key (kbd "<menu> c g") 'ido-switch-buffer)
    (local-set-key (kbd "<menu> RET") 'smex)))
(add-hook 'exwm-mode-hook 'spiderbit-exwm-mode-setup)
```

**Comment by spiderbit** [comment]
yes thanks very much that push command worked. now I guess I could use this send-key mechanism if I want to send some commands but for now thats as far as I can think and test, perfekt, very nice.

except some minor issues with youtube blockage and script crash and one crash of exwm so far and when gnus syncs I cant type in the browser it works now more or less flawless.

great work and thx.

**Comment by ch11ng** [comment]
Please consider report those 'minor' issues once you get reliable ways to reproduce them.

**Comment by spiderbit** [comment]
cant I reopen this bugreport? the workaround or way to push my global keys does not work anymore. or to be more precise it works now only in linemode and not in char-mode anymore.

and somehow since the switch from 0.1 to current git version, it starts windows now in linemode not in charmode, or was it always line mode and linemode works now different. when I start Conkeror in linemode I cant type into message input boxes, only if I switch to char-mode it let me type stuff into them.

**Comment by ch11ng** [comment]
I've noticed you opened a new issue, so let's just focus on that one.
