### ISSUE TITLE
german-postfix and exwm-xim

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#742]
exwm-xim works really well on simple input methods, where one key produces one letter.
For german-postfix entering `ae` will insert `ä` and to insert `ae` one need to enter `aee`. This input method shows in minibuffer current state: `ae[e]`. 

Usually any key not in square brackets will terminate current state, e.g. `ae` + `j` will insert `äj`, `ae` + `e` will insert `ae`. And `ae` + `RET` will insert `ä\n`. In exwm-xim `RET` doesn't terminate the state. Only next keypress does. `ae` + `RET` + `j` will insert `ä\nj` as expected.

**Comment by ch11ng** [comment]
In EXWM we use `'return` as opposed to `?\r` (`13` or `?\C-m`), which is 100% legal but arguably less common.  However it seems quail (upon which the 'german-postfix' input method is built) doesn't handle the `'return` event.  `function-key-map` seems to define the conversion rules but I'm not quite sure yet.  I'll think about it.

**Comment by ch11ng** [comment]
It turns out it's not the problem with translation but key not sent to Emacs.  Please checkout 7f4b9cdb0f4122f561d26dcb39d405deeadf931e for the fix.

**Comment by sarg** [comment]
Thank you, it worked out well.
