### ISSUE TITLE
How to open a terminal and send a command to it?

### ISSUE THREAD

**Issue by RidaAyed** [ch11ng/exwm#747]
I keep repeating 

- `M-x` 
- `ansi-term`
- changing to the `ansi-term` buffer
- resizing it
- typing `cd somefolder; ls`
- typing `enter`

How should I wrap this into a function in exwm?

**Comment by medranocalvo** [comment]
EXWM tries to support regular Emacs features, so one does this this under EXWM just like under non-EXWM Emacs:

```elisp
(defun my-ansi-term ()
  (interactive)
  (call-interactively 'ansi-term)
  (window-resize nil 10 10)
  (term-send-string (get-buffer-process (current-buffer))
                    "cd somefolder; ls\n")))
```

These questions are better asked on help-gnu-emacs, the Emacs StackExchange or the Emacs Reddit, as there's a bigger audience.

If the regular Emacs solution does not work under EXWM, do report it here.

I'm closing, but feel free to comment more.
