### ISSUE TITLE
In full screen mode exwm-input-prefix-keys don't work

### ISSUE THREAD

**Issue by CestDiego** [ch11ng/exwm#75]
Nevertheless keys defined in `exwm-mode-map` do work.

**Comment by ch11ng** [comment]
Fullscreen windows are forced to be in `char-mode` since it's impossible to interact with the underlying Emacs frame in this case. Thus there's nothing to do with `exwm-input-prefix-keys` here, and I think `exwm-mode-map` should not work either. What do you want to do with these variables?

**Comment by CestDiego** [comment]
well I have defined some prefix keys in `exwm-input-prefix-keys` to have functionality of splitting windows and opening things like org-agenda and other things. I like that `exwm-mode-map` works because how else are we going to toggle full screen mode?

**Comment by ch11ng** [comment]
How would it be possible to split windows in a workspace while there is a fullscreen X window completely covering it? Other things probably make little sense too. Anyway, if you do need such functionalities, you can bind them with `exwm-input-set-key`.

`exwm-reset` is a way to exit fullscreen mode and you should have it bound. <kbd>esc</kbd> and <kbd>f11</kbd> might also work, if the application supports them.
