### ISSUE TITLE
Issue with Picom

### ISSUE THREAD

**Issue by BlueFlo0d** [ch11ng/exwm#752]
When I start a Picom with blurring effect, it doesn't seem to blur the emacs running EXWM.
It prints the following suspicious message:
```
[ 05/19/2020 11:17:12.301 _win_bind_image ERROR ] Failed to get named pixmap for window 0x00820635(*scratch*)
```
Is this something to do with EXWM and if so how can I hack it?

**Comment by medranocalvo** [comment]
I don't know how it's supposed to work.  Perhaps other users of EXWM and picom can help: @minikN, @doolio,  @elnawe?

**Comment by doolio** [comment]
I don't use the blurring effect myself. However, share the settings you change from the default `picom.conf` file and describe how you start/enable `picom`. I do it via `~/.xinitrc` and I may be able to advise.

**Comment by BlueFlo0d** [comment]
I run `picom` in `.xsession` via `picom --experimental-backends --backend glx -f &`

My `picom.conf`:
```
shadow = false;
backend = "glx";
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur:
{
  method = "gaussian";
  size = 20;
  deviation = 20.0;
};
opacity-rule = [ "80:name *= \"Next\"",
                 "100:name *= \"i3lock\""];
active-opacity = 0.7;
inactive-opacity = 0.3;
frame-opacity = 0.7;
```

**Comment by minikN** [comment]
Sorry I cant help here. After I got rig of tearing from within my xorg conf, I ditched picom.

**Comment by BlueFlo0d** [comment]
Ah, I figured it out, it's `picom`'s issue. Using `ibhagwan`'s fork solves this. Closing it for now.

**Comment by medranocalvo** [comment]
Thanks everyone.
