### ISSUE TITLE
helm not displaying correctly when exwm-workspace-detach-minibuffer

### ISSUE THREAD

**Issue by BlueFlo0d** [ch11ng/exwm#753]
After mini buffer is detached, helm buffer pop up full screen (instead of being displayed in
the window), and uses a tiny font, not following the setting in `default-frame-alist`.

**Comment by medranocalvo** [comment]
Thank you for your report.

This is Helm's standard behaviour when using a minibuffer-only frame, see helm-resolve-display-function:

https://github.com/emacs-helm/helm/blob/master/helm.el#L3072-L3091

Could you bring this up in Helm's issue tracker?  I see no reason Helm could not support it (esp given the `helm-echo-input-in-header-line`), though there might be.  Please link this ticket, so that we become aware of the resolution.

**Comment by BlueFlo0d** [comment]
Thanks for your pointer! I hacked the function myself and it now works like a charm in my setup.

I'm closing this for now.

**Comment by BlueFlo0d** [comment]
It turns out that there's another issue with `helm`. Since `helm` secretly uses the mini buffer for input and copy it to the header line, it makes exwm pop up the minibuffer -- and a not-correctly-rendered mini buffer. I fixed it by adding those hooks
```
(defvar k--suppress-exwm-minibuffer nil)
  (make-variable-buffer-local 'k--suppress-exwm-minibuffer)
  (advice-add 'exwm-workspace--on-minibuffer-setup :around
              (lambda (cont)
                (unless k--suppress-exwm-minibuffer
                  (funcall cont))))
  (add-hook 'helm-minibuffer-set-up-hook
            (lambda ()
              (setq k--suppress-exwm-minibuffer t)))
  (add-hook 'helm-exit-minibuffer-hook
            (lambda ()
              (setq k--suppress-exwm-minibuffer nil)))
```
Now it seems that I've got quite a few snippets to make `helm` works better with `exwm`. I wonder where's a good place to share it? I can make a PR with those snippets wrapped in some `defcustom`, or, say, a `exwm-better-helm-mode`, but I'm not sure if you guys are happy with those seemingly very specific (for `helm`) patches.

**Comment by ch11ng** [comment]
@BlueFlo0d Thanks! Could you create an entry in the wiki? https://github.com/ch11ng/exwm/wiki#known-issues would fit for concise guides, or https://github.com/ch11ng/exwm/wiki/Cookbook for lengthy ones as @medranocalvo proposed.
