### ISSUE TITLE
Open emacsclient in new buffer / replacing current buffer

### ISSUE THREAD

**Issue by thomasheartman** [ch11ng/exwm#754]
Hi,

I was wondering whether it's possible to use `emacsclient` in a way such that it just opens a new buffer in the current frame, similar to what `magit` does, when invoking it from a terminal (either an emacs shell (eshell/multi-term etc) or an X application). Ideally, I'd like the new buffer to take the place of the terminal, mimicking how it'd work if it was invoked as a terminal application.

I might be doing something wrong, because I can't seem to make `emacsclient` create a GUI buffer without starting a completely new instance of Emacs. I am able to create a terminal window, but I'd like to get a regular GUI buffer.

I have started the server (and if I try and run `server-start`, I'm told that it's already running). 

- Using the `-c` flag, I get a new emacs instance.

- With no flags and only the name of the file, I get this message:
```
/nix/store/6k1z5hk4jrms46axc0s1qqy41d64hcsg-emacs-packages-deps/bin/emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
/nix/store/6k1z5hk4jrms46axc0s1qqy41d64hcsg-emacs-packages-deps/bin/emacsclient: No socket or alternate editor.  Please use:

        --socket-name
        --server-file      (or environment variable EMACS_SERVER_FILE)
        --alternate-editor (or environment variable ALTERNATE_EDITOR)
```

- Using `-s server <file>` (where `server` is the value of the `server-name` variable), I get a message saying `Waiting for Emacs...` and then nothing.

- Using `-t <file>` Opens a new terminal instance in an X application, but I get this message in an emacs terminal:
```
nix/store/6k1z5hk4jrms46axc0s1qqy41d64hcsg-emacs-packages-deps/bin/emacsclient: opening a frame in an Emacs term buffer is not supported
```

Overall I've not had any luck, but I did somehow manage to make `-c <file>` work just now (after presumably starting a server via `emacsclient -t <file>` and using `C-x #` to exit). But I don't know why that is or why it didn't work previously.

I've spent a couple hours now trying to make this work, but with no luck. It's likely that I'm missing something, but it's hard to find out what when I don't know what to search for. I've read the entire user guide, combed through the issues in this repo, and I've gone over a number of emacs wiki pages and manual sections, but I'm not making much progress. Any input would be greatly appreciated. I am very much at a loss here.

I'd be very happy to give you any additional information and perform any troubleshooting if you tell me what you want to know. If it is of relevance for this issue, I use spacemacs and NixOS.

Thanks for all your hard work on EXWM, by the way. It makes my day so much easier.

Cheers.

**Comment by thomasheartman** [comment]
Update: I did some further research. It seems the core of my problem was that I had an emacs service running as part of my NixOS configuration. Once I removed this, `emacsclient` worked just the way I wanted it to. Problem solved for now.

**Comment by medranocalvo** [comment]
Glad you found it.

I just created the https://github.com/ch11ng/exwm/wiki/Cookbook wiki page.  Could you write a short entry describing how to use `emacsclient` to open files from the terminal?  I think it can be useful for other users.

**Comment by thomasheartman** [comment]
Absolutely! I've created a first version and put it up. Feel free to edit it or provide other feedback and I can make another pass at it.

**Comment by medranocalvo** [comment]
That's outstanding!  Very clear.  Thank you very much.

**Comment by thomasheartman** [comment]
Great! Glad I could be of service.
