### ISSUE TITLE
Add functions to exwm-input.

### ISSUE THREAD

**Issue by sarg** [ch11ng/exwm#755]
I would like to share a way to make EXWM handle keyboard layout switching.
In my [setup](https://github.com/sarg/dotfiles/blob/master/emacs/.doom.d/modules/sarg/exwm/+xkb.el) pressing `C-\` in X windows will change xkb layout, but in emacs buffers it'll do the usual `toggle-input-method`.

**Comment by medranocalvo** [comment]
Sounds useful.  I don't change input methods, so can't judge it myself: is it something you think should be included in EXWM?

If you think it's not, I've been meaning to create a "Cookbook" section in the Wiki; this could be part of it.

Could the advice on `toggle-input-method` be substituted with `input-method-activate-hook` and `input-method-deactivate-hook`?

I think @ch11ng, might have more useful insights.

Thank you for sharing it.

**Comment by sarg** [comment]
Actually I could just replace advice with a function and bind it to `C-\`.

**Comment by ch11ng** [comment]
My use of input method is quite different so I'm not quite sure about this.  European languages speakers may find this useful.

I agree with @medranocalvo's point on the use of advice.  Advice is generally considered bad and should only be used as a last resort.  It'd be better to avoid it and define <kbd>C-\\</kbd> in `exwm-mode-map` directly.

**Comment by sarg** [comment]
Yeah, `exwm-mode-map` seems to be the perfect place for the binding. Thanks, I've adjusted my config.

**Comment by ch11ng** [comment]
Glad it helps.  Could you place a copy of it into the [cookbook](https://github.com/ch11ng/exwm/wiki/Cookbook)?

**Comment by sarg** [comment]
Sure, I've added a section to the cookbook.

**Comment by ch11ng** [comment]
Thank you!
