### ISSUE TITLE
Global prefix key

### ISSUE THREAD

**Issue by pedrojamaral** [ch11ng/exwm#757]
I was wondering if it was possible to set prefix keys that worked on both line and char modes. Basically exwm-input-prefix-keys that also works on char-mode. Thanks in advance - EXWM is great!

**Comment by ch11ng** [comment]
I think `exwm-input-invoke-factory` is what you need.  It should work in both char-mode and line-mode.  Please have a look at [this](https://github.com/ch11ng/exwm/issues/635#issuecomment-549365025) on one of its usage.

**Comment by pedrojamaral** [comment]
Thanks for the quick response!
