### ISSUE TITLE
External monitor floating windows position

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#76]
With external monitor (``` xrandr --output LVDS1 --auto --output HDMI3 --auto --right-of LVDS1 --primary```), floating windows position is somehow broken with certain applications, so their position is not in the center of the focused frame. So far I saw this behaviour with Thunar, Deluge, Nautilus, Transmission-gtk.

How to reproduce:
Move to external monitor, split into two frames, open some GUI application in first frame and do some operation that pops floating window, for example 'properties' of some file in Thunar/Nautilus. Floating window usually appears in the second frame and partially off the screen.

**Comment by ch11ng** [comment]
Does 3b518eec23e221aa2480970dd35c11c68653869a fix your problem?

**Comment by fm4d** [comment]
It does, thank you.
