### ISSUE TITLE
exwm-xim debug

### ISSUE THREAD

**Issue by rayslava** [ch11ng/exwm#765]
After update to latest version of `exwm` input via `exwm-xim` stopped working.
Are there any methods to debug what's wrong? Maybe some debug output for xim?

**Comment by rayslava** [comment]
Falled back to `exim`

**Comment by ch11ng** [comment]
There are some tips on debugging here: https://github.com/ch11ng/exwm/wiki#how-to-report-a-bug.  Please make sure the following lines are in your config file

```elisp
(require 'exwm-xim)
(exwm-xim-enable)
```

and the environment variable `XMODIFIERS` is correctly set via

```shell
export XMODIFIERS=@im=exwm-xim
```

(check it with `echo $XMODIFIERS`)
