### ISSUE TITLE
Extending exwm-input-simulation-keys to allow holding keys?

### ISSUE THREAD

**Issue by zackteo** [ch11ng/exwm#766]
Am thinking is it possible to allow holding down of keys. To allow recreating stuff like set-mark (S-SPC) etc, where it is toggling the holding of shift.

**Comment by ch11ng** [comment]
X11 seems to have <kbd>shift-lock</kbd> key for this, but your keyboard probabaly don't have it and you'll have to remap some key to it.  I'm afraid such key only toggles an internal state of X server, and I don't think this can be achieved through simulation keys.

**Comment by zackteo** [comment]
@ch11ng Sorry so could this potentially exist as a state like char mode/line mode. Like or could I potentially handle this with elisp? Like instead of having to press and hold a shift key :o . Or like could you direct me to resources which might be relevant? Thanks for your help!

**Comment by ch11ng** [comment]
I don't know any way to achieve it without key press.  For that key mapping thing try google 'x11 shift lock' and there are several tutorials on how to do it with 'xmodmap'.

**Comment by zackteo** [comment]
Okay will look into it!

**Comment by zackteo** [comment]
Wait but I'm not thinking without any key-press, as in I just want to press `C-SPC` like in normal emacs

**Comment by ch11ng** [comment]
I think such key mapping can only be done on the basis of KEYSYM but not a combination of them.
