### ISSUE TITLE
Shell commands in X windows

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#77]
I would like to use shell-command and async-shell-command in all buffers, not only emacs buffers, as with start-process-shell-command, can you give me some advice how to do so? Thanks.

**Comment by ch11ng** [comment]
```elisp
(push ?\M-! exwm-input-prefix-keys)
```

<kbd>M-&</kbd> already works.

**Comment by fm4d** [comment]
Yes, but I want to use single keys for these shortcuts, for example function keys and when I try to define something like ```(push ?\<XF86AudioRaiseVolume> exwm-input-prefix-keys)``` or some variation on this, it does not work.

What I want to do is to have actions binded on function keys that work in both emacs and x buffers:
```
(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>")
                    (lambda () (interactive) (async-shell-command "pulseaudio-ctl up")))
```

**Comment by ch11ng** [comment]
`?\<XF86AudioRaiseVolume>` should be `'XF86AudioRaiseVolume`. Function keys are represented as symbols.

**Comment by fm4d** [comment]
Thank you. It would be nice to have this noted in wiki, unless it is already there.
