### ISSUE TITLE
ido not working with exwm-workspace-switch

### ISSUE THREAD

**Issue by HumHongeKamyaab** [ch11ng/exwm#781]
I use `exwm-workspace-switch-to-buffer` to switch buffers.
`ido-mode` is not enabled while using this command.
Can someone tell me how to use `ido` while using this command.  

I am using following key-binding for it.
'''
(exwm-input-set-key (kbd "s-<tab>") #'exwm-workspace-switch-to-buffer)
'''

**Comment by WorldsEndless** [comment]
Like #782 I suspect this is an Ido-mode issue, rather than exwm

**Comment by HumHongeKamyaab** [comment]
I have switched to `ivy mode` now, where it is working perfectly. It is much better than `ido mode`.

**Comment by WorldsEndless** [comment]
Glad to hear it! Feel free to close this issue if it appears the problem was with a plugin not EXWM.
