### ISSUE TITLE
ido-switch-buffers not showing buffers of other workspaces

### ISSUE THREAD

**Issue by HumHongeKamyaab** [ch11ng/exwm#782]
My config:
'''
;; ido setting
(ido-mode 1)
(require 'exwm-config)
(exwm-config-ido)
(setq exwm-layout-show-all-buffers t)
'''
The `exwm-layout-show-all-buffers` is enabled, still command `ido-switch-buffer` don't show buffers from other workspaces.

Can someone tell me how to properly configure it.

**Comment by WorldsEndless** [comment]
I don't know about Ido mode, but this is probably an issue there. I have used Helm-switch-buffers, ivy-switch-buffers, and now counsel-switch-buffers, and they have all respected exwm-layout-show-all-buffers

**Comment by HumHongeKamyaab** [comment]
I have tried `ivy-switch-buffers` also, but it is also not working, i.e it doesn't show buffers of other workspaces.

This is my ivy setting
```
;; ivy setting
(setq exwm-layout-show-all-buffers t)
(setq read-buffer-completion-ignore-case t)
(ivy-mode 1)
```

**Comment by WorldsEndless** [comment]
This works for me (ie switch buffers always shows me everying), but I have one more config item that you didn't mention:

--8<---------------cut here---------------start------------->8---
    (setq exwm-workspace-show-all-buffers t)
    (setq exwm-layout-show-all-buffers t)
--8<---------------cut here---------------end--------------->8---

**Comment by HumHongeKamyaab** [comment]
@WorldsEndless Thanks for pointing it out. it solved the problem in `ivy`. I didn't test it with `ido`, but it should be fine. 
Just to repeat, you need to put following two lines in yr config to use above mentioned feature,
```
(setq exwm-workspace-show-all-buffers t)
(setq exwm-layout-show-all-buffers t)
```
