### ISSUE TITLE
conkeror lags much on js heavy sites 

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#79]
on js heavy sites like youtube conkeror under exwm (under other wms it works fine) lags heavily.

when I start a video the sound starts but the screen freeses after like 10 seconds or so I can move the screen again with mouse wheel. and the movie starts but only if I not move the mice else more picture freeses happen.

When I click on a comment field it also takes forever till I maybe can type in som stuff.

icecat dont has this problem.

**Comment by spiderbit** [comment]
k testet it with a config with only the exwm stuff and the same problem.
So it should be easy to reproduce.

**Comment by ch11ng** [comment]
I can reproduce this issue with other window managers like i3 and mutter. So it's supposed to be a problem in Conkeror. Please reopen this issue if you have more details to reveal.
