### ISSUE TITLE
Bind s-SPC and s-RET inside exwm-input-global-keys

### ISSUE THREAD

**Issue by minikN** [ch11ng/exwm#795]
Hello, I'd like to bind `s-SPC` and `s-RET` inside `exwm-input-global-keys`.

If I do `(kbd "s-RET)` it returns an integer. So this should be correct? However this doesn't work:

```lisp
  (setq exwm-input-global-keys
        `(
            ;; minimal example
            ([?\s-RET] . ansi-term)
          ))
```
I git `s-SPC` working with `[?\s- ]`, but this doesn't seem right.

Any help appreciated.

**Comment by acakojic** [comment]
@minikN 
Please check here is something fit to you, it is easy.. This is space in fake keys (exwm-input--fake-key '\ )
https://github.com/acakojic/.dotfiles/blob/master/.emacs.d/configuration/global-commands.el
