### ISSUE TITLE
display line number don't work in spacemacs

### ISSUE THREAD

**Issue by my2817** [ch11ng/exwm#796]
eamcs version: 26.1
spacemacs develop branch,  exwm layer, and enable line-number with:
``` lisp
   dotspacemacs-line-numbers 'relative
```
the value of display-line-numbers is 'relative

so, I need some advice to work with it, thanks.

**Comment by timor** [comment]
Are you sure this is related to exwm?

**Comment by my2817** [comment]
No,.and I'm looking for help just in case. thanks

**Comment by timor** [comment]
@my2817 Does `SPC t n r` (`SPC t n` in older Spacemacsen) work?

**Comment by my2817** [comment]
yes, it works, but after revert-buffer, line number disabled. I can enable it by set global value of display-line-number

**Comment by timor** [comment]
There's an entry in the manual specifically for this: https://www.spacemacs.org/doc/DOCUMENTATION#global-line-numbers
If that doesn't work, then you might want to open an issue in Spacemacs.

**Comment by my2817** [comment]
Thanks, I will check it!
