### ISSUE TITLE
xwem

### ISSUE THREAD

**Issue by yndi** [ch11ng/exwm#8]
Hi! Your window manager looks awesome.
I have a friend of mine, who has been developing some kind of similar project for XEmacs since 2003.
I believe his source code might be somewhat helpful for you: https://github.com/zevlg/xwem

**Comment by ch11ng** [comment]
Hi @yndi, I'm aware of the XWEM project and it's excellent except for that it does not run on GNU Emacs. XELB (on which EXWM is based) shares similar principles with its original code (hosted on savannah.nongnu.org), though the recent version of XWEM (as in the link you provided) relies on FFI which is not available in GNU Emacs. The XWEM project is surely helpful; it inspired my work on XELB/EXWM. Thank you @yndi for reminding me of this and, thank you @zevlg for your pioneering work.
