### ISSUE TITLE
Switch between windows in char/line mode

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#80]
I need to use char mode for my browser (conkeror/pentadactyl), but I want to be able to at least switch to other window in workspace without ```C-c k```, so I defined global keybinding ```(exwm-input-set-key (kbd "s-o") 'other-window)``` but I doesnt work as intended. With one window in char mode and second one in line or emacs buffer, after ````s-o``` it looks like focus changed to the other window (modeline highlight, carret and line highlight etc.), but actually the focus is still in char window.

**Comment by ch11ng** [comment]
Switching input focus between X windows should work irrespective of their input modes. Please double-check it. However, if an X window (the child) contains the pointer and the input focus is on the Emacs frame (the parent), then all key events, except those grabbed elsewhere, would be reported to the child, IIRC. You have to move the pointer out of the child in this case, or switch the input mode to `line-mode` before calling `other-window`.

**Comment by fm4d** [comment]
Well, I dont understand the theory behind pointers/input focus, I know that basically all GUI applications (Thunderbird, Firefox, Cherrytree..) behave as I described and the solution you mentioned, to switch input mode to ```line-mode```, which I use at the moment is really awkward, because I have to switch to line-mode before switching to other window and then switching back to char-mode.

**Comment by ch11ng** [comment]
You can perform both the switches when you press <kbd>s-o</kbd>.

You might alternatively alter the behavior of `line-mode` locally by making `exwm-input-prefix-keys` a buffer-local variable and modify its value.:

```elisp
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "Conkeror"))
              (make-variable-buffer-local 'exwm-input-prefix-keys)
              (setq exwm-input-prefix-keys '(?\C-c ?\C-x)))))
```

What do you think about this approach? Perhaps I will make other variables buffer-local if this proves useful.

**Comment by fm4d** [comment]
Yes, this approach works quite well, thanks.
