### ISSUE TITLE
[Question] how to get-buffer if buffer is on other workspace? 

### ISSUE THREAD

**Issue by gyps** [ch11ng/exwm#808]
Hello,
I'm pretty sure this has been answered before but somehow I can't find it.
I wonder how it is possible to get the buffer-id of a buffer on *any* workspace. 
The idea is to start a program (e.g. browser) only if it doesn't yet exist and otherwise just switch to it
I tried with 
`(lambda ()
		      (interactive)
		      (let ((c-buffer (get-buffer "Chromium")))
			(if c-buffer
			    (exwm-workspace-switch-to-buffer c-buffer)
			  (start-process-shell-command "chromium" nil  "chromium")))
		      )`
but if the Chromium buffer is on another workspace it doesn't find it.

Any hint?

Thanks,
Alex

**Comment by timor** [comment]
I had the same problem before, here is what works for me: https://github.com/timor/spacemacsOS/blob/d8ce7d6c8fab42bffeb157f850a36b258f6a8934/funcs.el#L63-L69

**Comment by gyps** [comment]
Thanks! This works perfectly and is exactly what I was looking for.
