### ISSUE TITLE
Spotify automatically closes

### ISSUE THREAD

**Issue by CestDiego** [ch11ng/exwm#81]
All I can see is the popup from spotify then stuff happening and spotify closing

**Comment by ch11ng** [comment]
Did you mean [this](https://www.spotify.com/us/download/linux/)? I just tried it and there seemed to be no problem. You'd better provide the procedure to reproduce this issue.

**Comment by CestDiego** [comment]
yes, it works on i3, all I can see is a popup (I guess its from the ads) opening in a new frame, with spotify behind it, then it shows up for a little bit and then it minimizes, I know it's minimizing because the process is still running and I can still control it via command line, but I cannot browse or anything, just play my old playlist.

**Comment by ch11ng** [comment]
Then what's the 'popup' and how to get it? Was the spotify buffer just buried?

**Comment by CestDiego** [comment]
Spotify buffer is not buried, I can't find it when listing buffers, I guess it's the same behaviour as other window managers, because even though you close the app, it still runs on the background and the only way to bring it to the foreground is to click on its icon in the tray...which we don't have.

**Comment by ch11ng** [comment]
Well, you didn't answer the first question. I mean when would the popup appear?

**Comment by CestDiego** [comment]
After trying again multiple times today I've seen that even if the popup doesn't show spotify just minimizes, I don't think this happens to other people so I will close this issue for now until I get a way for it to be reproducible.
