### ISSUE TITLE
How to make Emacs and not the current application capture the next key?

### ISSUE THREAD

**Issue by rdrg109** [ch11ng/exwm#827]
# The context

I'm currently using GNU Emacs 27.1 and EXWM 0.24.

I've mapped the `<f5>` key to `org-capture`.

When `<f5>` is pressed in Firefox, the current tab is refreshed. I want `org-capture` to be executed instead of refreshing the current tab in Firefox.

# The question

How can I make `<f5>` to execute `org-capture` while being in Firefox?

Is there a function that does the opposite of what `exwm-input-send-next-key` does (i.e. make Emacs capture the next key instead of the current application? Recall that the `exwm-input-send-next-key` function make the current application to capture the next key. This function is useful when we need the application to capture any key from `exwm-input-prefix-keys`, (e.g. `C-x`, `C-h`).

This content of this issue was originally published in Emacs Stack Exchange, you can find the discussion [here](https://emacs.stackexchange.com/questions/64034/how-to-make-emacs-capture-the-next-key-in-exwm) but because I didn't get any answer I decided to post it here just in case anybody knows the answer and is not active at Emacs Stack Exchange.

**Comment by thiderman** [comment]
```
(exwm-input-set-key (kbd "<f5>") #'org-capture)
```
The above should work - have you tried that? `exwm-input-set-key` will bind it both for EXWM buffers and regular ones, so it should cover your use case.

**Comment by rdrg109** [comment]
After evaluating that expression, `<f5>` still refreshes the current page in Firefox instead of executing `org-capture`.

**Comment by medranocalvo** [comment]
If evaluating the expression (as opposed to placing it in your configuration file), please evaluate `(exwm-input--update-global-prefix-keys)` afterwards.
