### ISSUE TITLE
EXWM not working with SDL2 application

### ISSUE THREAD

**Issue by drshapeless** [ch11ng/exwm#837]
I have wrote a few SDL2 applications for self use. They works fine in other window managers, like awesomewm. But when I use EXWM, whenever I initial my SDL2 applications, it results in an error of segmentation fault.
The application did appear on the middle of the screen for a fraction of second and crashed immediately.

EXWM is fine with other applications like Firefox and libreoffice, just my own SDL2 applications not working.

Is there anything I need to do in my SDL2 code to make it work on EXWM?

I am using Emacs 28.0.5 with native comp in the gccemacs branch, the master branch doesn't work for unknown reasons.

**Comment by theottm** [comment]
I think I have a similar issue. Though I am not able to track down the application causing the crash, because it doesn't happen when an app starts... Did you find a way to solve your problem? Maybe it can inspire me :)

**Comment by drshapeless** [comment]
> I think I have a similar issue. Though I am not able to track down the application causing the crash, because it doesn't happen when an app starts... Did you find a way to solve your problem? Maybe it can inspire me :)

My original repo was written on a mac machine, it compiled without modifying the code base except for a few build flags. But it crashed every time. I completely rewrote the whole repo, especially fine tuned my window resize callback function and it worked since then.
