### ISSUE TITLE
A question: how to use emacs built-in input method in LibreOffice under exwm?

### ISSUE THREAD

**Issue by wxie2017** [ch11ng/exwm#846]
Thanks for developing exwm.

This is not a bug report. I have a question:

1. I installed and setup it as in the wiki, and exwm is my only window manager for X.
2. I can use Emacs built-in input method, e.g. C-\ and choose chinese-py
3. The input method is only working in the emacs buffer, when I switch to another buffer like LibreOffice, C-\ will not work.
4. Is there a way to make the input method work for each buffer?

**Comment by zhenhua-wang** [comment]
You might want to try the exwm-xim module. It's configuration is mentioned in wiki. However, I didn't get any luck on this. I switched to ibus for x-window

**Comment by wxie2017** [comment]
Thanks for reply. I followed instruction here:
[https://parrotsec-cn.org/t/exwm/2748](https://parrotsec-cn.org/t/exwm/2748)
It works for me:

```
#+BEGIN_SRC emacs-lisp
  (require 'exwm)

  ;; simpel system tray
  (require 'exwm-systemtray)
  (exwm-systemtray-enable)

  (require 'exwm-config)
  (exwm-config-example)

  ;; using xim input
   ; (setenv "GTK_IM_MODULE" "xim")
   ; (setenv "QT_IM_MODULE" "xim")
   ; (setenv "XMODIFIERS" "@im=exwm-xim")
   ; (setenv "CLUTTER_IM_MODULE" "xim"))
  (require 'exwm-xim)
  (exwm-xim-enable)
  (push ?\C-\\ exwm-input-prefix-keys)   ;; 使用Ctrl + \ 切换输入法
#+END_SRC
```

**Comment by wxie2017** [comment]
This bug can be closed.

**Comment by aadcg** [comment]
@wxie2017, the idea of setting the relevant IM environment variables from Emacs, instead of adding them into `.xinitrc` is a good one. I think this piece of information should be added to the wiki. Care to add it?

You can close the issue by yourself.

**Comment by wxie2017** [comment]
Thank you, @aadcg 
I updated the wiki and close this issue.
