### ISSUE TITLE
Cursor Wheel

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#85]
After sending an email from gnus the cursor turns into the spinning wheel. This lasts even after the email has finished being sent and recieved. It seems to continue indefinitely.
To fix this problem persists even after quiting gnus.

**Comment by ch11ng** [comment]
This is due to an issue with the hourglass window and there is an [ugly solution](https://github.com/ch11ng/exwm/wiki#hourglass-cursor-prevents-mouse-input).  Please keep this issue open until I find a way to close the hourglass window.

**Comment by CestDiego** [comment]
I see the hourglass issue a lot. I'm getting used to pressing F10 and clicking on menus for it to disappear. :P

**Comment by ch11ng** [comment]
@CestDiego,
Yes, it's awkward.

**Comment by uu1101** [comment]
The following seems to work:
~~~{.elisp}
(setq display-hourglass nil)
~~~
Understanding the underlying issue would be best, though.

**Comment by ch11ng** [comment]
@uu1101,

We do understand the reason behind it but are just unable to fix it perfectly.  So it sounds most reasonable to disable it as it's not an essential feature.  Done in 7ee6d48a358b6d00cba77ad934dc431bbdd833c8.

**Comment by uu1101** [comment]
OK, that's fine.  Thank you!
