### ISSUE TITLE
How to make a floating frame persistent/stiky?

### ISSUE THREAD

**Issue by BuddhiLW** [ch11ng/exwm#852]
I have a frame that shows my webcam, through

```sh
mpv av://v4l2:/dev/video0 --profile=low-latency --untimed
```

How do I make this video-frame to be on top of all other frames, including when I toggle other frames in full-screen?

![pic-selected-211023-1419-05](https://user-images.githubusercontent.com/59554283/138565758-87778f36-0476-4db5-9be1-c45710dd2cce.png)

**Comment by medranocalvo** [comment]
@BuddhiLW, this feature is, as far as I know, not yet implemented in EXWM.  It is indeed something we'd like to support.

(NOTE: I sent you an important e-mail on 11.11.  Do have a look at or send me an e-mail for me to resend it.)

**Comment by BuddhiLW** [comment]
It didn't arrive, @medranocalvo. If you can, e-mail me as pedrogbranquinho@gmail.com directly. It's the github e-mail, but apparently, I didn't receive your message.

![pic-selected-211114-1439-59](https://user-images.githubusercontent.com/59554283/141692009-e1f2af34-1bc0-4594-9e93-72ff60542739.png)

**Comment by medranocalvo** [comment]
Just sent it again.  Let me know if you don't receive it.

**Comment by BuddhiLW** [comment]
Thank you! I did receive it now.

**Comment by zhenhua-wang** [comment]
@medranocalvo Hi, just to check, has this been implemented yet? This is a very useful functionality..
