### ISSUE TITLE
"Buffer is read only" with opened minibuffer 

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#86]
If you open minibuffer, for example with M-x, and switch to different workspace to EXWM buffer, input is ignored with message "Buffer is read only". This happens only with EXWM buffers.

**Comment by ch11ng** [comment]
How did you switch the workspace and what was the ignored 'input'?

**Comment by fm4d** [comment]
With exwm-workspace-switch binded to some key and the ignored input is all the standart key signals that are not captured, so for example C-p/C-n or M-x, C-x-f work (obviously commands that open minibuffer such as M-x will close the original minibuffer) but all the other key signals are not passed to application running in EXWM buffer and instead message "Buffer is read only" appears in minibuffer.

**Comment by ch11ng** [comment]
Thank you for the detailed report.  463d0da41139ccf48c9c0c9522c93041769dfcdb should fix the bug.
