### ISSUE TITLE
ultrawide experience with exwm

### ISSUE THREAD

**Issue by divansantana** [ch11ng/exwm#866]
Hi All,

Just wondering if any of you have been using an ultrawide monitor with exwm and any tips / feedback on this?

If it works well with exwm or if you handle it outside of exwm with xrandr etc?

**Comment by medranocalvo** [comment]
I haven't.  What are the difficulties you foresee?

**Comment by divansantana** [comment]
I guess it should just work.  I know some WM add special support for this, allowing full screen apps to not take the entire screen but stay confirmed to the virtual screen/space it's assigned.

I guess xrandr or something can split the monitor in 3 and it should be transparent to exwm.

I'll have to give it a try.

**Comment by medranocalvo** [comment]
If xrandr can split the screen in 3 monitors, EXWM will respect that.

I have some WIP patches to separate the "EXWM monitors" from xrandr; ideally we should be able to set a variable or somesuch.  I doubt I'll be able to propose them soon.

Please let us know how the experiment goes and, if you have some tips, please add them to the wiki!

**Comment by medranocalvo** [comment]
@divansantana, are you now a happy ultrawide user?  If so, does EXWM serve you well?  Kind regards, Adrián.

**Comment by divansantana** [comment]
@medranocalvo yes, finally got an ultrawide monitor.  Yes it works well.  I haven't split the monitor into virtual screens from an xrandr point of view.

Generally it works perfectly fine.  I guess making an app full screen, then would take the entire screen instead of just that section of the screen.  Implementing virtual screen splitting with xrandr may solve that.  Though I seldomly need that.

Have had no issues.
