### ISSUE TITLE
exwm freezes after long use

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#87]
No Emacs key bindings except M-x work. Attached image has *Messages* buffer entries. Last two errors may hint what was wrong.

![img_0916](https://cloud.githubusercontent.com/assets/52023/10706798/2a2688b8-799f-11e5-8909-928bd9794551.JPG)

This behavior is very intermittent. I was able to use exwm without any issues for weeks, but then this appears.

**Comment by ch11ng** [comment]
Since there is no backtrace and `window-normalize-window` is used intensively by `window.el` internally, I don't know where exactly the problem is. Perhaps the answers to the following questions can help narrow down the search:
* What were you trying to do (e.g. press a key or button) when that problem happens?
* Were there any floating windows?
* Was RandR module enabled?

BTW, I noticed there is a line

```
apply: Buffer name ` URxvt' is in use [11 times]
```

in the log.  Did you use `exwm-workspace-rename-buffer` as in the the example configuration?

**Comment by bvk** [comment]
> What were you trying to do (e.g. press a key or button) when that problem happens?

I was pressing keys.

> Were there any floating windows?

Yes, I was using java web start based application which has floating windows.

> Was RandR module enabled?

No, no RandR in use.

> Did you use exwm-workspace-rename-buffer as in the the example configuration?

Yes, I have the following snippet in my config.

(add-hook 'exwm-update-class-hook
					(lambda () (rename-buffer exwm-class-name t)))


Thanks,
Chaitanya

**Comment by ch11ng** [comment]
I have not find the cause of this problem yet but with ch11ng/xelb@35a055dfc825fec0101e2730d655aaecc930f193 I think such errors are no longer fatal.

**Comment by bvk** [comment]
I updated to the latest build and came across the freezing behavior again.

All keys were ignored, but M-x was working. Also, this time I was able to switch to another work space. When I switched back to the previous work space, I could see the keys I pressed earlier were *applied* without their modifier keys. For example, if I was pressing C-q repeatedly when exwm froze, I see bunch of qqq-s typed in the active buffer.

Also, when this happens, I noticed the following message in the mini-buffer.
 
 Attempt to delete minibuffer or sole ordinary window

This may be because some of the keys I pressed included C-k, but I am not sure.

Not sure how helpful above information is.  Is there anything specific I can do when the system freezes (assuming M-x is working)?

**Comment by ch11ng** [comment]
Is the new problem same with the original issue or does it have something to do with #93?

> Is there anything specific I can do when the system freezes (assuming M-x is working)?

I think the following information should be helpful:

1. The content of the `*Messages*` buffer.
2. The value of `exwm--connection`.
3. Recent operations you performed.

**Comment by bvk** [comment]
#93 happened separately, so is not related to emacs freeze.

I will post the requested information when exwm freezes next time. I will close this ticket for now.
