### ISSUE TITLE
Minibuffer + workspace switch with mouse click bug

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#88]
Open some X window application in EXWM buffer, go to other monitor, do any command that operates with minibuffer like C-x C-f and switch back to other monitor with mouse click => emacs will freeze/stop responding to input.

**Comment by ch11ng** [comment]
I cannot reproduce this issue exactly, but I think e8bc51280dba18dc394e15dd544e70ad27176f82 should fix your problem.

**Comment by fm4d** [comment]
This commit totally broke workspace switching for me, after switch modeline starts to rapidly blink for ~10 seconds and input is ignored.

**Comment by ch11ng** [comment]
Could you turn `exwm-debug-on` on and show me the log?

**Comment by ch11ng** [comment]
In my case, that commit doesn't cause the problem you described.  You may try placing a line below [this line](https://github.com/ch11ng/exwm/blob/master/exwm-workspace.el#L161) since I've just removed a delay there:

```
(sit-for 0.1)
```

**Comment by fm4d** [comment]
I am not able to show you the log, because emacs actually ends in endless loop. 
```(sit-for 0.1)``` broke it even more, emacs does not even load properly, randr setup is totaly wrong and I see just about half of screen and so.

It is really weird that you dont experience any issue, because before emacs get into endless loop, other things seems wrong, like changing workspace with mouse will change the focus but move mouse to the wrong workspace etc.

**Comment by ch11ng** [comment]
You can press <kbd>C-g</kbd> to quit the loop, I think.

**Comment by fm4d** [comment]
Right, after stopping the loop, the log is full of switching between two workspaces.
```
[EXWM] Workspace was switched unexpectedly
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Focus on workspace 2
[EXWM] Workspace was switched unexpectedly
[EXWM] Focus on #<window 5 on *scratch*>
[EXWM] Focus on workspace 1
[EXWM] Focus on #<window 7 on *scratch*>
[EXWM] Focus on workspace 2
[EXWM] Workspace was switched unexpectedly
[EXWM] Focus on #<window 5 on *scratch*>
[EXWM] Focus on workspace 1
[EXWM] Workspace was switched unexpectedly
[EXWM] Focus on #<window 7 on *scratch*>
etc...
```

**Comment by ch11ng** [comment]
And how does `sit-for` make it even worse? I think the original code does basically the same thing.

**Comment by fm4d** [comment]
But the original issue of this thread is actually fixed by this commit :)

**Comment by ch11ng** [comment]
I meant the delay code.  What's in the `*Messages*` buffer when `sit-for` is inserted?

**Comment by fm4d** [comment]
Weird, I tried ```sit-for``` again and no visible change, so I guess had some typo in it previously, but it does not solve the issue anyway.

**Comment by ch11ng** [comment]
Does it happen with the RandR module disabled?

**Comment by fm4d** [comment]
Also I should mention that the endless loop is caused by switching workspaces by shortcut -> exwm-workspace-switch, switching with mouse does not cause it.

**Comment by fm4d** [comment]
Yes, it is the same with RandR disabled.

**Comment by ch11ng** [comment]
I don't know if d05df51b0563b385da46384901c73daa073c28b9 fixes your problem.  If not, please try increase the timeout in [this line](https://github.com/ch11ng/exwm/blob/d05df51b0563b385da46384901c73daa073c28b9/exwm-input.el#L102).  I can reproduce the problem with smaller intervals such as 10 microseconds (0.00001).

**Comment by fm4d** [comment]
Setting the timeout to 0.05 indeed fixed the infinite loop problem for me, but the initial problem is still there. Steps: Open X window app on one monitor, switch to other, execute some command that opens minibuffer and click with mouse on the other monitor with X window. Result: minibuffer window is closed (but focus is not changed, because I use helm, it is weird but with helm, if you change focus with minibuffer open, minibuffer is closed but focus is not changed (without helm it works properly)) and now if you switch focus to that workspace with X window (click or shortcut, doesnt matter), emacs freeze ( you cannot switch workspace and input in the focused buffer is ignored)

**Comment by ch11ng** [comment]
With ch11ng/xelb@36b54b44987c2b05e0a78f7783373e977d706489 and ba536bb6e354577cd69926865aee0e6f90f7306a, EXWM should no longer freeze in such case.  There's still one issue though: the first click won't work since closing the minibuffer will switch to the original workspace, so you'll have to click the X window for a second time in order to make the switch.

OTOH, I'm very suspicious of the timeout interval; 50 ms is quite large.  We should definitely make it as short as possible.  Could you please verify whether substituting `run-with-timer` with `run-with-idle-timer` in [this line](https://github.com/ch11ng/exwm/blob/ba536bb6e354577cd69926865aee0e6f90f7306a/exwm-input.el#L102) solves your problem?

**Comment by fm4d** [comment]
Indeed, ```run-with-idle-timer``` fixed it for me, but I havent been able to test the dual-monitor click issue yet.
