### ISSUE TITLE
Understanding EXWM

### ISSUE THREAD

**Issue by heeh** [ch11ng/exwm#883]
Suppose I have ten workspaces. It seems that the text files are shared across workspaces.
However, the program executed by `start-process-shell-command` are bound to the workspace because I see the difference when executing `C-x C-b`.
For example, if I executed `google-chrome` on the workspace 1 and `firefox` on the workspace 2, I cannot see any of those on workspace 3.

1. Can someone explain this behavior?
2. Or, could you point me the file that I could take a look?
3. Is `workspace` in EXWM equivalent to `frame` in emacs?

**Comment by eval-on-point** [comment]
This is all documented in the project Wiki. See [ch11ng/exwm Wiki: x-window-handling-among-workspaces](https://github.com/ch11ng/exwm/wiki#x-window-handling-among-workspaces)

**Comment by heeh** [comment]
Thank you @eval-on-point.
