### ISSUE TITLE
EXWM with wslg

### ISSUE THREAD

**Issue by heeh** [ch11ng/exwm#896]
This may sound silly but what does it take to get EXWM working on win11 wslg?  
I believe that wslg internally uses wayland and EXWM does not support this at this point.

**Comment by heeh** [comment]
I do not want to add unnecessary request. Hence, I close this issue.

**Comment by medranocalvo** [comment]
I can say that EXWM does not work under Wayland.  I don't use wslg, so I can't comment further.  Tangentially, I use EXWM on macOS (https://github.com/ch11ng/exwm/wiki/Installation-on-macOS); I encourage you (or others) to try getting it to work and post instructions on the Wiki, or tickets when roadblocks are found.
