### ISSUE TITLE
Just thank you!

### ISSUE THREAD

**Issue by gdindi** [ch11ng/exwm#898]
Hi,

I just wanted to say thanks to @medranocalvo and others who are keeping EXWM alive!
The last release (0.27) has corrected a behaviour for which I had an [awful workaround](https://dindi.garjola.net/exwm-floating.html) that I can now remove from my config.

Thanks!

**Comment by medranocalvo** [comment]
I extend the thanks to everyone contributing, from the heroes digging in the code to all who open and comment in the tickets.
