### ISSUE TITLE
Keybinding to H-+

### ISSUE THREAD

**Issue by zevlg** [ch11ng/exwm#90]
I'vo got a keybinding in my EXWM configuration like:
<pre>
(exwm-input-set-key (kbd "H-+") 'lg-exwm-lupe-in)
</pre>

It does perfectly works in ordinar emacs buffers or event in X client buffer while in ``line`` mode, however it does not work in ``char`` mode.

**Comment by ch11ng** [comment]
Fixed in ch11ng/xelb@5c7a8a966765c74e90e1ee5e495788681eeb451e and 45c24eac7a1f9eab5e4a5244e2d14f9f35aa69fa.  Thank you for the report.  It was because Emacs has some special treatments of shift key, and `xcb:keysyms:event->keysym` did not handle one of those correctly.
