### ISSUE TITLE
click-to-focus vs. focus-follows-mouse

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#91]
EXWM is at the moment an hybrid between click-to-focus and focus-follows-mouse:

| Input focus | Mouse pointer | Behaviour |
|---|---|---|
| emacs     | emacs     | click-to-focus                |
| emacs     | line-mode | **flickering click-to-focus**[1][2] |
| emacs     | char-mode | **focus-follows-mouse**       |
| line-mode | emacs     | click-to-focus |
| line-mode | line-mode | click-to-focus |
| line-mode | char-mode | click-to-focus |
| char-mode | emacs     | click-to-focus |
| char-mode | line-mode | click-to-focus |
| char-mode | char-mode | click-to-focus |

(*emacs* is an Emacs buffer, *line-mode* an X window in `line-mode`, and
*char-mode* an X window in `char-mode`.)

The cause, as you surely know, is that the X windows are reparented to the
emacs frame; so even though the input focus is in the latter, keyboard events
still go to the X frames due to them being inferior windows.

Apart from the simplicity argument, I don't see why we couldn't use a "virtual
root" frame different from the Emacs frame, reparent both the Emacs frame and
the X windows on top of it, and then simply raise the X windows on top of the
Emacs frame while still adjusting their coordinates to match the "Emacs
windows" size.  This way the input focus would be respected.

On the other hand, the code has many details I don't understand.  Why would the
above approach not work?

See related issues:
 - https://github.com/ch11ng/exwm/issues/80
 - https://github.com/ch11ng/exwm/issues/44

**Comment by ch11ng** [comment]
Thanks, @uu1101.  The approach you proposed sounds quite reasonable when it comes to these input focus issues.  I'll have a look and see if we can overcome the possible stacking order problems (especially when there're floating windows) and other potential issues.

**Comment by ch11ng** [comment]
Sorry for the long delay.  This should be fixed in 9c95c03e18f6d5cf78bcd54bf00f8055a3863336.
