### ISSUE TITLE
[SPC SPC] does not work ([M-X] does, though)

### ISSUE THREAD

**Issue by allentiak** [ch11ng/exwm#911]
#### Reproduction guide :beetle:
- Start Emacs
- Open a file/project (in my case, a Clojure one)
- Press [SPC SPC]. This should show a list of commands, just like if you press [M-X].
- The [M-X] shortcut works fine.

*Observed behaviour:* :eyes: :broken_heart:

When pressing SPC one more time, I get "SPC SPC SPC is undefined".

*Expected behaviour:* :heart: :smile:
This should show a list of commands.

#### System Info

`~/.spacemacs.d` dir: https://github.com/allentiak/.spacemacs.d

 :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3512e43c9)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (clojure :variables cider-format-code-options
          '(("indents"
             (("ns"
               (("inner" 0)
                ("inner" 1))))))
          cider-overlays-use-font-lock t cider-preferred-build-tool 'clojure-cli cider-repl-buffer-size-limit 250 cider-result-overlay-position 'at-point clojure-backend 'lsp clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-kaocha-runner t clojure-enable-linters
          '(clj-kondo joker)
          clojure-indent-style 'align-arguments clojure-align-forms-automatically t clojure-toplevel-inside-comment-form t)
 colors command-log dap emacs-lisp
 (git :variables git-magit-status-fullscreen t magit-diff-adjust-tab-width t magit-diff-paint-whitespace t magit-diff-highlight-trailing t magit-diff-refine-hunk 'all)
 (go :variables go-backend 'lsp go-format-before-save t go-use-gocheck-for-testing t go-use-golangci-lint t)
 helm html
 (java :variables java-backend 'lsp)
 (keyboard-layout :variables kl-layout 'colemak-neio-inverted)
 latex lsp
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors org parinfer
 (plantuml :variables plantuml-jar-path "/usr/share/plantuml/plantuml.jar" org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spacemacs-visual spell-checking sql syntax-checking
 (treemacs :variables treemacs-indentation 1 treemacs-use-filewatch-mode t treemacs-use-follow-mode t treemacs-use-git-mode 'deferred)
 (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t)
 yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by eval-on-point** [comment]
This seems like a spacemacs issue. `SPC` is not bound in EXWM by default. Check the [keybindings section in the EXWM wiki](https://github.com/ch11ng/exwm/wiki#keybindings) to learn how to customize EXWM and confirm that there is code which performs that configuration in your Emacs configuration. I do not see any configuration of EXWM in your `.spacemacs`.

**Comment by allentiak** [comment]
Sorry. I opened this in the wrong repo. Closing.

**Comment by allentiak** [comment]
Thank you for your comment.
