### ISSUE TITLE
Firefox irresponsive on "This Connection is Untrusted"

### ISSUE THREAD

**Issue by uu1101** [ch11ng/exwm#92]
When trying to add an exception 
When visiting a page with an untrusted certificate in Firefox and clicking on "Add Exception..." the dialog does not show up and the firefox window does not respond to mouse events anymore.

It can be reproduced by visiting the following web page and clicking on the button labeled "Add Exception...":

https://www.cacert.org/

**Comment by ch11ng** [comment]
Strangely, I cannot reproduce it with either Debian's Iceweasel 38.4.0esr-1 or the Firefox 42.0/44.0a2 binaries I've just downloaded.  So

1. Which version of Firefox are you using?
2. Does it work elsewhere?
3. Does other floating windows work normally?

**Comment by uu1101** [comment]
Oh!  It is due to my configuration.  I am sorry, I hope I have not made lose much of your time.
