### ISSUE TITLE
minibuffer won't get focus if X buffer in char mode 

### ISSUE THREAD

**Issue by zevlg** [ch11ng/exwm#95]
If X client is running in EXWM's char mode and some command (f.i. `(exwm-input-set-key (kbd "H-:") 'eval-expression)` ) attends input from minibuffer, it won't get focused.  I use this to workaround it:

<pre>
(defun lg-minibuf-focus-in ()
  (select-frame-set-input-focus (selected-frame) t))

(defun lg-minibuf-focus-out ()
  (exwm-input--update-focus))

(add-hook 'minibuffer-setup-hook 'lg-minibuf-focus-in)
(add-hook 'minibuffer-exit-hook 'lg-minibuf-focus-out)
</pre>

**Comment by ch11ng** [comment]
Yes, this is a long-standing bug.  Your workaround works partly when the pointer is not contained by a `char-mode` X window.  I think it would be fixed naturally once we find a solution to #91.

**Comment by ch11ng** [comment]
Fixed in 9c95c03e18f6d5cf78bcd54bf00f8055a3863336.
